/*-----------------------------------------------------------------------
Source Name: benefit.c
System     : Personnel/Payroll.
Created  On: 30th Sept 91.
Created  By: C. Burns

DESCRIPTION:

MODIFICATIONS:        

Programmer     YY/MM/DD       Description of modification
------------------------------------------------------------------------*/
#define	MAIN		/* Main program. This is to declare Switches */
#define MAINFL		BENEFIT			/* main file used */

#define	SYSTEM		"Setup"			/* Sub System Name */
#define	MOD_DATE	"30-SEPT-91"		/* Progran Last Modified */

#include <stdio.h>
#include <cfomstrc.h>
#include <bfs_defs.h>
#include <bfs_pp.h>
#include <bfs_com.h>

/* User Interface define constants */
#ifdef ENGLISH
#define ADDREC		'A'
#define CHANGE		'C'
#define DELETE		'D'
#define INQUIRE		'I'
#define EXITOPT		'E'
#define	NEXT		'N'
#define	PREV		'P'

#define	YES		'Y'
#define NO		'N'
#define	LINEEDIT	'L'
#define SCREENEDIT	'S'
#define	CANCEL		'C'

#define	FIXED		'F'
#define	PERCENT		'P'

#else
#define ADDREC		'R'
#define CHANGE		'C'
#define DELETE		'E'
#define INQUIRE		'I'
#define EXITOPT		'F'
#define	NEXT		'S'
#define	PREV		'P'

#define	YES		'O'
#define NO		'N'
#define	LINEEDIT	'L'
#define SCREENEDIT	'S'
#define	CANCEL		'A'

#define	FIXED		'F'
#define	PERCENT		'P'

#endif

/* PROFOM Releted declarations */

#define	SCR_NAME	"benefit"	/* PROFOM screen Name */

#define MAX_FIELD	7		/* Maximum field # to edit */

/* PROFOM Screen STH file */

/* Field PROFOM numbers */
#define	FN_FLD		400	/* Fn: */
#define	KEY_START	500	/* Benefit Code: */
#define	KEY_END		600	/* Pay Period Code: */
#define	CHG_FLD		700	/* Field: */

#define DESC_FLD	900	/*  Description: */
#define INC_FLD 	1000	/*  Income */
#define T4_FLD 		1100	/*  T4 field */
#define T4_DESC 	1150	/*  T4 field */
#define	AMT_FLG		1200	/*  Amt Flag P or F */
#define AMT_FLD		1250	/*  T4 field */
#define FUND_FLD	1300	/*  Fund: */
#define ACCT_FLD	1400	/*  UIC Account: */
#define PP_FLD1		1500	/*  Pay Period 1 */
#define PP_FLD2		1600	/*  Pay Period 2 */
#define PP_FLD3		1700	/*  Pay Period 3 */
#define PP_FLD4		1800	/*  Pay Period 4 */
#define PP_FLD5		1900	/*  Pay Period 5 */


#define START_FLD	900	/* First Field on screen */
#define	END_FLD		2100	/* Last Field of the screen */
/* bargain.sth - header for C structure generated by PROFOM EDITOR */

typedef struct	{

	char	s_pgname[11];	/* 100 STRING X(10) */
	long	s_rundate;	/* 300 DATE YYYYFMMFDD */
	char	s_fn[2];	/* 400 STRING X */
	char	s_ben_code[7];	/* 500 STRING X(6) */
	char	s_pp_code[7];	/* 600 STRING X(6) */
	short	s_field;	/* 700 NUMERIC 99 */

	char	s_desc[31];	/* 900 STRING X(30) */
	char	s_income[2];	/* 1000 STRING X */
	char	s_t4_code[2];	/* 1100 STRING X */
	char	s_t4_desc[11];	/* 1150 STRING X(10) */
	char	s_fp_code[2];	/* 1200 STRING X */
	double	s_amount;	/* 1250 NUMERIC 9,999,999.99 */
	short	s_fund;		/* 1300 NUMERIC 999 */
	char	s_acct[19];	/* 1400 STRING X(18) */
	char	s_pp[5][2];	/* 1500 -1900 STRING X */

	char	s_mesg[78];	/* 2000 STRING X(76) */
	char	s_resp[2];	/* 2100 STRING X */
} s_struct;

static	s_struct  s_sth,image;	/* PROFOM Screen Structure */
static	struct  stat_rec  sr;		/* PROFOM status rec */

static	char 	e_mesg[100];  		/* dbh will return err msg in this */

static	Pa_rec		pa_rec;
static	Gl_rec		gl_rec;
static	Ctl_rec		ctl_rec;
static	Benefit	benefit, pre_benefit;
static	Pay_per		pay_per;
static	Emp_ben		emp_ben;

int	Validation() ;
int	WindowHelp();
int	Argc;
char	**Argv;

void	free() ;
char	*malloc() ;

main(argc,argv)
int argc;
char *argv[];
{
	int 	retval;

	/* These two are passed to execute() when it is called */
	Argc = argc;
	Argv = argv;

	retval = Initialize(argc,argv);	/* Initialization routine */

	if (retval == NOERROR) retval = Process();

	CloseRtn();			/* return to menu */
	if (retval != NOERROR) exit(-1);
	exit(0);
}

/*-------------------------------------------------------------------*/
/* Initialize PROFOM */

Initialize(argc, argv)
int	argc ;
char	*argv[] ;
{
	int	err ;

	/*
	*	Initialize DBH Environment
	*/
	strncpy(SYS_NAME,SYSTEM,50);	/* Sub system name */
	strncpy(CHNG_DATE,MOD_DATE,10);	/* Modification Date */

	proc_switch(argc, argv, MAINFL) ; 	/* Process Switches */

	/*
	*	Initialize PROFOM & Screen
	*/
	strcpy(sr.termnm,terminal);	/* Copy Terminal Name */
	fomin(&sr);
	ret(err_chk(&sr)) ;		/* Check for PROFOM Error */
	fomcf(1,1);			/* Enable Snap screen option */

	err = InitScreen() ;		/* Initialize Screen */
	if(NOERROR != err) return(err) ;

	/*
	*	Get The Parameter Record
	*/
	err = get_param(&pa_rec, BROWSE, 1, e_mesg) ;
	if(err == ERROR) {
		DispError((char *)&s_sth,e_mesg);
		return(ERROR) ;
	}
	else if(err == UNDEF) {
#ifdef ENGLISH
		DispError((char *)&s_sth,"Parameters Are Not Set Up ...");
#else
		DispError((char *)&s_sth,"Parametres ne sont pas etablis... ");
#endif
		return(ERROR) ;
	}

	return(NOERROR) ;
}	/* Initialize() */

/*--------------------------------------------------------------------------*/
/* Close nessary files and environment before exiting program               */

CloseRtn() 
{
	/* Set terminal back to normal mode from PROFOM */
	fomcs();
	fomrt();

	close_dbh();	/* Close files */

	return(NOERROR);
}	/* CloseRtn() */
/*----------------------------------------------------------------*/
/* Initialize screen before going to process options */

InitScreen()
{
	int	err ;

	/* move screen name to Profom status structure */
	strcpy(sr.scrnam,NFM_PATH);
	strcat(sr.scrnam,SCR_NAME) ;

	strcpy(s_sth.s_pgname,PROG_NAME);

	s_sth.s_rundate = get_date();	/* get Today's Date in YYYYMMDD format*/
	s_sth.s_field = HV_SHORT ;
	s_sth.s_mesg[0] = HV_CHAR ;
	s_sth.s_resp[0] = HV_CHAR ;

	/* Initialize Key Fields. So that, if user selectes 'N' option
	   immediately after invoking program, then he gets the first
	   record in the file */

	s_sth.s_ben_code[0] = '\0';
	s_sth.s_pp_code[0] = '\0';

	/* Move High Values to data fields and Display the screen */
	err = ClearScreen() ;
	if(NOERROR != err) return(err) ;

	return(NOERROR) ;
}	/* InitScreen() */

/*-------------------------------------------------------------------*/
/* Get Option from user and call corresponding function */

Process()
{
	int err;

	for( ; ; ){

		/* Get the Fn: option from the user */
		if((err = ReadFunction()) != NOERROR) return(err) ;

		err = ProcFunction() ;	/* Process Function */

		if(QUIT == err)		return(NOERROR) ;    /* Exit */
		if(NOACCESS == err)	fomen(e_mesg);	     /* security */
		if(PROFOM_ERR == err)	return(PROFOM_ERR);  /* PROFOM ERROR */
		if(DBH_ERR == err) {
			DispError((char *)&s_sth,e_mesg);
#ifdef ENGLISH
			sprintf(e_mesg,"%s %d Dberror: %d Errno: %d",
				"System Error... Iserror:",
				iserror, dberror, errno);
#else
			sprintf(e_mesg,"%s %d Dberror: %d Errno: %d",
				"Erreur du systeme... Iserror:",
				iserror, dberror, errno);
#endif
			DispError((char *)&s_sth,e_mesg);
			return(DBH_ERR); /* DBH ERROR */
		}
	}      /*   end of the for( ; ; )       */
}	/* Process() */
/*----------------------------------------------------------------*/
/* Display the Function (Fn:) options and get the option from the user */

ReadFunction()
{
	/* Display Fn: options */
#ifdef ENGLISH
	fomer("A(dd), C(hange), D(elete), I(nquire), N(ext), P(rev), E(xit)");
#else
	fomer("R(ajouter), C(hanger), E(liminer), I(nterroger), S(uivant), P(rec), F(in)");
#endif
	/* Read Fn: field to get the option */
	sr.nextfld = FN_FLD ;
	fomrf( (char *)&s_sth );
	ret(err_chk(&sr));	/* Check for PROFOM error */

	return(NOERROR) ;
}	/* ReadFunction() */
/*----------------------------------------------------------------*/
/* Process the user selected Fn: option */

ProcFunction()
{
	int retval;

	switch (s_sth.s_fn[0]) {
	case ADDREC  :			/* ADD */
		CHKACC(retval,ADD,e_mesg);
		return( Add() ) ;
	case CHANGE  :			/* CHANGE */
		CHKACC(retval,UPDATE,e_mesg);
		return( Change() ) ;
	case DELETE  :			/* CHANGE */
		CHKACC(retval,UPDATE,e_mesg);
		return( Delete() ) ;
	case INQUIRE  :			/* Inquire */
		CHKACC(retval,BROWSE,e_mesg);
		return( Inquire() ) ;
	case NEXT  :			/* Next */
		CHKACC(retval,BROWSE,e_mesg);
		return( Next(FORWARD) ) ;
	case PREV  :			/* Previous */
		CHKACC(retval,BROWSE,e_mesg);
		return( Next(BACKWARD) ) ;
	case EXITOPT  :			/* Exit */
		return( QUIT ) ;
	}  /*   end of the switch statement */

	return(retval);
}	/* ProcFunction() */
/*----------------------------------------------------------------------*/
/* Adding.  Get the unique Key, accept details and update the files */
Add()
{
	int	err ;

	for( ;; ) {
		err = ReadKey();
		if(err != NOERROR) return(err) ;
		strcpy(benefit.bn_code,s_sth.s_ben_code);
		strcpy(benefit.bn_pp_code,s_sth.s_pp_code);
		err = get_benefit(&benefit,BROWSE,0,e_mesg);
		if(err = UNDEF) break;
		if(err == NOERROR) {
			fomen("Benefit Already Exitst");
			continue;
		}
		if(err < 0)  {
			fomen(e_mesg);
			get();
			return(err);
		}
	}

	/* Clear The Screen */
	err = ClearScreen();
	if(err != NOERROR) return(err) ;

	err = GetDetails() ;
	if(PROFOM_ERR == err || DBH_ERR == err) return(err) ;
	if(err < 0 || CANCEL == err) {
		roll_back(e_mesg) ;	/* Unlock the locked Records */
		return(ClearScreen()) ;	/* Clear the Screen */
	}

	return(NOERROR);
}	/* Add() */
/*-----------------------------------------------------------------------*/
/* Change. Students Study halls and update the files if a day/semester   */
/* is changed to NO delete record.			  		 */
/*-----------------------------------------------------------------------*/
Change()
{
	int	err ;

	err = SelectRecord() ;
	if(NOERROR != err) return(err) ;

	for( ; ; ) {
		err = Confirm() ;
		if(err != YES) {
			roll_back(e_mesg);
			break;
		}

		err = WriteRecords(UPDATE) ;
		if(err==NOERROR) break;
		if(err==LOCKED) {
			roll_back(e_mesg) ;
			continue;
		}
		if (err < 0) {
			roll_back(e_mesg);
			return(err) ;
		}
	}

	return(NOERROR) ;
}	/* Change() */
/*-----------------------------------------------------------------------*/
/* Delete. Student Study Hall Records.  */
/*-----------------------------------------------------------------------*/
Delete()
{
	int	err ;

	err = SelectRecord() ;
	if(NOERROR != err) return(err) ;

	for( ; ; ) {
		err = Confirm() ;
		if(err != YES) {
			roll_back(e_mesg);
			break;
		}

		err = WriteRecords(P_DEL) ;
		if(err==NOERROR) break;
		if(err==LOCKED) {
			roll_back(e_mesg) ;
			continue;
		}
		if (err < 0) {
			roll_back(e_mesg);
			return(err) ;
		}
	}

	return(NOERROR) ;
}	/* Delete() */
/*-----------------------------------------------------------------------*/
/* Show Student Student halls base on users input */
Inquire()
{
	int	err ;

	err = SelectRecord() ;
	if(NOERROR != err) return(err) ;

	return(NOERROR) ;
}	/* Inquire() */
/*----------------------------------------------------------*/
/* Show the next or previous Students Study halls */

Next(direction)
int	direction ;
{
	int retval;

	strcpy(benefit.bn_code,s_sth.s_ben_code);
	strcpy(benefit.bn_pp_code,s_sth.s_pp_code);
	if (flg_start(BENEFIT) != direction) {
		inc_str(benefit.bn_pp_code, sizeof(benefit.bn_pp_code)-1, 
			direction);
		flg_reset(BENEFIT);
	}

	retval = get_n_benefit(&benefit, BROWSE, 0, direction, e_mesg);
#ifndef ORACLE
	seq_over(BENEFIT);
#endif
	if(ERROR == retval)return(DBH_ERR) ;
	if(EFL == retval) {
		fomen("No More Records....");
		get();
		return(NOERROR) ;
	}

	retval = ShowScreen(BROWSE);

	return( retval ) ;
}	/* Next() */
/*------------------------------------------------------------*/
/* Allows User to Add Record to File */
/*------------------------------------------------------------*/
GetDetails()
{
	int	i ;
	int	err;

	err = ReadScreen(ADD);
	if(PROFOM_ERR == err || DBH_ERR == err) return(err) ;
	if(RET_USER_ESC == err){
		return(RET_USER_ESC) ;
	}

	for( ; ; ) {
		i = Confirm() ;
		if(i != YES) break;

		i = WriteRecords(ADD) ;
		if(i < 0) {
			if(i == LOCKED) continue;
		}
		break;
	}
	if(i != NOERROR) return(i);
	return(NOERROR) ;
}	/* GetDetails() */
/*------------------------------------------------------------*/
/*------------------------------------------------------------*/
ReadScreen(mode)
int	mode;
{
	int err;

	scpy((char *)&image,(char *)&s_sth,sizeof(image));

	if(mode == ADD) {
		SetDupBuffers(START_FLD,END_FLD,0); /* Off Dup Control */
	}
	else {
		SetDupBuffers(START_FLD,END_FLD,1); /* Off Dup Control */
	}
	
	InitFields(LV_CHAR,LV_SHORT,LV_LONG,LV_DOUBLE);

	err = ReadFields((char *)&s_sth,START_FLD, END_FLD-200,
		Validation, WindowHelp,1) ;
	if(PROFOM_ERR == err || DBH_ERR == err) return(err) ;
	if(RET_USER_ESC == err){
		if(mode == ADD) {
			InitFields(HV_CHAR,HV_SHORT,HV_LONG,HV_DOUBLE);
			ret(WriteFields((char *)&s_sth,START_FLD,END_FLD-200));
		}
		else {
		/* When user gives ESC-F while changing fields, assumption is
		* he completed his changes, and remaining fields are same as
		* old. But, at this point STH will be having low values in the 
		* remaining fields. So move the old values form the linked list.
		*/

			err = CopyBack((char *)&s_sth,(char *)&image,
				sr.curfld, END_FLD);
			if(err == PROFOM_ERR) return(err);
		}
		s_sth.s_mesg[0] = HV_CHAR;
		DispMesgFld((char *)&s_sth);

		return(RET_USER_ESC) ;
	}

	return(NOERROR);
}
/*----------------------------------------------------------*/
/* Get the key and show the record */
SelectRecord()
{
	int	err ;

	err = ReadKey();
	if(err != NOERROR) return(err) ;

	err = ShowScreen(BROWSE);

	return(NOERROR);
}	/* SelectRecord() */
/*----------------------------------------------------------------------*/
/* Get the Student Study Hall key from user. In ADD mode disable dup buffers, */
/* other modes enable dup buffers and show the current key as a default key */
ReadKey()
{
	int	i;
	char	hold_ben[7];
	char	hold_pp[7];
	
	/* In Add mode turn off dup control for key fields.
	   Other modes reverse it */
	if(s_sth.s_fn[0] == ADDREC){	/* ADD */
		SetDupBuffers(KEY_START,KEY_END,0); /* Off Dup Control */
	}
	else {
		SetDupBuffers(KEY_START,KEY_END,1);
	}

#ifdef ENGLISH
	strcpy(s_sth.s_mesg,"Press ESC-F to Go Back to Fn:");
#else
	strcpy(s_sth.s_mesg,"Appuyer sur ESC-F pour retourner a Fn:");
#endif
	DispMesgFld((char *)&s_sth);

	strcpy(hold_ben,s_sth.s_ben_code);
	strcpy(hold_pp,s_sth.s_pp_code);

	s_sth.s_ben_code[0] = LV_CHAR;
	s_sth.s_pp_code[0] = LV_CHAR;

	i = ReadFields((char *)&s_sth,KEY_START, KEY_END,
		Validation, WindowHelp,1) ;
	if(PROFOM_ERR == i || DBH_ERR == i) return(i) ;
	if(RET_USER_ESC == i){
		strcpy(s_sth.s_ben_code,hold_ben);
		strcpy(s_sth.s_pp_code,hold_pp);
		
		ret( WriteFields((char *)&s_sth,KEY_START, KEY_END) ) ;

		s_sth.s_mesg[0] = HV_CHAR;
		DispMesgFld((char *)&s_sth);

		return(RET_USER_ESC) ;
	}

	s_sth.s_mesg[0] = HV_CHAR;
	DispMesgFld((char *)&s_sth);

	return(NOERROR);
}	/*  ReadKey() */
/*-----------------------------------------------------------------------*/ 
/* Check to see if record is to be added, changed or deleted .		 */
/*-----------------------------------------------------------------------*/ 
WriteRecords(mode)
int mode;
{
	int	i,retval;

	strcpy(benefit.bn_code,s_sth.s_ben_code);
	strcpy(benefit.bn_pp_code,s_sth.s_pp_code);
	if(mode != ADD) {
		retval = get_benefit(&benefit,UPDATE,0,e_mesg);
		if(retval < 0) {
			fomer(e_mesg);
			return(retval);
		}
	}
	strcpy(benefit.bn_desc,s_sth.s_desc);
	strcpy(benefit.bn_inc,s_sth.s_income);
	strcpy(benefit.bn_t4_fld,s_sth.s_t4_code);
	strcpy(benefit.bn_amt_flag,s_sth.s_fp_code);
	benefit.bn_amount = s_sth.s_amount;
	benefit.bn_fund = s_sth.s_fund;
	strcpy(benefit.bn_acct,s_sth.s_acct);
	for(i=0 ; i<5 ; i++) {
		strcpy(benefit.bn_add_pp[i], s_sth.s_pp[i]);
	}

	retval = put_benefit(&benefit,mode,e_mesg);
	if(retval < 0) {
		DispError((char *)&s_sth,e_mesg);
		roll_back(e_mesg);
		return(retval);
	}

	if(mode != ADD) {
		retval = rite_audit((char*)&s_sth,BENEFIT,mode,(char*)&benefit,
			(char*)&pre_benefit,e_mesg);
		if(retval==LOCKED) {
			DispError((char *)&s_sth,e_mesg);
			roll_back(e_mesg) ;
			return(LOCKED) ;
		}
		if(retval < 0 ){
#ifdef	ENGLISH
			DispError((char *)&s_sth,"ERROR in Saving Records"); 
#else
			DispError((char *)&s_sth,
					"ERREUR en conservant les fiches");
#endif
			DispError((char *)&s_sth,e_mesg);
			roll_back(e_mesg);
			return(retval);
		}
	}

	retval = commit(e_mesg) ;
	if(retval < 0) {
#ifdef ENGLISH
		DispError((char *)&s_sth,"ERROR in Saving Records"); 
#else
		DispError((char *)&s_sth,"ERREUR en conservant les fiches");
#endif
		DispError((char *)&s_sth,e_mesg);
		roll_back(e_mesg);
		return(retval);
	}

	return(NOERROR);
}
/*----------------------------------------------------------------*/
/* Set Duplication buffers for fields 				  */
SetDupBuffers( firstfld, lastfld, value )
int	firstfld, lastfld;	/* field numbers range */
int	value;			/* ENABLE or DISABLE */
{
	int i ;
	
	/* Added because amt_fld is number as 1250 */
	if( firstfld <= AMT_FLD && lastfld >= AMT_FLD)
		fomca1(AMT_FLD, 19, value);

	for( i=firstfld; i<=lastfld; i+=100 )
		fomca1( i, 19, value);
	if( value==0 )
		return(0);
	sr.nextfld = firstfld;
	sr.endfld = lastfld;
	fomud( (char *)&s_sth );
	ret( err_chk(&sr) );

	return( 0 );
}
/*----------------------------------------------------------------*/
/* Validation function() for Key and Header fields when PROFOM returns
  RET_VAL_CHK */

Validation()
{
	int	save_nextfld, save_endfld ;
	int	i, retval;

	switch(sr.curfld){
	case KEY_START:
		Right_Justify_Numeric(s_sth.s_ben_code,
			sizeof(s_sth.s_ben_code)-1);
		break;
	case KEY_END:
		Right_Justify_Numeric(s_sth.s_pp_code,
			sizeof(s_sth.s_pp_code)-1);
		strcpy(pay_per.pp_code,s_sth.s_pp_code);
		pay_per.pp_year = 0;
		flg_reset(PAY_PERIOD);

		retval = get_n_pay_per(&pay_per,BROWSE,0,FORWARD,e_mesg);
		if(retval < 0){
			DispError((char *)&s_sth,e_mesg);
			return(retval);
		}
		if(strcmp(pay_per.pp_code,s_sth.s_pp_code)!=0){
#ifdef ENGLISH
		    	sprintf(e_mesg,"Pay Period Code %s Not on File",
			    	s_sth.s_pp_code);
#else
			sprintf(e_mesg,"Pay Period Code %s Not on File",
	    			s_sth.s_pp_code);
#endif
			DispError((char *)&s_sth,e_mesg);
			s_sth.s_ben_code[0] = LV_CHAR;
			s_sth.s_pp_code[0] = LV_CHAR;
			sr.curfld -= 100 ;
			return(ERROR);
		}
		seq_over(PAY_PERIOD);
		strcpy(benefit.bn_code,s_sth.s_ben_code);
		strcpy(benefit.bn_pp_code,s_sth.s_pp_code);
		flg_reset(BENEFIT);

		retval = get_n_benefit(&benefit,BROWSE,0,FORWARD,e_mesg);
		if(s_sth.s_fn[0] != ADDREC) {
			if(retval < 0) {
				fomer("Benefit Code Does not Exist");
				s_sth.s_ben_code[0] = LV_CHAR;
				s_sth.s_pp_code[0] = LV_CHAR;
				sr.curfld -= 100;
				return(ERROR);
			}
			if(strcmp(benefit.bn_code, s_sth.s_ben_code) != 0 ||
			   strcmp(benefit.bn_pp_code, s_sth.s_pp_code) != 0) {
				fomer("Benefit Code Does not Exist");
				s_sth.s_ben_code[0] = LV_CHAR;
				s_sth.s_pp_code[0] = LV_CHAR;
				sr.curfld -= 100;
				return(ERROR);
			}
		}
		break;
	case	DESC_FLD:
		if(s_sth.s_desc[0] == '\0') {
			fomer("This is a Required Field");
			return(ERROR);
		}
		break;
	case	T4_FLD:
		retval = GetT4Description(s_sth.s_t4_code);
		if ( WriteFields((char *)&s_sth,T4_DESC, T4_DESC) < 0 ) 
			return(-1);
		break;
	case	INC_FLD:
		if(s_sth.s_income[0] != YES && s_sth.s_income[0] != NO) {
			fomer("Must Be Y or N");
			s_sth.s_income[0] = LV_CHAR;
			return(ERROR);
		}
		break;
	case	AMT_FLG:
		if(s_sth.s_fp_code[0] != FIXED &&
		   s_sth.s_fp_code[0] != PERCENT) {
			fomer("Must Be F(ixed) or P(ercentage)");
			s_sth.s_fp_code[0] = LV_CHAR;
			return(ERROR);
		}
		break;
	case	AMT_FLD:
		break;
	case	FUND_FLD:
		if(pa_rec.pa_glmast[0] == YES) {
			ctl_rec.fund = s_sth.s_fund;
			retval = get_ctl(&ctl_rec,BROWSE,0,e_mesg);
			if(retval < 0 && retval != UNDEF) {
				DispError((char *)&s_sth);
				return(retval);
			}
			if(retval == UNDEF) {
				s_sth.s_fund = LV_SHORT;
				fomer("Fund Does not Exist");
				return(ERROR);
			}
		}
		break;
	case	ACCT_FLD:
		if(strcmp(s_sth.s_acct, "\0") == 0) {
			sr.curfld += 100;
			return(NOERROR);
		}

		if(acnt_chk(s_sth.s_acct) < 0) {
			fomer("Invalid Account Number");
			s_sth.s_acct[0] = LV_CHAR;
			return(ERROR);
		}
		if(pa_rec.pa_glmast[0] == YES) {
		   gl_rec.funds = s_sth.s_fund;
		   strcpy(gl_rec.accno,s_sth.s_acct);
		   gl_rec.reccod = 99;
		   retval = get_gl(&gl_rec,BROWSE,0,e_mesg);
		   if(retval < 0) {
			fomer(e_mesg);

			s_sth.s_acct[0]=LV_CHAR;
			return(ERROR);
		   }
		}
		break;
	case	PP_FLD1:
		if (s_sth.s_pp[0][0] != 'Y' &&
		    s_sth.s_pp[0][0] != 'N') {
			fomen("Must enter Y or N");
			get();
			s_sth.s_pp[0][0] = LV_CHAR;
			return(ERROR);
		}
		if(s_sth.s_pp[0][0] == 'N') {
			for(i=1;i<5;i++)
				s_sth.s_pp[i][0] = 'N' ;
		}
		sr.curfld+=100;
		break;
	case	PP_FLD2:
		if (s_sth.s_pp[1][0] != 'Y' &&
		    s_sth.s_pp[1][0] != 'N') {
			fomen("Must enter Y or N");
			get();
			s_sth.s_pp[1][0] = LV_CHAR;
			return(ERROR);
		}
		if(s_sth.s_pp[1][0] == 'N') {
			for(i=2;i<5;i++)
				s_sth.s_pp[i][0] = 'N' ;
		}
		sr.curfld+=100;
		break;
	case	PP_FLD3:
		if (s_sth.s_pp[1][0] != 'Y' &&
		    s_sth.s_pp[1][0] != 'N') {
			fomen("Must enter Y or N");
			get();
			s_sth.s_pp[2][0] = LV_CHAR;
			return(ERROR);
		}
		if(s_sth.s_pp[2][0] == 'N') {
			for(i=3;i<5;i++)
				s_sth.s_pp[i][0] = 'N' ;
		}
		sr.curfld+=100;
		break;
	case	PP_FLD4:
		if (s_sth.s_pp[1][0] != 'Y' &&
		    s_sth.s_pp[1][0] != 'N') {
			fomen("Must enter Y or N");
			get();
			s_sth.s_pp[3][0] = LV_CHAR;
			return(ERROR);
		}
		if(s_sth.s_pp[3][0] == 'N') {
			for(i=4;i<5;i++)
				s_sth.s_pp[i][0] = 'N' ;
		}
		sr.curfld+=100;
		break;
	case	PP_FLD5:
		if (s_sth.s_pp[1][0] != 'Y' &&
		    s_sth.s_pp[1][0] != 'N') {
			fomen("Must enter Y or N");
			get();
			s_sth.s_pp[4][0] = LV_CHAR;
			return(ERROR);
		}
		sr.curfld+=100;
		break;
	default :
#ifdef ENGLISH
		sprintf(e_mesg,"No Validity Check For Field#  %d",sr.curfld);
#else
		sprintf(e_mesg,"Pas de controle de validite pour le Champ#  %d",sr.curfld);
#endif
		fomen(e_mesg);
		get();
		return(ERROR) ;
	}	/* Switch sr.curfld */

	return(NOERROR) ;
}	/* Validation() */
/*----------------------------------------------------------------*/
/* Show Help Windows, if applicable, when user gives ESC-H in key
   and header fields */

WindowHelp()
{
	int	retval ;
	short	reccod ;

	switch(sr.curfld){
	case KEY_START:
		retval = benefit_hlp(s_sth.s_ben_code,s_sth.s_pp_code,7,13);
		if(retval == DBH_ERR) return(retval);
		if(retval >= 0) redraw();
		if(retval == 0) return(ERROR);
		if(retval < 0) return(ERROR);
		strcpy(benefit.bn_code,s_sth.s_ben_code);
		strcpy(benefit.bn_pp_code,s_sth.s_pp_code);
		retval = get_benefit(&benefit,BROWSE,0,e_mesg);
		if(s_sth.s_fn[0] == ADDREC) {
			if(retval != UNDEF) {
				fomer("Benefit Code Already Exist");
				s_sth.s_ben_code[0] = LV_CHAR;
				s_sth.s_pp_code[0] = LV_CHAR;
				return(ERROR);
			}
		}
		else {
			if(retval < 0)  {
				fomer(e_mesg);
				s_sth.s_ben_code[0] = LV_CHAR;
				s_sth.s_pp_code[0] = LV_CHAR;
				return(ERROR);
			}
			SetDupBuffers(KEY_START, KEY_END, 1);
			s_sth.s_pp_code[0] = LV_CHAR ;
		}
		break;
	case KEY_END:
		retval = payper_hlp(s_sth.s_pp_code,7,13);
		if(retval == DBH_ERR) return(retval);
		if(retval >= 0) redraw();
		if(retval == 0) return(ERROR);
		if(retval < 0) return(ERROR);

		strcpy(benefit.bn_code,s_sth.s_ben_code);
		strcpy(benefit.bn_pp_code,s_sth.s_pp_code);
		flg_reset(BENEFIT);
		retval = get_n_benefit(&benefit,BROWSE,0,FORWARD,e_mesg);
		if(s_sth.s_fn[0] != ADDREC) {
			if(retval < 0) {
				fomer("Benefit Code Does not Exist");
				s_sth.s_ben_code[0] = LV_CHAR;
				s_sth.s_pp_code[0] = LV_CHAR;
				sr.curfld -= 100;
				return(ERROR);
			}
			if(strcmp(benefit.bn_code, s_sth.s_ben_code) != 0 ||
			   strcmp(benefit.bn_pp_code, s_sth.s_pp_code) != 0) {
				fomer("Benefit Code Does not Exist");
				s_sth.s_ben_code[0] = LV_CHAR;
				s_sth.s_pp_code[0] = LV_CHAR;
				sr.curfld -= 100;
				return(ERROR);
			}
		}
		break;
	case	DESC_FLD:
		break;
	case ACCT_FLD:
		if(pa_rec.pa_glmast[0] == YES) {
			retval = gl_hlp(s_sth.s_fund,
				s_sth.s_acct,&reccod, 7, 10 );
			if(retval == DBH_ERR) return(retval) ;
			if(retval >=0 ) redraw();
			if(retval < 1) return(ERROR) ;	/* Not Selected */
			if(reccod != 99) {
#ifdef ENGLISH
				fomer("Select records with 99 as Record Code only");
#else
				fomer("Choisir les fiches avec 99 seulement comme code de fiche");
#endif
				s_sth.s_acct[0] = LV_CHAR ;
				return(ERROR) ;
			}
		}
		break;
	default :
		fomer("No Help Window For This Field");
	}	/* Switch sr.curfld */

	return(NOERROR) ;
}	/* HdrAndKeyWindowHelp() */
/*-----------------------------------------------------------------------*/
/* Take the confirmation from user for the header part */

Confirm()
{
	int	err ;

	/* Options:
	   Add      - YALSNPC
	   Change   - YALSNPC
	   Delete   - YC
	*/

	for( ; ; ) {
	    switch(s_sth.s_fn[0]) {
	    case  ADDREC :		/* Add */
#ifdef ENGLISH
		err = GetOption((char *)&s_sth,
		"Y(es), S(creen Edit), L(ine edit), C(ancel)"
		,"YASLC");
#else
		err = GetOption((char *)&s_sth,
		"O(ui), S(creen edit), L(ine edit), A(nnul)"
		,"ORSLA");
#endif
		break ;
	    case  CHANGE :		/* Change */
#ifdef ENGLISH
		err = GetOption((char *)&s_sth,
		"Y(es), S(creen edit), L(ine edit), C(ancel)","YSLC");
#else
		err = GetOption((char *)&s_sth,
		"O(ui), S(creen edit), L(ine edit), A(nnul)","OSLA");
#endif
		break ;
	    case  DELETE :		/* Delete */
#ifdef ENGLISH
		err = GetOption((char *)&s_sth,"Y(es), C(ancel)","YC");
#else
		err = GetOption((char *)&s_sth,"O(ui), A(nnul)","OA");
#endif
		break ;
	    }
	    if(err == PROFOM_ERR) return(err) ;

	    switch(err) {
	    case  YES  :
		return(YES);
	    case  SCREENEDIT:
		err = ReadScreen(UPDATE);
		break;
	    case  LINEEDIT  :
		err = ChangeFields();
		break ;
	    case  CANCEL :
#ifdef ENGLISH
		err = GetOption((char *)&s_sth,
				"Confirm the Cancel (Y/N)?", "YN") ;
#else
		err = GetOption((char *)&s_sth,
				"Confirmer l'annulation (O/N)?", "ON") ;
#endif
		if(err == YES) return(CANCEL) ;
		break ;
	    }	/* switch err */

	    if(err == PROFOM_ERR) return(err) ;
	    if(err == DBH_ERR) return(err) ;
	}	/* for(; ; ) */
}	/* Confirm() */
/*-----------------------------------------------------------*/
ChangeFields()
{
	int	i, retval ;
	int	fld_no, end_fld;

	SetDupBuffers(START_FLD, END_FLD - 200, 1);

	/* Get The Field to Be Modified */
#ifdef	ENGLISH
	strcpy(s_sth.s_mesg,"Enter RETURN to Terminate Edit");
#else
	strcpy(s_sth.s_mesg,"Appuyer sur RETURN pour terminer l'ajustement");
#endif
	DispMesgFld((char *)&s_sth); ;
        
     	for (; ;) {
		s_sth.s_field = LV_SHORT;
		retval = ReadFields((char *)&s_sth,CHG_FLD,CHG_FLD,
			(int (*)())NULL,(int (*)())NULL, 1);

		if (retval < 0) return(-1);
		if (retval == RET_USER_ESC) break;	/* User enter ESC-F */

       		if (s_sth.s_field == 0 ) break;  /* Finished changing fields */

		if (s_sth.s_field > MAX_FIELD) {
			fomen("Invalid Field Number");
			get();
			continue;
		}

		fld_no = START_FLD + (100 * (s_sth.s_field-1));
		if(fld_no == AMT_FLG) {
			s_sth.s_fp_code[0] = LV_CHAR;
			s_sth.s_amount = LV_DOUBLE;
			end_fld = AMT_FLD;
		}
		else { if(fld_no == PP_FLD1) {
				for(i=0; i<5 ; i++) {
					s_sth.s_pp[i][0] = LV_CHAR;
				}
				end_fld = PP_FLD5;
			}
			else
				end_fld = fld_no;
		}

		retval = ReadFields((char *)&s_sth,fld_no, end_fld,
			Validation, WindowHelp,1) ;
	}
     	s_sth.s_field = HV_SHORT ;
	if ( WriteFields((char *)&s_sth,CHG_FLD, CHG_FLD) < 0 ) return(-1);

     	s_sth.s_mesg[0] = HV_CHAR ;
     	DispMesgFld((char *)&s_sth);

	if(SetDupBuffers(START_FLD, END_FLD-200, 0)<0) return(PROFOM_ERR);

	return(NOERROR);
}
/*-----------------------------------------------------------*/
/* Move Header to Screen Hdr Fields */
ShowScreen(mode)
int	mode;
{
	int	i, retval;

	strcpy(s_sth.s_ben_code, benefit.bn_code);
	strcpy(s_sth.s_pp_code, benefit.bn_pp_code);
	strcpy(s_sth.s_desc, benefit.bn_desc);
	strcpy(s_sth.s_income, benefit.bn_inc);
	strcpy(s_sth.s_t4_code, benefit.bn_t4_fld);
	retval = GetT4Description(s_sth.s_t4_code);
	strcpy(s_sth.s_fp_code, benefit.bn_amt_flag);
	s_sth.s_amount = benefit.bn_amount;
	for (i=0 ; i<5 ; i++) {
		strcpy(s_sth.s_pp[i],benefit.bn_add_pp[i]);
	}
	s_sth.s_fund = benefit.bn_fund;
	strcpy(s_sth.s_acct, benefit.bn_acct);

	ret( WriteFields((char *)&s_sth, KEY_START, END_FLD - 200) ) ;

	return(NOERROR) ;
}	/* ShowScreen() */
/*-----------------------------------------------------------*/
/* Read T4 description of field on T4 form from file         */
GetT4Description(t4_code)
char	t4_code[2];
{
	strcpy(s_sth.s_t4_desc, "NOT SETUP");
	return(NOERROR);
}
/*------------------------------------------------------------------------*/
/* Move High values to all data fields and clear the screen */

ClearScreen()
{
	/* Move High Values to Hedaer part */
	InitFields(HV_CHAR, HV_SHORT, HV_LONG, HV_DOUBLE) ;

	ret( WriteFields((char *)&s_sth,START_FLD, (END_FLD - 200)) );

	return(NOERROR);
}	/* ClearScreen() */
/*-------------------------------------------------------------------------*/
/* Initialize Screen Header with either Low or High Values */

InitFields( t_char, t_short,t_long,t_double )
char	t_char ;
short	t_short ;
long	t_long;
double	t_double;
{
	int	i;

	s_sth.s_desc[0] = t_char;
	s_sth.s_income[0] = t_char;
	s_sth.s_t4_code[0] = t_char;
	if(t_char == HV_CHAR) 
		s_sth.s_t4_desc[0] = t_char;
	s_sth.s_fp_code[0] = t_char;
	s_sth.s_amount = t_double;
	s_sth.s_fund = t_short;
	s_sth.s_acct[0] = t_char;
	for( i=0; i<5 ; i++) {
		s_sth.s_pp[i][0] = t_char;
	}

	return(NOERROR) ;
}	/* InitFields() */
/*-------------------- E n d   O f   P r o g r a m ---------------------*/
