/*-----------------------------------------------------------------------
Source Name: aphist.c
System     : Accounts Payables.
Created  On: 18 DECEMBER 89.
Created  By: T AMARENDRA.

COBOL Source(s): cp090---04

DESCRIPTION:
	Program to Inquire on AP History File and Purge Paid Invoices.

MODIFICATIONS:        

Programmer     YY/MM/DD       Description of modification
~~~~~~~~~~     ~~~~~~~~       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
peter ralph    90/11/23		Right justify numeric supplier code.  
C.Leadbeater   90/12/17		Add sort options by period or trans. date.
F.Tao 	       90/12/18       	Round up amounts before printing.
L.Robichaud	1993/10/13	Pass new parameter to close_rep function for 
				a banner to print with 3000 family.
------------------------------------------------------------------------*/

#define	MAIN
#define MAINFL		APHIST		/* main file used */

#include <stdio.h>
#include <cfomstrc.h>
#include <bfs_defs.h>
#include <bfs_recs.h>
#include <repdef.h>

#define	SYSTEM	"ACCOUNTS PAYABLE"	/* Sub System Name */
#define	MOD_DATE	"17-DEC-90"		/* Program Last Modified */

#define	PROJECT	"aphstrep"
#define	LOGREC	1
#define	FORMAT	1

#define	MASK_3		"_0_"			/* 3 Char Mask */
#define	MASK_8		"______0_"		/* 8 Char Mask */
#define	DATE_MASK	"____/__/__"		/* Date in YYYY/MM/DD format */
#define	MASK_4_2	"_,_0_.__-"		/* 4.2 Mask + Minus Sign */
#define	MASK_12_2	"__,___,_0_.__-"	/* 12.2 Mask + Minus Sign */

/* Options */
#define	INQUIRY	'1'
#define	LIST	'2'
#define	PURGE	'3'

/* User Interface define constants */
#ifdef ENGLISH
#define EXITOPT		'E'
#define	YES		'Y'
#define	EDIT		'E'
#define	CANCEL		'C'
#define	SORT_BY_PD	'P'
#define	SORT_BY_TRDT	'T'
#define	SORT_BY_SUPP	'S'
#else
#define EXITOPT		'F'
#define	YES		'O'
#define	EDIT		'M'
#define	CANCEL		'A'
#define	SORT_BY_PD	'P'
#define	SORT_BY_TRDT	'D'
#define	SORT_BY_SUPP	'C'
#endif

/* PROFOM Releted declarations */

#define	SCR_NAME	"aphist"	/* PROFOM screen Name */

/* PROFOM Screen STH file */

/* Field PROFOM numbers */

#define	OPTION_FLD	800	/* Option: */
#define	RANGES_START	900	/* Key Start Field */
#define	RANGES_END	1400	/* Key Start Field */
#define	END_FLD		1600	/* Last Field of the screen */
#define	FROMSUPP_FLD	900	/* From Supplier Cd: */
#define	TOSUPP_FLD	1000	/* To Supplier Cd: */
#define	CUTOFFDT_FLD	1100	/* Cutoff Date: */
#define	FROMTRDATE_FLD	1300	/* From Trans Date: */
#define	TOTRDATE_FLD	1400	/* To Trans Date: */

/* aphist.sth - header for C structure generated by PROFOM EDITOR */

struct	s_struct	{

	char	s_pgm[11];	/* STRING XXXXXXXXXX Field 100 */
	long	s_rundate;	/* DATE YYYYFMMFDD Field 300 */
	char	s_option[2];	/* STRING X Field 800 */
	char	s_fm_supp[11];	/* STRING XXXXXXXXXX Field 900 */
	char	s_to_supp[11];	/* STRING XXXXXXXXXX Field 1000 */
	long	s_cutoff_dt;	/* DATE YYYYFMMFDD Field 1100 */
	char	s_invc_no[16];	/* STRING XXXXXXXXXX Field 1200 */
	long	s_fm_date;	/* DATE YYYYFMMFDD Field 1300 */
	long	s_to_date;	/* DATE YYYYFMMFDD Field 1400 */
	char	s_mesg[78];	/* STRING X[77] Field 1500 */
	char	s_resp[2];	/* STRING X Field 1600 */
};

static	struct	s_struct  s_sth;	/* PROFOM Screen Structure */

static	struct  	stat_rec  sr;	/* PROFOM status rec */

static	Pa_rec		pa_rec ;	/* Parameters Record */
static	Ap_hist		ap_hist ;	/* Ap History Record */
static	Supplier	supplier;	/* Supplier Record */

static	char 		e_mesg[100];	/* dbh will return err msg in this */

static	short	pgcnt ;

extern	int	rperror ;

static	int	sort_opt;

double  D_Roundoff();

/*------------------------------------------------------------------------*/

main(argc,argv)
int	argc;
char	*argv[];
{
	int	err;

	if(argc < 2){
#ifdef  DEVELOP
#ifdef ENGLISH
		printf("MAIN ARGUMENTS ARE NOT PROPER\n");
#else
		printf("ARGUMENTS PRINCIPAUX SONT INCORRECTS\n");
#endif
		printf("Usage: %s {-tTerminal Name} {-dDist#} [{-sSwitches}]\n",
			argv[0]);
#endif
		exit(1);
	}

	err = Initialize(argc,argv) ;	/* Initialize Variables , DBH
						Environment and PROFOM */
	if(err == NOERROR) err = Process();	/* Initiate Process */

	CloseProcess() ;

	if(err != NOERROR)exit(1);
	exit(0);
}	/* main() */
/*-------------------------------------------------------------------*/
/* Initialize Variables, PROFOM, DBH etc. */

Initialize(argc, argv)
int	argc ;
char	*argv[] ;
{
	int	i ;

	/*
	*	Initialize DBH Environment
	*/
	strncpy(SYS_NAME,SYSTEM,50);	/* Sub system name */
	strncpy(CHNG_DATE,MOD_DATE,10);	/* Modification Date */

	proc_switch(argc, argv, MAINFL) ;	/* Process Switches */

	/*
	*	Initialize PROFOM & Menu Screen
	*/
	STRCPY(sr.termnm,terminal);	/* Copy Terminal Name */
	fomin(&sr);
	ret(err_chk(&sr)) ;		/* Check for PROFOM Error */
	fomcf(1,1);			/* Enable Snap screen option */

	/* move screen name to Profom status structure */
	STRCPY(sr.scrnam,NFM_PATH);
	strcat(sr.scrnam,SCR_NAME) ;

	/* Initialize SCR */
	STRCPY(s_sth.s_pgm,PROG_NAME);
	s_sth.s_rundate = get_date();	/* get Today's Date in YYYYMMDD format*/
	s_sth.s_mesg[0] = HV_CHAR ;
	s_sth.s_resp[0] = HV_CHAR ;

	InitRanges(HV_CHAR, HV_LONG) ;

	ret( WriteFields(1,0) ) ;

	/*
	*	Get The Parameter Record
	*/
	i = get_param(&pa_rec, BROWSE, 1, e_mesg) ;
	if(i == ERROR) {
		DispError(e_mesg);
		return(ERROR) ;
	}
	else if(i == UNDEF) {
#ifdef ENGLISH
		DispError("Parameters Are Not Setup..");
#else
		DispError("Parametres ne sont pas etablis..");
#endif
		return(ERROR) ;
	}

	return(NOERROR) ;
}	/* Initialize() */
/*-------------------------------------------------------------------*/
/* Get Option: from user and call corresponding function */

Process()
{
	int err;

	for( ; ; ){
		/* Get the Option: from the user */
		if((err = ReadOption()) != NOERROR) return(err) ;

		err = ProcOption() ;	/* Process Option */

		if(QUIT == err)		return(NOERROR) ;	/* Exit */
		if(NOACCESS == err) {
			fomen(e_mesg);
			get();
		}
		if(PROFOM_ERR == err)	return(PROFOM_ERR);  /* PROFOM ERROR */
		if(DBH_ERR == err) {
			DispError(e_mesg);
#ifdef ENGLISH
			sprintf(e_mesg,"%s %d Dberror: %d Errno: %d",
				"System Error... Iserror:",
				iserror, dberror, errno);
#else
			sprintf(e_mesg,"%s %d Dberror: %d Errno: %d",
				"Erreur du systeme... Iserror:",
				iserror, dberror, errno);
#endif
			DispError(e_mesg);
			return(DBH_ERR);	/* DBH ERROR */
		}
	}      /*   end of the for( ; ; )       */
}	/* Process() */
/*----------------------------------------------------------------*/
/* Close necessary files and environment before exiting program */

CloseProcess()
{
	/* Set terminal back to normal mode from PROFOM */
	fomcs();
	fomrt();

	close_dbh();	/* Close DBH(files) */

	return(NOERROR) ;
}	/* CloseProcess() */
/*----------------------------------------------------------------*/
/* Display the Options (Option:) and get the option from the user */

ReadOption()
{
	/* Display options */
#ifdef ENGLISH
	fomer("Select 1, 2 ,3, E(xit)");
#else
	fomer("Choisir 1, 2, 3, F(in)");
#endif
	/* Read Option: field */
	sr.nextfld = OPTION_FLD ;
	fomrf( (char *)&s_sth );
	ret(err_chk(&sr));	/* Check for PROFOM error */

	return(NOERROR) ;
}	/* ReadOption() */
/*----------------------------------------------------------------*/
/* Process the user selected option */

ProcOption()
{
	int retval;

	switch (s_sth.s_option[0]) {
	case INQUIRY  :			/* Inquiry */
		CHKACC(retval,BROWSE,e_mesg);
		return(Inquiry()) ;
	case PURGE    :			/* Purge */
		CHKACC(retval,P_DEL,e_mesg);
	case LIST     :			/* List */
		CHKACC(retval,BROWSE,e_mesg);
		return(PurgeList()) ;
	case EXITOPT  :			/* Exit */
		return( QUIT ) ;
	}  /*   end of the switch statement */

	if(retval<0)
		return(retval);
	return(NOERROR);
}	/* ProcOption() */
/*-----------------------------------------------------------------------*/
/* Take the ranges from the user and display the Transactions */

Inquiry()
{
	int	err ;

	err = ReadRanges() ;
	if(PROFOM_ERR == err || DBH_ERR == err) return(err) ;
	if(NOERROR != err) return(err) ;

	err = DisplayHistory() ;
	if(err < 0) return(err) ;

	InitRanges(HV_CHAR,HV_LONG) ;
	ret( WriteFields(RANGES_START, RANGES_END) ) ;

	return(NOERROR) ;
}	/* Inquiry() */
/*-----------------------------------------------------------------------*/
/* Take the ranges from the user and Purge/List the transactions */

PurgeList()
{
	int	err ;

	err = ReadRanges() ;
	if(PROFOM_ERR == err || DBH_ERR == err) return(err) ;
	if(NOERROR != err) return(err) ;

#ifdef ENGLISH
	STRCPY(s_sth.s_mesg,"Compiling Data... Please Wait");
#else
	STRCPY(s_sth.s_mesg,"Compile les donnees... Attendez S.V.P.");
#endif
	ShowMesg();
	fflush(stdout);

	err = TransHistory() ;
	if(err < 0) return(err);

	InitRanges(HV_CHAR,HV_LONG) ;
	ret( WriteFields(RANGES_START, RANGES_END) ) ;

	s_sth.s_mesg[0] = HV_CHAR ;
	ShowMesg();

	return(NOERROR) ;
}	/* PurgeList() */
/*----------------------------------------------------------------------*/
/* Read the Range Options form user */

ReadRanges()
{
	int	i;

	for(i = RANGES_START ; i <= RANGES_END ; i += 100)
		fomca1(i,19,0) ;

#ifdef ENGLISH
	STRCPY(s_sth.s_mesg,"Press ESC-F to Go Back to Option:");
#else
	STRCPY(s_sth.s_mesg,"Appuyer sur ESC-F pour retourner a option:");
#endif
	ShowMesg();

	fomca1(FROMSUPP_FLD, 19, 2) ;
	STRCPY(s_sth.s_fm_supp, "0");

	if(s_sth.s_option[0] != INQUIRY) {
		fomca1(TOSUPP_FLD, 19, 2) ;
		STRCPY(s_sth.s_to_supp, "ZZZZZZZZZZ");
	}
	if(s_sth.s_option[0] == INQUIRY) {
		fomca1(TOTRDATE_FLD, 19, 2) ;
		s_sth.s_to_date = 99991231 ;
	}
	sr.nextfld = RANGES_START ;
	sr.endfld  = RANGES_END ;
	fomud((char*)&s_sth);
	ret(err_chk(&sr));

	InitRanges(LV_CHAR, LV_LONG) ;

	i = ReadFields(RANGES_START, RANGES_END) ;
	if(PROFOM_ERR == i || DBH_ERR == i) return(i) ;
	if(i == NOERROR) {
#ifdef ENGLISH
		sort_opt = GetOption("Sort by S(upplier code), T(rans date), P(eriod)?","STP");
#else
		sort_opt = GetOption("Trie par C(ode de fournisseur), D(ate de trans), P(eriode)?","CDP");
#endif
		if(PROFOM_ERR == sort_opt) return(sort_opt) ;

#ifdef ENGLISH
		i = GetOption("Confirm (Y/N)?", "YN") ;
#else
		i = GetOption("Confirmer (O/N)?", "ON") ;
#endif
		if(PROFOM_ERR == i) return(i) ;
		if(i == YES) return(NOERROR) ;
	}
	/* RET_USER_ESC */
	InitRanges(HV_CHAR,HV_LONG) ;
	ret( WriteFields(RANGES_START, RANGES_END) ) ;
	s_sth.s_mesg[0] = HV_CHAR;
	ShowMesg();
	return(ERROR) ;
}	/*  ReadRanges() */
/*------------------------------------------------------------*/
/* Read the PROFOM Screen for a given Range of fields */

ReadFields(st_fld, end_fld)
int	st_fld ;
int	end_fld ;
{
	int	err ;

	sr.nextfld = st_fld ;
	sr.endfld  = end_fld ;

	for( ; ;){
		fomrd( (char*)&s_sth );
		ret(err_chk(&sr));
		if(sr.retcode == RET_VAL_CHK){
			err = Validate() ;
			if(DBH_ERR == err || PROFOM_ERR == err) return(err);
			sr.nextfld = sr.curfld ;
			continue;
		}
		if(sr.retcode == RET_USER_ESC){
			if(sr.escchar[0] == 'f' || sr.escchar[0] == 'F')
				return(RET_USER_ESC) ;
			sr.nextfld = sr.curfld ;
			continue;
		}
		/* else RET_NO_ERROR */
		break;
	}

	return(NOERROR) ;
}	/* ReadFields() */
/*----------------------------------------------------------------*/
/* Validation function() for Data fields when PROFOM returns RET_VAL_CHK */

Validate()
{
	int retval;

	switch(sr.curfld){
	case	FROMSUPP_FLD	:	/* To Supplier Cd: */
		Right_Justify_Numeric(s_sth.s_fm_supp,
						(sizeof(s_sth.s_fm_supp)-1));
		break;
	case	TOSUPP_FLD	:	/* To Supplier Cd: */
		Right_Justify_Numeric(s_sth.s_to_supp,
				(sizeof(s_sth.s_to_supp)-1));
		if(strcmp(s_sth.s_to_supp, s_sth.s_fm_supp) < 0 ||
				s_sth.s_to_supp[0] == '\0') {
#ifdef ENGLISH
			fomer("Invalid Range");
#else
			fomer("Excede les limites");
#endif
			s_sth.s_fm_supp[0] = LV_CHAR ;
			s_sth.s_to_supp[0] = LV_CHAR ;
			sr.curfld = FROMSUPP_FLD ;
			return(ERROR) ;
		}
		break ;
	case	CUTOFFDT_FLD	:	/* Cutoff Date: */
		if((s_sth.s_cutoff_dt + 10000) > s_sth.s_rundate) {
#ifdef ENGLISH
			fomer("Purge Date Must Be At Least One Year Ago") ;
#else
			fomer("Date de l'elimination doit etre au moins un an passe");
#endif
			s_sth.s_cutoff_dt = LV_LONG ;
			return(ERROR) ;
		}
		break ;
	case	TOTRDATE_FLD	:	/* To Trans Date: */
		if(s_sth.s_to_date < s_sth.s_fm_date || s_sth.s_to_date == 0) {
#ifdef ENGLISH
			fomer("Invalid Range");
#else
			fomer("Option invalide");
#endif
			s_sth.s_fm_date = LV_LONG ;
			s_sth.s_to_date = LV_LONG ;
			sr.curfld = FROMTRDATE_FLD ;
			return(ERROR) ;
		}
		break ;
	default :
#ifdef ENGLISH
		sprintf(e_mesg,"No Validity Check For Field#  %d",sr.curfld);
#else
		sprintf(e_mesg,"Pas de controle de validite pour le Champ#  %d",sr.curfld);
#endif
		fomen(e_mesg);
		get();
		return(ERROR) ;
	}	/* Switch sr.curfld */

	return(NOERROR) ;
}	/* Validate() */
/*-------------------------------------------------------------------------*/
/* MOve low/High Values to Ranges fields */

InitRanges(t_char, t_long)
char	t_char ;
long	t_long ;
{


	if(t_long == LV_LONG) {
		s_sth.s_fm_supp[0] = t_char ;
		if(s_sth.s_option[0] != INQUIRY)
			s_sth.s_to_supp[0] = t_char ;
		if(s_sth.s_option[0] == INQUIRY) {
			s_sth.s_invc_no[0] = t_char ;
			s_sth.s_fm_date    = t_long ;
			s_sth.s_to_date    = t_long ;
		}
		if(s_sth.s_option[0] == PURGE)
			s_sth.s_cutoff_dt  = t_long ;
	}
	else {
		s_sth.s_fm_supp[0] = t_char ;
		s_sth.s_to_supp[0] = t_char ;
		s_sth.s_cutoff_dt  = t_long ;
		s_sth.s_invc_no[0] = t_char ;
		s_sth.s_fm_date    = t_long ;
		s_sth.s_to_date    = t_long ;
	}

	return(NOERROR) ;
}	/* InitRanges() */
/*------------------------------------------------------------------------*/
/* Write fields on Screen for a given Range */

WriteFields(st_fld, end_fld)
int	st_fld ;
int	end_fld ;
{
	sr.nextfld = st_fld ;
	sr.endfld  = end_fld ;

	fomwr( (char*)&s_sth ) ;
	ret(err_chk(&sr));

	return(NOERROR) ;
}	/* WriteFields() */
/*-----------------------------------------------------------------------*/
/* Display message and get the option */

GetOption(msg,options)
char	*msg ;
char	*options ;
{
	int	i, j ;

	STRCPY(s_sth.s_mesg, msg);
	ShowMesg() ;

	sr.nextfld = END_FLD ;
	for( ; ; ) {
		fomrf( (char*)&s_sth ) ;
		ret(err_chk(&sr)) ;

		j = strlen(options) ;
		for( i = 0 ; i < j ; i++)
			if(s_sth.s_resp[0] == options[i]) break ;
		if(i != j) break ;	/* Valid Option Selected */
#ifdef ENGLISH
		fomer("Invalid Option..");
#else
		fomer("Option invalide..");
#endif
	}
	s_sth.s_mesg[0] = HV_CHAR;
	s_sth.s_resp[0] = HV_CHAR;

	ret( WriteFields((END_FLD - 100), END_FLD) );

	return((int)(options[i])) ;
}	/* GetOption() */
/*-------------------------------------------------------------------------*/
/* Copy the given message to SCR message line, display it and seek
   user response */

DispError(s)    /* show ERROR and wait */
char	*s;
{
	STRCPY(s_sth.s_mesg, s);
	ShowMesg();
#ifdef ENGLISH
	fomen("Press any key to continue");
#else
	fomen("Appuyer sur une touche pour continuer");
#endif
	get();
	s_sth.s_mesg[0] = HV_CHAR;
	ShowMesg();

	return(NOERROR);
}	/* DispError() */
/*-------------------------------------------------------------------------*/
/* Write the Message Field */

ShowMesg()  /* shows or clears message field */
{
	sr.nextfld = END_FLD - 100;
	fomwf( (char*)&s_sth ) ;

	return(NOERROR) ;
}	/* ShowMesg() */
/*------------------------------------------------------------*/
/* Read the AP History records and display it on the screen */

DisplayHistory()
{
	int	err, suppress ;
	char	pre_supp[11] ;
	char	pre_invc[16] ;
	char	pre_type[3] ;
	double	diff ;

	err = opn_prnt( "D", sr.termnm, 0, e_mesg, 0) ;
	if(err < 0) {
		DispError(e_mesg) ;
		return(ERROR) ;
	}
	cur_pos = 0 ;
	linecnt = PGSIZE ;
	LNSZ = 80 ;
	pgcnt = 0 ;

	fomcs() ;
	fomrt() ;

	STRCPY(ap_hist.a_supp_cd, s_sth.s_fm_supp) ;
	STRCPY(ap_hist.a_invc_no, s_sth.s_invc_no) ;
	ap_hist.a_tr_type[0] = '\0';
	ap_hist.a_sno = 0 ;
	ap_hist.a_tr_date = 0;
	ap_hist.a_period = 0;
	flg_reset(APHIST) ;

	for ( ; ; ) {
		if(sort_opt == SORT_BY_PD)
			err=get_n_aphist(&ap_hist, BROWSE, 1, FORWARD, e_mesg) ;
		else
		if(sort_opt == SORT_BY_TRDT)
			err=get_n_aphist(&ap_hist, BROWSE, 2, FORWARD, e_mesg) ;
		else
		if(sort_opt == SORT_BY_SUPP)
			err=get_n_aphist(&ap_hist, BROWSE, 0, FORWARD, e_mesg) ;
	
		if(err == ERROR) return(DBH_ERR) ;
		if(err == EFL) break ;

		if(ap_hist.a_tr_date > s_sth.s_to_date) continue ;
		if(ap_hist.a_tr_date < s_sth.s_fm_date) continue ;

		if(linecnt >= PGSIZE || strcmp(ap_hist.a_supp_cd, pre_supp) ) {
			err = PrintHeadings() ;
			if(err < 0) break ;
			STRCPY(pre_supp, ap_hist.a_supp_cd) ;
			suppress = 0 ;
		}
		if(strcmp(pre_invc, ap_hist.a_invc_no) ||
				strcmp(pre_type, ap_hist.a_tr_type)) {
			STRCPY(pre_invc, ap_hist.a_invc_no) ;
			STRCPY(pre_type, ap_hist.a_tr_type) ;
			suppress = 0 ;
		}
		if(suppress == 0) {
			mkln(1, ap_hist.a_invc_no,15) ;
			mkln(17,ap_hist.a_tr_type,2);
			suppress = 1 ;
		}
		mkln(19, " ", 1);
		tedit((char*)&ap_hist.a_tr_date,DATE_MASK,line+cur_pos,R_LONG) ;
		cur_pos += 10 ;
		if(ap_hist.a_paid[0] == YES) 
#ifdef ENGLISH
			mkln(31, "YES", 3);
#else
			mkln(31, "OUI", 3);
#endif
		mkln(34, " ", 1);
		tedit((char*)&ap_hist.a_chq_no, MASK_8, line+cur_pos, R_LONG) ;
		cur_pos += 8 ;
		tedit((char*)&ap_hist.a_gr_amt, MASK_12_2,
				line+cur_pos, R_DOUBLE) ;
		cur_pos += 14 ;
		tedit((char*)&ap_hist.a_disc_taken, MASK_4_2,
				line+cur_pos, R_DOUBLE) ;
		cur_pos += 9;
		diff = ap_hist.a_gr_amt - ap_hist.a_disc_taken ;
		diff = D_Roundoff(diff);
		tedit((char*)&diff, MASK_12_2, line+cur_pos, R_DOUBLE) ;
		cur_pos += 14 ;
		if((err = prnt_line() < 0)) break ;
	}
	seq_over(APHIST) ;

	if(pgcnt && err != QUIT)
		last_page() ;
	close_rep(BANNER) ;

	fomst() ;
	ret( WriteFields(1, 0) );

	if(pgcnt == 0) {
#ifdef ENGLISH
		fomen("No Records...");
#else
		fomen("Pas de fiches...");
#endif
		get() ;
	}

	return(NOERROR) ;
}	/* DisplayHistory() */
/*------------------------------------------------------------*/
/* Print Headings */
static	int
PrintHeadings()
{
	int	i,err ;

	if(pgcnt) {
		if(next_page() < 0) return(QUIT) ;
	}
	rite_top() ;
	linecnt = 0 ;

	/* Print Program-Id, School District name and Date */
	mkln(1,PROG_NAME, 10) ;
	i = strlen(pa_rec.pa_co_name);
	mkln(((LNSZ-1-i) / 2)+1,pa_rec.pa_co_name, i);
#ifdef ENGLISH
	mkln(64,"Date: ",6);
#else
	mkln(64,"Date: ",6);
#endif
	tedit((char*)&s_sth.s_rundate, DATE_MASK, line+cur_pos,R_LONG);
	cur_pos += 10;
	if(prnt_line() < 0) return(ERROR);
	
	pgcnt++ ;
#ifdef ENGLISH
	mkln(30, "TRANSACTION  HISTORY", 20) ;
	mkln(64,"Page: ",6);
#else
	mkln(27, "HISTORIQUE DES TRANSACTIONS", 27) ;
	mkln(64,"Page: ",6);
#endif

	tedit((char*)&pgcnt, MASK_3, line+cur_pos,R_SHORT);
	cur_pos += 3 ;
	if(prnt_line() < 0) return(ERROR);

	/* Get Supplier To Display Name */
	STRCPY(supplier.s_supp_cd, ap_hist.a_supp_cd); 	
	err = get_supplier(&supplier,BROWSE,0,e_mesg);

	if( (err==ERROR) || (supplier.s_name[0] == '\0') ||
	    (err==UNDEF) ){
#ifdef ENGLISH
		STRCPY(supplier.s_name, "*  N/A  *"); 
#else
		STRCPY(supplier.s_name, "*  P/D  *"); 
#endif
		if (err==ERROR && err!=UNDEF) return(err);
	}
	
#ifdef ENGLISH
	mkln(1,"Supplier Cd:", 12);
#else
	mkln(1,"Cd du fourn:", 12);
#endif
	mkln(14,ap_hist.a_supp_cd, 10) ;

	mkln(26,supplier.s_name,49 );
	if(prnt_line() < 0) return(ERROR);
	if(prnt_line() < 0) return(ERROR);

	/* Print Column Headings */
#ifdef ENGLISH
	mkln(4, "Tran Ref#    Type   Date   Paid? Cheque#   Gross Amt", 52);
	mkln(57, "Disc Taken  Net Amount", 22) ;
#else
	mkln(3, "#Ref de tran Genre   Date  Paye?  #Cheque  Mont. brut", 53);
	mkln(57, "Escpte prise  Mont. net", 25) ;
#endif
	if(prnt_line() < 0) return(ERROR);
	if(prnt_line() < 0) return(ERROR);

	return(NOERROR) ;
}	/* PrintHeadings() */
/*-------------------------------------------------------------------*/
/* Print the AP History for given ranges. If PURGE option, then purge the
    Paid transactions */

TransHistory()
{
	char	chardate[11];
	char	projname[50] ;
	int	code, no_recs ;
	char 	*arayptr[5] ; 	/** Declarations for Report writer usage **/
	
	/* Form the project name with full path */
	STRCPY(projname,FMT_PATH) ;
	strcat(projname,PROJECT) ;

	mkdate(get_date(),chardate);

	code = rpopen(projname,LOGREC,FORMAT,2,"\0",PROG_NAME,chardate);
	if ( code < 0 ){
#ifdef ENGLISH
		sprintf(e_mesg,"REPORT-WRITER ERROR... rpopen()   rperror: %d",
#else
		sprintf(e_mesg,"ERREUR DU REPORT-WRITER... rpopen()   rperror: %d",
#endif
			rperror ) ;
		DispError(e_mesg) ;
		return(ERROR) ;
	}

	/* Change first title line to Company/School district name */
	rpChangetitle(1, pa_rec.pa_co_name);

	if(s_sth.s_option[0] == PURGE) {
#ifdef ENGLISH
		rpChangetitle(2, "TRANSACTION HISTORY - PURGE");
#else
		rpChangetitle(2, "HISTORIQUE DES TRANSACTIONS - EFFACER");
#endif
#ifdef ENGLISH
		STRCPY(e_mesg, "Cutoff Date: ") ;
#else
		STRCPY(e_mesg, "Date de demarcation: ") ;
#endif
		tedit((char*)&s_sth.s_cutoff_dt, DATE_MASK,
			e_mesg+strlen(e_mesg), R_LONG) ;
		rpChangetitle(3, e_mesg) ;
	}
	else {
#ifdef ENGLISH
		rpChangetitle(2, "TRANSACTION HISTORY - LIST");
#else
		rpChangetitle(2, "HISTORIQUE DES TRANSACTIONS - LISTE");
#endif
		rpChangetitle(3, "\0") ;
	}

	arayptr[0] = (char*)&ap_hist ;
	arayptr[1] = (char*)&supplier ;
	arayptr[2] = NULL ;

	STRCPY(ap_hist.a_supp_cd, s_sth.s_fm_supp) ;
	ap_hist.a_invc_no[0] = '\0' ;
	ap_hist.a_tr_type[0] = '\0' ;
	ap_hist.a_tr_date = 0;
	ap_hist.a_period  = 0;
	ap_hist.a_sno     = 0 ;
	flg_reset( APHIST );
	flg_reset(SUPPLIER);

	no_recs = 0 ;
	for( ; ; ) {
		if(sort_opt == SORT_BY_PD)
			code=get_n_aphist(&ap_hist, BROWSE, 1, FORWARD, e_mesg);
		else
		if(sort_opt == SORT_BY_TRDT)
			code=get_n_aphist(&ap_hist, BROWSE, 2, FORWARD, e_mesg) ;
		else
		if(sort_opt == SORT_BY_SUPP)
			code=get_n_aphist(&ap_hist, BROWSE, 0, FORWARD, e_mesg) ;
		
		if( code == ERROR) {
			rpclose() ;
			return(DBH_ERR) ;
		}
		if(code == EFL) break ;

		if(strcmp(ap_hist.a_supp_cd, s_sth.s_to_supp) > 0) break ;
		if(strcmp(ap_hist.a_supp_cd, s_sth.s_fm_supp) < 0) continue ;

			/* read supplier record, retrieve supplier name if
			   found, otherwise supplier name 'NOT AVAILABLE'  */

		STRCPY(supplier.s_supp_cd, ap_hist.a_supp_cd); 	
		code = get_supplier(&supplier,BROWSE,0,e_mesg);

		if( (code==ERROR) || (supplier.s_name[0] == '\0') ||
		    (code==UNDEF) ){
#ifdef ENGLISH
			STRCPY(supplier.s_name, "*  N/A  *"); 
#else
			STRCPY(supplier.s_name, "*  P/D  *"); 
#endif
			if (code==ERROR && code!=UNDEF) return(code);
		}
		if(s_sth.s_option[0] == PURGE) {
			if(ap_hist.a_tr_date > s_sth.s_cutoff_dt) continue ;
			if(ap_hist.a_paid[0] != YES) continue ;

			/* Get in Update mode for deletion */
			code = get_aphist(&ap_hist,UPDATE,0,e_mesg);
			if(code == ERROR) return(DBH_ERR) ;
			if(code < 0) {
				DispError(e_mesg);
				/* Increment the last part of the key to get
				   the next rec after random read */
				ap_hist.a_sno++ ;
				continue ;
			}
		}

		code = rpline(arayptr) ;
		if ( code < 0 ){
#ifdef ENGLISH
		    sprintf(e_mesg,"REPORT-WRITER ERROR...rpline() rperror: %d",
#else
		    sprintf(e_mesg,"ERREUR DU REPORT-WRITER...rpline() rperror: %d",
#endif
			rperror) ;
		    DispError(e_mesg) ;
		    break ;
		}

		no_recs++ ;
	
		if(s_sth.s_option[0] == PURGE) {
			code = put_aphist(&ap_hist,P_DEL,e_mesg);
			if(code < 0) {
				DispError(e_mesg) ;
				rpclose() ;
				return(DBH_ERR) ;
			}
			if((no_recs % 10) == 0 ){
				if(commit(e_mesg) < 0) {
					DispError(e_mesg) ;
					rpclose() ;
					return(DBH_ERR) ;
				}
			}
			/* Increment the last part of the key to get the next
			    rec after random read */
			ap_hist.a_sno++ ;
		}
	}
	seq_over(APHIST) ;

	if(s_sth.s_option[0] == PURGE && no_recs) {
		if((no_recs % 10) != 0 ){
			if(commit(e_mesg) < 0) {
				DispError(e_mesg) ;
				rpclose() ;
				return(DBH_ERR) ;
			}
		}
		/* Print Total */
		if(rpPutline() < 0) return(REPORT_ERR);
#ifdef ENGLISH
		rpMkline(1,"Deleted:");
#else
		rpMkline(1,"Elimine:");
#endif
		sprintf(e_mesg,"%d",no_recs);
		rpMkline(2,e_mesg);
		if(rpPutline() < 0) return(REPORT_ERR);
	}
	rpclose() ;

	if(no_recs == 0) {
#ifdef ENGLISH
		fomen("No Records...");
#else
		fomen("Pas de fiches...");
#endif
		get() ;
	}
	return(NOERROR) ;
}	/* TransHistory() */
/*-------------------- E n d   O f   P r o g r a m ---------------------*/

