/*------------------------------------------------------------------------
Source Name: roe_prt.c
System     : Personnel/Payroll.
Created  On: November 27, 1991.
Created  By: Eugene Roy.

DESCRIPTION:
	Program to print Record of Employments.

MODIFICATIONS:        

Programmer     YY/MM/DD       Description of modification
~~~~~~~~~~     ~~~~~~~~       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
------------------------------------------------------------------------*/
#define 	MAIN 

#include <stdio.h>
#include <cfomstrc.h>
#include <repdef.h>
#include <bfs_defs.h>
#include <bfs_com.h>
#include <bfs_pp.h>

#define	SYSTEM		"PERSONNEL/PAYROLL"	/* Sub System Name */
#define	MOD_DATE	"27-NOV-91"		/* Program Last Modified */
#define	SCR_NAME	"roe_prt"		/* First screen */

#define	ST_FLD		400 
#define	END_FLD		600 
#define MESG_FLD	700
#define PRINTER_FLD	400
#define OPTION_FLD	500

#define EXIT	12

#ifdef ENGLISH

#define PRINTROE	'P'
#define EXITOPT	'E'

#define	YES	'Y'
#define NO	'N'
#define EDIT	'E'
#define CANCEL	'C'

#else

#define PROCCHQ	'P'
#define EXITOPT	'F'

#define	YES	'O'
#define NO	'N'
#define EDIT	'M'
#define CANCEL	'A'

#endif
/* cheque.sth - header for C structure generated by PROFOM EDITOR */

typedef struct	{

	char	s_pgm[11];	/* STRING XXXXXXXXXX 	Field 100 */
	long	s_rundate;	/* NUMERIC 9999F99F99 	Field 300 */
	short	s_printer;	/* NUMERIC 99 		Field 800 */
	char	s_resp[2]; 	/* STRING X 		Field 900 */
	long	s_no_writ;	/* NUMERIC 99999 	Field 1000 */
	char	s_mesg[78];	/* STRING X(78) 	Field 1500 */
	char	s_opt[2];	/* STRING X 		Field 1600 */
	} S_STRUCT;

static	S_STRUCT	s_sth ;

/* PROFOM Related variables */

struct  	stat_rec  sr;	/* PROFOM status rec */

static	Pa_rec	param;
static	Gov_param	gov_param;
static	Pay_param	pay_param;
static	Sch_rec	scho;
static	Pay_per	pay_per;
static	Position	position;
static	Roe	roe;
static	Emp	emp_rec;
static	Barg_unit	barg_unit;

char 	e_mesg[100];	/* dbh will return err msg in this */
static	char	temp_buf[80] ;	/* work variable for tedit */

int	Validation();
int	Window();

double 	D_Roundoff();

static	char	emp_name[48];
static	short	tot_num_ins_wk;
static	double	total;

main(argc,argv)
int argc;
char *argv[];
{

	strncpy(SYS_NAME,SYSTEM,50);	/* Sub system name */
	strncpy(CHNG_DATE,MOD_DATE,10);	/* Modification Date */
	proc_switch(argc, argv, CHQHIST) ; 	/* Process Switches */

	STRCPY(sr.termnm,terminal);	/* Copy Terminal Name */

	if (Initialize()<0)
		exit(-1);		/* Initialization routine */

	if ( Process() < 0) { 		/* Initiate Process */
		Close();
		exit(-1);
	}

	Close();			/* return to menu */
	exit(NOERROR);

} /* END OF MAIN */

/*-------------------------------------------------------------------*/
/* Reset information */
Close()
{
	/* Set terminal back to normal mode from PROFOM */

	fomcs();
	fomrt();
	close_dbh();			/* Close files */
	close_rep();
}
/*-------------------------------------------------------------------*/
/* Initialize PROFOM  and Screens*/
Initialize()
{
	if(InitProfom()<0) { 			/* Initialize PROFOM */
		fomcs();
		fomrt();
		return(-1);
	}	
	if(InitScreens()<0) { 
		fomcs();
		fomrt();
		return(-1);
	}	
	return(NOERROR);
}

/*-------------------------------------------------------------------*/
/* Initialize PROFOM */

InitProfom()
{
	fomin(&sr);
	/* Check for Error */
	ret( err_chk(&sr) );

	fomcf(1,1);			/* Enable Print screen option */
	return(NOERROR);
}	/* InitProfom() */
/*----------------------------------------------------------------*/
/* Initialize screens before going to process options */
InitScreens()
{
	int	retval ;

	STRCPY(sr.scrnam,NFM_PATH);
	strcat(sr.scrnam,SCR_NAME) ;

	STRCPY(s_sth.s_pgm,PROG_NAME);
	s_sth.s_rundate = get_date();	/* get Today's Date in YYMMDD format */
	s_sth.s_mesg[0] = HV_CHAR ;
	s_sth.s_opt[0] = HV_CHAR ;

	/* Move High Values to 1st screen data fields & Display */
	retval = ClearScreen() ;
	if( retval < 0 ) return(-1) ;

	return(NOERROR);

}	/* InitScreens() */
/*-----------------------------------------------------------------*/
InitPrinter()
{
	char	resp[2] ;
	char	discfile[15] ;

	/* Always to Printer */
	STRCPY( resp, "P" );
	discfile[0] = '\0';

	if( opn_prnt( resp, discfile, s_sth.s_printer, e_mesg, 0 )<0 ){
		fomen(e_mesg); get();
		return(-1);
	}
	return(NOERROR) ;
}
/*-----------------------------------------------------------------*/
InitPrinter1()
{
	char	resp[2] ;
	char	discfile[15] ;

	/* Always to Printer */
	STRCPY( resp, "F" );
	strcpy(discfile,"roe.dat");

	if( opn_prnt( resp, discfile, s_sth.s_printer, e_mesg, 0 )<0 ){
		fomen(e_mesg); get();
		return(-1);
	}
	return(NOERROR) ;
}
/*-----------------------------------------------------------------*/
/* Clears the screen. 						   */
ClearScreen()
{
	s_sth.s_resp[0] = LV_CHAR ;
	
	return(WriteFields((char *)&s_sth,ST_FLD,END_FLD) ) ;
}
/*-----------------------------------------------------------------*/
Process()
{
	int	err;

	s_sth.s_mesg[0] = HV_CHAR;
	DispMesgFld((char *)&s_sth);	
	for( ; ; ){

#ifdef ENGLISH
		fomer("P(rint), E(xit)");
#else
		fomer("I(mprimer), F(in)");
#endif
		sr.nextfld = OPTION_FLD;
		fomrf((char *)&s_sth);
		ret(err_chk(&sr));

		switch(s_sth.s_resp[0]) {
		case  EXITOPT :
			return(EXIT);
		case  PRINTROE :
			CHKACC(err,ADD,e_mesg);	
			CHKACC(err,UPDATE,e_mesg);	
			err = RoeProcess() ;
			break ;
		default :
			continue;
		}

		if(NOACCESS == err) {
			fomen(e_mesg);
			get();
		}
		if(PROFOM_ERR == err)	return(PROFOM_ERR);  /* PROFOM ERROR */
		if(DBH_ERR == err) {
			DispError((char *)&s_sth,e_mesg);
#ifdef ENGLISH
			sprintf(e_mesg,"%s %d Dberror: %d Errno: %d",
				"System Error... Iserror:",
				iserror, dberror, errno);
#else
			sprintf(e_mesg,"%s %d Dberror: %d Errno: %d",
				"Erreur du systeme... Iserror:",
				iserror, dberror, errno);
#endif
			DispError((char *)&s_sth,e_mesg);
			return(DBH_ERR); /* DBH ERROR */
		
		}
	}      /*   end of the for( ; ; )       */
}
/*-----------------------------------------------------------------*/
RoeProcess()
{
	int 	retval ;
	int	prntno;
	char	devname[30];

	retval = ReadInfo() ;
	if( retval < 0 ) return(retval) ;
	if( retval == EXIT ) return(NOERROR) ;

	retval = ConfirmScreen() ;
	if( retval != YES ) 
		return(NOERROR) ;
	
#ifdef ENGLISH
        retval = GetOption((char *)&s_sth, "Are you ready to print ROEs (Y/N)?","YN") ;
#else
        retval = GetOption((char *)&s_sth, "Etes-vous prets a imprimer les releve d'emplois (O/N)?","ON") ;
#endif

	if(retval != YES) 
	return(NOERROR) ;

	LNSZ = 132;		/* line size in no. of chars */
	if(InitPrinter()<0) {
		return(-1);
	}	

	retval = DoTestPrint() ;

	close_rep();
	if(InitPrinter1()<0) {
		return(-1);
	}	

	retval = RoeProc();
	if( retval < 0 ) 
		return(retval) ;

	close_rep();

	/* Printer option */
	prntno = s_sth.s_printer;
	retval = get_prn_fd(prntno,devname);
	if(retval < 0){

#ifdef ENGLISH
		strcpy(s_sth.s_mesg,"Given Printer# NOT Found in Terminal/Printer ");
		strcat(s_sth.s_mesg,"Maintenance File");
#else
		strcpy(s_sth.s_mesg,"#d'imprimante donne pas retrouve dans le Dossier d'entretien");
		strcat(s_sth.s_mesg," du term/imprimante");
#endif
		return(-1);
	}

	strcpy(e_mesg,"cat roe.dat > ");
	strcat(e_mesg,devname);
	system(e_mesg);
	strcpy(e_mesg,"echo  > ");
	strcat(e_mesg,devname);
	system(e_mesg);

	DispMesgFld((char *)&s_sth);
	fflush(stdout) ;
	retval = WriteFields((char *)&s_sth,ST_FLD,END_FLD) ;

	return(NOERROR) ;
 
}
/*-----------------------------------------------------------------------*/
/*                                                                       */
/* Reads Cheque processing information.                                  */
ReadInfo()
{
	int 	i,retval ;

	/* In Add mode turn off dup control for key fields.
	   Other modes reverse it */
	fomca1(750,19,2) ;	/* The printer duplication and ESC F */
	fomca1(750,10,1) ;

	sr.endfld = PRINTER_FLD;
	fomud((char*)&s_sth);	/* Update Dup Buffers */

#ifdef ENGLISH
	STRCPY(s_sth.s_mesg,"Press ESC-F to Go Back to Option:");
#else
	STRCPY(s_sth.s_mesg,"Appuyer sur ESC-F pour retourner a Option:");
#endif
	DispMesgFld((char *)&s_sth);

	s_sth.s_printer = 1 ;
	retval = WriteFields((char *)&s_sth,PRINTER_FLD,PRINTER_FLD) ;
	if (retval < 0) return(retval) ; 
	s_sth.s_printer = LV_SHORT ;

	i = ReadFields((char *)&s_sth,PRINTER_FLD, PRINTER_FLD,Validation,Window,1); 
	if(PROFOM_ERR == i || DBH_ERR == i) return(i) ;
	if(EXIT == i){
		s_sth.s_mesg[0] = HV_CHAR;
		DispMesgFld((char *)&s_sth);
		return(i) ;
	}
	return(NOERROR) ;
}

/*-----------------------------------------------------------------------*/
/*  Printing the Test as many times needed for cheques to line up        */
DoTestPrint()
{
	int 	i,	retval ;

	STRCPY(temp_buf, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX") ;

	for( ; ; ) {
#ifdef ENGLISH
		retval = GetOption((char *)&s_sth,"Do you want a Test Print (Y/N)?","YN") ;
#else
		retval = GetOption((char *)&s_sth,"Desirez-vous un test d'impression (O/N)?","ON") ;
#endif

		if( retval == NO ) 
			break ;
		if( prnt_line() < 0) return(-1) ;
		if( prnt_line() < 0) return(-1) ;
		if( prnt_line() < 0) return(-1) ;

		/* Serial No. */
		mkln(30,temp_buf,10) ;
		/* Empl ref. numb. */
		mkln(58,temp_buf,20) ;
		if( prnt_line() < 0) return(-1) ;
		if( prnt_line() < 0) return(-1) ;

		/* School name */
		mkln(8,temp_buf,30) ;
		if( prnt_line() < 0) return(-1) ;

		/* Address 1 and Rev Can business No. */
		mkln(8,temp_buf,30) ;
		mkln(58,temp_buf,20) ;
		if( prnt_line() < 0) return(-1) ;
		/* Address 2 */
		mkln(8,temp_buf,30) ;
		if( prnt_line() < 0) return(-1) ;
	
		/* Address 3 & Pay period type */
		mkln(8,temp_buf,30) ;
		mkln(58,temp_buf,17) ;

		if( prnt_line() < 0) return(-1) ;
		if( prnt_line() < 0) return(-1) ;
		if( prnt_line() < 0) return(-1) ;

		/* Postal Code */
		mkln(45,temp_buf,3) ;
		mkln(49,temp_buf,3) ;
		/* SIN # */
		mkln(58,"XXX-XXX-XXX",11) ;

		if( prnt_line() < 0) return(-1) ;
		if( prnt_line() < 0) return(-1) ;

		/* Name of emp */
		mkln(8,temp_buf,30);
		/* First Day Worked */
		mkln(73,"99",2) ; 
		mkln(77,"99",2) ; 
		mkln(81,"99",2) ; 
		if( prnt_line() < 0) return(-1) ;
		/* Employee address 1 */
		mkln(8,temp_buf,30) ;
		if( prnt_line() < 0) return(-1) ;
		/* Employee address 2 */
		mkln(8,temp_buf,30) ;
		if( prnt_line() < 0) return(-1) ;
		/* Employees address 3 */
		mkln(8,temp_buf,30) ;
		/* Emp last day paid */
		mkln(73,"99",2) ; 
		mkln(77,"99",2) ; 
		mkln(81,"99",2) ; 
		if( prnt_line() < 0) return(-1) ;
		/* Employees address 4 */
		mkln(8,temp_buf,30) ;
		if( prnt_line() < 0) return(-1) ;

		/* Employee Postal code */
		mkln(8,"ZZZZZZZZZ9",10) ;
		/* Final Pay Ending Date */
		mkln(73,"99",2) ; 
		mkln(77,"99",2) ; 
		mkln(81,"99",2) ; 
		if( prnt_line() < 0) return(-1) ;
		if( prnt_line() < 0) return(-1) ;
		if( prnt_line() < 0) return(-1) ;
		/* Ocupation */
		mkln(8,temp_buf,30) ;
		/* Recall */
		mkln(47,"X",1);
		mkln(56,"X",1);
		/* Recall date */
		mkln(73,"99",2) ; 
		mkln(77,"99",2) ; 
		mkln(81,"99",2) ; 
		if( prnt_line() < 0) return(-1) ;
		if( prnt_line() < 0) return(-1) ;
		if( prnt_line() < 0) return(-1) ;

		/* Ins. Hours from chart on back */
		mkln(35,"Z,ZZ9.99",8);
		/* ROE Code */
		mkln(74,temp_buf,1);
		if( prnt_line() < 0) return(-1) ;
		if( prnt_line() < 0) return(-1) ;
		if( prnt_line() < 0) return(-1) ;

		/* Contact Person */
		mkln(48,temp_buf,15) ; 
		if( prnt_line() < 0) return(-1) ;

		/* Total ins earnings from chart on back */
		mkln(35,"Z,ZZ9.99",8);
		mkln(59,"999 999-9999",12);

		if( prnt_line() < 0) return(-1) ;
		if( prnt_line() < 0) return(-1) ;
		if( prnt_line() < 0) return(-1) ;
		if( prnt_line() < 0) return(-1) ;
		if( prnt_line() < 0) return(-1) ;

		/* First 3 insurance earnings */
		mkln(4,"Z,ZZ9.99",8) ; 
		mkln(19,"Z,ZZ9.99",8) ; 
		mkln(34,"Z,ZZ9.99",8) ; 

		/* Vacation Pay */
		mkln(50,"ZZ,ZZZ.ZZ",9);

		/* Stat Holiday Pay */
		mkln(62,"99",2) ; 
		mkln(66,"99",2) ; 
		mkln(70,"99",2) ; 
		/* Stat Pat */
		mkln(73,"Z,ZZZ.ZZ",8);

		if( prnt_line() < 0) return(-1) ;
		if( prnt_line() < 0) return(-1) ;

		/* 4,5,6 insurance earnings */
		mkln(4,"Z,ZZ9.99",8) ; 
		mkln(19,"Z,ZZ9.99",8) ; 
		mkln(34,"Z,ZZ9.99",8) ; 

		/* Stat Holiday Pay */
		mkln(62,"99",2) ; 
		mkln(66,"99",2) ; 
		mkln(70,"99",2) ; 
		/* Stat Pat */
		mkln(73,"Z,ZZZ.ZZ",8);
		if( prnt_line() < 0) return(-1) ;

		/* 7,8,9 insurance earnings */
		mkln(4,"Z,ZZ9.99",8) ; 
		mkln(19,"Z,ZZ9.99",8) ; 
		mkln(34,"Z,ZZ9.99",8) ; 

		/* Stat Holiday Pay */
		mkln(62,"99",2) ; 
		mkln(66,"99",2) ; 
		mkln(70,"99",2) ; 
		/* Stat Pay */
		mkln(73,"Z,ZZZ.ZZ",8);
		if( prnt_line() < 0) return(-1) ;
		if( prnt_line() < 0) return(-1) ;

		/* 10,11,12 insurance earnings */
		mkln(4,"Z,ZZ9.99",8) ; 
		mkln(19,"Z,ZZ9.99",8) ; 
		mkln(34,"Z,ZZ9.99",8) ; 
		if( prnt_line() < 0) return(-1) ;

		/* 13,14,15 insurance earnings */
		mkln(4,"Z,ZZ9.99",8) ; 
		mkln(19,"Z,ZZ9.99",8) ; 
		mkln(34,"Z,ZZ9.99",8) ; 
		/* Other Monies */
		mkln(47,temp_buf,15) ; 
		mkln(73,"Z,ZZ9.99",8) ; 
		if( prnt_line() < 0) return(-1) ;
		if( prnt_line() < 0) return(-1) ;

		/* 16,17,18 insurance earnings */
		mkln(4,"Z,ZZ9.99",8) ; 
		mkln(19,"Z,ZZ9.99",8) ; 
		mkln(34,"Z,ZZ9.99",8) ; 
		/* Other Monies */
		mkln(47,temp_buf,15) ; 
		mkln(73,"Z,ZZ9.99",8) ; 
		if( prnt_line() < 0) return(-1) ;

		/* 19,20,21 insurance earnings */
		mkln(4,"Z,ZZ9.99",8) ; 
		mkln(19,"Z,ZZ9.99",8) ; 
		mkln(34,"Z,ZZ9.99",8) ; 
		/* Other Monies */
		mkln(47,temp_buf,15) ; 
		mkln(73,"Z,ZZ9.99",8) ; 
		if( prnt_line() < 0) return(-1) ;
		if( prnt_line() < 0) return(-1) ;

		/* 22,23,24 insurance earnings */
		mkln(4,"Z,ZZ9.99",8) ; 
		mkln(19,"Z,ZZ9.99",8) ; 
		mkln(34,"Z,ZZ9.99",8) ; 
		if( prnt_line() < 0) return(-1) ;

		/* 25,26,27 insurance earnings */
		mkln(4,"Z,ZZ9.99",8) ; 
		mkln(19,"Z,ZZ9.99",8) ; 
		mkln(34,"Z,ZZ9.99",8) ; 
		if( prnt_line() < 0) return(-1) ;
		if( prnt_line() < 0) return(-1) ;
		if( prnt_line() < 0) return(-1) ;
		if( prnt_line() < 0) return(-1) ;
		if( prnt_line() < 0) return(-1) ;
		if( prnt_line() < 0) return(-1) ;
		if( prnt_line() < 0) return(-1) ;

		/* Payment Start Date */
		mkln(5,"99",2) ; 
		mkln(9,"99",2) ; 
		mkln(13,"99",2) ; 
		/* Amount */
		mkln(21,"Z,ZZ9.99",8) ; 
		if( prnt_line() < 0) return(-1) ;
		if( prnt_line() < 0) return(-1) ;
		if( prnt_line() < 0) return(-1) ;

		/* Language */
		mkln(4,"X",1) ; 
		mkln(12,"X",1) ; 
		/* Phone Number */
		mkln(25,"999 999-9999",12);
		/* Total Ins Weeks */
		mkln(50,"ZZZ9",4) ; 
		/* Total Ins Earnings */
		mkln(72,"Z,ZZ9.99",8) ; 
		if( prnt_line() < 0) return(-1) ;
		if( prnt_line() < 0) return(-1) ;
		if( prnt_line() < 0) return(-1) ;
		if( prnt_line() < 0) return(-1) ;

		/* Name of issuer and date */
		mkln(40,temp_buf,20) ; 
		mkln(68,"99",2) ; 
		mkln(72,"99",2) ; 
		mkln(76,"99",2) ; 
		if( prnt_line() < 0) return(-1) ;

		rite_top();

#ifdef ENGLISH
		fomen("The Test Print Is Printing. Press any key to continue.");
#else
		fomen("La copie d'essaie imprime. Appuyer une touche pour continuer.");
#endif
		get();
	}
	return(NOERROR) ;
}
/*-----------------------------------------------------------------------*/
/*                                                                       */
/* Reads the cheque and prints the cheque after accumulating invoices.   */
RoeProc()
{
	int	retval ;

#ifdef ENGLISH
	STRCPY(s_sth.s_mesg, "ROE's being Printed, PLEASE WAIT");
#else
	STRCPY(s_sth.s_mesg, "Les RELEVE D'EMPLOI sont en train d'etre imprimes, ATTENDEZ S.V.P.");
#endif
	DispMesgFld((char *)&s_sth);
	fflush(stdout) ;

	s_sth.s_no_writ = 0 ;
	
	retval = get_param(&param,BROWSE,1,e_mesg);
	if(retval < 0){
		DispError((char *)&s_sth,e_mesg) ;
		roll_back(e_mesg);
		return(-1);
	}

	retval = get_pay_param(&pay_param,BROWSE,1,e_mesg);
	if(retval < 0){
		DispError((char *)&s_sth,e_mesg) ;
		roll_back(e_mesg);
		return(-1);
	}

	gov_param.gp_eff_date = get_date();

	flg_reset(GOV_PARAM);

	retval = get_n_gov_param(&gov_param,BROWSE, 0, BACKWARD, e_mesg) ;
	if(retval == EFL) {
		fomen("Government Parameter Record Not Setup");
		return(retval);
	}
	if(retval < 0) {
		fomer(e_mesg) ;
		return(ERROR) ;
	}

	scho.sc_numb = param.pa_distccno; 

	retval = get_sch(&scho,BROWSE,0,e_mesg);
	if(retval < 0){
		DispError((char *)&s_sth,e_mesg) ;
		return(-1);
	}

	roe.ro_emp_numb[0] = LV_CHAR;
	flg_reset(ROE) ;

	for( ; ; ){
		retval = get_n_roe(&roe,BROWSE,0,FORWARD,e_mesg) ;
		if(retval == EFL) 
			break;

		if( retval < 0) {
			DispError((char *)&s_sth,e_mesg) ;
			return(retval) ;
		}

		strcpy(emp_rec.em_numb,roe.ro_emp_numb);

		retval = get_employee(&emp_rec,UPDATE,0,e_mesg);
		if(retval < 0){
			DispError((char *)&s_sth,e_mesg) ;
			return(-1);
		}
		retval = PrntRec() ;
		if(retval < 0){
			DispError((char *)&s_sth,e_mesg) ;
			roll_back(e_mesg);
			return(retval);
		}

		emp_rec.em_last_roe = roe.ro_last_dt;
		emp_rec.em_num_ins_wk = tot_num_ins_wk;
		emp_rec.em_term_dt =  roe.ro_last_dt;
		strcpy(emp_rec.em_term, roe.ro_reason);

		retval = put_employee(&emp_rec,UPDATE,e_mesg);
		if(retval < 0) {
			DispError((char *)&s_sth,e_mesg);
			roll_back(e_mesg);
			return(retval);
		}

		retval = commit(e_mesg) ;
		if(retval < 0) {
#ifdef ENGLISH
		DispError((char *)&s_sth,"ERROR in Saving Records"); 
#else
		DispError((char *)&s_sth,"ERREUR en conservant les fiches");
#endif
			DispError((char *)&s_sth,e_mesg);
			roll_back(e_mesg);
			return(retval);
		}

		s_sth.s_no_writ++ ;
		WriteFields((char *)&s_sth,ST_FLD,END_FLD);
	}
	seq_over(ROE);

	if(s_sth.s_no_writ == 0){
#ifdef ENGLISH
		DispError((char *)&s_sth,"No ROE to Print");
#else
		DispError((char *)&s_sth,"Pas de releve d'emploi a imprimer");

#endif
		return(ERROR) ;
	}

#ifdef ENGLISH
	STRCPY(s_sth.s_mesg, "ROE Printed Successfully");
#else
	STRCPY(s_sth.s_mesg, "Impression des RELEVE D'EMPLOI reussie");
#endif
	DispMesgFld((char *)&s_sth) ;
	fflush(stdout) ;

	unlink_file(ROE);

	return(NOERROR) ;

}

/*----------------------------------------------------------------*/
/* Validation function() for Key and Header fields when PROFOM returns
  RET_VAL_CHK */

Validation()
{
	return(NOERROR) ;
}	/* Validation() */
/*----------------------------------------------------------------*/
Window()
{
	return(NOERROR);
}
/*-----------------------------------------------------------------------*/
/*                                                                       */
ConfirmScreen() 
{
	int	err ;

	for( ; ; ) {
#ifdef ENGLISH
		err = GetOption((char *)&s_sth,"Y(es), E(dit), C(ancel)", "YEC");
#else
		err = GetOption((char *)&s_sth,"O(ui), M(odifier), A(nnuler)",
									 "OMA");
#endif
		if(err == PROFOM_ERR) return(err) ;

		switch(err) {
		case  YES :
			return(YES) ;
		case  EDIT  :
			err = ReadInfo();
			break ;
		case  CANCEL :
#ifdef ENGLISH
			err = GetOption((char *)&s_sth,"Confirm the Cancel (Y/N)?", "YN") ;
#else
			err = GetOption((char *)&s_sth,"Confirmer l'annulation (O/N)?", "ON") ;
#endif
			if(err == YES) { 
				roll_back(e_mesg) ;	/* Unlock  Records */
				return(CANCEL) ;
			}
			break ;
		}	/* switch err */

		if(err == PROFOM_ERR) return(err) ;
		if(err == DBH_ERR) return(err) ;
	}	/* for(; ; ) */
}	/* ConfirmScreen() */

/*-------------------------------------------------------------------------*/
/*  Print Roe information				      */

PrntRec()
{
	long	dollars;
	int	i, retval;
	double	fraction;

	strcpy(position.p_code,emp_rec.em_pos);

	retval = get_position(&position,BROWSE,0,e_mesg);
	if(retval < 0){
		DispError((char *)&s_sth,e_mesg) ;
	}

	if( prnt_line() < 0) return(-1) ;
	if( prnt_line() < 0) return(-1) ;
	if( prnt_line() < 0) return(-1) ;

	/* Serial Numb. */
	mkln(30,roe.ro_serial,10) ;
	/* Emp Numb */
	mkln(58,emp_rec.em_numb,12) ;
	if( prnt_line() < 0) return(-1) ;
	if( prnt_line() < 0) return(-1) ;

	/* School Name */
	mkln(8,scho.sc_name,28) ;
	if( prnt_line() < 0) return(-1) ;

	/* School address 1 */
	mkln(8,scho.sc_add1,30) ;
	/* Rev Canada Bus. Numb */
	if(strcmp(position.p_type,"PT") == 0 ||
		strcmp(position.p_type,"FT") == 0)
		mkln(58,gov_param.gp_empl_ref,20) ;
	else
		mkln(58,gov_param.gp_tax_acct,20) ;
	if( prnt_line() < 0) return(-1) ;

	/* School Address 2 */
	mkln(8,scho.sc_add2,30) ;
	if( prnt_line() < 0) return(-1) ;

	/* School Address 3 */
	mkln(8,scho.sc_add3,30) ;
	/* Pay period type */
	strcpy(barg_unit.b_code,emp_rec.em_barg);
	barg_unit.b_date = get_date();
	flg_reset(BARG);

	retval = get_n_barg(&barg_unit,BROWSE,0,BACKWARD,e_mesg);
	if(retval == EFL ||
		strcmp(barg_unit.b_code, emp_rec.em_barg) != 0){
  	  DispError((char *)&s_sth,"Bargaining Unit does not Exist");
		return(ERROR);
	}
	if(retval < 0){
  		DispError((char *)&s_sth,e_mesg);
  		return(ERROR);
	}
	seq_over(BARG);
	strcpy(pay_per.pp_code,barg_unit.b_pp_code);
	pay_per.pp_year = 9999;
	flg_reset(PAY_PERIOD);

	retval = get_n_pay_per(&pay_per,BROWSE,0,BACKWARD,e_mesg);
	if(retval < 0){
		DispError((char *)&s_sth,e_mesg) ;
	}
	seq_over(PAY_PERIOD);

	mkln(58,pay_per.pp_desc,17) ;
	if( prnt_line() < 0) return(-1) ;
	if( prnt_line() < 0) return(-1) ;
	if( prnt_line() < 0) return(-1) ;

	/* School Postal code */
	mkln(45,scho.sc_pc,8) ;
	/* Employee SIN */
	mkln(58,emp_rec.em_sin,3);
	mkln(61,"-",1);
	mkln(62,emp_rec.em_sin+3,3);
	mkln(65,"-",1);
	mkln(66,emp_rec.em_sin+6,3);
	if( prnt_line() < 0) return(-1) ;
	if( prnt_line() < 0) return(-1) ;

	/* Employee Name */
	strcpy(emp_name,emp_rec.em_last_name);
	strcat(emp_name,", ");
	strcat(emp_name,emp_rec.em_first_name);
	mkln(8,emp_name,30) ;
	/* First Day worked */
	SetupDate(roe.ro_first_dt,temp_buf);
	mkln(73,temp_buf,10) ; 
	if( prnt_line() < 0) return(-1) ;

	/* Employee Address 1 */
	mkln(8,emp_rec.em_add1,30) ;
	if( prnt_line() < 0) return(-1) ;

	/* Employee Address 2 */
	mkln(8,emp_rec.em_add2,30) ;
	if( prnt_line() < 0) return(-1) ;

	/* Employee address 3 */
	mkln(8,emp_rec.em_add3,30) ;
	/* Last day paid */
	SetupDate(roe.ro_last_dt,temp_buf);
	mkln(73,temp_buf,10) ; 
	if( prnt_line() < 0) return(-1) ;

	/* Employee address 4 */
	mkln(8,emp_rec.em_add4,30) ;
	if( prnt_line() < 0) return(-1) ;

	/* Employee Postal Code */
	mkln(8,emp_rec.em_pc,10) ;
	/* Final Pay Period Ending date */
	SetupDate(roe.ro_final_dt,temp_buf);
	mkln(73,temp_buf,10) ; 
	if( prnt_line() < 0) return(-1) ;
	if( prnt_line() < 0) return(-1) ;
	if( prnt_line() < 0) return(-1) ;

	/* Occupation */
	mkln(8,position.p_desc,30) ;
	/* Return Date */
	if(roe.ro_ret_dt == 0)
		mkln(47,"X",1) ; 
	else{
		SetupDate(roe.ro_ret_dt,temp_buf);
		mkln(73,temp_buf,10) ;
	}
	if( prnt_line() < 0) return(-1) ;
	if( prnt_line() < 0) return(-1) ;
	if( prnt_line() < 0) return(-1) ;

	/* The Ins Hours on back of form go here at 35 */
	for(i=0;i<20;i++)
		tot_num_ins_wk += roe.ro_ins_wks[i];

	tedit((char*)&roe.ro_ins_week,"_ _",temp_buf,R_SHORT);
	mkln(35,temp_buf,3) ; 

	/* Reason code */
	mkln(74,roe.ro_reason,1) ; 
	if( prnt_line() < 0) return(-1) ;
	if( prnt_line() < 0) return(-1) ;
	if( prnt_line() < 0) return(-1) ;

	/* Contact Person */
	mkln(48,roe.ro_contact,15) ; 
	if( prnt_line() < 0) return(-1) ;

	/* Total Ins Earings from chart on back go here at 35 */
	total = 0;
	for(i=0;i<20;i++)
		total += roe.ro_ins_earn[i];
	dollars = (long)total;
	fraction = total - (double)dollars;
	if(fraction > 0.49)
		dollars += 1;	
	tedit((char*)&dollars,"_ _ _ _ _",temp_buf,R_LONG);
	mkln(35,temp_buf,9) ; 

	/* Contact person phone # */
	strcpy(temp_buf,roe.ro_cntct_tel);
	Format_Str(temp_buf,"___ ___-____");
	mkln(59,temp_buf,12) ; 

	if( prnt_line() < 0) return(-1) ;
	if( prnt_line() < 0) return(-1) ;
	if( prnt_line() < 0) return(-1) ;
	if( prnt_line() < 0) return(-1) ;
	if( prnt_line() < 0) return(-1) ;

	retval = PrntRec2();
	if(retval < 0){
		DispError((char *)&s_sth,e_mesg) ;
		return(-1);
	}

	/* Print comments on form */
	mkln(46,roe.ro_com1,30) ;
	if( prnt_line() < 0) return(-1) ;
	mkln(46,roe.ro_com2,30) ;
	if( prnt_line() < 0) return(-1) ;
	mkln(46,roe.ro_com3,30) ;
	if( prnt_line() < 0) return(-1) ;
	mkln(46,roe.ro_com4,30) ;
	if( prnt_line() < 0) return(-1) ;
	if( prnt_line() < 0) return(-1) ;
	if( prnt_line() < 0) return(-1) ;

	/* Payment Start Date */
	SetupDate(roe.ro_start_dt,temp_buf);
	mkln(5,temp_buf,10) ; 
	/* Payment amount */
	tedit((char*)&roe.ro_amnt,"____._0",temp_buf,R_DOUBLE);
	mkln(38,temp_buf,7) ; 
	if( prnt_line() < 0) return(-1) ;
	if( prnt_line() < 0) return(-1) ;
	if( prnt_line() < 0) return(-1) ;

	/* Language */
	if(strcmp(emp_rec.em_lang,"F") == 0)
		mkln(12,"X",1) ;
	else
		mkln(4,"X",1) ;
	/* Phone Number */
	strcpy(temp_buf,roe.ro_issuer_tel);
	Format_Str(temp_buf,"___  ___  ____");
	mkln(25,temp_buf,14) ; 
	tedit((char*)&pay_param.pr_tel_ext,"____",temp_buf,R_LONG);
	mkln(40,temp_buf,4) ; 

	if( prnt_line() < 0) return(-1) ;
	if( prnt_line() < 0) return(-1) ;
	if( prnt_line() < 0) return(-1) ;
	if( prnt_line() < 0) return(-1) ;

	/* Name of Issuer and date */
	mkln(40,roe.ro_issuer,25) ; 
	SetupDate(roe.ro_issue_dt,temp_buf);
	mkln(68,temp_buf,10) ; 
	if( prnt_line() < 0) return(-1) ;


	rite_top();
	
	return(NOERROR) ;
}
/*------------------------------------------------------------------------*/
PrntRec2()
{
	int	i,j,k;

	tot_num_ins_wk = 0;
	k = 0;
	/* Check to see if detail has to be printed */
	/* If there is an uninsurable pay period then do detail */
	if(roe.ro_un_ins[0] == 'Y'){
	  for(i=0;i<9;i++){
	    for(j=0;j<3;j++){
		  tedit((char*)&roe.ro_ins_earn[k],"_,___._0",
						temp_buf,R_DOUBLE);
		if(j == 0)
	  	  mkln(4,temp_buf,8) ; 
		if(j == 1)
	  	  mkln(19,temp_buf,8) ; 
		if(j == 2)
	  	  mkln(34,temp_buf,8) ; 
		k++;
if(k>19)k=19;
	    }

/* Figure out what line to print vacation, holiday pay and other money */
	    switch(i){
		case 0:
			PrintVac();
			break;
		case 1:
			PrintStat2();
			break;
		case 2:
			PrintStat3();
			break;
		case 4:
			PrintOtherMon1();
			break;
		case 5:
			PrintOtherMon2();
			break;
		case 6:
			PrintOtherMon3();
			break;
		}
	    if( prnt_line() < 0) return(-1) ;
	  }
	}
	else{
	    for(i=0;i<10;i++){
/* Figure out what line to print vacation, holiday pay and other money */
		switch(i){
			case 0:
				PrintVac();
				break;
			case 1:
				PrintStat2();
				break;
			case 2:
				PrintStat3();
				break;
			case 4:
				PrintOtherMon1();
				break;
			case 5:
				PrintOtherMon2();
				break;
			case 6:
				PrintOtherMon3();
				break;
		}
	    	if( prnt_line() < 0) return(-1) ;
	    }
	}

	return(NOERROR) ;
}

/*----------------------------------------------------------------------*/
/* Vacation Pay and stat holiday pay 1 */
PrintVac()
{
	tedit((char*)&roe.ro_vac,"_,___._0",temp_buf,R_DOUBLE);
	mkln(50,temp_buf,8) ; 
	/* Stat holiday date and pay */
	SetupDate(roe.ro_stat1_dt,temp_buf);
	mkln(62,temp_buf,10) ; 
	tedit((char*)&roe.ro_stat1_amnt,"_,___._0", temp_buf,R_DOUBLE);
	mkln(73,temp_buf,8) ; 
	/* Add an extra line return */
	if( prnt_line() < 0) return(-1) ;
}
/*----------------------------------------------------------------------*/
/* Print Stat date and pay 2 */
PrintStat2()
{
	SetupDate(roe.ro_stat2_dt,temp_buf);
	mkln(62,temp_buf,10) ; 
	tedit((char*)&roe.ro_stat2_amnt,"_,___._0", temp_buf,R_DOUBLE);
	mkln(73,temp_buf,8) ; 
}
/*----------------------------------------------------------------------*/
/* Print Stat date and pay 3 */
PrintStat3()
{
	SetupDate(roe.ro_stat3_dt,temp_buf);
	mkln(62,temp_buf,10) ; 
	tedit((char*)&roe.ro_stat3_amnt,"_,___._0", temp_buf,R_DOUBLE);
	mkln(73,temp_buf,8) ; 
	/* Add an extra line return */
	if( prnt_line() < 0) return(-1) ;
}
/*----------------------------------------------------------------------*/
PrintOtherMon1()
{

	mkln(47,roe.ro_reas1,15) ; 
	tedit((char*)&roe.ro_reas1_amnt,"_,___._0", temp_buf,R_DOUBLE);
	mkln(73,temp_buf,8) ; 
	/* Add an extra line return */
	if( prnt_line() < 0) return(-1) ;
}
/*----------------------------------------------------------------------*/
PrintOtherMon2()
{
	mkln(47,roe.ro_reas2,15) ; 
	tedit((char*)&roe.ro_reas2_amnt,"_,___._0", temp_buf,R_DOUBLE);
	mkln(73,temp_buf,8) ; 
}
/*----------------------------------------------------------------------*/
PrintOtherMon3()
{
	mkln(47,roe.ro_reas3,15) ; 
	tedit((char*)&roe.ro_reas3_amnt,"_,___._0", temp_buf,R_DOUBLE);
	mkln(73,temp_buf,8) ; 
	/* Add an extra line return */
	if( prnt_line() < 0) return(-1) ;
}
/*----------------------------------------------------------------------*/
/*  Setup Date		      */

SetupDate(ldate,sdate)
long	ldate;
char	*sdate;
{
	long	dd, mm, yy;

	if(ldate <=0){
		sprintf(sdate,"          ");
	}
	else{
		ldate -= 19000000;
		dd = ldate % 100;
		mm = (ldate / 100) % 100;
		yy = ldate / 10000;
		sprintf(sdate,"%02d  %02d  %02d",dd,mm,yy);
	}
}

/*----------------------------------------------------------------------*/
/*  Setup Date		      */

Format_Str(string,mask)
char	*string, *mask;
{
	int	len;
	int	cnt=0;
	char	output[20];

	for(len=0; len<strlen(mask);len++){
		if(mask[len] == '_') {
			output[len] = string[cnt];
			cnt++;
		}
		else
			output[len] = mask[len];
	}
	strcpy(string,output);
}
/*-------------------- E n d   O f   P r o g r a m ---------------------*/
