/******************************************************************************
		Sourcename    : streputl.c
		System        : Budgetary Financial system.
		Module        : Inventory reports
		Created on    : 89-09-14
		Created  By   : K HARISH.
		Cobol sources : 

HISTORY:
 Date           Programmer     Description of modification
____/__/__      __________     ___________________________
1991/01/30	F.Tao 		Add Period Selection.

Calls for the user:	( Check for the value returned: -1 on error )

int	AddMenuItem( char *name, int (* fnptr)() );
int	Initialize( char *terminalname , char *heading );
int	Process();
int	GetFund( short *);
int	GetFundRange( short *, short * );
int	GetCode( char * );
int	GetCodeRange( char *, char * );
int	GetType( char  *);
int	GetTypeRange( char *, char * );
int	GetLoc( short  *);
int	GetLocRange( short *, short * );
int	GetDate( long * );
int	GetDateRange( long *, long * );
int	DisplayMessage( char * );
int	GetPeriod( short *);
int	GetPeriodRange( short *, short *);
int	GetResponse( char * );
int	HideMessage();
int	GetOutputon( char * );
int	GetFilename( char * );
int	GetPrinter( short * );
int	GetPagesize( short * );
int	Confirm();	     *	returns 1 for Yes, and 0 for anyother input *
int	GetResp( char * );  * Printer or File option */

/***************************************************************************
The programmer should make calls for appending menuitems in the following order.
		AddMenuItem( menuname, functionpointer );( max. 9 options )
		Initialize( screenheading );
		Process();	 for menu item selection
		{	Any "Get...." calls }
		Confirm();	It clears the screen and resets terminal
A maximum of 9 menuitems can be added, excluding one for Quitting the screen
which is automatically appended by the system.

For all the calls starting with "Get", user can pass any default values by 
initialising the corresponding variables before passing their address(es)
as parameters. The program doesnot do any validation except that it disallows
user's entry of end value ( range limit ) if it is smaller than starting value.

The last call should be "Confirm()",  which clears the profom screen and resets
the terminal characteristics

******************************************************************************/
#include <stdio.h>

#include <bfs_defs.h>
#include <cfomstrc.h>

#define SCREEN_NAME	"stockrep"
#define EXIT		12
#define PATH_FILE_SIZE	50
#define STARTLINENUM	18
#define FROM_COL	24	/* Column# for 'From' field input mask */
#define TO_COL		45	/* Column# for 'To' field input mask */
#define LOW 		-1
#define HIGH 		 1
#define HL_CHAR(VAL)	VAL==HIGH ? HV_CHAR : LV_CHAR
#define ESC_F		sr.retcode==RET_USER_ESC && \
			(sr.escchar[0]=='F'||sr.escchar[0]=='f')
#define	OPTIONLEN	36
#define MAXOPTIONS	10
#define MAXQUERYLINES	6
#define PERIOD 		0
#define	FUND		1
#define	CODE		2
#define	TRTYPE		3
#define	LOCATION	4
#define	DATE		5

#ifdef ENGLISH
#define PRINTER		'P'
#define DISPLAY		'D'
#define FILE_IO		'F'
#define YES		'Y'
#else
#define PRINTER		'I'
#define DISPLAY		'A'
#define FILE_IO		'D'
#define YES		'O'
#endif

/* glrep.sth - header for C structure generated by PROFOM EDITOR */

static struct	s_struct	{
	char	s_progname[12];	/* 100 program name */
	char	s_scrhdg[16];	/* 200 */
	long	s_rundt;	/* 300 DATE YYYYFMMFDD */
	char	s_item[MAXOPTIONS][OPTIONLEN];	/* 400 - 1300 options */
	short	s_option;	/* 1400 user's input */
	char	s_hypline[2];	/* 1500 mask for seperator line */
	char	s_outputon[2];	/* 1600 report output on D / F / P */
	char	s_respans[2];	/* 1650 report output on D / F / P */
	char	s_filename[16];	/* 1700 name of file if option is F */
	short	s_printer;	/* 1800 printer# if option is P */
	short	s_nbrcopies;	/* 1900 page length in no of lines */
	short	s_period1;	/* 1950 period #1  */
	short	s_period2;	/* 1975 period #2  */
	short	s_fund1;	/* 2000 starting fund # */
	short	s_fund2;	/* 2100 ending fund # */
	char	s_code1[11];	/* 2200 starting stock code  */
	char	s_code2[11];	/* 2300 ending stock code  */
	char	s_tr1type[3];	/* 2400 starting transaction code */
	char	s_tr2type[3];	/* 2500 ending transaction code */
	short	s_loc1;		/* 2600 starting location# */
	short	s_loc2;		/* 2700 ending location# */
	long	s_date1;	/* 2800 start date */
	long	s_date2;	/* 2900 start date */
	char	s_mesg[77];	/* 3000 message field */
	char	s_resp[2];	/* 3100 response field */
}	s_rec;

typedef struct{
	char	name[OPTIONLEN];
	int	(* fnptr)();
	int	mainflno;
}Menu;

struct stat_rec 	sr;		/* profom status record */

static int		line[MAXQUERYLINES];/* for positioning key queries */
static short		call_no;
static short		totaloptions;
static int retval;	/* Global variable to store function values */
static Menu	menu[MAXOPTIONS];
static	int	initialised ;
extern	e_mesg[80];	/* used to store error messages */

Initialize( terminal,heading )	/* initialize profom and screen */
char *terminal;
char *heading;	
{
	if( (retval=InitProfom(terminal))<0 ){	/* initialize profom */
		fomcs();
		fomrt();
		return(retval);
	}
	if( (retval=InitScreen(heading))<0 ){		/* initialize screen */
		fomcs();
		fomrt();
		return(retval);
	}
	initialised = 1 ;
	return(0);
}	
static
InitProfom(terminal)	/* initialize profom */
char *terminal;
{
	if ( initialised )
		return(0) ;
	STRCPY( sr.termnm, terminal );
	fomin( &sr );		/* initialize the screen */
	ret( err_chk(&sr) );	/* if profom error return */

	return(0);
}
static
InitScreen(heading)		/* initialize the screen */
char 	*heading;
{
	/* initialize the profom screen variables */
	STRCPY( sr.scrnam, NFM_PATH );
	strcat( sr.scrnam, SCREEN_NAME );

	/* initialize the fields of the profom screen */
	if( initialised==0 ){
		if( FillScrHdg(heading)<0 ) 		return(-1);
		if( FillMenu()<0 ) 			return(-1);
		if( FillOption(HIGH)<0 )		return(-1);
		if( FillSeperatorLine()<0 ) 	return(-1);
	}

	/* Move Highs to inquiry area and write the entire screen */
	if( (retval=ClearInquiryArea())<0 )	return(retval);

	fomcf( 1,1 ) ;		/* Enable snap screen */
	return(0);
}

/* Fill the screen heading fields, the program name and the date */
static
FillScrHdg(heading)
char *heading;
{
	STRCPY( s_rec.s_progname, PROG_NAME );
	STRCPY( s_rec.s_scrhdg, heading );
	s_rec.s_rundt = get_date();
	return(0);
}

/* Add a menu item to the array of report menu items */
AddMenuItem( menuname, fnptr, mainflno )
char	*menuname;
int	(* fnptr)();
int	mainflno;
{
	if( totaloptions==0 ){ /* no options added to array yet */
#ifdef ENGLISH
		STRCPY( menu[totaloptions].name, "RETURN TO PREVIOUS MENU" );
#else
		STRCPY( menu[totaloptions].name, "RETOURNER AU MENU PRECEDENT");
#endif
		menu[totaloptions].fnptr = NULL;
		totaloptions++;
	}

	if( totaloptions>=MAXOPTIONS )	/* array can't accomodate any more */ 
		return(-1);
	if( menuname==NULL )		/* menu name can't be null */
		return(-1);
	STRCPY( menu[totaloptions].name, menuname );
	menu[totaloptions].fnptr = fnptr;	/* copy function pointer */
	menu[totaloptions].mainflno = mainflno;  /* copy main file used */

	totaloptions++;

	return(totaloptions-1);
}
/* Fill Menu Options with the proper names */
static
FillMenu()
{
	short	i;

	for( i=0; i<totaloptions; i++ )
		STRCPY( s_rec.s_item[i], menu[i].name );
	for( i=totaloptions; i<MAXOPTIONS; i++ )
		s_rec.s_item[i][0] = HV_CHAR;
	return(0);
}
static
FillOption( value )
short value;
{
	s_rec.s_option = value * HV_SHORT;
	return(0);
}
/* Fill the demarkating line field with high/low values */
static
FillSeperatorLine()
{
	s_rec.s_hypline[0] = LV_CHAR;
	return(0);
}
/* Fill output details with high or low values */
static
FillOutputDetails( value )
short value;
{
	s_rec.s_outputon[0] = HL_CHAR(value);
	s_rec.s_respans[0] = HL_CHAR(value);
	s_rec.s_filename[0] = HL_CHAR(value);
	s_rec.s_printer = HV_SHORT * value;
	s_rec.s_nbrcopies = HV_SHORT * value;
	return(0);
}
static
FillFund( val1, val2 )
short	val1, val2;
{
	s_rec.s_fund1 = HV_SHORT * val1;
	s_rec.s_fund2 = HV_SHORT * val2;
	return(0);
}
static
FillCode( val1, val2 )
short	val1, val2;
{
	s_rec.s_code1[0] = HL_CHAR( val1 );
	s_rec.s_code2[0] = HL_CHAR( val2 );
	return(0);
}
static
FillTrtype( val1, val2 )
short	val1, val2;
{
	s_rec.s_tr1type[0] = HL_CHAR( val1 );
	s_rec.s_tr2type[0] = HL_CHAR( val2 );
	return(0);
}
static
FillLocation( val1, val2 )
short	val1, val2;
{
	s_rec.s_loc1 = HV_SHORT * val1;
	s_rec.s_loc2 = HV_SHORT * val2;
	return(0);
}
static
FillDate( val1, val2 )
short	val1, val2;
{
	s_rec.s_date1 = HV_LONG * val1;
	s_rec.s_date2 = HV_LONG * val2;
	return(0);
}
static
FillPeriod( val1, val2)
short	val1;
{
	s_rec.s_period1 = HV_SHORT * val1;
	s_rec.s_period2 = HV_SHORT * val2;
	return(0);
}
/* Fill the message and response fields with high or low values */
static
FillMsgRespFields( value )
short value;
{
	s_rec.s_mesg[0] = HL_CHAR( value );
	s_rec.s_resp[0] = HL_CHAR( value );

	return(0);
}
/* Accept user's option and call the corresponding routine in a loop */
Process(terminal, heading)
char	*terminal ;
char	*heading  ;
{
	int	field;

	Initialize(terminal, heading) ;
	call_no = 0;	/* No get calls made yet */
	for( ; ; ){
		mainfileno = -1 ;

		retval = ReadOption();
		if( retval<0 )
			return(retval);
		if( s_rec.s_option>=totaloptions ){
#ifdef ENGLISH
			fomer("Invalid option");
#else
			fomer("Option invalide");
#endif
			continue;
		}
		if( s_rec.s_option==0 ){   /* option 0 is reserved to quit */
			fomcs();
			fomrt();
			return(0);
		}
		
		if((retval = CheckAccess(menu[s_rec.s_option].mainflno,
					BROWSE,e_mesg))<0) {
			return(retval);
		}

		mainfileno = menu[s_rec.s_option].mainflno ;

		/* Highlight option. Dehighlight in Confirm() */
		field = 400+(s_rec.s_option*100);
		fomca1( field, 9, 3 );

		/* if a corresponding function exists, call it  */
		if( menu[s_rec.s_option].fnptr ){
			if( (retval=(*menu[s_rec.s_option].fnptr)())<0 )
				return(retval);
			fomst();
		}
		else 	/* there isn't corr. function,  return value */
			return (s_rec.s_option);
	
		if( (retval=ClearInquiryArea())<0 )
			return(retval);
	}
}

/*	The following Get....() calls display default values given as parameter 
*	and fill up the variable with the value entered by the user 
*	The fields for accepting input are positioned in the order in which
*	they are called. For this, they make use of variable 'call_no'
*/

GetFund( fund )
short	*fund;
{
	int	retval=0;

	if( line[FUND]==0 )	/* no fund call made yet */
		line[FUND] = STARTLINENUM + call_no++;
	fomca2( 2000,1, line[FUND], 1 );
	fomca2( 2000,2, line[FUND], FROM_COL );
	fomca2( 2100,1, line[FUND], 40 );
	fomca2( 2100,2, line[FUND], TO_COL );

	s_rec.s_fund1 = *fund ;
	fomca1( 2000, 19, 2 );
	sr.nextfld = 2000;
	sr.endfld = 2000;
	fomud( (char *)&s_rec );
	s_rec.s_fund1 = LV_SHORT;
	retval = ReadFields( 2000, 2000 );
	if( retval!=EXIT && retval>=0 )
		*fund = s_rec.s_fund1;
	fomca1( 2000, 19, 0 );

	return(retval);
}
GetFundRange( fund1, fund2 )
short	*fund1, *fund2;
{
	int	retval=0;

	if( line[FUND]==0 )	/* no fund call made yet */
		line[FUND] = STARTLINENUM + call_no++;
	fomca2( 2000,1, line[FUND], 1 );
	fomca2( 2000,2, line[FUND], FROM_COL );
	fomca2( 2100,1, line[FUND], 40 );
	fomca2( 2100,2, line[FUND], TO_COL );

	s_rec.s_fund1 = *fund1 ;
	s_rec.s_fund2 = *fund2 ;
	fomca1( 2000, 19, 2 );
	fomca1( 2100, 19, 2 );
	sr.nextfld = 2000;
	sr.endfld = 2100;
	fomud( (char *)&s_rec );
	if( FillFund( LOW, LOW )<0 )
		return(-1);
	retval = ReadFields( 2000, 2100 );
	if( retval!=EXIT && retval>=0 ){
		*fund1 = s_rec.s_fund1;
		*fund2 = s_rec.s_fund2;
	}
	fomca1( 2000, 19, 0 );
	fomca1( 2100, 19, 0 );

	return(retval);
}
GetCode( code )
char *code;
{
	int	retval=0;

	if( line[CODE]==0 )	/* no stock code call made yet */
		line[CODE] = STARTLINENUM + call_no++;
	fomca2( 2200,1, line[CODE], 1 );
	fomca2( 2200,2, line[CODE], FROM_COL );
	fomca2( 2300,1, line[CODE], 40 );
	fomca2( 2300,2, line[CODE], TO_COL );

	STRCPY( s_rec.s_code1, code );
	fomca1( 2200, 19, 2 );
	sr.nextfld = 2200;
	sr.endfld = 2200;
	fomud( (char *)&s_rec );
	s_rec.s_code1[0] = LV_CHAR;
	retval = ReadFields( 2200, 2200 );
	if( retval!=EXIT && retval>=0 )
		strcpy( code, s_rec.s_code1 );
	fomca1( 2200, 19, 0 );

	return(retval);
}
GetCodeRange( code1, code2 )
char *code1, *code2;
{
	int	retval=0;

	if( line[CODE]==0 )	/* no stock code call made yet */
		line[CODE] = STARTLINENUM + call_no++;
	fomca2( 2200,1, line[CODE], 1 );
	fomca2( 2200,2, line[CODE], FROM_COL );
	fomca2( 2300,1, line[CODE], 40 );
	fomca2( 2300,2, line[CODE], TO_COL );

	STRCPY( s_rec.s_code1, code1 );
	STRCPY( s_rec.s_code2, code2 );
	fomca1( 2200, 19, 2 );
	fomca1( 2300, 19, 2 );
	sr.nextfld = 2200;
	sr.endfld = 2300;
	fomud( (char *)&s_rec );
	s_rec.s_code1[0] = LV_CHAR;
	s_rec.s_code2[0] = LV_CHAR;
	retval = ReadFields( 2200, 2300 );
	if( retval!=EXIT && retval>=0 ){
		strcpy( code1, s_rec.s_code1 );
		strcpy( code2, s_rec.s_code2 );
	}
	fomca1( 2200, 19, 0 );
	fomca1( 2300, 19, 0 );

	return(retval);
}
GetType( code )
char *code;		/* Transaction code, 2 chars */
{
	int	retval=0;

	if( line[TRTYPE]==0 )	/* no stock code call made yet */
		line[TRTYPE] = STARTLINENUM + call_no++;
	fomca2( 2400,1, line[TRTYPE], 1 );
	fomca2( 2400,2, line[TRTYPE], FROM_COL );
	fomca2( 2500,1, line[TRTYPE], 40 );
	fomca2( 2500,2, line[TRTYPE], TO_COL );

	STRCPY( s_rec.s_tr1type, code );
	fomca1( 2400, 19, 2 );
	sr.nextfld = 2400;
	sr.endfld = 2400;
	fomud( (char *)&s_rec );
	s_rec.s_tr1type[0] = LV_CHAR;
	retval = ReadFields( 2400, 2400 );
	if( retval!=EXIT && retval>=0 )
		strcpy( code, s_rec.s_tr1type );
	fomca1( 2400, 19, 0 );

	return(retval);
}
GetTypeRange( code1, code2 )
char *code1, *code2;
{
	int	retval=0;

	if( line[TRTYPE]==0 )	/* no stock code call made yet */
		line[TRTYPE] = STARTLINENUM + call_no++;
	fomca2( 2400,1, line[TRTYPE], 1 );
	fomca2( 2400,2, line[TRTYPE], FROM_COL );
	fomca2( 2500,1, line[TRTYPE], 40 );
	fomca2( 2500,2, line[TRTYPE], TO_COL );

	STRCPY( s_rec.s_tr1type, code1 );
	STRCPY( s_rec.s_tr2type, code2 );
	fomca1( 2400, 19, 2 );
	fomca1( 2500, 19, 2 );
	sr.nextfld = 2400;
	sr.endfld = 2500;
	fomud( (char *)&s_rec );
	s_rec.s_tr1type[0] = LV_CHAR;
	s_rec.s_tr2type[0] = LV_CHAR;
	retval = ReadFields( 2400, 2500 );
	if( retval!=EXIT && retval>=0 ){
		strcpy( code1, s_rec.s_tr1type );
		strcpy( code2, s_rec.s_tr2type );
	}
	fomca1( 2400, 19, 0 );
	fomca1( 2500, 19, 0 );

	return(retval);
}
GetLoc( loc_no )
short	*loc_no;
{
	int	retval=0;

	if( line[LOCATION]==0 )	/* no loc_no call made yet */
		line[LOCATION] = STARTLINENUM + call_no++;
	fomca2( 2600,1, line[LOCATION], 1 );
	fomca2( 2600,2, line[LOCATION], FROM_COL );
	fomca2( 2700,1, line[LOCATION], 40 );
	fomca2( 2700,2, line[LOCATION], TO_COL );

	s_rec.s_loc1 = *loc_no ;
	fomca1( 2600, 19, 2 );
	sr.nextfld = 2600;
	sr.endfld = 2600;
	fomud( (char *)&s_rec );
	s_rec.s_loc1 = LV_SHORT;
	retval = ReadFields( 2600, 2600 );
	if( retval!=EXIT && retval>=0 )
		*loc_no = s_rec.s_loc1;
	fomca1( 2600, 19, 0 );

	return(retval);
}
GetLocRange( loc_1, loc_2 )
short	*loc_1, *loc_2;
{
	int	retval=0;

	if( line[LOCATION]==0 )	/* no period call made yet */
		line[LOCATION] = STARTLINENUM + call_no++;
	fomca2( 2600,1, line[LOCATION], 1 );
	fomca2( 2600,2, line[LOCATION], FROM_COL );
	fomca2( 2700,1, line[LOCATION], 40 );
	fomca2( 2700,2, line[LOCATION], TO_COL );

	s_rec.s_loc1 = *loc_1 ;
	s_rec.s_loc2 = *loc_2 ;
	fomca1( 2600, 19, 2 );
	fomca1( 2700, 19, 2 );
	sr.nextfld = 2600;
	sr.endfld = 2700;
	fomud( (char *)&s_rec );
	s_rec.s_loc1 = LV_SHORT;
	s_rec.s_loc2 = LV_SHORT;
	retval = ReadFields( 2600, 2700 );
	if( retval!=EXIT && retval>=0 ){
		*loc_1 = s_rec.s_loc1;
		*loc_2 = s_rec.s_loc2;
	}
	fomca1( 2600, 19, 0 );
	fomca1( 2700, 19, 0 );

	return(retval);
}
GetDate( date )
long	*date;
{
	int	retval=0;

	if( line[DATE]==0 )	/* no fund call made yet */
		line[DATE] = STARTLINENUM + call_no++;
	fomca2( 2800,1, line[DATE], 1 );
	fomca2( 2800,2, line[DATE], FROM_COL );
	fomca2( 2900,1, line[DATE], 40 );
	fomca2( 2900,2, line[DATE], TO_COL );

	s_rec.s_date1 = *date ;
	fomca1( 2800, 19, 2 );
	sr.nextfld = 2800;
	sr.endfld = 2800;
	fomud( (char *)&s_rec );
	s_rec.s_date1 = LV_LONG;
	retval = ReadFields( 2800, 2800 );
	if( retval!=EXIT && retval>=0 )
		*date = s_rec.s_date1;
	fomca1( 2800, 19, 0 );

	return(retval);
}
GetDateRange( date1, date2 )
long	*date1, *date2;
{
	int	retval=0;

	if( line[DATE]==0 )	/* no date call made yet */
		line[DATE] = STARTLINENUM + call_no++;
	fomca2( 2800,1, line[DATE], 1 );
	fomca2( 2800,2, line[DATE], FROM_COL );
	fomca2( 2900,1, line[DATE], 40 );
	fomca2( 2900,2, line[DATE], TO_COL );

	s_rec.s_date1 = *date1 ;
	s_rec.s_date2 = *date2 ;
	fomca1( 2800, 19, 2 );
	fomca1( 2900, 19, 2 );
	sr.nextfld = 2800;
	sr.endfld = 2900;
	fomud( (char *)&s_rec );
	if( FillDate( LOW, LOW )<0 )
		return(-1);
	retval = ReadFields( 2800, 2900 );
	if( retval!=EXIT && retval>=0 ){
		*date1 = s_rec.s_date1;
		*date2 = s_rec.s_date2;
	}
	fomca1( 2800, 19, 0 );
	fomca1( 2900, 19, 0 );

	return(retval);
}
GetPeriod( period )
short	*period;
{
	int	retval=0;

	if( line[PERIOD]==0 ){	/* no period call made yet */
		line[PERIOD] = STARTLINENUM + 1 +call_no++;
		call_no ++;
	}
	fomca2( 1950,1, line[PERIOD], 1 );
	fomca2( 1950,2, line[PERIOD], FROM_COL );
	fomca2( 1975,1, line[PERIOD], 40 );
	fomca2( 1975,2, line[PERIOD], TO_COL );

	s_rec.s_period1 = *period ;
	fomca1( 1950, 19, 2 );
	sr.nextfld = 1950;
	sr.endfld = 1950;
	fomud( (char *)&s_rec );
	s_rec.s_period1 = LV_SHORT;
	retval = ReadFields( 1950, 1950 );
	if( retval!=EXIT && retval>=0 )
		*period = s_rec.s_period1;
	fomca1( 1950, 19, 0 );

	return(retval);
}
GetPeriodRange( period1, period2 )
short	*period1, *period2;
{
	int	retval=0;

	if( line[PERIOD]==0 ){	/* no period call made yet */
		line[PERIOD] = STARTLINENUM + 1 +call_no++;
		call_no ++;
	}
	fomca2( 1950,1, line[PERIOD], 1 );
	fomca2( 1950,2, line[PERIOD], FROM_COL );
	fomca2( 1975,1, line[PERIOD], 40 );
	fomca2( 1975,2, line[PERIOD], TO_COL );

	s_rec.s_period1 = *period1 ;
	s_rec.s_period2 = *period2 ;
	fomca1( 1950, 19, 2 );
	fomca1( 1975, 19, 2 );
	sr.nextfld = 1950;
	sr.endfld = 1975;
	fomud( (char *)&s_rec );
	if( FillPeriod( LOW, LOW )<0 )
		return(-1);
	retval = ReadFields( 1950, 1975 );
	if( retval!=EXIT && retval>=0 ){
		*period1 = s_rec.s_period1;
		*period2 = s_rec.s_period2;
	}
	fomca1( 1950, 19, 0 );
	fomca1( 1975, 19, 0 );

	return(retval);
}
Confirm()	/* returns 1 for yes, 0 for no, -1 for error */
{		/* Clears the profom screen when user's response is 'Y' */
	int	field;

#ifdef ENGLISH
	if( (retval=DisplayMessage("Confirm (Y/N)?"))<0 )
#else
	if( (retval=DisplayMessage("Confirmer (O/N)?"))<0 )
#endif
		return(retval);
	if( (retval=GetResponse(s_rec.s_resp))<0 )
		return(retval);
	field = s_rec.s_option*100 + 400;

	if( s_rec.s_resp[0]==YES ){
		fflush( stdout );
		fomcs();
		fomrt();
		return(1);
	}
	/* Dehighlight the option which is highlighted in Process() */
	fomca1( field, 9, 5 );

	return( HideMessage() );
}

static
ClearInquiryArea()
{
	short i;

	call_no = 0;	/* Reset the call_no */
	for( i=0; i<MAXQUERYLINES; i++ )/* so that next time fields can be */
		line[i] = 0;	/* repositioned for next routine calls */
	if(FillOutputDetails(HIGH)<0 )
		return(-1);
	if(FillFund(HIGH,HIGH)<0 )
		return(-1);
	if(FillCode(HIGH,HIGH)<0 )
		return(-1);
	if(FillTrtype(HIGH,HIGH)<0 )
		return(-1);
	if(FillLocation(HIGH,HIGH)<0 )
		return(-1);
	if(FillDate(HIGH,HIGH)<0 )
		return(-1);
	if(FillPeriod(HIGH,HIGH)<0 )
		return(-1);
	if(FillMsgRespFields(HIGH)<0 )
		return(-1);
	return( WriteFields(1,0) );
}
static
ReadOption()
{
	s_rec.s_option = LV_SHORT;
	return( ReadFields( 1400, 1400 ) );
}
static
ReadFields(start,end)	/* read fields whose numbers range from start to end */
int start, end;		/* start and end fields */
{
	int retval;

	sr.nextfld = start;
	sr.endfld = end;
	for( ; ; ){
		fomrd( (char *)&s_rec );
		ret(err_chk(&sr));
		if( sr.retcode==RET_USER_ESC || sr.retcode==RET_VAL_CHK ){
			if( ESC_F ) return(EXIT);
			retval=Validate();
			if( retval<0 || retval==EXIT)	return(retval);
			continue;
		}
		break;
	}
	return(0);
}
static
WriteFields( start,end )/* write fields whose numbers range from start to end */
int start, end;
{
	sr.nextfld = start;
	sr.endfld = end;
	fomwr( (char *)&s_rec );
	ret( err_chk(&sr) );
	return(0);
}
static
Validate()	/* Validate the values entered by the user */
{
	int	retval;

	switch( sr.curfld ){
		case 1400:	/* menu option */
			if( s_rec.s_option<0 || s_rec.s_option>=totaloptions ){
#ifdef ENGLISH
				fomer("Invalid option");
#else
				fomer("Option invalide");
#endif
				s_rec.s_option = LV_SHORT;
			}
			break;
		case 1600:	/* output on */
			if( s_rec.s_outputon[0]!= DISPLAY &&
			    s_rec.s_outputon[0]!= PRINTER &&
			    s_rec.s_outputon[0]!= FILE_IO ){
#ifdef ENGLISH
				fomer("D(isplay), P(rinter), F(ile)");
#else
				fomer("A(fficher), I(mprimante), D(ossier)");
#endif
				s_rec.s_outputon[0] = LV_CHAR;
			}
			break;
		case 1650:	/* output on */
			if( s_rec.s_respans[0]!= PRINTER &&
			    s_rec.s_respans[0]!= FILE_IO ){
#ifdef ENGLISH
				fomer("P(rinter), F(ile)");
#else
				fomer("I(mprimante), D(ossier)");
#endif
				s_rec.s_respans[0] = LV_CHAR;
			}
			break;
		case 1700:	/* Filename */
			break;
		case 1800:	/* Printer */
			break;
		case 1900:	/* number of copies */
			if(s_rec.s_nbrcopies == 0) {
#ifdef ENGLISH
				fomer("No. of Copies can't be Zero");
#else
				fomer("Nombre de copies ne peut pas etre zero");
#endif
				s_rec.s_nbrcopies = LV_SHORT;
			}
			break;
		case 2000:	/* start fund code */
			if( s_rec.s_fund1<1 ){
#ifdef ENGLISH
				fomer("Fund# can't be less than 1");
#else
				fomer("#fond ne peut pas etre moins que 1");
#endif
				s_rec.s_fund1 = LV_SHORT;
			}
			break;
		case 2100:	/* end fund code */
			if( s_rec.s_fund2 < s_rec.s_fund1 ){
#ifdef ENGLISH
				fomer("Value can't be less than starting fund");
#else
				fomer("Valeur ne peut pas etre moins que le fond debutant");
#endif
				s_rec.s_fund2 = LV_SHORT;
			}
			break;
		case 2300:	/* ending stock code */
			if( strcmp( s_rec.s_code2,s_rec.s_code1 )<0 ){
#ifdef ENGLISH
				fomer("End code smaller than start code");
#else
				fomer("Code de la fin est plus petit que le code de debut");
#endif
				s_rec.s_code2[0]=LV_CHAR;
			}
			break; 
		case 2500:	/* ending transaction code */
			if( strcmp( s_rec.s_tr2type,s_rec.s_tr1type )<0 ){
#ifdef ENGLISH
				fomer("End type lesser than start type");
#else
				fomer("Genre de la fin est moins que le genre du debut");
#endif
				s_rec.s_tr2type[0]=LV_CHAR;
			}
			break; 
		case 2600:	/* start location */
			if( s_rec.s_loc1<1 ){
#ifdef ENGLISH
				fomer("Invalid location number");
#else
				fomer("Numero d'emplacement invalide");
#endif
				s_rec.s_loc1 = LV_SHORT ;
			}
			break;
		case 2700:	/* end period */
			if( s_rec.s_loc2 < s_rec.s_loc1 ){
#ifdef ENGLISH
				fomer("End location# less than start location#");
#else
				fomer("#d'emplacement de la fin est moins que celui du debut");
#endif
				s_rec.s_loc2 = LV_SHORT; 
			} 
			break;
		case 2900:	/* end date */
			if( s_rec.s_date2 < s_rec.s_date1 ){
#ifdef ENGLISH
				fomer("End date can't be less than start date");
#else
				fomer("Date de la fin ne peut pas etre plus tot que la date de debut");
#endif
				s_rec.s_date2 = LV_LONG; 
			} 
			break;
	}
	sr.nextfld = sr.curfld;
	return(0);
}
DisplayMessage(mesg)	/* Display the given message in the message field */
char *mesg;
{
	STRCPY( s_rec.s_mesg, mesg );
	return( WriteFields(3000,3000) );
}
HideMessage()	/* Hide the message field */
{
	if( (retval=FillMsgRespFields(HIGH))<0 )	return(retval);
	return( WriteFields(3000,3100) );
}
GetResponse( respchar )
char *respchar;
{
	int	retval;

	s_rec.s_resp[0] = LV_CHAR;
	retval = ReadFields( 3100, 3100 );
	if( retval!=EXIT && retval>=0 )
		*respchar = s_rec.s_resp[0];
	return( retval );
}
GetOutputon( outputon )
char	*outputon;
{
	int	retval;

#ifdef ENGLISH
	fomer("D(isplay), P(rinter), F(ile)");
#else
	fomer("A(fficher), I(mprimante), D(ossier)");
#endif
	STRCPY( s_rec.s_outputon, outputon );
	fomca1( 1600, 19, 2 );
	sr.nextfld = 1600;
	sr.endfld = 1600;
	fomud( (char *)&s_rec );
	s_rec.s_outputon[0] = LV_CHAR;
	retval = ReadFields(1600,1600);
	if( retval!=EXIT && retval>=0 )
		*outputon = s_rec.s_outputon[0];
	fomca1( 1600, 19, 0 );
	return( retval );
}
GetResp( getresp )
char	*getresp;
{
	int	retval;

#ifdef ENGLISH
	fomer("P(rinter), F(ile)");
#else
	fomer("I(mprimante), D(ossier)");
#endif
	STRCPY( s_rec.s_respans, getresp );
	fomca1( 1650, 19, 2 );
	sr.nextfld = 1650;
	sr.endfld = 1650;
	fomud( (char *)&s_rec );
	s_rec.s_respans[0] = LV_CHAR;
	retval = ReadFields(1650,1650);
	if( retval!=EXIT && retval>=0 )
		*getresp = s_rec.s_respans[0];
	fomca1( 1650, 19, 0 );
	return( retval );
}

GetFilename( filename )
char	*filename;
{
	int	retval;

	STRCPY( s_rec.s_filename, filename );
	fomca1( 1700, 19, 2 );
	sr.nextfld = 1700;
	sr.endfld = 1700;
	fomud( (char *)&s_rec );
	s_rec.s_filename[0] = LV_CHAR;
	retval = ReadFields(1700,1700);
	if( retval!=EXIT && retval>=0 )
		strcpy( filename , s_rec.s_filename ) ;
	fomca1( 1700, 19, 0 );
	return( retval );
}
GetPrinter( printer )
short	*printer;
{
	int	retval;

	s_rec.s_printer = *printer ;
	fomca1( 1800, 19, 2 );
	sr.nextfld = 1800;
	sr.endfld = 1800;
	fomud( (char *)&s_rec );
	s_rec.s_printer = LV_SHORT;
	retval = ReadFields(1800,1800);
	if( retval!=EXIT && retval>=0 )
		*printer = s_rec.s_printer;
	fomca1( 1800, 19, 0 );
	return( retval );
}
GetNbrCopies( copies )
short	*copies;
{
	int	retval;

	s_rec.s_nbrcopies = *copies ;
	fomca1( 1900, 19, 2 );
	sr.nextfld = 1900;
	sr.endfld = 1900;
	fomud( (char *)&s_rec );
	s_rec.s_nbrcopies = LV_SHORT;
	retval = ReadFields(1900,1900);
	if( retval!=EXIT && retval>=0 )
		*copies = s_rec.s_nbrcopies;
	fomca1( 1900, 19, 0 );
	return( retval );
}

