/*------------------------------------------------------------------------
Source Name: roll_sen.c
System     : Personnel/Payroll System.
Created  On: July 05th, 93.
Created  By: Andre Cormier.

DESCRIPTION:
	Program to update YTD totals in employee file and purge seniority 
	file.e.

MODIFICATIONS:        

Programmer     YY/MM/DD       Description of modification
~~~~~~~~~~     ~~~~~~~~       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
------------------------------------------------------------------------*/

#define	MAIN		/* Main program. This is to declare Switches */

#define	SYSTEM		"YEAR END"	/* Sub System Name */
#define	MOD_DATE	"07-JUL-93"		/* Program Last Modified */

#include <stdio.h>
#include <cfomstrc.h>
#include <bfs_defs.h>
#include <bfs_com.h>
#include <bfs_pp.h>

/* User Interface define constants */
#ifdef ENGLISH
#define ROLLOVER	'R'
#define EXITOPT		'E'

#define	YES		'Y'
#define NO		'N'
#define	CANCEL		'C'
#else
#define ROLLOVER	'R'
#define EXITOPT		'F'

#define	YES		'O'
#define NO		'N'
#define	CANCEL		'A'
#endif

/* PROFOM Releted declarations */

#define	SCR_NAME	"roll_sen"	/* PROFOM screen Name */

/* Field PROFOM numbers */

#define OPTION		400	/* */
#define MESSAGE		500	/* */
#define RESPONSE	600	/* */

/* roll_att.sth - header for C structure generated by PROFOM EDITOR */

typedef struct	{

	char	s_pgm[11];	/* 100 program name */
	long	s_rundate;	/* 300 run date */
	char	s_option[2];	/* 1300 option choice */
	char	s_mesg[78];	/* 1500 message field */
	char	s_resp[2];	/* 1600 response field */
	} S_STRUCT;


S_STRUCT	s_sth;	/* PROFOM Screen Structure */
static	struct  stat_rec  sr;		/* PROFOM status rec */

/* File structures */
static	Emp	emp_rec;
static	Emp_sen	emp_sen;
static	Sen_par	sen_par;

static	char 	e_mesg[180];  		/* dbh will return err msg in this */

static	Validation();
static	WindowHelp();

static	int	PG_SIZE;
static	char	discfile[15];	/* for storing output name */
static	short 	pgcnt;		/* for page count */	

double 	D_Roundoff();
main(argc,argv)
int argc;
char *argv[];
{
	int 	retval;

	retval = Initialize(argc,argv);	/* Initialization routine */

	if (retval == NOERROR) retval = Process();

	CloseRtn();			/* return to menu */
	if (retval != NOERROR) exit(1);
	exit(0);
}

/*-------------------------------------------------------------------*/
/* Initialize PROFOM */

Initialize(argc, argv)
int	argc ;
char	*argv[] ;
{
	int	retval ;

	/*
	*	Initialize DBH Environment
	*/
	strncpy(SYS_NAME,SYSTEM,50);	/* Sub system name */
	strncpy(CHNG_DATE,MOD_DATE,10);	/* Modification Date */

	proc_switch(argc, argv, CHEQUE) ; 	/* Process Switches */

	/*
	*	Initialize PROFOM & Screen
	*/
	STRCPY(sr.termnm,terminal);	/* Copy Terminal Name */
	fomin(&sr);
	ret(err_chk(&sr)) ;		/* Check for PROFOM Error */
	fomcf(1,1);			/* Enable Snap screen option */

	retval = InitScreen() ;		/* Initialize Screen */
	if(NOERROR != retval) return(retval) ;

	return(NOERROR) ;
}	/* Initialize() */

/*--------------------------------------------------------------------------*/
/* Close nessary files and environment before exiting program               */

CloseRtn() 
{
	/* Set terminal back to normal mode from PROFOM */
	fomcs();
	fomrt();

	close_dbh();	/* Close files */
	close_rep();	/* Close report */

	return(NOERROR);
}	/* CloseRtn() */
/*----------------------------------------------------------------*/
/* Initialize screen before going to process options */

InitScreen()
{
	/* move screen name to Profom status structure */
	STRCPY(sr.scrnam,NFM_PATH);
	strcat(sr.scrnam,SCR_NAME) ;

	STRCPY(s_sth.s_pgm,PROG_NAME);
	s_sth.s_rundate = get_date();	/* get Today's Date in YYYYMMDD format*/
	s_sth.s_option[0] = HV_CHAR;
	s_sth.s_mesg[0] = HV_CHAR ;
	s_sth.s_resp[0] = HV_CHAR ;

	return(NOERROR) ;
}	/* InitScreen() */

/*-------------------------------------------------------------------*/
/* Get Option from user and call corresponding function */

Process()
{
	int	retval;

	for( ; ; ){

		if((retval = ReadOption())<0) 
			return(retval);

		switch(s_sth.s_option[0]) {
		case  EXITOPT :
			return(NOERROR);
		case  ROLLOVER :
			CHKACC(retval,ADD,e_mesg);
			retval = ProcOption() ;
			break ;
		default :
			continue;
		}

		if(NOACCESS == retval)	fomen(e_mesg);
		if(PROFOM_ERR == retval)	return(PROFOM_ERR);  /* PROFOM ERROR */
		if(DBH_ERR == retval) {
			DispError((char *)&s_sth,e_mesg);
#ifdef ENGLISH
			sprintf(e_mesg,"%s %d Dberror: %d Errno: %d",
				"System Error... Iserror:",
				iserror, dberror, errno);
#else
			sprintf(e_mesg,"%s %d Dberror: %d Errno: %d",
				"Erreur du systeme... Iserror:",
				iserror, dberror, errno);
#endif
			DispError((char *)&s_sth,e_mesg);
			return(DBH_ERR); /* DBH ERROR */
		
		}
	}      /*   end of the for( ; ; )       */
}	/* Process() */
/*------------------------------------------------------------*/
ReadOption()
{

	s_sth.s_mesg[0] = HV_CHAR;
	DispMesgFld((char *)&s_sth);	
#ifdef ENGLISH
	fomer("R(ollover), E(xit)");
#else
	fomer("R(ouler), F(in)");
#endif
	sr.nextfld = OPTION;
	fomrf((char *)&s_sth);
	ret(err_chk(&sr));

}	/* ReadOption */
/*------------------------------------------------------------*/
ProcOption()
{
	int	i, retval ;

	retval = Confirm() ;
	if(retval != YES) return(NOERROR) ;

	retval = Proc() ;

	return(NOERROR);
}	/* ProcOption() */
/*----------------------------------------------------------------*/
/* Validation function() for Key and Header fields when PROFOM returns
  RET_VAL_CHK */

static
Validation()
{

	return(NOERROR) ;
}	/* Validation() */
/*----------------------------------------------------------------*/
/* Show Help Windows, if applicable, when user gives ESC-H in key
   and header fields */

static
WindowHelp()
{

	fomer("No Help Window for This Field");

	return(NOERROR) ;
}	/* HdrAndKeyWindowHelp() */
/*-----------------------------------------------------------------------*/
/* Take the confirmation from user for the header part */

Confirm()
{
	int	retval ;

	for( ; ; ) {
#ifdef ENGLISH
		retval = GetOption((char *)&s_sth,"Y(es), C(ancel)", "YEC");
#else
		retval = GetOption((char *)&s_sth,"O(ui), A(nnuler)", "OMA");
#endif
		if(retval == PROFOM_ERR) return(retval) ;

		switch(retval) {
		case  YES :
			return(YES) ;
		case  CANCEL :
#ifdef ENGLISH
			retval = GetOption((char *)&s_sth,"Confirm the Cancel (Y/N)?", "YN") ;
#else
			retval = GetOption((char *)&s_sth,"Confirmer l'annulation (O/N)?", "ON") ;
#endif
			if(retval == YES) { 
				roll_back(e_mesg) ;	/* Unlock  Records */
				return(CANCEL) ;
			}
			break ;
		}	/* switch retval */

		if(retval == PROFOM_ERR) return(retval) ;
		if(retval == DBH_ERR) return(retval) ;
	}	/* for(; ; ) */
}	/* Confirm() */
/*-----------------------------------------------------------------------*/
Proc()
{
	int	i, j, retval;

	emp_rec.em_numb[0] = '\0';
	flg_reset(EMPLOYEE);

	for( ; ; ){
		retval = get_n_employee(&emp_rec,UPDATE,0,FORWARD,e_mesg);
		if(retval < 0) {
			if(retval == EFL) break;
			DispError((char *)&s_sth,e_mesg);
			seq_over(EMPLOYEE);
			return(retval);
		}

		sprintf(e_mesg,"Employee #: %s", emp_rec.em_numb);
		fomen(e_mesg);
		fflush(stdout) ;

		retval = ProcSen();
		if(retval < 0)	return(retval);

		retval = UpdtEmp();
		if(retval < 0)	return(retval);

		inc_str(emp_rec.em_numb, sizeof(emp_rec.em_numb)-1, 
			FORWARD);
		flg_reset(EMPLOYEE);
	}
	seq_over(EMPLOYEE);

	return(NOERROR) ;
}
/*--------------------------------------------------------------------
 ProcSen()     - this routine reads the seniority information to calculate
		 employee seniority YTD totals
--------------------------------------------------------------------*/
static	int
ProcSen()
{
	int 	retval, i, j;

	strcpy(sen_par.sn_position,emp_rec.em_pos);
	sen_par.sn_eff_date = get_date();
	flg_reset(SEN_PAR);

	retval = get_n_sen_par(&sen_par,BROWSE,0,BACKWARD,e_mesg);
	if(strcmp(sen_par.sn_position, emp_rec.em_pos) != 0){
		fomer("Seniority Parameter Not Setup for Position Code");
		get();
	}
	if(retval < 0){
		fomer(e_mesg);
		get();
	}
	seq_over(SEN_PAR);

	strcpy(emp_sen.esn_numb, emp_rec.em_numb);
	emp_sen.esn_month =  0;
	emp_sen.esn_pos[0] = '\0';
	emp_sen.esn_class[0] = '\0';
	flg_reset(EMP_SEN);

	for( ; ; ){
		retval = get_n_emp_sen(&emp_sen, BROWSE, 0, FORWARD, e_mesg);
		if(retval==EFL || strcmp(emp_sen.esn_numb,emp_rec.em_numb)!=0)
			break;

		if(retval < 0) {
			fomen(e_mesg);
			get();
			return(-1);
		}

		emp_rec.em_per_tot_days += emp_sen.esn_perm_days;
		emp_rec.em_cas_tot_days += emp_sen.esn_cas_totd;

		if(emp_rec.em_per_tot_days > sen_par.sn_max_days_yr){ 
			emp_rec.em_per_tot_yrs++;
			emp_rec.em_per_tot_days -= sen_par.sn_max_days_yr;
		}
		if(emp_rec.em_cas_tot_days > sen_par.sn_max_days_yr){ 
			emp_rec.em_cas_tot_yrs++;
			emp_rec.em_cas_tot_days -= sen_par.sn_max_days_yr;
		}
		retval = put_emp_sen(&emp_sen,P_DEL,e_mesg);	
		if(retval < 0) {
		 	DispError((char *)&s_sth,e_mesg);
			roll_back(e_mesg);
		  	return(ERROR);
		}
		retval = commit(e_mesg);
		if(retval < 0) {
			DispError((char *)&s_sth,e_mesg);
			roll_back(e_mesg);
			return(ERROR);
		}
	}
	seq_over(EMP_SEN);

	return(NOERROR);
}
/*-----------------------------------------------------------------------*/
UpdtEmp()
{
	int retval;

	retval = put_employee(&emp_rec,UPDATE,e_mesg);	
	if(retval < 0) {
	 	DispError((char *)&s_sth,e_mesg);
		roll_back(e_mesg);
	  	return(ERROR);
	}
	retval = commit(e_mesg);
	if(retval < 0) {
		DispError((char *)&s_sth,e_mesg);
		roll_back(e_mesg);
		return(ERROR);
	}
	return(NOERROR) ;
}
/******************   END OF PROGRAM *******************************/
