/*-----------------------------------------------------------------------
Source Name: payhis.c
System     : Personnel/Payroll System.
Created  On: 4th Nov. 91.
Created  By: Sheldon Floyd 

DESCRIPTION:
	Program used to monitor the payroll history.

MODIFICATIONS:        

Programmer     YY/MM/DD       Description of modification
------------------------------------------------------------------------*/
#define	MAIN		/* Main program. This is to declare Switches */
#define MAINFL		EMP_EARN		/* main file used */

#define	SYSTEM		"SETUP"			/* Sub System Name */
#define	MOD_DATE	"04-NOV-91"		/* Progran Last Modified */

#include <stdio.h>
#include <cfomstrc.h>
#include <bfs_defs.h>
#include <bfs_pp.h>
#include <ctype.h>
#include <repdef.h>
#include <pp_msgs.h>

/* User Interface define constants */
#ifdef ENGLISH
#define INQUIRE		'1'
#define PURGE		'3'
#define LIST		'2'
#define EXIT		'E'

#else
#define INQUIRE		'1'
#define PURGE		'3'
#define LIST		'2'
#define EXIT		'E'
#endif

/* PROFOM Releted declarations */

#define	SCR_NAME	"payhis"	/* PROFOM screen Name */

#define	PAGESIZE	15		/* No of Items */
/* PROFOM Screen STH file */

/* Field PROFOM numbers */
#define	DATE_FLD	300
#define OPT_FLD		1200
#define EMPCD_FLD	1300
#define	STPD_FLD	1400

#define	ENDPD_FLD	1500
#define CUTOFF_FLD	1600
#define MESG_FLD	1700
#define RESP_FLD	1800

/* payhis.sth - header for C structure generated by PROFOM EDITOR */

typedef struct	{

	long	s_date;		/* 300 system date */
	char	s_opt[2];	/* 1200 option */
	char	s_empcd[13];	/* 1300 employee code */
	short   s_stpd;		/* 1400 start pay period */
	short	s_endpd;	/* 1500 end pay period */
	long	s_cdate;	/* 1600 cutoff date */
	char	s_mesg[78];	/* 1700 message field */
	char	s_resp[2];	/* 1800 response field */
} s_struct;

static	s_struct  s_sth;	/* PROFOM Screen Structure */
static	struct  stat_rec  sr;		/* PROFOM status rec */

static	char 	e_mesg[100];  		/* dbh will return err msg in this */

static  int	Validate();
static  int	WindowHelp();

int	Argc;
char	**Argv;

static 	Emp_earn	empearn;	/* employee earning file */
static	Emp_bh		empbh;		/* employee benefit history file */
static  Emp_dh		empdh;		/* employee deduction history file */
static	Emp_ln_his	lnhis;		/* employee loan history file */
static	Emp_gr_his	grhis;		/* employee garnish history file */
static	Csb_loan	loan;		/* loan file	*/
static	Deduction	deduct;		/* deduction file */
static  Benefit		benefit;	/* benefit file */
static	Emp		emp;		/* employee file */
static  Pay_per		paypd;		/* pay period file */
static	Emp_ins		empins;		/* employee insurable earnings file */
static	Barg_unit	barg_unit;

int head_check, page_no, pg_size;

/*----------------------------------------------------------------------------*/
main(argc,argv)
int argc;
char *argv[];
{
	int 	retval;

	/* These two are passed to execute() when it is called */
	Argc = argc;
	Argv = argv;

	retval = Initialize(argc,argv);	/* Initialization routine */

	if (retval == NOERROR) retval = Process();

	CloseRtn();			/* return to menu */
	if (retval != NOERROR) exit(-1);
	exit(0);

}
/*-------------------------------------------------------------------*/
/* Initialize PROFOM */
Initialize(argc, argv)
int	argc ;
char	*argv[] ;
{
	int	err ;

	/*
	*	Initialize DBH Environment
	*/
	strncpy(SYS_NAME,SYSTEM,50);	/* Sub system name */
	strncpy(CHNG_DATE,MOD_DATE,10);	/* Modification Date */

	proc_switch(argc, argv, MAINFL) ; 	/* Process Switches */

	/*
	*	Initialize PROFOM & Screen
	*/
	strcpy(sr.termnm,terminal);	/* Copy Terminal Name */
	fomin(&sr);
	ret(err_chk(&sr)) ;		/* Check for PROFOM Error */
	fomcf(1,1);			/* Enable Snap screen option */

	err = InitScreen() ;		/* Initialize Screen */
	if(NOERROR != err) return(err) ;

	return(NOERROR) ;
}	/* Initialize() */
/*--------------------------------------------------------------------------*/
/* Close nessary files and environment before exiting program               */
CloseRtn() 
{
	/* Set terminal back to normal mode from PROFOM */
	fomcs();
	fomrt();

	close_dbh();	/* Close files */

	return(NOERROR);
}	/* CloseRtn() */
/*----------------------------------------------------------------*/
/* Initialize screen before going to process options */

InitScreen()
{
	int	err ;

	/* move screen name to Profom status structure */
	strcpy(sr.scrnam,NFM_PATH);
	strcat(sr.scrnam,SCR_NAME) ;

	s_sth.s_date = get_date();	/* get Today's Date in YYYYMMDD format*/
	s_sth.s_empcd[0] = HV_CHAR;
	s_sth.s_stpd = HV_SHORT;
	s_sth.s_endpd = HV_SHORT;

	s_sth.s_cdate = HV_LONG;
	s_sth.s_mesg[0] = HV_CHAR ;
	s_sth.s_resp[0] = HV_CHAR ;

	/* Move High Values to data fields and Display the screen */
	err = ClearScreen() ;
	if(NOERROR != err) return(err) ;

	return(NOERROR) ;
}	/* InitScreen() */
/*-------------------------------------------------------------------*/
/* Get Option from user and call corresponding function */
Process()
{
	int err;

	for( ; ; ){

		/* Get the Fn: option from the user */
		if((err = ReadFunction()) != NOERROR) return(err) ;
		if(err < 0) return(err);
		if(s_sth.s_opt[0] == EXIT) return(NOERROR);

		if(QUIT == err)		return(NOERROR) ;    /* Exit */
		s_sth.s_empcd[0] = LV_CHAR;
		s_sth.s_stpd = LV_SHORT;
		s_sth.s_endpd = LV_SHORT;

		if(s_sth.s_opt[0] == LIST || s_sth.s_opt[0] == INQUIRE){
			page_no = 1;
			err = ProReport();
			if(err < 0) return(err);
			if(s_sth.s_opt[0] == LIST){
				close_rep();
			}
			ClearScreen();
		}

		if(s_sth.s_opt[0] == PURGE){
			s_sth.s_cdate = LV_LONG;
			err = ProPurge();
			if(err < 0) return(err);
			ClearScreen();
		}

	}      /*   end of the for( ; ; )       */
}	/* Process() */
/*----------------------------------------------------------------*/
/* enter the menu option					  */
ReadFunction()
{
	int retval;

	retval = ReadFields((char *)&s_sth,OPT_FLD,OPT_FLD,Validate,
		WindowHelp,0);
	if(retval < 0) return(retval);

	return(NOERROR) ;
}	/* ReadFunction() */
/*----------------------------------------------------------------*/
/* Inquire on payroll history information   			  */
ProReport()
{
	int retval, line_chk = 0;

	retval = ReadFields((char *)&s_sth,EMPCD_FLD,ENDPD_FLD,Validate,
		WindowHelp,0);
	if(retval < 0) return(retval);
	
	retval = InitPrinter();
	if(retval < 0) return(retval);

	strcpy(empearn.en_numb,s_sth.s_empcd);
	empearn.en_date = 0;
	empearn.en_pp = 0;
	empearn.en_week = 0;
	flg_reset(EMP_EARN);

	for(;;){
		retval = get_n_emp_earn(&empearn,BROWSE,0,FORWARD,e_mesg);
		if(retval == EFL) break;
		if(retval < 0){
			DispError((char *)&s_sth,e_mesg);
			return(retval);
		}

		if(strcmp(s_sth.s_empcd,empearn.en_numb)!=0) break;
		if(empearn.en_pp > s_sth.s_endpd || empearn.en_pp <
			 s_sth.s_stpd) continue;

		strcpy(empins.in_numb,empearn.en_numb);
		empins.in_date = empearn.en_date;
		empins.in_pp = empearn.en_pp;
		retval = get_emp_ins(&empins,BROWSE,0,e_mesg);
		if(retval < 0){
			DispError((char *)&s_sth,e_mesg);
			return(retval);
		}

		if((s_sth.s_opt[0] == LIST && line_chk == 1) ||
			(s_sth.s_opt[0] == INQUIRE)) rite_top();
		line_chk = 1;
		retval = PrintHeadings();
		if(retval < 0) return(retval);

		/* Report Line 1 */
		mkln(5,"PAY PERIOD",10);
		mkln(21,":",1);
		sprintf(e_mesg,"%d",empearn.en_pp);
		mkln(23,e_mesg,2);

		mkln(40,"UIC PREMIUMS    :",17);
		tedit((char *)&empearn.en_uic,"_,___,_0_.__-",e_mesg,R_DOUBLE);
		mkln(58,e_mesg,13);
		if(prnt_line()< 0) return(REPORT_ERR);

		/* Report Line 2 */
		mkln(5,"DATE",4);
		mkln(21,":",1);
		tedit((char *)&empearn.en_date,"____/__/__-",e_mesg,R_LONG);
		mkln(23,e_mesg,10);

		mkln(40,"UIC INS EARNINGS:",17);
		tedit((char *)&empins.in_uic_ins,"_,___,_0_.__-",
			e_mesg,R_DOUBLE);
		mkln(58,e_mesg,13);
		if(prnt_line()< 0) return(REPORT_ERR);

		/* Report Line 3 */
		mkln(5,"CHEQUE NUMBER   :",17);
		sprintf(e_mesg,"%d",empearn.en_chq_no);
		mkln(23,e_mesg,8);

		mkln(40,"NO WEEKS INS    :",17);
		sprintf(e_mesg,"%d",empins.in_num_ins_wk);
		mkln(58,e_mesg,2);
		if(prnt_line()< 0) return(REPORT_ERR);

		/* Report Line 4 */
		mkln(5,"UNITS           :",17);
		tedit((char *)&empearn.en_reg_units,"_0_.__-",
			e_mesg,R_DOUBLE);
		mkln(23,e_mesg,7);

		mkln(40,"INCOME TAX      :",17);
		tedit((char *)&empearn.en_tax,"_,___,_0_.__-",
			e_mesg,R_DOUBLE);
		mkln(58,e_mesg,13);
		if(prnt_line()< 0) return(REPORT_ERR);

		/* Report Line 5 */
		mkln(5,"GROSS PAY       :",17);
		empearn.en_high_inc += empearn.en_reg_inc;
		tedit((char *)&empearn.en_high_inc,"_,___,_0_.__-",
			e_mesg,R_DOUBLE);
		mkln(23,e_mesg,13);
		
		mkln(40,"REG PEN CONTR   :",17);
		empearn.en_reg1 += (empearn.en_reg2 + empearn.en_reg3);
		tedit((char *)&empearn.en_reg1,"_,___,_0_.__-",
			e_mesg,R_DOUBLE);
		mkln(58,e_mesg,13);
		if(prnt_line()< 0) return(REPORT_ERR);

		/* Report Line 6 */
		mkln(5,"DEFERRED INCOME :",17);
		tedit((char *)&empearn.en_def_inc,"_,___,_0_.__-",
			e_mesg,R_DOUBLE);
		mkln(23,e_mesg,13);
		
		mkln(40,"NET PAY         :",17);
		tedit((char *)&empearn.en_net,"_,___,_0_.__-",
			e_mesg,R_DOUBLE);
		mkln(58,e_mesg,13);
		if(prnt_line()< 0) return(REPORT_ERR);

		/* Report Line 7 */
		mkln(5,"CPP CONTRIBUTION:",17);
		tedit((char *)&empearn.en_cpp,"_,___,_0_.__-",
			e_mesg,R_DOUBLE);
		mkln(23,e_mesg,13);
		
		mkln(40,"CPP PEN EARNINGS:",17);
		tedit((char *)&empearn.en_cpp_pen,"_,___,_0_.__-",
			e_mesg,R_DOUBLE);
		mkln(58,e_mesg,13);
		if(prnt_line()< 0) return(REPORT_ERR);
		if(prnt_line()< 0) return(REPORT_ERR);

		mkln(5,"BENEFITS",8);
		mkln(38,"CODE",4);
		mkln(49,"AMOUNTS",7);
		if(prnt_line()< 0) return(REPORT_ERR);
		head_check = 0;

		line_chk = 0;
		/* print the benefits */
		strcpy(empbh.ebh_numb,empearn.en_numb);
		empbh.ebh_code[0] = '\0';
		empbh.ebh_pp = empearn.en_pp;
		empbh.ebh_date = empearn.en_date;
		flg_reset(EMP_BEN_HIS);

		for(;;){
			retval = get_n_emp_bhis(&empbh,BROWSE,0,FORWARD,e_mesg);
			if(retval == EFL) break;
			if(retval < 0){
				DispError((char *)&s_sth,e_mesg);
				return(retval);
			}

			if(strcmp(empearn.en_numb,empbh.ebh_numb)!=0) break;
			if(empearn.en_pp != empbh.ebh_pp) continue;
			if(empearn.en_date != empbh.ebh_date) continue;

			retval = CheckPage();
			if(retval < 0) return(retval);
		
			strcpy(benefit.bn_code,empbh.ebh_code);
			benefit.bn_pp_code[0] = '\0';
			flg_reset(BENEFIT);
			retval =get_n_benefit(&benefit,BROWSE,0,FORWARD,e_mesg);
			if(retval < 0 && retval != EFL){
				DispError((char *)&s_sth,e_mesg);
				return(retval);
			}
			if(retval == EFL || (strcmp(benefit.bn_code,
				empbh.ebh_code)!=0)){
				strcpy(benefit.bn_desc,"NOT ON FILE");
			}

			mkln(5,benefit.bn_desc,30);
			mkln(37,empbh.ebh_code,6);
			tedit((char *)&empbh.ebh_amount,"_,___,_0_.__-",
				e_mesg,R_DOUBLE);
			mkln(45,e_mesg,13);
			if(prnt_line()< 0) return(REPORT_ERR);
			line_chk = 1;
		}
		seq_over(EMP_BEN_HIS);
		if(linecnt < pg_size && line_chk == 1){
			if(prnt_line()< 0) return(REPORT_ERR);
		}

		retval = CheckPage();
		if(retval < 0) return(retval);

		mkln(5,"DEDUCTIONS",10);
		mkln(38,"CODE",4);
		mkln(49,"AMOUNTS",7);
		if(prnt_line()< 0) return(REPORT_ERR);
		head_check = 1;

		strcpy(empdh.edh_numb,empearn.en_numb);
		empdh.edh_pp = empearn.en_pp;
		empdh.edh_date = empearn.en_date;
		empdh.edh_code[0] = '\0';
		empdh.edh_group[0] = '\0';
		flg_reset(EMP_DED_HIS);
		
		for(;;){
			retval = get_n_emp_dhis(&empdh,BROWSE,0,FORWARD,e_mesg);
			if(retval == EFL) break;
			if(retval < 0){
				DispError((char *)&s_sth,e_mesg);
				return(retval);
			}

			if(strcmp(empearn.en_numb,empdh.edh_numb)!=0) break;
			if(empearn.en_pp != empdh.edh_pp) continue;
			if(empearn.en_date != empdh.edh_date) continue;

			retval = CheckPage();
			if(retval < 0) return(retval);

			strcpy(deduct.dd_code,empdh.edh_code);
			deduct.dd_pp_code[0] = '\0';
			flg_reset(DEDUCTION);
			retval=get_n_deduction(&deduct,BROWSE,0,FORWARD,e_mesg);
			if(retval < 0 && retval != EFL){
				DispError((char *)&s_sth,e_mesg);
				return(retval);
			}
			if(retval == EFL || 
				(strcmp(deduct.dd_code,empdh.edh_code)!=0)){
				strcpy(deduct.dd_desc,"NOT ON FILE");
			}

			mkln(5,deduct.dd_desc,30);
			mkln(37,empdh.edh_code,6);
			tedit((char *)&empdh.edh_amount,"_,___,_0_.__-",
				e_mesg,R_DOUBLE);
			mkln(45,e_mesg,13);
			if(prnt_line()< 0) return(REPORT_ERR);
		}
		seq_over(EMP_DED_HIS);

		strcpy(lnhis.elh_numb,empearn.en_numb);	
		lnhis.elh_code[0] = '\0';
		lnhis.elh_seq = 0;
		flg_reset(EMP_LOAN_HIS);

		for(;;){
			retval = get_n_emp_lhis(&lnhis,BROWSE,0,FORWARD,e_mesg);
			if(retval == EFL) break;
			if(retval < 0){
				DispError((char *)&s_sth,e_mesg);
				return(retval);
			}

			if(strcmp(empearn.en_numb,lnhis.elh_numb)!=0) break;
			if(empearn.en_pp != lnhis.elh_pp) continue;
			if(empearn.en_date != lnhis.elh_date) continue;

			retval = CheckPage();
			if(retval < 0) return(retval);

			strcpy(loan.cs_code,lnhis.elh_code);
			retval = get_loan(&loan,BROWSE,0,e_mesg);
			if(retval < 0 && retval != UNDEF){
				DispError((char *)&s_sth,e_mesg);
				return(retval);
			}
			if(retval == UNDEF){
				strcpy(loan.cs_desc,"NOT ON FILE");
			}

			mkln(5,loan.cs_desc,30);
			mkln(37,lnhis.elh_code,6);
			tedit((char *)&lnhis.elh_amount,"_,___,_0_.__-",
				e_mesg,R_DOUBLE);
			mkln(45,e_mesg,13);
			if(prnt_line()< 0) return(REPORT_ERR);
		}
		seq_over(EMP_LOAN_HIS);

		strcpy(grhis.egh_numb,empearn.en_numb);	
		grhis.egh_pr_cd = 0;
		grhis.egh_seq = 0;
		flg_reset(EMP_GARN_HIS);

		for(;;){
			retval = get_n_emp_ghis(&grhis,BROWSE,0,
				FORWARD,e_mesg);
			if(retval == EFL) break;
			if(retval < 0){
				DispError((char *)&s_sth,e_mesg);
				return(retval);
			}

			if(strcmp(empearn.en_numb,grhis.egh_numb)!=0) break;
			if(empearn.en_pp != grhis.egh_pp) continue;
			if(empearn.en_date != grhis.egh_date) continue;

			retval = CheckPage();
			if(retval < 0) return(retval);

			sprintf(e_mesg,"%d",grhis.egh_pr_cd);
			mkln(37,e_mesg,2);
			tedit((char *)&grhis.egh_amount,"_,___,_0_.__-",
				e_mesg,R_DOUBLE);
			mkln(45,e_mesg,13);
			if(prnt_line()< 0) return(REPORT_ERR);
		}
		seq_over(EMP_GARN_HIS);

		if(s_sth.s_opt[0] == INQUIRE){
			fomen(ANYKEY);
			get();
		}
		page_no++;
	}
	seq_over(EMP_EARN);
	redraw();

	return(NOERROR) ;
}	/* Inquire() */
/*----------------------------------------------------------------*/
/* check for page break						  */
CheckPage()
{
	int retval;

	if(linecnt < pg_size) return(NOERROR);

	if(s_sth.s_opt[0] == INQUIRE){
		retval = DispError((char *)&s_sth,"Press 'Q' to QUIT or 'Return' to CONTINUE");
		if(retval == 'Q' || retval == 'q') return(1);
	}

	page_no++;
	rite_top();
	
	retval = PrintHeadings();
	if(retval < 0) return(retval);

	if(head_check == 0){
		mkln(5,"BENEFITS",8);
		mkln(38,"CODE",4);
		mkln(48,"AMOUNTS",7);
		if(prnt_line()< 0) return(REPORT_ERR);
	}
	else{
		mkln(5,"DEDUCTIONS",10);
		mkln(38,"CODE",4);
		mkln(48,"AMOUNTS",7);
		if(prnt_line()< 0) return(REPORT_ERR);
	}

	return(NOERROR);
}
/*----------------------------------------------------------------*/
/* print the screen headings					  */
PrintHeadings()
{
	char	blank_line[80];
	int i;

	mkln(1,"payhis",6);
	mkln(28,"PAYROLL HISTORY INQUIRY",23);
	tedit((char *)&s_sth.s_date,"____/__/__-",e_mesg,R_LONG);
	mkln(64,e_mesg,10);
	if(prnt_line()< 0) return(REPORT_ERR);
	if(prnt_line()< 0) return(REPORT_ERR);

	mkln(1,"FN:",3);
	mkln(5,s_sth.s_opt,1);
	mkln(9,"EMPLOYEE NUMBER:",16);
	mkln(26,s_sth.s_empcd,12);
	if(prnt_line()< 0) return(REPORT_ERR);

	blank_line[0] = '\0';
	for(i=0;i<79;i++){
		strcat(blank_line,"-");
	}
	mkln(1,blank_line,79);
	if(prnt_line()< 0) return(REPORT_ERR);

	mkln(70,"PAGE:",5);
	sprintf(e_mesg,"%d",page_no);
	mkln(76,e_mesg,2);
	if(prnt_line()< 0) return(REPORT_ERR);
	if(prnt_line()< 0) return(REPORT_ERR);
	
	return(NOERROR);
}
/*----------------------------------------------------------------*/
InitPrinter()
{
	char	resp[2] ;
	char	discfile[15] ;

	/* Always to Printer */
	if(s_sth.s_opt[0] == LIST){
		strcpy(resp,"P");
		discfile[0] = '\0';
		pg_size = 60;
	}
	else{
		strcpy(discfile,terminal);
		strcpy(resp,"D");
		pg_size = 21;
	}
	
	linecnt = 0;
	page_no = 1;

	if(opn_prnt(resp,discfile,1,e_mesg,1)<0){
		fomen(e_mesg);
		get();
		return(-1);
	}
	return(NOERROR) ;
}
/*-----------------------------------------------------------------*/
/* purge records from file up to the cutoff date		   */
ProPurge()
{
	int retval;

	retval = ReadFields((char *)&s_sth,EMPCD_FLD,CUTOFF_FLD,Validate,
		WindowHelp,0);
	if(retval < 0) return(retval);

	strcpy(empearn.en_numb,s_sth.s_empcd);
	empearn.en_date = 0;
	empearn.en_pp = 0;
	empearn.en_week = 0;
	flg_reset(EMP_EARN);

	for(;;){
		retval = get_n_emp_earn(&empearn,UPDATE,0,FORWARD,e_mesg);
		if(retval == EFL) break;
		if(retval < 0){
			DispError((char *)&s_sth,e_mesg);
			return(retval);
		}

		if(strcmp(empearn.en_numb,s_sth.s_empcd)!=0) break;

		if(s_sth.s_cdate > empearn.en_date) continue;

		retval = put_emp_earn(&empearn,P_DEL,e_mesg);
		if(retval < 0){
			DispError((char *)&s_sth,e_mesg);
			return(retval);
		}

		retval = commit();
		if(retval < 0) return(retval);

		empearn.en_date++;
		flg_reset(EMP_EARN);
	}
	seq_over(EMP_EARN);

	strcpy(empdh.edh_numb,s_sth.s_empcd);
	empdh.edh_pp = 0;
	empdh.edh_date = 0;
	empdh.edh_code[0] = '\0';
	empdh.edh_group[0] = '\0';
	flg_reset(EMP_DED_HIS);

	for(;;){
		retval = get_n_emp_dhis(&empdh,UPDATE,0,FORWARD,e_mesg);
		if(retval == EFL) break;
		if(retval < 0){
			DispError((char *)&s_sth,e_mesg);
			return(retval);
		}

		if(strcmp(empdh.edh_numb,s_sth.s_empcd)!=0) break;

		if(s_sth.s_cdate > empdh.edh_date) continue;

		retval = put_emp_dhis(&empdh,P_DEL,e_mesg);
		if(retval < 0){
			DispError((char *)&s_sth,e_mesg);
			return(retval);
		}

		retval = commit();
		if(retval < 0) return(retval);

		empdh.edh_date++;
		flg_reset(EMP_DED_HIS);
	}
	seq_over(EMP_DED_HIS);

	strcpy(empbh.ebh_numb,s_sth.s_empcd);
	empbh.ebh_pp = 0;
	empbh.ebh_date = 0;
	empbh.ebh_code[0] = '\0';
	flg_reset(EMP_BEN_HIS);

	for(;;){
		retval = get_n_emp_bhis(&empbh,UPDATE,0,FORWARD,e_mesg);
		if(retval == EFL) break;
		if(retval < 0){
			DispError((char *)&s_sth,e_mesg);
			return(retval);
		}

		if(strcmp(empbh.ebh_numb,s_sth.s_empcd)!=0) break;

		if(s_sth.s_cdate > empbh.ebh_date) continue;

		retval = put_emp_bhis(&empbh,P_DEL,e_mesg);
		if(retval < 0){
			DispError((char *)&s_sth,e_mesg);
			return(retval);
		}

		retval = commit();
		if(retval < 0) return(retval);

		empbh.ebh_date++;
		flg_reset(EMP_BEN_HIS);
	}
	seq_over(EMP_BEN_HIS);

	strcpy(lnhis.elh_numb,s_sth.s_empcd);
	lnhis.elh_seq = 0;
	lnhis.elh_code[0] = '\0';
	flg_reset(EMP_LOAN_HIS);

	for(;;){
		retval = get_n_emp_lhis(&lnhis,UPDATE,0,FORWARD,e_mesg);
		if(retval == EFL) break;
		if(retval < 0){
			DispError((char *)&s_sth,e_mesg);
			return(retval);
		}

		if(strcmp(lnhis.elh_numb,s_sth.s_empcd)!=0) break;

		if(s_sth.s_cdate > lnhis.elh_date) continue;

		retval = put_emp_lhis(&lnhis,P_DEL,e_mesg);
		if(retval < 0){
			DispError((char *)&s_sth,e_mesg);
			return(retval);
		}

		retval = commit();
		if(retval < 0) return(retval);

		lnhis.elh_seq++;
		flg_reset(EMP_LOAN_HIS);
	}
	seq_over(EMP_LOAN_HIS);

	strcpy(grhis.egh_numb,s_sth.s_empcd);
	grhis.egh_seq = 0;
	grhis.egh_pr_cd = 0;
	flg_reset(EMP_GARN_HIS);

	for(;;){
		retval = get_n_emp_ghis(&grhis,UPDATE,0,FORWARD,e_mesg);
		if(retval == EFL) break;
		if(retval < 0){
			DispError((char *)&s_sth,e_mesg);
			return(retval);
		}

		if(strcmp(grhis.egh_numb,s_sth.s_empcd)!=0) break;

		if(s_sth.s_cdate > grhis.egh_date) continue;

		retval = put_emp_ghis(&grhis,P_DEL,e_mesg);
		if(retval < 0){
			DispError((char *)&s_sth,e_mesg);
			return(retval);
		}

		retval = commit();
		if(retval < 0) return(retval);

		grhis.egh_seq++;
		flg_reset(EMP_GARN_HIS);
	}
	seq_over(EMP_GARN_HIS);

	return(NOERROR);
}
/*-----------------------------------------------------------------*/
/* Set Duplication buffers for fields 				  */
SetDupBuffers( firstfld, lastfld, value )
int	firstfld, lastfld;	/* field numbers range */
int	value;			/* ENABLE or DISABLE */
{
	int i ;

	for( i=firstfld; i<=lastfld; i+=100 )
		fomca1( i, 19, value);
	if( value==0 )
		return(0);
	sr.nextfld = firstfld;
	sr.endfld = lastfld;
	fomud( (char *)&s_sth );
	ret( err_chk(&sr) );

	return( 0 );
}
/*----------------------------------------------------------------*/
/* Validation function() when PROFOM returns RET_VAL_CHK          */
Validate()
{
	int	retval;

	switch(sr.curfld){
	case OPT_FLD:
		if(s_sth.s_opt[0] == '\0'){
			s_sth.s_opt[0] = LV_CHAR;
			return(-1);
		}

		if(s_sth.s_opt[0] == INQUIRE) break;
		if(s_sth.s_opt[0] == PURGE) break;
		if(s_sth.s_opt[0] == LIST) break;
		if(s_sth.s_opt[0] == EXIT) break;

		fomen(INVOPT);
		s_sth.s_opt[0] = LV_CHAR;
		return(-1);

	case EMPCD_FLD:
		if(s_sth.s_empcd[0] == '\0'){
			s_sth.s_empcd[0] = LV_CHAR;
			return(-1);
		}
		
		strcpy(emp.em_numb,s_sth.s_empcd);
		retval = get_employee(&emp,BROWSE,0,e_mesg);
		if(retval == UNDEF){
			fomen(NOKEY);
			s_sth.s_empcd[0] = LV_CHAR;
			return(-1);
		}

		if(retval < 0){
			DispError((char *)&s_sth,e_mesg);
			return(retval);
		}

		strcpy(barg_unit.b_code,emp.em_barg);
		barg_unit.b_date = get_date();
		flg_reset(BARG);

		retval = get_n_barg(&barg_unit,BROWSE,0,BACKWARD,e_mesg);
		if(retval == EFL ||
			strcmp(barg_unit.b_code, emp.em_barg) != 0){
			sprintf(e_mesg,"Bargaining Unit does no exist: %s",
				emp.em_barg);
  			DispError((char *)&s_sth,e_mesg);
			s_sth.s_empcd[0] = LV_CHAR;
			return(ERROR);
		}
		if(retval < 0){
  			DispError((char *)&s_sth,e_mesg);
			s_sth.s_empcd[0] = LV_CHAR;
  			return(ERROR);
		}
		seq_over(BARG);

		break;

	case STPD_FLD:
		if(s_sth.s_stpd == 0){
			s_sth.s_stpd = LV_SHORT;
			return(-1);
		}

		strcpy(paypd.pp_code,barg_unit.b_code);
		paypd.pp_year = 0;
		flg_reset(PAY_PERIOD);

		retval = get_n_pay_per(&paypd,BROWSE,0,FORWARD,e_mesg);
		if(retval < 0){
			    DispError((char *)&s_sth,e_mesg);
			    return(retval);
		}
		if(strcmp(paypd.pp_code,barg_unit.b_pp_code)!=0){
#ifdef ENGLISH
		    sprintf(e_mesg,"Pay Period Code %s Not on File",
			    	barg_unit.b_pp_code);
#else
		    sprintf(e_mesg,"Pay Period Code %s Not on File",
	    			barg_unit.b_pp_code);
#endif
		    DispError((char *)&s_sth,e_mesg);
		    return(ERROR);
		}
		seq_over(PAY_PERIOD);

		if(paypd.pp_numb < s_sth.s_stpd){
#ifdef ENGLISH
			fomen("Pay Period Greater Than Maximum");
#else
			fomen("Pay Period Greater Than Maximum");
#endif
			s_sth.s_stpd = LV_SHORT;
			return(-1);
		}
		break;

	case ENDPD_FLD:
		if(s_sth.s_endpd == 0){
			s_sth.s_endpd = LV_SHORT;
			return(-1);
		}

		strcpy(paypd.pp_code,barg_unit.b_pp_code);
		paypd.pp_year = 0;
		flg_reset(PAY_PERIOD);

		retval = get_n_pay_per(&paypd,BROWSE,0,FORWARD,e_mesg);
		if(retval < 0){
			DispError((char *)&s_sth,e_mesg);
			return(retval);
		}
		if(strcmp(paypd.pp_code,barg_unit.b_pp_code)!=0){
#ifdef ENGLISH
		    	sprintf(e_mesg,"Pay Period Code %s Not on File",
			    	barg_unit.b_pp_code);
#else
			sprintf(e_mesg,"Pay Period Code %s Not on File",
	    			barg_unit.b_pp_code);
#endif
			DispError((char *)&s_sth,e_mesg);
			return(ERROR);
		}
		seq_over(PAY_PERIOD);

		if(paypd.pp_numb < s_sth.s_endpd){
#ifdef ENGLISH
			fomen("Pay Period Greater Than Maximum");
#else
			fomen("Pay Period Greater Than Maximum");
#endif
			s_sth.s_endpd = LV_SHORT;
			return(-1);
		}

		if(s_sth.s_endpd < s_sth.s_stpd){
			fomen(NOTGRTR);
			s_sth.s_endpd = LV_SHORT;
			s_sth.s_stpd = LV_SHORT;
			sr.curfld-= 100;
			return(-1);
		}
		break;

	case CUTOFF_FLD:
		if(s_sth.s_cdate == 0){
			s_sth.s_cdate = LV_LONG;
			return(-1);
		}
		break;

	default:
#ifdef ENGLISH
		sprintf(e_mesg,"No Validity Check for Field#  %d",sr.curfld);
		
#else
		sprintf(e_mesg,"Pas de controle de validite pour le Champ#  %d",sr.curfld);
#endif
		fomen(e_mesg);
		get();
		return(ERROR) ;
	}	/* Switch sr.curfld */

	return(NOERROR) ;
}	/* Validation() */
/*----------------------------------------------------------------*/
/* Show Help Windows, if applicable, when user gives ESC-H        */
WindowHelp()
{
	int	retval;

	switch(sr.curfld){
	case EMPCD_FLD:
		retval = emp_hlp(s_sth.s_empcd,7,13);
		if(retval == DBH_ERR) return(retval);
		redraw();

		strcpy(barg_unit.b_code,emp.em_barg);
		barg_unit.b_date = get_date();
		flg_reset(BARG);

		retval = get_n_barg(&barg_unit,BROWSE,0,BACKWARD,e_mesg);
		if(retval == EFL ||
			strcmp(barg_unit.b_code, emp.em_barg) != 0){
			sprintf(e_mesg,"Bargaining Unit does no exist: %s",
				emp.em_barg);
  			DispError((char *)&s_sth,e_mesg);
			s_sth.s_empcd[0] = LV_CHAR;
			return(ERROR);
		}
		if(retval < 0){
  			DispError((char *)&s_sth,e_mesg);
			s_sth.s_empcd[0] = LV_CHAR;
  			return(ERROR);
		}
		seq_over(BARG);

		break;

	default :
		fomer("No Help Window for This Field");
	}	/* Switch sr.curfld */

	return(NOERROR) ;
}
/*---------------------------------------------------------------------*/
/* Move High values to all data fields and clear the screen */
ClearScreen()
{
	int	retval;

	s_sth.s_opt[0] = ' ';
	s_sth.s_empcd[0] = HV_CHAR;
	s_sth.s_stpd = HV_SHORT;
	s_sth.s_endpd = HV_SHORT;
	s_sth.s_cdate = HV_LONG;

	retval = WriteFields((char *)&s_sth,DATE_FLD,RESP_FLD);
	if(retval < 0) return(retval);

	return(NOERROR);
}	/* ClearScreen() */
/*-------------------- E n d   O f   P r o g r a m ---------------------*/
