/*-----------------------------------------------------------------------
Source Name: fixars.c
System     : Accounts Receivable.
Created  On: 7-DEC-94.
Created  By: L.Robichaud

DESCRIPTION:
	Program to fix invoices that were put on the system and not properly 
	completed.  This program allows access to the completion flag.

MODIFICATIONS:        

Programmer     YY/MM/DD         Description of modification

------------------------------------------------------------------------*/
#define MAIN            /* Main program. This is to declare Switches */
#define MAINFL          ARSHDR           /* main file used */

#define SYSTEM          "ACCOUNTS RECEIVABLE"   /* Sub System Name */
#define MOD_DATE        "7-DEC-94"              /* Progran Last Modified */

#include <stdio.h>
#include <cfomstrc.h>
#include <bfs_defs.h>
#include <bfs_recs.h>

#define EXIT 12

/* User Interface define constants */
#define ADDREC          'A'
#define INQUIRE         'I'
#define NEXT            'N'
#define PREV            'P'
#define EXITOPT         'E'

#define YES             'Y'
#define NO              'N'
#define APPLY           'A'
#define UNAPPLY         'U'
#define NEXTPAGE        'N'
#define PREVPAGE        'P'
#define CANCEL          'C'

#define T_INVOICE       "IN"
#define T_CRMEMO        "CM"
#define T_DBMEMO        "DM"

#define APPLY_STAT      "APP"
#define UNAPP_STAT      "UAP"

/* PROFOM Releted declarations */

#define SCR_NAME        "fixars"        /* PROFOM screen Name */

/* PROFOM Screen STH file */

/* Field PROFOM numbers */

/* HDR Fields */
#define FN_FLD          400     /* Fn: */
#define CUST_FLD        600     /* Customer Code: */
#define STATUS_FLD      1100
#define END_FLD		2500

/* Message/Response Fields */
#define MESSAGE_FLD     2400
#define RESP_FLD        2500

/* fixars.sth - header for C structure generated by PROFOM EDITOR */

typedef struct	{

	char	s_pgm[11];	/* field 100 Program name */
	long	s_rundate;	/* field 300 Date on the top of screen */
	char	s_fn[2];	/* field 400 function */
	char	s_cu_code[11];	/* field 600 customer code */
	short	s_fund;		/* field 700 fund */
	long	s_inv_no;	/* field 800 invoice number */
	short	s_sno;		/* field 900 sequence number */
	char	s_type[3];	/* field 1000 type (IN/CM/DM) */
	char	s_status[1];	/* field 1100 status of invoice */
	long	s_trandt;	/* field 1200 transaction date */
	long	s_duedt;	/* field 1300 due date */
	double	s_netamt;	/* field 1400 net amount */
	double	s_gramt;	/* field 1500 gross amount */
	double	s_gstpercent;	/* field 1600 gst percent */
	double	s_gstamt;	/* field 1700 gst amount */
	double	s_txpercent;	/* field 1800 pst percent */
	double	s_txamt;	/* field 1900 pst amount */
	double	s_oriamt;	/* field 2000 original amount */
	double	s_balance;	/* field 2100 balance */
	short	s_period;	/* field 2200 accounting period */
	char	s_remarks[21];	/* field 2300 comments */
	char	s_mesg[78];	/* field 2400 */
	char	s_resp[2];	/* field 2500 */
} s_struct;


double  D_Roundoff();

static  s_struct  s_sth;        /* PROFOM Screen Structure */
static  struct  stat_rec  sr;           /* PROFOM status rec */

static  Cu_rec          cu_rec ;        /* Customer Record */
static  Rcpt_hdr        rcpt_hdr ;      /* Receipts Header Record */
static  Rcpt_item       rcpt_item ;     /* Receipts Item Record */
static  Ar_hdr          ar_hdr ;        /* Sales Invoice Header Record */
static  Pa_rec          pa_rec ;        /* Parameter Record */

static  char    e_mesg[100];            /* dbh will return err msg in this */

int     Validation() ;
int     HdrAndKeyWindowHelp() ;


main(argc,argv)
int argc;
char *argv[];
{
	int     retval;

	retval = Initialize(argc,argv); /* Initialization routine */

	if (retval == NOERROR) 
		retval = Process();

	CloseRtn();                     /* return to menu */
	if (retval != NOERROR) exit(-1);
	exit(0);
}

/*-------------------------------------------------------------------*/
/* Initialize PROFOM */

Initialize(argc, argv)
int     argc ;
char    *argv[] ;
{
	int     err ;

	/*
	*       Initialize DBH Environment
	*/
	strncpy(SYS_NAME,SYSTEM,50);    /* Sub system name */
	strncpy(CHNG_DATE,MOD_DATE,10); /* Modification Date */

	proc_switch(argc, argv, MAINFL) ;       /* Process Switches */

	/*
	*       Initialize PROFOM & Screen
	*/
	strcpy(sr.termnm,terminal);     /* Copy Terminal Name */
	fomin(&sr);
	ret(err_chk(&sr)) ;             /* Check for PROFOM Error */
	fomcf(1,1);                     /* Enable Snap screen option */

	err = InitScreen() ;            /* Initialize Screen */
	if(NOERROR != err) return(err) ;

	/*
	*       Get The Parameter Record
	*/
	err = get_param(&pa_rec, BROWSE, 1, e_mesg) ;
	if(err == ERROR) {
		DispError(e_mesg);
		return(ERROR) ;
	}
	else if(err == UNDEF) {
#ifdef ENGLISH
		DispError("Parameters Are Not Set Up ...");
#else
		DispError("Parametres ne sont pas etablis... ");
#endif
		return(ERROR) ;
	}


	return(NOERROR) ;
}       /* Initialize() */

/*--------------------------------------------------------------------------*/
/* Close nessary files and environment before exiting program               */

CloseRtn() 
{
	/* Set terminal back to normal mode from PROFOM */
	fomcs();
	fomrt();

	close_dbh();    /* Close files */

	return(NOERROR);
}       /* CloseRtn() */
/*----------------------------------------------------------------*/
/* Initialize screen before going to process options */

InitScreen()
{
	int     err ;

	/* move screen name to Profom status structure */
	strcpy(sr.scrnam,NFM_PATH);
	strcat(sr.scrnam,SCR_NAME) ;

	strcpy(s_sth.s_pgm,PROG_NAME);

	s_sth.s_rundate = get_date();   /* get Today's Date in YYYYMMDD format*/
	s_sth.s_mesg[0] = HV_CHAR ;
	s_sth.s_resp[0] = HV_CHAR ;

	/* Move High Values to data fields and Display the screen */
	err = ClearScreen() ;
	if(NOERROR != err) return(err) ;

	return(NOERROR) ;
}       /* InitScreen() */

/*-------------------------------------------------------------------*/
/* Get Option from user and call corresponding function */

Process()
{
	int err;

	for( ; ; ){

		/* Get the Fn: option from the user */
		if((err = ReadFunction()) != NOERROR) return(err) ;

		err = ProcFunction() ;  /* Process Function */

		if(QUIT == err)         return(NOERROR) ;    /* Exit */
		if(NOACCESS == err)     fomen(e_mesg);       /* security */
		if(PROFOM_ERR == err)   return(PROFOM_ERR);  /* PROFOM ERROR */
		if(DBH_ERR == err) {
			DispError(e_mesg);
#ifdef ENGLISH
			sprintf(e_mesg,"%s %d Dberror: %d Errno: %d",
				"System Error... Iserror:",
				iserror, dberror, errno);
#else
			sprintf(e_mesg,"%s %d Dberror: %d Errno: %d",
				"Erreur du systeme... Iserror:",
				iserror, dberror, errno);
#endif
			DispError(e_mesg);
			return(DBH_ERR); /* DBH ERROR */
		}
	}      /*   end of the for( ; ; )       */
}       /* Process() */
/*----------------------------------------------------------------*/
/* Display the Function (Fn:) options and get the option from the user */

ReadFunction()
{
	/* Display Fn: options */

	fomer("I(nquire), N(ext), P(rev), C(omplete), E(xit)");
	
	/* Read Fn: field to get the option */
	sr.nextfld = FN_FLD ;
	fomrf( (char *)&s_sth );
	ret(err_chk(&sr));      /* Check for PROFOM error */

	return(NOERROR) ;
}       /* ReadFunction() */
/*----------------------------------------------------------------*/
/* Process the user selected Fn: option */

ProcFunction()
{
	int retval;

	switch (s_sth.s_fn[0]) {
	case COMPLETE :                  /* COMPLETE */
		CHKACC(retval,UPDATE,e_mesg);
		return( ChangeInvoice() ) ;
	case INQUIRE  :         
		CHKACC(retval,BROWSE,e_mesg);
		return( Inquire() ) ;
	case NEXT  :                    
		CHKACC(retval,BROWSE,e_mesg);
		return( GetDetails(FORWARD) ) ;
	case PREV  :            
		CHKACC(retval,BROWSE,e_mesg);
		return( GetDetails(BACKWARD) ) ;
	case EXITOPT  :                 /* Exit */
		return( QUIT ) ;
	}  /*   end of the switch statement */

	return(retval);
}       /* ProcFunction() */
/*----------------------------------------------------------------------*/
/* Get receipt to Apply to invoices */

ChangeInvoice()
{
	int     err;

	SetDupBuffers( CUST_FLD, CUST_FLD, 2 );

	err = get_arhdr( &ar_hdr, UPDATE, 1, e_mesg);
	if(err == UNDEF) {
		DispError(e_mesg);
		return(NOERROR);
	}
	if(err < 0){
		DispError(e_mesg);
		return(err);
	}

	err = GetOption("Complete this Invoice Y/N","YN");
	if(err==NO)
		return(NOERROR);

	ar_hdr.ah_status[0] = COMPLETE;
	ar_hdr.ah_balance = 0.00;
	err = put_arhdr(&ar_hdr,UPDATE,e_mesg);
	if(err < 0) {
		fomer(e_mesg); get();
		roll_back(e_mesg);
		return(DBH_ERR);
	}
       
	return(NOERROR);
}       /* ChangeInvoice() */
/*-----------------------------------------------------------------------*/
Inquire()
{
	int     retval;


	s_sth.s_cu_code[0] = LV_CHAR;

	/* Get reference number */
	retval = ReadFields(CUST_FLD, CUST_FLD,
		Validation, HdrAndKeyWindowHelp, 0) ;
	if(PROFOM_ERR == retval || DBH_ERR == retval) return(retval) ;
	if(RET_USER_ESC == retval) { /* ESC-F */
		s_sth.s_mesg[0] = HV_CHAR ;
		ShowMesg() ;
		return(NOERROR) ;
	}

	retval = GetDetails(FORWARD) ;
	if(PROFOM_ERR == retval || DBH_ERR == retval) return(retval) ;
	if(retval < 0 || CANCEL == retval) {
		roll_back(e_mesg) ;     /* Unlock the locked Records */
		return(ClearScreen()) ; /* Clear the Screen */
	}

	return(NOERROR) ;
}       /* Inquire() */
/*-----------------------------------------------------------------------*/
/* Get Item Details.                                                     */
GetDetails(dir)
int	dir; /* Direction of the get next */
{
	int err;

	strcpy(ar_hdr.ah_cu_code,s_sth.s_cu_code);

	/* Check for the initialization of key */
	if(s_sth.s_fn[0] == INQUIRE || s_sth.s_cu_code[0] == HV_CHAR){
		ar_hdr.ah_fund = 0;
		ar_hdr.ah_inv_no = 0;
		ar_hdr.ah_sno = 0;
	}
	else{
		if(dir == FORWARD)
			ar_hdr.ah_sno ++;
		else
			ar_hdr.ah_sno --;
	}

	flg_reset(ARSHDR);

	for( ; ; ) {
		err = get_n_arhdr( &ar_hdr, BROWSE, 1, dir, e_mesg);
		if(ERROR == err) return(DBH_ERR) ;
		if(EFL == err){
			DispError("No More Records...");
			return(NOERROR); 
		}

		/* process if is status is not complete */
		if(ar_hdr.ah_status[0] != COMPLETE)
				break;

	}

	seq_over(ARSHDR) ;

	err = FillScreen();
	if(err < 0) return(err);

	return(NOERROR);
}       /* GetDetails() */
/*-----------------------------------------------------------------------*/
CheckRcptExist(exists)
int     *exists;
{
	int     err;

	/* Assume receipt does not exist until it finds it */
	*exists = 0;

	strcpy(rcpt_item.ritm_cust,s_sth.s_cu_code);
	rcpt_item.ritm_invnumb = ar_hdr.ah_inv_no;
	rcpt_item.ritm_refno = 0;
	rcpt_item.ritm_seqno = 0;
	flg_reset(RCPTITEM);
	for( ; ; ) {
		err = get_n_rcptitem(&rcpt_item,BROWSE,1,FORWARD,e_mesg);
		if(err == EFL) break;
		if(err < 0) {
			fomer(e_mesg); get();
			return(DBH_ERR);
		}

		if(strcmp(rcpt_item.ritm_cust,s_sth.s_cu_code) != 0 ||
		   rcpt_item.ritm_invnumb != ar_hdr.ah_inv_no ||
		   rcpt_item.ritm_refno != rcpt_hdr.rhdr_refno) break;

		if(rcpt_item.ritm_invnumb == ar_hdr.ah_inv_no) {
			*exists = 1;
			break;
		}
	}
	seq_over(RCPTITEM);
	return(NOERROR);
}

/*------------------------------------------------------------*/
/* Read the PROFOM Screen for a given Range of fields */
static
ReadFields(st_fld, end_fld, Validate, WindowHelp, mode)
int	st_fld ;
int	end_fld;
int	(*Validate)() ;
int	(*WindowHelp)() ;
int	mode ;	/* ADD or UPDATE. This is required only when reading item */
{
	int	err ;

	sr.nextfld = st_fld ;
	sr.endfld  = end_fld;
	for( ; ;){
		fomrd( (char *)&s_sth );
		ret(err_chk(&sr));

		if(sr.retcode == RET_VAL_CHK){
			err = (*Validate)(mode) ;
			if(DBH_ERR == err || PROFOM_ERR == err) return(err);
			sr.nextfld = sr.curfld ;
			continue;
		}
		if(sr.retcode == RET_USER_ESC){
			if(sr.escchar[0] == 'f' || sr.escchar[0] == 'F')
				return(RET_USER_ESC) ;
			if(sr.escchar[0] == 'h' || sr.escchar[0] == 'H'){
				err = (*WindowHelp)() ;
				if(DBH_ERR == err || PROFOM_ERR == err)
					return(err) ;
				sr.nextfld = sr.curfld ;
				continue;
			}
			continue;
		}
		/* else RET_NO_ERROR */
		break;
	}

	return(NOERROR) ;
}
/*------------------------------------------------------------*/
/* Write fields on Screen for a given Range */
static
WriteFields(st_fld, end_fld)
int     st_fld ;
int     end_fld ;
{
	sr.nextfld = st_fld ;
	sr.endfld  = end_fld ;

	fomwr( (char *)&s_sth );
	ret(err_chk(&sr));

	return(NOERROR) ;
}       /* WriteFields() */
/*----------------------------------------------------------------*/
/* Set Duplication buffers for fields                             */
SetDupBuffers( firstfld, lastfld, value )
int     firstfld, lastfld;      /* field numbers range */
int     value;                  /* ENABLE or DISABLE */
{
	int i;

	for( i=firstfld; i<=lastfld; i+=100 )
		fomca1( i, 19, value);
	if( value==0 )
		return(0);
	sr.nextfld = firstfld;
	sr.endfld = lastfld;
	fomud( (char *)&s_sth );
	ret( err_chk(&sr) );

	return( 0 );
}
/*----------------------------------------------------------------*/
/* Validation function() for Key and Header fields when PROFOM returns
  RET_VAL_CHK */
static
Validation()
{
	int     err ;

	switch(sr.curfld){
	case    CUST_FLD:       /* customer number*/

			Right_Justify_Numeric(s_sth.s_cu_code,
					sizeof(s_sth.s_cu_code)-1);
			break;

	default :
#ifdef ENGLISH
		sprintf(e_mesg,"No Validity Check For Field#  %d",sr.curfld);
#else
		sprintf(e_mesg,"Pas de controle de validite pour le Champ#  %d",sr.curfld);
#endif
		fomen(e_mesg);
		get();
		return(ERROR) ;
	}       /* Switch sr.curfld */

	return(NOERROR) ;
}       /* Validation() */
/*----------------------------------------------------------------*/
/* read receipts item file. */
GetRcptItems()
{
	int     err;

	/* rcpt_item_total = 0.00; */
	
	rcpt_item.ritm_refno = rcpt_hdr.rhdr_refno;
	rcpt_item.ritm_seqno = 0;
	flg_reset(RCPTITEM);
	for( ; ; ) {
		err = get_n_rcptitem(&rcpt_item,BROWSE,0,FORWARD,e_mesg);
		if(err == EFL) break;
		if(err < 0) {
			fomer(e_mesg); get();
			return(DBH_ERR);
		}
		if(rcpt_item.ritm_refno != rcpt_hdr.rhdr_refno) break;
		/* rcpt_item_total += rcpt_item.ritm_amount; */
	}
	seq_over(RCPTITEM);
	return(NOERROR);
}       /* GetRcptItem() */
/*----------------------------------------------------------------*/
/* read customer file. */
GetCustomer()
{
	int     err;
	
	strcpy(cu_rec.cu_code,rcpt_hdr.rhdr_cust);
	err = get_cust(&cu_rec,BROWSE,0,e_mesg);
	if(err < 0) {
		fomer(e_mesg); get();
		return(DBH_ERR);
	}
	return(NOERROR);
}       /* GetCustomer() */
/*----------------------------------------------------------------*/
/* Show Help Windows, if applicable, when user gives ESC-H in key
   and header fields */

HdrAndKeyWindowHelp()
{
#ifdef ENGLISH
	fomer("No Help Window For This Field");
#else
	fomer("Pas de fenetre d'assistance pour ce champ");
#endif

	return(NOERROR) ;
}       /* HdrAndKeyWindowHelp() */
/*-----------------------------------------------------------------------*/
/* Display message and get the option */
static
GetOption(msg,options)
char    *msg ;
char    *options ;
{
	int     i, j ;

	strcpy(s_sth.s_mesg,msg);
	ShowMesg() ;

	sr.nextfld = END_FLD ;
	for( ; ; ) {
		fomrf( (char *)&s_sth ) ;
		ret(err_chk(&sr)) ;

		j = strlen(options) ;
		for( i = 0 ; i < j ; i++)
			if(s_sth.s_resp[0] == options[i]) break ;
		if(i != j) break ;      /* Valid Option Selected */
#ifdef ENGLISH
		fomer("Invalid Option..");
#else
		fomer("Option invalide..");
#endif
	}

	s_sth.s_mesg[0] = HV_CHAR ;
	s_sth.s_resp[0] = HV_CHAR ;
	
	ret( WriteFields(END_FLD -100, END_FLD) );

	return((int)(options[i])) ;
}       /* GetOption() */
/*-----------------------------------------------------------*/
/* Move High values to all data fields and clear the screen */

ClearScreen()
{

	/* Move High Values to Hedaer part */
	s_sth.s_cu_code[0] = HV_CHAR;
	s_sth.s_fund = HV_SHORT;
	s_sth.s_inv_no = HV_LONG;
	s_sth.s_sno = HV_SHORT;
	s_sth.s_type[0] = HV_CHAR;
	s_sth.s_status[0] = HV_CHAR;
	s_sth.s_trandt = HV_LONG;
	s_sth.s_duedt = HV_LONG;
	s_sth.s_oriamt = HV_DOUBLE;
	s_sth.s_gramt = HV_DOUBLE;
	s_sth.s_txpercent = HV_DOUBLE;
	s_sth.s_txamt = HV_DOUBLE;
	s_sth.s_netamt = HV_DOUBLE;
	s_sth.s_balance = HV_DOUBLE;
	s_sth.s_period = HV_SHORT;
	s_sth.s_gstpercent = HV_DOUBLE;
	s_sth.s_gstamt = HV_DOUBLE;
	s_sth.s_remarks[0] = HV_CHAR;

	ret( WriteFields(CUST_FLD, (END_FLD - 200)) );

	return(NOERROR);
}
/*-----------------------------------------------------------*/
/* This routine is designed to populate the screen with the values from file*/
FillScreen()
{

	/* Fill screen vaibles with file contents */
	strcpy(s_sth.s_cu_code, ar_hdr.ah_cu_code);
	s_sth.s_fund = ar_hdr.ah_fund;
	s_sth.s_inv_no = ar_hdr.ah_inv_no;
	s_sth.s_sno = ar_hdr.ah_sno;
	strcpy(s_sth.s_type, ar_hdr.ah_type);
	strcpy(s_sth.s_status, ar_hdr.ah_status);
	s_sth.s_trandt = ar_hdr.ah_trandt;
	s_sth.s_duedt = ar_hdr.ah_duedt;
	s_sth.s_oriamt = ar_hdr.ah_oriamt;
	s_sth.s_gramt = ar_hdr.ah_gramt;
	s_sth.s_txpercent = ar_hdr.ah_txpercent;
	s_sth.s_txamt = ar_hdr.ah_txamt;
	s_sth.s_netamt = ar_hdr.ah_netamt;
	s_sth.s_balance = ar_hdr.ah_balance;
	s_sth.s_period = ar_hdr.ah_period;
	s_sth.s_gstpercent = ar_hdr.ah_gstpercent;
	s_sth.s_gstamt = ar_hdr.ah_gstamt;
	strcpy(s_sth.s_remarks, ar_hdr.ah_remarks);

	ret( WriteFields(CUST_FLD, (END_FLD - 200)) );

	return(NOERROR);
}
/*-------------------------------------------------------------------------*/

ShowMesg()  /* shows or clears message field */
{
	sr.nextfld = END_FLD - 100;
	fomwf( (char *)&s_sth ) ;
}
