/*----------------------------------------------------------------------
Source Name: empben.c  
System     : PP
Module     : Payroll/Personel
Created On : Nov. 16, 1991
Created By : Andre Cormier

DESCRIPTION:

	This program allows the user to maintain the employee benefit
	file.
MODIFICATIONS:        

Programmer     	YY/MM/DD       	Description of modification
~~~~~~~~~~     	~~~~~~~~       	~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
------------------------------------------------------------------------*/

#define	MAINFL		EMP_BEN

#include <stdio.h>
#include <cfomstrc.h>
#include <bfs_defs.h>
#include <bfs_pp.h>
#include <bfs_com.h>
#include <empldrvr.h>

#define MOD_DATE	"16-NOV-91"
#define SYSTEM   	"PAYROLL/PERSONEL"

#define PRGNM  		"emp_ben"
#define	SCR_NAME	"emp_ben"


#define	ALLOC_ERROR	-19
#define	MAX_KEYS	13
#define	PAGESIZE	13

#ifdef ENGLISH

#define EDITITEMS	'E'
#define INQREC		'I'
#define FIXED		'F'
#define PERCENT		'P'
#define ADDITEMS	'A'
#define DELITEM		'D'
#define REACTIVATE	'R'
#define END 		'E'
#define ACTIVE		"ACT"
#define INACTIVE	"DEL"
#define ADDREC		'A'
#define	CHGREC		'C'
#define DELREC		'D'
#define EXITOPT		'E'
#define ITEMEDIT	'I'
#define	HDREDIT		'H'
#define YES		'Y'
#define NO		'N'
#define	LINEEDIT	'L'
#define	SCREDIT		'S'
#define	CANCEL		'C'
#define	ALL		'A' 

#else		/* if FRENCH */

#define EDITITEMS	'E'
#define INQREC		'I'
#define FIXED		'F'
#define PERCENT		'P'
#define ADDITEMS	'A'
#define DELITEM		'D'
#define REACTIVATE	'R'
#define END 		'E'
#define ACTIVE		"ACT"
#define INACTIVE	"DEL"
#define ADDREC		'A'
#define	CHGREC		'C'
#define DELREC		'D'
#define EXITOPT		'E'
#define ITEMEDIT	'I'
#define YES		'O'
#define NO		'N'
#define	LINEEDIT	'M'
#define	SCREDIT		'C'
#define	CANCEL		'A'
#define	ALL		'T' 

#endif

#define FN_FLD		400 	/* system date field */
#define	KEY_START	500	/* program name field */
#define KEY_END		500 	/* system date field */
#define NAME_FLD	600 	/* employee name field */
#define	CHG_FLD		700	/* field: prompt */

#define PAGE_FLD	900	/* page number field */
#define DUMMY1_FLD	1000 	/* dummy field */
#define DUMMY2_FLD	1100 	/* dummy field */

#define	ITEM_ST_FLD	1200
#define	ITEM_END_FLD	1600

#define BEN_FLD		1200	/* start item field */
#define DESC_FLD	1300	/* end item field */
#define AMOUNT_FLD	1400 	/* start amount field */
#define YTD_FLD		1500 	/* start amount field */
#define STAT_FLD	1600	/* start status field */

#define STEP		500

#define	MESG_FLD	7700
#define	END_FLD 	7800

/* repcd1.sth - header for C structure generated by PROFOM EDITOR */
typedef struct{
	char	s_bencd[7];	/* benefit code */
	char	s_desc[33];	/* benefit description */
	double	s_amount;	/* amount */
	double	s_benytd;	/* benefit YTD amount */
	char	s_status[4];	/* status */
	} S_item;

typedef struct{
	char	s_prgnm[11];	/* 100 program name */
	long	s_sysdate;	/* 300 system date */
	char	s_fn[2];	/* 400 fucntion */
	char	s_emp[13];	/* 500 employee code */
	char	s_name[31];	/* 600 employee name */
	short	s_field;	/* 700 field number */
	short	s_page;		/* 1100 line number 1 */
	char	s_dummy1[8];	/* 1200 dummy field */
	char	s_dummy2[10];	/* 1200 dummy field */
	S_item	s_items[PAGESIZE];/*3300 - 4000 group information */
	char	s_mesg[78];	/* 4100 message line */
	char	s_opt[2];	/* 4200 message option line */
	} s_struct;

static	s_struct  s_sth,image;	/* PROFOM Screen Structure */

/* link list node for holding one page of entries */

typedef	struct 	 Page{

	S_item  Items[PAGESIZE];	/* array of lines per page */
	struct	Page	*PrevPage ;	/* ptr to previous page */
	struct	Page	*NextPage ;	/* ptr to next page */
	char	I_Status[PAGESIZE][2];
	short	NoItems;		/* number of Items on the page */
	short	Pageno;		/* no of lines entered */

}	Page;

static	Page	*FirstPage,		/* Address of First Page */
		*CurPage,		/* Address of Current Page */
		*CurLast,		/* Address of Curr. record last page */
		*LastPage;		/* Address of Last Page of Memory
					   Allocated */

static  Pay_param	param;		/* pay roll parameter file */
static	Emp_ben		empben, pre_empben;	/* employee benefit file */
static	Emp_bh		empbh;		/* employee benefit history file */
static	Benefit		benefit;	/* benefit file */
static	Barg_unit	barg_unit;

void	free();
char	*malloc() ;

static  int	mode;
static  double	calc_benytd;

static	int	Validate();
static	int	WindowHelp();

/*-------------------------------------------------------------------*/ 
EmpBenefit()
{
	int	err ;

	err = InitScreen() ; 	/* Initialization routine */

	if(emp_rec.em_numb[0] != '\0') {
		flg_reset(EMPLOYEE);

		err = get_n_employee(&emp_rec, BROWSE, 0, FORWARD, e_mesg);
#ifndef ORACLE
		seq_over(EMPLOYEE);
#endif
		if(ERROR == err)return(DBH_ERR) ;
		if(EFL == err) {
			fomen("No More Records....");
			get();
			return(NOERROR) ;
		}

		err = UsrBargVal(BROWSE,emp_rec.em_numb,emp_rec.em_barg,1,e_mesg);
		if(err < 0){
			DispError((char *)&s_sth,e_mesg);
		}
		else{
			strcpy( s_sth.s_emp,emp_rec.em_numb);
			err = ShowScreen();
		}
	}

	err = Process(); 	/* Initiate Process */

	return( err ) ;

} /* end of main */
/*-------------------------------------------------------------------*/
/* Reset information */

static
Close()
{
	/* Set terminal back to normal mode from PROFOM */
	FreeList();
	fomcs();
	fomrt();
	close_dbh();			/* Close files */
	close_rep();

	return(NOERROR);
}
/*----------------------------------------------------------------*/
/* Initialize screen before going to process options */
static
InitScreen()
{
	int	err ;

	/* move screen name to Profom status structure */
	strcpy(sr.scrnam,NFM_PATH);
	strcat(sr.scrnam,SCR_NAME) ;

	strcpy(s_sth.s_prgnm,"emp_ben");

	s_sth.s_sysdate = get_date();	/* get Today's Date in YYYYMMDD format*/
	s_sth.s_field = HV_SHORT ;
	s_sth.s_mesg[0] = HV_CHAR ;
	s_sth.s_opt[0] = HV_CHAR ;

	/* Initialize Key Fields. So that, if user selectes 'N' option
	   immediately after invoking program, then he gets the first
	   record in the file */

	s_sth.s_fn[0] = '\0';
	s_sth.s_emp[0] = '\0';

	/* Move High Values to data fields and Display the screen */
	err = ClearScreen() ;
	if(NOERROR != err) return(err) ;

	return(NOERROR) ;
}	/* InitScreen() */
/*-------------------------------------------------------------------*/
/* Get Option from user and call corresponding function */
static	int
Process()
{
	int	err;

	for( ; ; ){

		/* Get the Fn: from the user */

		if((err = ReadFunction()) != NOERROR) return(err) ;

		err = ProcFunction() ;	/* Process Fn */

		if(QUIT == err)		return(NOERROR) ;	/* Exit */
		if(JUMP == err)		return(JUMP) ;
		if(NOACCESS == err) {
			fomen(e_mesg);
			get();
		}
		if(PROFOM_ERR == err)	return(PROFOM_ERR);  /* PROFOM ERROR */
		if(DBH_ERR == err) {
			DispError((char*)&s_sth, e_mesg);
#ifdef	ENGLISH
			sprintf(e_mesg,"%s %d Dberror: %d Errno: %d",
				"System Error... Iserror:",
				iserror, dberror, errno);
#else
			sprintf(e_mesg,"%s %d Dberror: %d Errno: %d",
				"Erreur du systeme... Iserror:",
				iserror, dberror, errno);
#endif
			DispError((char*)&s_sth, e_mesg);
			return(DBH_ERR);	/* DBH ERROR */
		}
	}      /*   end of the for( ; ; )       */
}	/* Process() */
/*----------------------------------------------------------------*/
/* Display the Function (Fn:) options and get the option from the user */
static int
ReadFunction()
{
	/* Display Fn: options */
#ifdef ENGLISH
	fomer("C(hange), I(nquire), F(orward), B(ack), N(ext), P(rev), S(creen), E(xit)");
#else
	fomer("R(ajouter), C(hanger), I(nterroger), S(uivant), P(recedent), F(in)");
#endif
	/* Read Fn: field to get the option */
	sr.nextfld = FN_FLD ;
	fomrf( (char *)&s_sth );
	ret(err_chk(&sr));	/* Check for PROFOM error */

	return(NOERROR) ;
}	/* ReadFunction() */
/*----------------------------------------------------------------*/
/* Process the user selected Fn: option */
static int
ProcFunction()
{
	int retval;

	switch (s_sth.s_fn[0]) {
	case CHANGE  :			/* CHANGE */
		CHKACC(retval,UPDATE,e_mesg);
		mode = UPDATE;
		return( Change() ) ;
	case INQUIRE  :			/* Inquire */
		CHKACC(retval,BROWSE,e_mesg);
		mode = BROWSE;
		return( Inquire() ) ;
	case NEXT_RECORD  :			/* Next */
		CHKACC(retval,BROWSE,e_mesg);
		return( Next(FORWARD) ) ;
	case PREV_RECORD  :			/* Previous */
		CHKACC(retval,BROWSE,e_mesg);
		return( Next(BACKWARD) ) ;
	case NEXT_SCR  : 	/* Next Screen */
		Cur_Option += 1 ;	/* Set to Next Screen */
		return( JUMP ) ; 
	case PREV_SCR  : 	/* Next Screen */
		Cur_Option -= 1 ;	/* Set to Next Screen */
		return( JUMP ) ; 
	case SCREEN  :			/* Inquire */
		CHKACC(retval,BROWSE,e_mesg);
		return( Screen() ) ;
	case EXITOPT  :			/* Exit */
		return( QUIT ) ;
	}  /*   end of the switch statement */

	return(retval);
}	/* ProcFunction() */
/*-----------------------------------------------------------------------*/
/* Change. Students Study halls and update the files if a day/semester   */
/* is changed to NO delete record.			  		 */
/*-----------------------------------------------------------------------*/
static int
Change()
{
	int	err ;

	err = SelectRecord() ;
	if(NOERROR != err) return(err);

	for( ; ; ) {
		err = ConfirmItems() ;
		if(err != YES) {
			roll_back(e_mesg);
			break;
		}

		err = ProcItemUpdates() ;
		if(err==NOERROR) break;
		if(err==LOCKED) {
			roll_back(e_mesg) ;
			continue;
		}
		if (err < 0) {
			roll_back(e_mesg);
			return(err) ;
		}
	}

	return(NOERROR) ;
}	/* Change() */
/*-----------------------------------------------------------------------*/
/* Show Student Student halls base on users input */
static int
Inquire()
{
	int	err ;

	err = SelectRecord() ;
	if(NOERROR != err) return(err) ;

	err = ConfirmItems() ;
	
	return(NOERROR) ;
}	/* Inquire() */
/*----------------------------------------------------------*/
/* Show the next or previous Students Study halls */
static int
Next(direction)
int	direction ;
{
	int err;

	if(flg_start(EMPLOYEE) != direction) {
		strcpy(emp_rec.em_numb,s_sth.s_emp);
		inc_str(emp_rec.em_numb,sizeof(emp_rec.em_numb)-1,direction);
		flg_reset(EMPLOYEE);
	}
	for( ; ; ){
	  err = get_n_employee(&emp_rec, BROWSE, 0, direction, e_mesg);
#ifndef ORACLE
	  seq_over(EMPLOYEE);
#endif
	  if(ERROR == err)return(DBH_ERR) ;
	  if(EFL == err) {
		fomen("No More Records....");
		get();
		return(NOERROR) ;
	  }

	  err = UsrBargVal(BROWSE,emp_rec.em_numb,emp_rec.em_barg,0,e_mesg);
	  if(err < 0){
		if(err == UNDEF){
			DispError((char *)&s_sth,e_mesg);
			return(ERROR);
		}
	  }
	  else{
		break;
	  }
	}
	strcpy(s_sth.s_emp,emp_rec.em_numb);
	return(ShowScreen());
}	/* Next() */
/*----------------------------------------------------------------------*/
/* Get the Student Study Hall key from user. In ADD mode disable dup buffers, */
/* other modes enable dup buffers and show the current key as a default key */
/*----------------------------------------------------------------------*/
static int
ReadKey()
{
	int	i;
	
	/* In Add mode turn off dup control for key fields.
	   Other modes reverse it */
	if(s_sth.s_fn[0] == ADDREC){	/* ADD */
		SetDupBuffers(KEY_START,KEY_END,0); /* Off Dup Control */
	}
	else {
		SetDupBuffers(KEY_START,KEY_END,1);
	}

#ifdef ENGLISH
	strcpy(s_sth.s_mesg,"Press ESC-F to Go Back to Fn:");
#else
	strcpy(s_sth.s_mesg,"Appuyer sur ESC-F pour retourner a Fn:");
#endif
	DispMesgFld((char *)&s_sth);

	s_sth.s_emp[0] = LV_CHAR;

	i = ReadFields((char *)&s_sth,KEY_START, KEY_END,
		Validate, WindowHelp,1) ;
	if(PROFOM_ERR == i || DBH_ERR == i) return(i) ;
	if(RET_USER_ESC == i){
		
		ret( WriteFields((char *)&s_sth,KEY_START, KEY_END) ) ;

		s_sth.s_mesg[0] = HV_CHAR;
		DispMesgFld((char *)&s_sth);

		return(RET_USER_ESC) ;
	}

	s_sth.s_mesg[0] = HV_CHAR;
	DispMesgFld((char *)&s_sth);

	return(NOERROR);
}	/*  ReadKey() */
/*------------------------------------------------------------*/
/* Read Item Details from the User */
static int
AddItems()
{
	int	i, err ;

	/* If the last node of po is Partial filled then Show Page */
	if(CurLast != NULL && CurLast->NoItems < PAGESIZE ) {
		ret( ShowItems(CurLast) ) ;
		i = CurLast->NoItems ;
		CurPage = CurLast ;
	}
	else {
		/* Calculate the page# */
		if(CurLast != NULL) {
			i = PAGESIZE ;
			CurPage = CurLast ;
		}
		else {
			strcpy(s_sth.s_dummy1,"STATUS");
			strcpy(s_sth.s_dummy2,"(Act/Del)");
			s_sth.s_page = 1 ;
			ret( WriteFields((char *)&s_sth,PAGE_FLD,PAGE_FLD+200));
			i = 0 ;
		}
	}


	for( ; ; ) {
		if( PAGESIZE == i) {	/* Page Full */

			/* Calculate the page# */
			s_sth.s_page = CurLast->Pageno + 1 ;

			ret( WriteFields((char *)&s_sth,PAGE_FLD, 
				(END_FLD - 200)) ) ;

			InitItem(HV_CHAR,HV_DOUBLE,1);
			WriteFields((char *)&s_sth,ITEM_ST_FLD,ITEM_END_FLD);

			i = 0 ;
		}

		err = ReadItem(i) ;		/* Read Each Item Line */
		if(PROFOM_ERR == err || DBH_ERR == err) return(err) ;
		if(NOERROR != err) break ;	/* ESC-F */

		if(0 == i)	/* First Item in the Page */
			if((err = MakeFreshPage()) < 0) return(err) ;
		
		/* Copy the Item to List */
		scpy((char*)&(CurPage->Items[i]), (char*)&(s_sth.s_items[i]),
			sizeof(S_item)) ;

		CurPage->I_Status[i][0] = ADDITEMS;

		i++ ;

		CurPage->NoItems = i;
	}
	if(i == 0) 
		if((err=ShowItems(CurPage))<0) return(err) ;

	return(NOERROR) ;
}	/* AddItems() */
/*----------------------------------------------------------*/
/* Get the key and show the record */
static int
SelectRecord()
{
	int	err ;

	err = ReadKey();
	if(err != NOERROR) return(err) ;

	strcpy(emp_rec.em_numb,s_sth.s_emp);
	err = get_employee(&emp_rec,mode,0,e_mesg);
	if(err < 0) {
		DispError((char *)&s_sth,e_mesg);
		return(err);
	}

	err = ShowScreen();
	if(err < 0) {
		return(err);
	}

	return(NOERROR);
}	/* SelectRecord() */
/*------------------------------------------------------------*/
/* Read details of given item# */
/*------------------------------------------------------------*/
static int
ReadItem(item_no)
int	item_no ;
{

	int	i;
	int	st_fld ;
	int	end_fld ;
	int	retval;

	scpy((char *)&image,(char *)&s_sth,sizeof(image));

	if(mode == ADD) {
		SetDupBuffers(ITEM_ST_FLD, END_FLD - 200,0);
	}
	else {
		SetDupBuffers(ITEM_ST_FLD, END_FLD - 200,1);
	
	}

#ifdef ENGLISH
	strcpy(s_sth.s_mesg,"Press ESC-F to Terminate");
#else
	strcpy(s_sth.s_mesg,"Appuyer sur ESC-F pour terminer");
#endif
	DispMesgFld((char *)&s_sth);

	st_fld = ITEM_ST_FLD + (STEP * item_no);
	end_fld  = st_fld + STEP ;
	if(mode == ADD){
		InitItem(LV_CHAR,LV_DOUBLE,item_no);
		strcpy(s_sth.s_items[item_no].s_status, "ACT");
	}
	else{
		s_sth.s_items[item_no].s_amount = LV_DOUBLE;
	}

	i = ReadFields((char *)&s_sth,st_fld,end_fld,Validate,WindowHelp,1) ;
	if(PROFOM_ERR == i || DBH_ERR == i) return(i) ;
	if(RET_USER_ESC == i) {
		if(mode == ADD) {
			InitItem(HV_CHAR,HV_DOUBLE,item_no);
			WriteFields((char *)&s_sth,st_fld,end_fld);
			return(RET_USER_ESC);
		}
		/* When user gives ESC-F while changing fields, assumption is
		* he completed his changes, and remaining fields are same as
		* old. But, at this point STH will be having low values in the 
		* remaining fields. So move the old values form the linked list.
		*/

		i = CopyBack((char *)&s_sth,(char *)&image,sr.curfld, END_FLD);
		if(i == PROFOM_ERR) return(i);

		return(RET_USER_ESC) ;
	}

	return(NOERROR) ;
}	/* ReadItem() */
/*-----------------------------------------------------------------------*/
/* Take the confirmation from user for the items part of the screen      */
/*-----------------------------------------------------------------------*/
static int
ConfirmItems()
{
	int	err ;

	/* Options: YSLNPC */

	for( ; ; ) {
	    if(s_sth.s_fn[0] == DELREC) {
#ifdef ENGLISH
			err = GetOption((char *)&s_sth,"Y(es), C(ancel)","YC");
#else
			err = GetOption((char *)&s_sth,"O(ui), A(nnul)","OA");
#endif
	    }
	    else if(s_sth.s_fn[0] != INQUIRE) {
#ifdef ENGLISH
			err = GetOption((char *)&s_sth,
		"Y(es), A(dd), L(ine), D(el), R(eactivate), N(ext), P(rev), C(ancel)"
		,"YAHLDRNPC");
#else
			err = GetOption((char *)&s_sth,
		"O(ui), S(creen edit), L(ine edit), S(uiv), P(rec), A(nnul)"
		,"OSLA");
#endif
	    }
	    else {
#ifdef ENGLISH
			err = GetOption((char *)&s_sth,
		"Y(es), N(ext), P(rev)","YNP");
#else
			err = GetOption((char *)&s_sth,
		"O(ui), S(uiv), P(rec)" ,"OSP");
#endif
	    }
	    switch(err) {
	    case  YES  :
		return(YES);
	    case  ADDITEMS:
		err = AddItems();
		break;
	    case  LINEEDIT  :
		err = ChangeFields();
		break ;
	    case  DELITEM:
	    case  REACTIVATE:
		err = ChangeStatus(err);
		break;
	    case NEXT_RECORD  :			/* Next */
		if(CurPage == CurLast || CurLast == NULL) {
#ifdef ENGLISH
			fomer("No More Pages....");
#else
			fomer("Plus de pages....");
#endif
			continue;
		}
		CurPage = CurPage->NextPage ;
		err = ShowItems(CurPage);
		break;
	    case PREV_RECORD  :			/* Next */
		if(CurLast == NULL || CurPage == FirstPage) {
#ifdef ENGLISH
			fomer("No More Pages....");
#else
			fomer("Plus de pages....");
#endif
			continue;
		}
		CurPage = CurPage->PrevPage ;
		err = ShowItems(CurPage);
		break;
	    case  CANCEL :
#ifdef ENGLISH
		err = GetOption((char *)&s_sth,
				"Confirm the Cancel (Y/N)?", "YN") ;
#else
		err = GetOption((char *)&s_sth,
				"Confirmer l'annulation (O/N)?", "ON") ;
#endif
		if(err == YES) return(CANCEL) ;
		break ;
	    }	/* switch err */

	    if(err == PROFOM_ERR) return(err) ;
	    if(err == DBH_ERR) return(err) ;
	}	/* for(; ; ) */
}	/* ConfirmItems() */
/*-----------------------------------------------------------------------*/
/* calculate the YTD amount						 */
static
CalcYTD()
{
	int retval;
	
	calc_benytd = 0;
	
	strcpy(empbh.ebh_numb,emp_rec.em_numb);
	strcpy(empbh.ebh_code,empben.eb_code);
	empbh.ebh_date = 0;
	flg_reset(EMP_BEN_HIS);

	for(;;){
		retval = get_n_emp_bhis(&empbh,BROWSE,1,FORWARD,e_mesg);
		if(retval == EFL) break;
		
		if(retval < 0){
			DispError((char *)&s_sth,e_mesg);
			return(retval);
		}

		if(strcmp(empbh.ebh_numb,emp_rec.em_numb)!=0) break;
		if(strcmp(empbh.ebh_code,empben.eb_code)!=0) break;

/*		if(empbh.ebh_date < param.pr_fisc_st_dt) continue;
		if(empbh.ebh_date > param.pr_fisc_end_dt) continue;*/

		calc_benytd += empbh.ebh_amount;
	}
	seq_over(EMP_BEN_HIS);
	
	return(NOERROR);
}
/*-----------------------------------------------------------------------*/
/* Validate flds when PROFOM returns RET_VAL_CHK    			 */
static
Validate()	
{
	int	retval, i;
	int	fld_no, item_no;
	Page	*temppage;

	if(sr.curfld >= BEN_FLD){
		item_no = (sr.curfld - BEN_FLD) / STEP;
		fld_no = sr.curfld - (item_no * STEP);
	}
	else {
		fld_no = sr.curfld;
	}

	switch(fld_no){

	case 	KEY_START:
		Right_Justify_Numeric(s_sth.s_emp,sizeof(emp_rec.em_numb)-1);
		if(s_sth.s_emp[0] == '\0'){
			s_sth.s_emp[0] = LV_CHAR;
			return(-1);
		}

		strcpy(emp_rec.em_numb,s_sth.s_emp);
		retval = get_employee(&emp_rec,BROWSE,0,e_mesg);
		if(retval == UNDEF){
			fomen(e_mesg);
			s_sth.s_emp[0] = LV_CHAR;
			return(-1);
		}

		if(retval < 0){
			DispError((char *)&s_sth,e_mesg);
			return(retval);
		}
		retval = UsrBargVal(mode,emp_rec.em_numb,emp_rec.em_barg,1,e_mesg);
		if(retval < 0){
			DispError((char *)&s_sth,e_mesg);
		  	s_sth.s_emp[0] = LV_CHAR;
			return(-1);
		}
		strcpy(e_mesg,emp_rec.em_last_name);
		strcat(e_mesg,", ");
		strcat(e_mesg,emp_rec.em_first_name);
		strncpy(s_sth.s_name,e_mesg,30);

		retval=WriteFields((char *)&s_sth,NAME_FLD,NAME_FLD);
		if(retval < 0) return(retval);
		break;

	case	BEN_FLD:

		if(s_sth.s_items[item_no].s_bencd[0] == '\0'){
			s_sth.s_items[item_no].s_bencd[0] = LV_CHAR;
			return(-1);
		}

		strcpy(barg_unit.b_code,emp_rec.em_barg);
		barg_unit.b_date = get_date();
		flg_reset(BARG);

		retval = get_n_barg(&barg_unit,BROWSE,0,BACKWARD,e_mesg);
		if(retval == EFL ||
			strcmp(barg_unit.b_code, emp_rec.em_barg) != 0){
  		   DispError((char *)&s_sth,"Bargaining Unit does not Exist");
			return(NOERROR);
		}
		if(retval < 0){
  			DispError((char *)&s_sth,e_mesg);
  			return(ERROR);
		}
		seq_over(BARG);

		strcpy(benefit.bn_code,s_sth.s_items[item_no].s_bencd);
		strcpy(benefit.bn_pp_code,barg_unit.b_pp_code);
		retval = get_benefit(&benefit,BROWSE,0,e_mesg);
		if(retval < 0){
			fomen(e_mesg);
			s_sth.s_items[item_no].s_bencd[0] = LV_CHAR;
			return(-1);
		}

		strcpy(s_sth.s_items[item_no].s_desc,benefit.bn_desc) ;
	
		strcpy(empben.eb_numb,emp_rec.em_numb);
		strcpy(empben.eb_code,benefit.bn_code);
		retval = get_emp_ben(&empben,BROWSE,0,e_mesg);
		if(retval < 0 && retval != UNDEF){
			DispError((char *)&s_sth,e_mesg);
			return(retval);
		}

		if(retval >= 0){
#ifdef ENGLSH
			fomen("Record Already Exists - Please Re-enter");
#else
			fomen("Record Already Exists - Please Re-enter");
#endif
			s_sth.s_items[item_no].s_bencd[0] = LV_CHAR;
			return(-1);
		}

		/* check to see if item is already in list */
		if(CurLast != NULL) {
		   for(temppage=FirstPage; temppage!=NULL; temppage=temppage->NextPage) { 
		      for(i =0; i< temppage->NoItems; i++) {
			if(temppage->Items[i].s_bencd[0] == NULL) {
				return(NOERROR);
			}
			if(strcmp(temppage->Items[i].s_bencd,
			s_sth.s_items[item_no].s_bencd) == 0) {
#ifdef ENGLSH
			  fomen("Record Already Exists - Please Re-enter");
#else
			  fomen("Record Already Exists - Please Re-enter");
#endif
			  s_sth.s_items[item_no].s_bencd[0] = LV_CHAR;
			  return(-1);
			}
		      }
		      if(temppage == CurLast) break;
		   }
		}

		retval = CalcYTD();
		if(retval < 0) return(retval);

		s_sth.s_items[item_no].s_benytd = calc_benytd;

		break;


	default:
		break;
	}/* end switch */	

	return(NOERROR) ;

}	/* Validate() */
/*-----------------------------------------------------------------------*/
/*                                                                       */
/*  Display help window for applicable Items                            */
static
WindowHelp()
{
	int	i, err, retval;
	char 	tmp_pp[7];
	int	fld_no, item_no;
	Page	*temppage;

	tmp_pp[0] = '\0';
	if(sr.curfld >= BEN_FLD){
		item_no = (sr.curfld - BEN_FLD) / STEP;
		fld_no = sr.curfld - (item_no * STEP);
	}
	else {
		fld_no = sr.curfld;
	}

	strcpy(barg_unit.b_code,emp_rec.em_barg);
	barg_unit.b_date = get_date();
	flg_reset(BARG);

	retval = get_n_barg(&barg_unit,BROWSE,0,BACKWARD,e_mesg);
	if(retval == EFL ||
		strcmp(barg_unit.b_code, emp_rec.em_barg) != 0){
		sprintf(e_mesg,"Bargaining Unit does no exist: %s",
			emp_rec.em_barg);
  		DispError((char *)&s_sth,e_mesg);
		return(NOERROR);
	}
	if(retval < 0){
  		DispError((char *)&s_sth,e_mesg);
  		return(ERROR);
	}
	seq_over(BARG);

	switch(fld_no){
	case BEN_FLD:
		err =benefit_hlp(s_sth.s_items[item_no].s_bencd,
			tmp_pp,7,13);
		if(err < 0) return(err);
		redraw();

		strcpy(benefit.bn_code,s_sth.s_items[item_no].s_bencd);
		strcpy(benefit.bn_pp_code,barg_unit.b_pp_code);
		retval = get_benefit(&benefit,BROWSE,0,e_mesg);
		if(retval < 0){
			DispError((char *)&s_sth,e_mesg);
			s_sth.s_items[item_no].s_bencd[0] = LV_CHAR;
			return(-1);
		}
		strcpy(s_sth.s_items[item_no].s_desc,benefit.bn_desc) ;
	
		strcpy(empben.eb_numb,emp_rec.em_numb);
		strcpy(empben.eb_code,benefit.bn_code);
		retval = get_emp_ben(&empben,BROWSE,0,e_mesg);
		if(retval < 0 && retval != UNDEF){
			DispError((char *)&s_sth,e_mesg);
			return(retval);
		}

		if(retval >= 0){
#ifdef ENGLSH
			fomen("Record Already Exists - Please Re-enter");
#else
			fomen("Record Already Exists - Please Re-enter");
#endif
			s_sth.s_items[item_no].s_bencd[0] = LV_CHAR;
			return(-1);
		}

		/* check to see if item is already in list */
		if(CurLast != NULL) {
		   for(temppage=FirstPage; temppage!=NULL; temppage=temppage->NextPage) { 
		      for(i =0; i< temppage->NoItems; i++) {
			if(temppage->Items[i].s_bencd[0] == NULL) {
				return(NOERROR);
			}
			if(strcmp(temppage->Items[i].s_bencd,
			s_sth.s_items[item_no].s_bencd[0]) == 0) {
#ifdef ENGLSH
			  fomen("Record Already Exists - Please Re-enter");
#else
			  fomen("Record Already Exists - Please Re-enter");
#endif
			  s_sth.s_items[item_no].s_bencd[0] = LV_CHAR;
			  return(-1);
			}
		      }
		      if(temppage == CurLast) break;
		   }
		}

		retval = CalcYTD();
		if(retval < 0) return(retval);

		s_sth.s_items[item_no].s_benytd = calc_benytd;

		strcpy(s_sth.s_items[item_no].s_desc,benefit.bn_desc);
		retval =WriteFields((char *)&s_sth,sr.curfld+100,sr.curfld+300);
		if(retval < 0) return(retval);
		break;

	case KEY_START:
		retval = emp_hlp(s_sth.s_emp,7,13);
		if(retval < 0) return(retval);

		redraw();
		strcpy(emp_rec.em_numb,s_sth.s_emp);
		retval = get_employee(&emp_rec,BROWSE,0,e_mesg);
		if(retval == UNDEF){
			fomen(e_mesg);
			s_sth.s_emp[0] = LV_CHAR;
			return(-1);
		}

		if(retval < 0){
			DispError((char *)&s_sth,e_mesg);
			return(retval);
		}
		strcpy(e_mesg,emp_rec.em_last_name);
		strcat(e_mesg,", ");
		strcat(e_mesg,emp_rec.em_first_name);
		strncpy(s_sth.s_name,e_mesg,30);

		retval=WriteFields((char *)&s_sth,NAME_FLD,NAME_FLD);
		if(retval < 0) return(retval);
		break;
		
	default:
		fomen(e_mesg);
		break;
	}
	sr.nextfld = sr.curfld ;
	return(NOERROR) ;

}	/* WindowHelp() */
/*-------------------------------------------------------------------*/
static
ClearScreen()
{
	int 	j;
	int	retval;

	s_sth.s_page = HV_SHORT;
	s_sth.s_dummy1[0] = HV_CHAR;
	s_sth.s_dummy2[0] = HV_CHAR;

	for( j=0; j < PAGESIZE ; j++ ){
		InitItem(HV_CHAR,HV_DOUBLE,j);
	}

	retval = WriteFields((char*)&s_sth,KEY_START, END_FLD-200);
	if(retval < 0) return(-1);

	return(NOERROR);
}
/*----------------------------------------------------------------*/
/* Set Duplication buffers for fields 				  */
static int
SetDupBuffers( firstfld, lastfld, value )
int	firstfld, lastfld;	/* field numbers range */
int	value;			/* ENABLE or DISABLE */
{
	int i ;

	for( i=firstfld; i<=lastfld; i+=100 )
		fomca1( i, 19, value);
	if( value==0 )
		return(0);
	sr.nextfld = firstfld;
	sr.endfld = lastfld;
	fomud( (char *)&s_sth );
	ret( err_chk(&sr) );

	return( 0 );
}
/*-----------------------------------------------------------------------*/
/*                                                                       */
static
Screen()
{
	int	retval;

	s_sth.s_field = LV_SHORT;
	retval = ReadFields((char *)&s_sth,CHG_FLD,CHG_FLD,
		(int (*)())NULL,(int (*)())NULL, 1);

	if (retval < 0) return(-1);
	if (retval == RET_USER_ESC) return(NOERROR);	/* User enter ESC-F */

       	if (s_sth.s_field == 0 ) return(NOERROR); /* Finished changing Items */

	if (s_sth.s_field > MAX_SCREEN) {
		fomen("Invalid Field Number");
		get();
		s_sth.s_field = LV_SHORT;
		return(NOERROR);
	}

	switch (s_sth.s_field) {
	case SCR_1  :		/* SCR - 1  'DEMOGRAPHIC' */
	case SCR_2  :		/* SCR - 2  'EMPLOYMENT' */
	case SCR_3  :		/* SCR - 3  'RESPONSIBILITY' */
	case SCR_4  :		/* SCR - 4  'EARNINGS' */
	case SCR_5  :		/* SCR - 5  'MISCELLANIOUS' */
	case SCR_7  :		/* SCR - 7  'DEDUCTION' */
	case SCR_8  :		/* SCR - 8  'CSB/LOAN' */
	case SCR_9  :		/* SCR - 9  'GARNISHMENT' */
	case SCR_10 :		/* SCR - 10 'CHEQUE LOCATION' */
	case SCR_11 :		/* SCR - 11 'ATTENDANCE' */
	case SCR_12 :		/* SCR - 12 'SENIORITY' */
	case SCR_13 :		/* SCR - 13 'TEACHER QUALIFICATION' */
	case SCR_14 :		/* SCR - 14 'TEACHER ASSIGNMENT' */
	case SCR_15 :		/* SCR - 15 'COMPETITION' */
	case SCR_16 :		/* SCR - 16 'STATUS' */
		Cur_Option = s_sth.s_field ;
		return( JUMP ) ;
	default   : 
		return(NOERROR);
	}  /*   end of the switch statement */
}
/*------------------------------------------------------------*/
BuildList()
{
	int retval;
	int i;
	int j;
	CurLast = CurPage = NULL;
	i = 0;

	strcpy(barg_unit.b_code,emp_rec.em_barg);
	barg_unit.b_date = get_date();
	flg_reset(BARG);

	retval = get_n_barg(&barg_unit,BROWSE,0,BACKWARD,e_mesg);
	if(retval == EFL ||
		strcmp(barg_unit.b_code, emp_rec.em_barg) != 0){
		sprintf(e_mesg,"Bargaining Unit does no exist: %s",
			emp_rec.em_barg);
  		DispError((char *)&s_sth,e_mesg);
		return(NOERROR);
	}
	if(retval < 0){
  		DispError((char *)&s_sth,e_mesg);
  		return(ERROR);
	}
	seq_over(BARG);

	strcpy(empben.eb_numb, emp_rec.em_numb);
	empben.eb_code[0] = '\0';
	flg_reset(EMP_BEN);


	for( ; ; ) {
		retval = get_n_emp_ben(&empben, BROWSE, 0, FORWARD, e_mesg);
		if(retval < 0) {
			if(retval == EFL) break;
			DispError((char *)&s_sth,e_mesg);
			return(retval);
		}
		if(strcmp(empben.eb_numb,emp_rec.em_numb) != 0) break;

		if(PAGESIZE == i) i = 0;
		if(i == 0) {
			if((retval = MakeFreshPage()) < 0) return(retval);
		}

		strcpy(CurPage->Items[i].s_bencd,empben.eb_code);

		strcpy(benefit.bn_code,empben.eb_code);
		strcpy(benefit.bn_pp_code,barg_unit.b_pp_code);
		retval = get_benefit(&benefit,BROWSE,0,e_mesg);
		if(retval == UNDEF){
			strcpy(benefit.bn_desc,"Not On File");
		}
		if(retval < 0 && retval != UNDEF){
			DispError((char *)&s_sth,e_mesg);
			return(retval);
		}

		retval = CalcYTD();
		if(retval < 0) return(retval);

		strcpy(CurPage->Items[i].s_desc,benefit.bn_desc);
 
		if(benefit.bn_amt_flag[0] == 'F'){
			CurPage->Items[i].s_amount = empben.eb_amount; 
		}
		else{
			CurPage->Items[i].s_amount = HV_DOUBLE;
		}
		CurPage->Items[i].s_benytd = calc_benytd;
		strcpy(CurPage->Items[i].s_status,ACTIVE);

		CurPage->I_Status[i][0] = ' ';
		CurPage->NoItems++;
		i++;
	}
	seq_over(EMP_BEN);


	if(CurLast != NULL) {
		CurPage = FirstPage;
	}

	if(retval == EFL) return(retval);
	return(NOERROR);
}
/*-----------------------------------------------------------------------*/
/*	Get the next node in linked list to add invoice items. If the
*	(Cur. invc last page) = (Last Page in linked List) or no
*	nodes in list, allocate node and add to linked list
*/

MakeFreshPage()
{
	Page	*tempptr ;

	/* If, no node is allocated yet or Current invoice used all the nodes,
	   then allocate new node */

	if( LastPage == NULL || CurLast == LastPage ){
		tempptr= (Page *)malloc((unsigned)sizeof(Page)) ;

		if( tempptr == NULL ){
			DispError((char*)&s_sth,"Memory Allocation Error");
			return(ERROR);
		}
		tempptr->NextPage = NULL ;

		if( LastPage == NULL ){	/* No node is allocated Yet */
			tempptr->PrevPage = NULL ;
			tempptr->Pageno = 1 ;
			FirstPage = tempptr ;
		}
		else {				/* Not a first node in list */
			tempptr->Pageno = LastPage->Pageno + 1 ;
			LastPage->NextPage = tempptr ;
			tempptr->PrevPage = LastPage ;
		}
		LastPage = tempptr ;
	}

	if(CurLast == NULL)
		CurLast = FirstPage ;
	else
		CurLast = CurLast->NextPage ;

	CurLast->NoItems = 0 ;
	CurPage = CurLast ;

	return(NOERROR);
}	/* MakeFreshPage() */
/*-----------------------------------------------------------------------*/
static
FreeList()	
{
	int 	i;

	/* clear the screen items from linked list */

	for(CurPage = FirstPage;CurPage;CurPage = CurPage->NextPage){

		for( i=0; i <= PAGESIZE; i++) {
			if(i >= CurPage->NoItems) break;
		}
	}

	for( CurPage=LastPage; CurPage; CurPage=LastPage){
		LastPage=LastPage->PrevPage;
		free((char *)CurPage );
	}

	FirstPage = NULL;

	return(NOERROR);
}
/*-----------------------------------------------------------------------*/ 
/* Process all the items in the link list and write any changes to the   */
/* file.								 */
/*-----------------------------------------------------------------------*/ 
static int
ProcItemUpdates()
{
	Page	*temppage;
	int	i;
	int	retval;
	int	write_mode;

	if(CurLast != NULL) {
	   for(temppage=FirstPage; temppage!=NULL;temppage=temppage->NextPage) {
	      for(i =0; i< temppage->NoItems; i++) {
		 retval = GetMode(temppage,i,&write_mode);
		 if(write_mode == NOOP) continue;
		 retval = WriteRecords(temppage,i,write_mode);
  		 if(retval < 0) {
			if(retval == LOCKED) return(LOCKED);
		   	break;
		 }
	      }
	      if(temppage == CurLast) break;
	   }
	}
	return(NOERROR);
}
/*-----------------------------------------------------------------------*/ 
static int
GetMode(temppage,item_no,write_mode)
Page	*temppage;
int	item_no;
int	*write_mode;
{
	if(mode == ADD) {
		if(strcmp(temppage->Items[item_no].s_status,INACTIVE)==0) {
			*write_mode = NOOP;
		}
		else {
			*write_mode = ADD;
		}
	}
	else if(mode == UPDATE) {
		if(strcmp(temppage->Items[item_no].s_status,INACTIVE)==0) {
			*write_mode = P_DEL;
		}
		else if(temppage->I_Status[item_no][0] == ADDITEMS) {
			*write_mode = ADD;
		}
		else if(temppage->I_Status[item_no][0] == CHANGE) {
			*write_mode = UPDATE;
		}
		else if(temppage->I_Status[item_no][0] == ' ') {
			*write_mode = NOOP;
		}
	}
	else if(mode == P_DEL) {
		*write_mode = P_DEL;
	}

	return(NOERROR);
}
/*-----------------------------------------------------------------------*/ 
/* Write the Area record to the file.			 		 */ 
/*-----------------------------------------------------------------------*/ 
static int
WriteRecords(temppage,item_no,write_mode)
Page	*temppage;
int	item_no;
int	write_mode;
{
	int	retval;
	int	i;

	retval = put_emp_ben(&empben,mode,e_mesg) ;
	if(retval < 0) {
		DispError((char *)&s_sth,e_mesg);
		roll_back(e_mesg);
		return(retval);
	}

	if(write_mode != ADD) {
		retval = rite_audit((char*)&s_sth,EMP_BEN,mode,(char*)&empben,
			(char*)&pre_empben,e_mesg);
		if(retval==LOCKED) {
			DispError((char *)&s_sth,e_mesg);
			roll_back(e_mesg) ;
			return(LOCKED) ;
		}
		if(retval < 0 ){
			DispError((char *)&s_sth,"ERROR: Saving Records"); 
			DispError((char *)&s_sth,e_mesg);
			roll_back(e_mesg);
			return(retval);
		}
	}

	return(NOERROR);
}
/*-------------------------------------------------------------------------*/
/* Initialize Given screen item with either Low values or High values	 */
static
InitItem(t_char, t_double,item_no)
char	t_char ;
double	t_double ;
int	item_no;
{
	int	i;

	s_sth.s_items[item_no].s_bencd[0] = t_char;
	s_sth.s_items[item_no].s_desc[0] = t_char;
	s_sth.s_items[item_no].s_amount = t_double;
	if(t_char != LV_CHAR)
		s_sth.s_items[item_no].s_benytd = t_double;
		s_sth.s_items[item_no].s_status[0] = t_char;

	return(NOERROR) ;
}	/* Inititem() */
/*---------------------------------------------------------------------*/
/* Change Header.  Allows editing of the students on the screen        */
/*-----------------------------------------------------------------------*/
/*                                                                       */
/* Changing fields. Accept fld of the student to be changed and read     */
/* that fld 		 */
static
ChangeFields()
{
	int retval;
	int day;

	/* make copy screen every time field changed in case user */
	/* presses ESC-F */
	scpy((char*)&image,(char*)&s_sth, sizeof(s_sth));

	SetDupBuffers(ITEM_ST_FLD, END_FLD - 200, 2);

	/* Get The Field to Be Modified */
#ifdef	ENGLISH
	strcpy(s_sth.s_mesg,"Enter RETURN to Terminate Edit");
#else
	strcpy(s_sth.s_mesg,"Appuyer sur RETURN pour terminer l'ajustement");
#endif
	DispMesgFld((char *)&s_sth); ;
        
     	for (; ;) {
		s_sth.s_field = LV_SHORT;
		retval = ReadFields((char *)&s_sth,CHG_FLD,CHG_FLD,
			(int (*)())NULL,(int (*)())NULL, 1);

		if (retval < 0) return(-1);
		if (retval == RET_USER_ESC) break;	/* User enter ESC-F */

       		if (s_sth.s_field == 0 ) break;  /* Finished changing fields */
		if (s_sth.s_field > CurPage->NoItems) {
			fomer("Line Number out of Range");
			continue;
		}

		if(strcmp(CurPage->Items[s_sth.s_field-1].s_status,INACTIVE)==0){
			fomer("Item Has a Deleted Status Cannot Edit");
			continue;
		}
		retval = ReadItem(s_sth.s_field - 1);
		if(retval != NOERROR && retval != RET_USER_ESC) {
			return(retval);
		}

		if(retval == RET_USER_ESC)
			continue;

		/* make copy screen every time field changed in case user */
		/* presses ESC-F */
		scpy((char*)&image,(char*)&s_sth, sizeof(s_sth));

		scpy((char*)&(CurPage->Items[s_sth.s_field -1]), 
		     (char*)&(s_sth.s_items[s_sth.s_field -1]),sizeof(S_item)) ;

		if(s_sth.s_fn[0] == CHANGE) {
		  if(CurPage->I_Status[s_sth.s_field-1][0] != ADD)
			CurPage->I_Status[s_sth.s_field-1][0] = CHANGE;
		}
	}

     	s_sth.s_field = HV_SHORT ;
	if ( WriteFields((char *)&s_sth,CHG_FLD, CHG_FLD) < 0 ) return(-1);

     	s_sth.s_mesg[0] = HV_CHAR ;
     	DispMesgFld((char *)&s_sth);

	if(SetDupBuffers(ITEM_ST_FLD, END_FLD - 200, 0)<0) return(PROFOM_ERR);

	return(NOERROR);
}	/* ChangeFields() */
/*------------------------------------------------------------------------*/
static int
ChangeStatus(status)
int	status;
{
	int	retval;
	int	st_fld, end_fld;

	/* Get The Field to Be Modified */
#ifdef	ENGLISH
	strcpy(s_sth.s_mesg,"Enter RETURN to Terminate Edit");
#else
	strcpy(s_sth.s_mesg,"Appuyer sur RETURN pour terminer l'ajustement");
#endif
	DispMesgFld((char *)&s_sth); ;
        
     	for (; ;) {
		s_sth.s_field = LV_SHORT;
		retval = ReadFields((char *)&s_sth,CHG_FLD,CHG_FLD,
			(int (*)())NULL,(int (*)())NULL, 1);

		if (retval < 0) return(-1);
		if (retval == RET_USER_ESC) break;	/* User enter ESC-F */

       		if (s_sth.s_field == 0 ) break;  /* Finished changing fields */

	
		st_fld  = ITEM_ST_FLD + (STEP * (s_sth.s_field-1)) + 400;
		end_fld  = st_fld;

		if(status == DELITEM) {
			if(strcmp(s_sth.s_items[s_sth.s_field-1].s_status,
			   INACTIVE)==0) {
				fomer("Item is Already Deleted");
			}
			else {
				strcpy(s_sth.s_items[s_sth.s_field-1].s_status,
			   		INACTIVE);
			}
		}
		else {
			if(strcmp(s_sth.s_items[s_sth.s_field-1].s_status,
			   ACTIVE)==0) {
				fomer("Item is Already Active");
			}
			else {
				strcpy(s_sth.s_items[s_sth.s_field-1].s_status,
			   		ACTIVE);
			}
		}
		/* Update Linked List */
		scpy((char*)&(CurPage->Items[s_sth.s_field -1]), 
		     (char*)&(s_sth.s_items[s_sth.s_field -1]),sizeof(S_item)) ;
		
		ret(WriteFields((char *)&s_sth,st_fld,end_fld));
	}
     	s_sth.s_field = HV_SHORT ;
	if ( WriteFields((char *)&s_sth,CHG_FLD, CHG_FLD) < 0 ) return(-1);

	return(NOERROR);
}
/*------------------------------------------------------------*/
static int
ShowScreen()
{
	int	err ;


	err = ShowHdr();
	if(err < 0) {
		return(err);
	}

	/* Get area records i.e. Build list */
	err = BuildList();
	if(err < 0 && err != EFL) {
		return(err);
	}

	err = ShowItems(CurPage);
	if(err < 0) {
		return(err);
	}
	
	return(NOERROR);
}
/*------------------------------------------------------------*/
static int
ShowHdr() 
{
	Page	*itemptr;
	int	retval;
	
	strcpy(s_sth.s_name, emp_rec.em_last_name);
	strcat(s_sth.s_name, ", ");
	strcat(s_sth.s_name, emp_rec.em_first_name);
	strcat(s_sth.s_name, " ");
	strcat(s_sth.s_name, emp_rec.em_mid_name);
	/* Copy Record to Screen */

	ret( WriteFields((char *)&s_sth, KEY_START, KEY_START+100));
	
	return(NOERROR);
}
/*------------------------------------------------------------*/
/* Show all the items on the current page 		      */
static int
ShowItems(pageptr)
Page	*pageptr ;
{
	int	i ;

	if(pageptr != NULL) {
		/* Copy the items to screen */
		scpy((char*)s_sth.s_items, (char*)pageptr->Items,
			(pageptr->NoItems * sizeof(S_item)) );

		s_sth.s_page   = pageptr->Pageno ;
		i = pageptr->NoItems ;
	}
	else {
		s_sth.s_page = HV_SHORT ;
		strcpy(s_sth.s_dummy1, "STATUS") ;
		strcpy(s_sth.s_dummy2, "(Act/Del)") ;
		i = 0 ;
	}

	/* Move High Values to remaining Items */
	for( ; i < PAGESIZE ; i++ )
		InitItem(HV_CHAR,HV_DOUBLE,i);

	ret( WriteFields((char *)&s_sth, PAGE_FLD, (END_FLD - 200)) );

	return(NOERROR) ;
}	/* ShowItems() */
/*-------------------- E n d   O f   P r o g r a m ---------------------*/
