/*-----------------------------------------------------------------------
Source Name: respons.c
System     : Personnel/Payroll System.
Created  On: 12th Nov. 91.
Created  By: Andre Cormier 

DESCRIPTION:

MODIFICATIONS:        

Programmer     YY/MM/DD       Description of modification
------------------------------------------------------------------------*/
#define MAINFL		EMP_EXTRA		/* main file used */

#define	SYSTEM		"SETUP"			/* Sub System Name */
#define	MOD_DATE	"12-NOV-91"		/* Progran Last Modified */

#define	SCR_NAME	"emp_resp"	/* PROFOM screen Name */

#include <stdio.h>
#include <ctype.h>
#include <cfomstrc.h>
#include <bfs_defs.h>
#include <bfs_pp.h>
#include <pp_msgs.h>
#include <empldrvr.h>

/* User Interface define constants */
#ifdef ENGLISH
#define CHANGE		'C'
#define DELETE		'D'
#define INQUIRE		'I'
#define EXITOPT		'E'
#define	NEXT		'N'
#define	PREV		'P'

#define	YES		'Y'
#define NO		'N'
#define ADDITEMS	'A'
#define	LINEEDIT	'L'
#define SCREENEDIT	'S'
#define DELITEM		'D'
#define REACTITEM	'R'
#define	CANCEL		'C'

#define ACTIVE		"ACT"
#define INACTIVE	"DEL"
#else
#define CHANGE		'C'
#define DELETE		'E'
#define INQUIRE		'I'
#define EXITOPT		'F'
#define	NEXT		'S'
#define	PREV		'P'

#define	YES		'O'
#define NO		'N'
#define ADDITEMS	'A'
#define	LINEEDIT	'L'
#define SCREENEDIT	'S'
#define DELITEM		'D'
#define REACTITEM	'R'
#define	CANCEL		'A'

#define ACTIVE		"ACT"
#define INACTIVE	"DEL"
#endif

/* PROFOM Releted declarations */

#define	PAGESIZE	14		/* No of Items */
/* PROFOM Screen STH file */

/* Field PROFOM numbers */

#define FN_FLD		400	/* Fn: */

#define KEY_START	500	/* Key Start Field */
#define KEY_END		600	/* Key End Field */

#define CHG_FLD		700

#define PAGE_FLD	900	/* Page# Field */
#define	DUMMY_FLD	1000
#define	ITEM_ST_FLD	1100	/* Item 1 Start Field */
#define	END_FLD		5400	/* Last Field of the screen */
#define	STEP		300	/* NO of fields diff. between 2 items */

#define	CODE_FLD	1100	/* Deduction Code Field */
#define	AMOUNT_FLD	1200	/* Pay Period Code Field */
#define STATUS_FLD	200	/* Offset of Status in item line */

/* certif.sth - header for C structure generated by PROFOM EDITOR */

typedef	struct	{	/* Start Fld 900, Endfld 5300 and Step 300 */

	char	s_class_code[7];/* 1100-5000 STRING X(7) */
	double	s_amount;	/* 1200-5100 STRING X(30) */
	char	s_status[4]; 	/* 1300-5200 STRING X(3) */
}	S_item ;

typedef struct	{

	char	s_pgname[11];	/* 100 STRING X(10) */
	long	s_rundate;	/* 300 DATE YYYYFMMFDD */
	char	s_fn[2];	/* 400 STRING X */
	char	s_employee[13];	/* 500 STRING X(6) */
	char	s_name[30];	/* 600 STRING X(6) */
	short	s_field;	/* 700 NUMERIC 99 */
	short	s_page;		/* 800 NUMERIC 99 */
	char	s_dummy[2];

	S_item	s_items[PAGESIZE] ;	/* Start Fld 1000, End Fld 6900  */

	char	s_mesg[78];	/* 7000 STRING X(77) */
	char	s_resp[2];	/* 7100 STRING X */
} s_struct;

static	s_struct  s_sth,image;	/* PROFOM Screen Structure */

static	char 	e_mesg[100];  		/* dbh will return err msg in this */

int	Validation() ;
int	WindowHelp() ;

int	Argc;
char	**Argv;

typedef struct Page {
	S_item	Items[PAGESIZE] ;	/* Items Information */
	struct	Page	*PrevPage ;	/* ptr to previous page */
	struct	Page	*NextPage ;	/* ptr to next page */
	char	I_Status[PAGESIZE][2];	/* item status ie A(DD) C(hange) */
	short	NoItems;		/* number of Items on the page */
	short	Pageno;			/* Page number */
}	Page;

static	Page	*FirstPage,		/* Address of First Page */
		*CurPage,		/* Address of Current Page */
		*CurLast,		/* Address of Curr. record last page */
		*LastPage;		/* Address of Last Page of Memory
					   Allocated */

static	Emp_extra	emp_extra, pre_emp_extra;
static	Barg_unit	barg_unit;
static	Class		class;
static	Pay_per		pay_per;

static	short	LevelNo;

void	free() ;
char	*malloc() ;

Responsibility()
{
	int 	retval, err;

	if(Initialize() < 0)
		exit(-1);

	if(emp_rec.em_numb[0] != '\0') {
		flg_reset(EMPLOYEE);
		err = get_n_employee(&emp_rec,BROWSE,0,FORWARD,e_mesg);
		if(err < 0) {
			fomen(e_mesg);
			get();
			return(err);
		}
		err = UsrBargVal(BROWSE,emp_rec.em_numb,emp_rec.em_barg,1,e_mesg);
		if(err < 0){
			DispError((char *)&s_sth,e_mesg);
		}
		else {
			strcpy(emp_extra.ee_numb, emp_rec.em_numb);
			emp_extra.ee_type[0] = 'E';
			emp_extra.ee_class[0] = '\0';
			flg_reset(EMP_EXTRA);

			retval = BuildList();
#ifndef ORACLE
			seq_over(EMP_EXTRA);
#endif
			if(ERROR == retval)return(DBH_ERR) ;

			strcpy(s_sth.s_employee,emp_rec.em_numb);
			retval = ShowItems(CurPage);
		}
	}

	retval = Empresp(); 		/* maintenance processing */

	err = Close();			/* return to menu */
	if (err < 0) return(err);
	return(retval);
}

/*-------------------------------------------------------------------*/
/* Initialize PROFOM */

static
Initialize()
{

	if(InitScreens() < 0){
		fomcs();
		fomrt();		/* Initialize Screen */
		return(-1);
	}

	FirstPage = NULL;
	LastPage = NULL;

	return(NOERROR) ;
}	/* Initialize() */

/*--------------------------------------------------------------------------*/
/* Close nessary files and environment before exiting program               */

static
Close() 
{
	/* Free the linked list for the end */
	for( ;LastPage != FirstPage ; ) {
		LastPage = LastPage->PrevPage;
		free((char *)LastPage->NextPage);
		LastPage->NextPage = NULL;
	}
	if(FirstPage != NULL) {
		free((char *)FirstPage);
	}

	FirstPage = LastPage = NULL;

	/* Set terminal back to normal mode from PROFOM */
	fomcs();
	fomrt();

	close_dbh();	/* Close files */

	return(NOERROR);
}	/* CloseRtn() */
/*----------------------------------------------------------------*/
/* Initialize screen before going to process options */

static
InitScreens()
{
	int	err ;

	/* move screen name to Profom status structure */
	strcpy(sr.scrnam,NFM_PATH);
	strcat(sr.scrnam,SCR_NAME) ;

	strcpy(s_sth.s_pgname,"emp_resp");

	s_sth.s_rundate = get_date();	/* get Today's Date in YYYYMMDD format*/
	s_sth.s_field = HV_SHORT ;
	s_sth.s_mesg[0] = HV_CHAR ;
	s_sth.s_resp[0] = HV_CHAR ;
	s_sth.s_dummy[0] = ' ';

	/* Move High Values to data fields and Display the screen */
	err = ClearScreens() ;
	if(NOERROR != err) return(err) ;

	return(NOERROR) ;
}	/* InitScreens() */
/*-------------------------------------------------------------------*/
/* Get Option from user and call corresponding function */

static
Empresp()
{
	int err;

	for( ; ; ){

		/* Get the Fn: option from the user */
		if((err = ReadFn()) != NOERROR) return(err) ;

		err = ProcFn() ;	/* Process Function */

		if(QUIT == err)		return(NOERROR) ;    /* Exit */
		if(JUMP == err)		return(JUMP) ;
		if(NOACCESS == err)	fomen(e_mesg);	     /* security */
		if(PROFOM_ERR == err)	return(PROFOM_ERR);  /* PROFOM ERROR */
		if(DBH_ERR == err) {
			DispError((char *)&s_sth,e_mesg);
#ifdef ENGLISH
			sprintf(e_mesg,"%s %d Dberror: %d Errno: %d",
				"System Error... Iserror:",
				iserror, dberror, errno);
#else
			sprintf(e_mesg,"%s %d Dberror: %d Errno: %d",
				"Erreur du systeme... Iserror:",
				iserror, dberror, errno);
#endif
			DispError((char *)&s_sth,e_mesg);
			return(DBH_ERR); /* DBH ERROR */
		}
	}      /*   end of the for( ; ; )       */
}	/* Process() */
/*----------------------------------------------------------------*/
/* Display the Function (Fn:) options and get the option from the user */

static
ReadFn()
{
	/* Display Fn: options */
#ifdef ENGLISH
	fomer("C(hange), D(el), I(nq), F(orward), B(ack), N(ext), P(rev), S(creen), E(xit)");
#else
	fomer("C(hanger), I(nterroger), S(uivant), P(recedent), F(in)");
#endif
	/* Read Fn: field to get the option */
	sr.nextfld = FN_FLD ;
	fomrf( (char *)&s_sth );
	ret(err_chk(&sr));	/* Check for PROFOM error */

	return(NOERROR) ;
}	/* ReadFn() */
/*----------------------------------------------------------------*/
/* Process the user selected Fn: option */

static
ProcFn()
{
	int retval;

	switch (s_sth.s_fn[0]) {
	case CHANGE  :			/* CHANGE */
		CHKACC(retval,UPDATE,e_mesg);
		return( ChangeResp() ) ;
	case DELETE  :			/* DELETE */
		CHKACC(retval,UPDATE,e_mesg);
		return( DeleteResp() ) ;
	case INQUIRE  :			/* Inquire */
		CHKACC(retval,BROWSE,e_mesg);
		return( InquireResp() ) ;
	case NEXT_RECORD  :			/* Inquire */
		CHKACC(retval,BROWSE,e_mesg);
		return( NextResp(FORWARD) ) ;
	case PREV_RECORD  :			/* Inquire */
		CHKACC(retval,BROWSE,e_mesg);
		return( NextResp(BACKWARD) ) ;
	case NEXT_SCR  : 	/* Next Screen */
		Cur_Option += 1 ;	/* Set to Next Screen */
		return( JUMP ) ; 
	case PREV_SCR  : 	/* Next Screen */
		Cur_Option -= 1 ;	/* Set to Next Screen */
		return( JUMP ) ; 
	case SCREEN  : 	/* Next Screen */
		CHKACC(retval,BROWSE,e_mesg);
		return( Screen() ) ;

	case EXITOPT  :
		return(QUIT);

	default   : 
		return(NOERROR);
	}  /*   end of the switch statement */

	return(retval);
}	/* ProcFn() */
/*-----------------------------------------------------------------------*/
/* Change. Students Study halls and update the files if a day/semester   */
/* is changed to NO delete record.			  		 */
/*-----------------------------------------------------------------------*/
static
ChangeResp()
{
	int	err ;

	err = SelectRc() ;
	if(NOERROR != err) return(err);

	for( ; ; ) {
		err = ConfirmItems() ;
		if(err != YES) {
			roll_back(e_mesg);
			break;
		}

		err = ProcItemUpdates(UPDATE) ;
		if(err==NOERROR) break;
		if(err==LOCKED) {
			roll_back(e_mesg) ;
			continue;
		}
		if (err < 0) {
			roll_back(e_mesg);
			return(err) ;
		}
	}

	return(NOERROR) ;
}	/* Change() */
/*-----------------------------------------------------------------------*/
/* Delete. Student Study Hall Records.  */
/*-----------------------------------------------------------------------*/
static
DeleteResp()
{
	int	err ;

	err = SelectRc() ;
	if(NOERROR != err) return(err) ;
	
	for( ; ; ) {
		err = ConfirmItems() ;
		if(err != YES) {
			roll_back(e_mesg);
			break;
		}

		err = ProcItemUpdates(P_DEL) ;
		if(err==NOERROR) break;
		if(err==LOCKED) {
			roll_back(e_mesg) ;
			continue;
		}
		if (err < 0) {
			roll_back(e_mesg);
			return(err) ;
		}
	}

	return(NOERROR) ;
}	/* Delete() */
/*-----------------------------------------------------------------------*/
/* Show Student Student halls base on users input */
static
InquireResp()
{
	int	err ;

	err = SelectRc() ;
	if(NOERROR != err) return(err) ;

	err = ConfirmItems() ;
	
	return(NOERROR) ;
}	/* Inquire() */
/*----------------------------------------------------------*/
/* Show the next or previous Students Study halls */

static
NextResp(direction)
int	direction ;
{
	int err;

	if (flg_start(EMPLOYEE) != direction) {
		inc_str(emp_rec.em_numb, sizeof(emp_rec.em_numb)-1, 
			direction);
		flg_reset(EMPLOYEE);
	}

	for(;;) {
		err = get_n_employee(&emp_rec,BROWSE,0,direction,e_mesg);
		if(err == EFL) {
			fomer("No More Records...");
			get();
			err = NOERROR;	
		}
		if(err < 0) {
			fomen(e_mesg);
			get();
			return(err);
		}
		strcpy(s_sth.s_employee,emp_rec.em_numb);
		err = UsrBargVal(BROWSE,emp_rec.em_numb,emp_rec.em_barg,
			1,e_mesg);
		if(err < 0){
			continue;
		}
		else
			break;
	}
	strcpy(emp_extra.ee_numb,emp_rec.em_numb);
	emp_extra.ee_type[0] = 'E';
	emp_extra.ee_class[0] = '\0';

	flg_reset(EMP_EXTRA);

	err = get_n_emp_extra(&emp_extra,BROWSE,0,FORWARD,e_mesg);

	if(err < 0 && err != EFL) {
		DispError((char *)&s_sth,e_mesg);
		return(err);
	}

	strcpy(s_sth.s_name, emp_rec.em_last_name);
	strcat(s_sth.s_name, ", ");
	strcat(s_sth.s_name, emp_rec.em_first_name);
	strcat(s_sth.s_name, " ");
	strcat(s_sth.s_name, emp_rec.em_mid_name);

	ret( WriteFields((char *)&s_sth,KEY_START, KEY_END) ) ;

	/* Get area records i.e. Build list */
	strcpy(emp_extra.ee_numb,s_sth.s_employee);

	flg_reset(EMP_EXTRA);

	err = BuildList();
	if(err < 0 && err != EFL) {
		return(err);
	}

	err = ShowItems(CurPage);
	if(err < 0) {
		return(err);
	}

	return( err ) ;
}	/* Next() */
/*----------------------------------------------------------------------*/
/* Get the Student Study Hall key from user. In ADD mode disable dup buffers, */
/* other modes enable dup buffers and show the current key as a default key */
/*----------------------------------------------------------------------*/
static
ReadKey()
{
	int	i;
	char	employee[13];
	
	/* In Add mode turn off dup control for key fields.
	   Other modes reverse it */
	SetDupBuffers(KEY_START,KEY_END,0);

#ifdef ENGLISH
	strcpy(s_sth.s_mesg,"Press ESC-F to Go Back to Fn:");
#else
	strcpy(s_sth.s_mesg,"Appuyer sur ESC-F pour retourner a Fn:");
#endif
	DispMesgFld((char *)&s_sth);

	strcpy(employee,s_sth.s_employee);
	s_sth.s_employee[0] = LV_CHAR;

	i = ReadFields((char *)&s_sth,KEY_START, KEY_START,
		Validation, WindowHelp,1) ;
	if(PROFOM_ERR == i || DBH_ERR == i) return(i) ;
	if(RET_USER_ESC == i){
		strcpy(s_sth.s_employee,employee);
		ret( WriteFields((char *)&s_sth,KEY_START, KEY_END) ) ;

		s_sth.s_mesg[0] = HV_CHAR;
		DispMesgFld((char *)&s_sth);

		return(RET_USER_ESC) ;
	}

	return(NOERROR);
}	/*  ReadKey() */
/*------------------------------------------------------------*/
/* Read Item Details from the User */

static
AddItems()
{
	int	curr_item, i, err ;

	/* If the last node of po is Partial filled then Show Page */
	if(CurLast != NULL && CurLast->NoItems < PAGESIZE ) {
		ret( ShowItems(CurLast) ) ;
		i = CurLast->NoItems ;
		CurPage = CurLast ;
	}
	else {
		/* Calculate the page# */
		if(CurLast != NULL) {
			i = PAGESIZE ;
			CurPage = CurLast ;
		}
		else {
			s_sth.s_dummy[0] = ' ';
			s_sth.s_page = 1 ;
			ret( WriteFields((char *)&s_sth,PAGE_FLD, DUMMY_FLD) ) ;
			i = 0 ;
		}
	}

	i = 0;
	curr_item = 0;

	for( ; ; ) {
		if( PAGESIZE == i) {	/* Page Full */

			/* Move High Values to All items except first */
			for(i-- ; i > 0 ; i--)
				InitItem(i, HV_CHAR,HV_DOUBLE) ;

			/* Calculate the page# */
			s_sth.s_page = CurLast->Pageno + 1 ;
			s_sth.s_dummy[0] = ' ';

			ret( WriteFields((char *)&s_sth,PAGE_FLD, 
				(END_FLD - 200)) ) ;

			i = 0 ;
		}

		err = ReadItem(i,ADD) ;		/* Read Each Item Line */
		if(PROFOM_ERR == err || DBH_ERR == err) return(err) ;
		if(NOERROR != err) break ;	/* ESC-F */
		if(0 == i)	/* First Item in the Page */
			if((err = MakeFreshPage()) < 0) return(err) ;
		
		/* Copy the Item to List */
		scpy((char*)&(CurPage->Items[i]), (char*)&(s_sth.s_items[i]),
			sizeof(S_item)) ;

		CurPage->I_Status[i][0] = ADDITEMS;

		i++ ;

		CurPage->NoItems = i;
		curr_item +=1;

	}
	if(i == 0) 
		if((err=ShowItems(CurPage))<0) return(err) ;

	return(NOERROR) ;
}	/* AddItems() */

/*-----------------------------------------------------------------------*/
/* Prevents duplicate code from being entered				 */
static
CheckCode(curr_item)
int curr_item;
{
	int  a;
	int	i;
	Page	*temppage;

	/* check to see if item is already in list */
	if(CurLast != NULL) {
	   for(temppage=FirstPage; temppage!=NULL;temppage=temppage->NextPage) {
	      for(i =0; i< temppage->NoItems; i++) {
			if(temppage->Items[i].s_class_code[0] == NULL) {
				return(NOERROR);
			}
			if(strcmp(temppage->Items[i].s_class_code,
				s_sth.s_items[a].s_class_code) == 0) {
				return(-1);
			}
	      }
	      if(temppage == CurLast) break;
	   }
	}

	return(NOERROR);
}

/*-----------------------------------------------------------------------*/
/*	Get the next node in linked list to add invoice items. If the
*	(Cur. invc last page) = (Last Page in linked List) or no
*	nodes in list, allocate node and add to linked list
*/

static
MakeFreshPage()
{
	Page	*tempptr ;

	/* If, no node is allocated yet or Current invoice used all the nodes,
	   then allocate new node */

	if( LastPage == NULL || CurLast == LastPage ){
		tempptr= (Page *)malloc((unsigned)sizeof(Page)) ;

		if( tempptr == NULL ){
			DispError((char*)&s_sth,"Memory Allocation Error");
			return(ERROR);
		}
		tempptr->NextPage = NULL ;

		if( LastPage == NULL ){	/* No node is allocated Yet */
			tempptr->PrevPage = NULL ;
			tempptr->Pageno = 1 ;
			FirstPage = tempptr ;
		}
		else {				/* Not a first node in list */
			tempptr->Pageno = LastPage->Pageno + 1 ;
			LastPage->NextPage = tempptr ;
			tempptr->PrevPage = LastPage ;
		}
		LastPage = tempptr ;
	}

	if(CurLast == NULL)
		CurLast = FirstPage ;
	else
		CurLast = CurLast->NextPage ;

	CurLast->NoItems = 0 ;
	CurPage = CurLast ;

	return(NOERROR);
}	/* MakeFreshPage() */
/*----------------------------------------------------------*/
/* Get the key and show the record */
static
SelectRc()
{
	int	err ;

	err = ReadKey();
	if(err != NOERROR) return(err) ;

	/* Get area records i.e. Build list */
	strcpy(emp_extra.ee_numb,s_sth.s_employee);
	emp_extra.ee_type[0] = '\0';
	emp_extra.ee_class[0] = '\0';

	flg_reset(EMP_EXTRA);

	err = BuildList();
	if(err < 0 && err != EFL) {
		return(err);
	}

	err = ShowItems(CurPage);
	if(err < 0) {
		return(err);
	}

	return(NOERROR);
}	/* SelectRc() */
/*------------------------------------------------------------*/
static
BuildList()
{
	int retval;
	int i;
	CurLast = CurPage = NULL;
	i = 0;

	for( ; ; ) {
		retval = get_n_emp_extra(&emp_extra,BROWSE,0,FORWARD,e_mesg);
		if(retval < 0) {
			if(retval == EFL) break;
			DispError((char *)&s_sth,e_mesg);
			return(retval);
		}

		if(strcmp(emp_extra.ee_numb,s_sth.s_employee)!=0) { 
			break;
		}

		if(PAGESIZE == i) i = 0;
		if(i == 0) {
			if((retval = MakeFreshPage()) < 0) return(retval);
		}
		strcpy(CurPage->Items[i].s_class_code,emp_extra.ee_class);
		CurPage->Items[i].s_amount = emp_extra.ee_amount;
		strcpy(CurPage->Items[i].s_status,ACTIVE);
		CurPage->I_Status[i][0] = ' ';
		CurPage->NoItems++;
		i++;
	}
	seq_over(EMP_EXTRA);


	if(CurLast != NULL) {
		CurPage = FirstPage;
	}

	if(retval == EFL) return(retval);
	return(NOERROR);
}
/*------------------------------------------------------------*/
/* Show all the items on the current page 		      */
static
ShowItems(pageptr)
Page	*pageptr ;
{
	int	i ;

	if(pageptr != NULL) {
		/* Copy the items to screen */
		scpy((char*)s_sth.s_items, (char*)pageptr->Items,
			(pageptr->NoItems * sizeof(S_item)) );

		s_sth.s_dummy[0] = ' ';
		s_sth.s_page   = pageptr->Pageno ;

		i = pageptr->NoItems ;
	}
	else {
		s_sth.s_dummy[0] = HV_CHAR;
		s_sth.s_page = HV_SHORT ;
		i = 0 ;
	}

	/* Move High Values to remaining Items */
	for( ; i < PAGESIZE ; i++ )
		InitItem(i, HV_CHAR,HV_DOUBLE);

	WriteFields((char *)&s_sth, PAGE_FLD, (END_FLD - 200)) ;

	return(NOERROR) ;
}	/* ShowItems() */
/*-----------------------------------------------------------------------*/ 
/* Process all the items in the link list and write any changes to the   */
/* daily attendance file.						 */
/*-----------------------------------------------------------------------*/ 
static
ProcItemUpdates(mode)
int	mode;
{
	Page	*temppage;
	int	i;
	int	retval;
	int	write_mode;

	LevelNo = 0;
	if(CurLast != NULL) {
	   for(temppage=FirstPage; temppage!=NULL;temppage=temppage->NextPage) {
	      for(i =0; i< temppage->NoItems; i++) {
		 LevelNo++;
		 retval = GetMode(temppage,i,mode,&write_mode);
		 if(write_mode == NOOP) {
			continue;
		 }
		 retval = WriteRecords(temppage,i,write_mode);
  		 if(retval < 0) {
			if(retval == LOCKED) return(LOCKED);
		   	break;
		 }
	      }
	      if(temppage == CurLast) break;
	   }
	}
	return(NOERROR);
}
/*-----------------------------------------------------------------------*/ 
static
GetMode(temppage,item_no,mode,write_mode)
Page	*temppage;
int	item_no;
int	mode;
int	*write_mode;
{
	if(mode == ADD) {
		if(strcmp(temppage->Items[item_no].s_status,INACTIVE)==0) {
			LevelNo--; /* no level to write */
			*write_mode = NOOP;
		}
		else {
			*write_mode = ADD;
		}
	}
	else if(mode == UPDATE) {
		if(strcmp(temppage->Items[item_no].s_status,INACTIVE)==0) {
			LevelNo--; /* delete record a reseqence levels */
			*write_mode = P_DEL;
		}
		else if(temppage->I_Status[item_no][0] == ADDITEMS) {
			*write_mode = ADD;
		}
		else if(temppage->I_Status[item_no][0] == CHANGE) {
			*write_mode = UPDATE;
		}
		else if(temppage->I_Status[item_no][0] == ' ') {
			*write_mode = NOOP;
		}
	}
	else if(mode == P_DEL) {
		*write_mode = P_DEL;
	}

	return(NOERROR);
}
/*-----------------------------------------------------------------------*/ 
/* Write the Area record to the file.			 		 */ 
/*-----------------------------------------------------------------------*/ 
static
WriteRecords(temppage,item_no,mode)
Page	*temppage;
int	item_no;
int	mode;
{
	int	retval;

	strcpy(emp_extra.ee_numb,s_sth.s_employee) ;
	strcpy(emp_extra.ee_class,temppage->Items[item_no].s_class_code) ;
	emp_extra.ee_amount = temppage->Items[item_no].s_amount ;
	emp_extra.ee_type[0] = 'E';
	emp_extra.ee_earn[0] = '\0';
	emp_extra.ee_amt_flg[0] = '\0';
	emp_extra.ee_target = 0;
	emp_extra.ee_cc = 0;
	if(mode != ADD) {
		scpy((char *)&pre_emp_extra,(char *)&emp_extra,
			sizeof(pre_emp_extra));

		retval = get_emp_extra(&emp_extra,UPDATE,0,e_mesg) ;
		if(retval < 0) {
			DispError((char *)&s_sth,e_mesg);
			roll_back(e_mesg);
			return(retval);
		}

	}

	retval = put_emp_extra(&emp_extra,mode,e_mesg) ;
	if(retval < 0) {
		DispError((char *)&s_sth,e_mesg);
		roll_back(e_mesg);
		return(retval);
	}

	if(mode != ADD) {
		retval = rite_audit((char*)&s_sth,EMP_EXTRA,mode,(char*)&emp_extra,
			(char*)&pre_emp_extra,e_mesg);
		if(retval==LOCKED) {
			DispError((char *)&s_sth,e_mesg);
			roll_back(e_mesg) ;
			return(LOCKED) ;
		}
		if(retval < 0 ){
			DispError((char *)&s_sth,"ERROR: Saving Records"); 
			DispError((char *)&s_sth,e_mesg);
			roll_back(e_mesg);
			return(retval);
		}
	}

	retval = commit(e_mesg) ;
	if(retval < 0) {
		DispError((char *)&s_sth,"ERROR: Saving Records"); 
		DispError((char *)&s_sth,e_mesg);
		roll_back(e_mesg);
		return(retval);
	}
	return(NOERROR);
}
/*------------------------------------------------------------*/
/* Read details of given item# */
/*------------------------------------------------------------*/
static
ReadItem(item_no,mode)
int	item_no ;
int	mode ;
{
	int	i;
	int	st_fld ;
	int	end_fld ;

#ifdef ENGLISH
	strcpy(s_sth.s_mesg,"Press ESC-F to Terminate");
#else
	strcpy(s_sth.s_mesg,"Appuyer sur ESC-F pour terminer");
#endif
	DispMesgFld((char *)&s_sth);

	st_fld  = ITEM_ST_FLD + (STEP * item_no);
	end_fld  = ITEM_ST_FLD + (STEP * item_no) + STATUS_FLD;
	s_sth.s_items[item_no].s_class_code[0] = LV_CHAR;
	strcpy(s_sth.s_items[item_no].s_status,ACTIVE);

	SetDupBuffers(CODE_FLD+(STEP*item_no), CODE_FLD+(STEP*item_no),1);

	i = ReadFields((char *)&s_sth,st_fld,end_fld,Validation,WindowHelp,1) ;
	if(PROFOM_ERR == i || DBH_ERR == i) return(i) ;
	if(RET_USER_ESC == i) {
		if(mode == ADD) {
			InitItem(item_no,HV_CHAR,HV_DOUBLE);
			WriteFields((char *)&s_sth,st_fld,end_fld);
			return(RET_USER_ESC);
		}
		/* When user gives ESC-F while changing fields, assumption is
		* he completed his changes, and remaining fields are same as
		* old. But, at this point STH will be having low values in the 
		* remaining fields. So move the old values form the linked list.
		*/

		i = CopyBack((char *)&s_sth,(char *)&image,sr.curfld, END_FLD);
		if(i == PROFOM_ERR) return(i);

		return(RET_USER_ESC) ;
	}

	return(NOERROR) ;
}	/* ReadItem() */
/*----------------------------------------------------------------*/
/* Set Duplication buffers for fields 				  */
static
SetDupBuffers( firstfld, lastfld, value )
int	firstfld, lastfld;	/* field numbers range */
int	value;			/* ENABLE or DISABLE */
{
	int i ;

	for( i=firstfld; i<=lastfld; i+=100 )
		fomca1( i, 19, value);
	if( value==0 )
		return(0);
	sr.nextfld = firstfld;
	sr.endfld = lastfld;
	fomud( (char *)&s_sth );
	ret( err_chk(&sr) );

	return( 0 );
}
/*----------------------------------------------------------------*/
/* Validation function() for Key and Header fields when PROFOM returns
  RET_VAL_CHK */

static
Validation()
{
	int	mode,retval;
	int	fld_no;
	int	item_no;

	if(s_sth.s_fn[0] == CHANGE)	mode = UPDATE;
	if(s_sth.s_fn[0] == INQUIRE)	mode = BROWSE;

	if(sr.curfld >= ITEM_ST_FLD) {	
		item_no = (sr.curfld - ITEM_ST_FLD) / STEP;
		fld_no = sr.curfld - (item_no * STEP);
	}
	else {
		fld_no = sr.curfld;
	}
	switch(fld_no){
	case KEY_START:
		Right_Justify_Numeric(s_sth.s_employee,sizeof(emp_rec.em_numb)-1);
		strcpy(emp_rec.em_numb,s_sth.s_employee);
		retval = get_employee(&emp_rec,BROWSE,0,e_mesg);
		if(retval < 0) {
			fomen(e_mesg);
			get();
			return(retval);
		}

		retval = UsrBargVal(mode,emp_rec.em_numb,emp_rec.em_barg,1,e_mesg);
		if(retval < 0){
			DispError((char *)&s_sth,e_mesg);
			s_sth.s_employee[0] = LV_CHAR;
			return(ERROR);
		}
		strcpy(emp_extra.ee_numb,s_sth.s_employee);
		emp_extra.ee_type[0] = 'E';
		emp_extra.ee_class[0] = '\0';
		flg_reset(EMP_EXTRA);
		retval = get_n_emp_extra(&emp_extra,BROWSE,0,FORWARD,e_mesg);

		if(retval == EFL || strcmp(emp_extra.ee_numb,
					s_sth.s_employee) != 0) {
			fomer("Employee Number Does not Exist");
			s_sth.s_employee[0] = LV_CHAR;
			return(ERROR);
		}
		strcpy(s_sth.s_name, emp_rec.em_last_name);
		strcat(s_sth.s_name, ", ");
		strcat(s_sth.s_name, emp_rec.em_first_name);
		strcat(s_sth.s_name, " ");
		strcat(s_sth.s_name, emp_rec.em_mid_name);
		break;

	case	CODE_FLD:
		strcpy(class.c_code,s_sth.s_items[item_no].s_class_code);
		class.c_date = get_date();

		flg_reset(CLASSIFICATION);

		retval = get_n_class(&class,BROWSE,0,BACKWARD,e_mesg);
		if(retval == EFL || 
		strcmp(class.c_code,s_sth.s_items[item_no].s_class_code)!=0){
			fomer("Classification Code Does not Exist");
			s_sth.s_items[item_no].s_class_code[0] = LV_CHAR;
			return(ERROR);
		}
		/* Check if code already entered */
		if(item_no != 0) {
			retval = CheckCode(item_no);
			if(retval < 0){
				fomer("Classification Code Already Listed, Please Re-Enter");
				s_sth.s_items[item_no].s_class_code[0]=LV_CHAR;
				return(ERROR);
			}
		}
		
		strcpy(barg_unit.b_code,emp_rec.em_barg);
		barg_unit.b_date = get_date();
		flg_reset(BARG);

		retval = get_n_barg(&barg_unit,BROWSE,0,BACKWARD,e_mesg);
		if(retval == EFL ||
			strcmp(barg_unit.b_code, emp_rec.em_barg) != 0){
			sprintf(e_mesg,"Bargaining Unit does no exist: %s",
				emp_rec.em_barg);
  			DispError((char *)&s_sth,e_mesg);
			return(NOERROR);
		}
		if(retval < 0){
  			DispError((char *)&s_sth,e_mesg);
  			return(ERROR);
		}
		seq_over(BARG);

		strcpy(pay_per.pp_code,barg_unit.b_pp_code);
		pay_per.pp_year = 0;
		flg_reset(PAY_PERIOD);

		retval = get_n_pay_per(&pay_per,BROWSE,0,FORWARD,e_mesg);
		if(retval < 0){
		   DispError((char *)&s_sth,e_mesg);
		   return(retval);
		}
		if(strcmp(pay_per.pp_code,barg_unit.b_pp_code)!=0){
#ifdef ENGLISH
		   sprintf(e_mesg,"Pay Period Code %s Not on File",
			    	barg_unit.b_pp_code);
#else
		   sprintf(e_mesg,"Pay Period Code %s Not on File",
	    			barg_unit.b_pp_code);
#endif
			    DispError((char *)&s_sth,e_mesg);
			    return(ERROR);
		}
		seq_over(PAY_PERIOD);

		s_sth.s_items[item_no].s_amount = class.c_yrly_inc /
						  pay_per.pp_numb;


		break;

	default:
#ifdef ENGLISH
		sprintf(e_mesg,"No Validity Check for Field#  %d",sr.curfld);
		
#else
		sprintf(e_mesg,"Pas de controle de validite pour le Champ#  %d",sr.curfld);
#endif
		fomen(e_mesg);
		get();
		return(ERROR) ;
	}	/* Switch sr.curfld */

	return(NOERROR) ;
}	/* Validation() */
/*----------------------------------------------------------------*/
/* Show Help Windows, if applicable, when user gives ESC-H in key
   and header fields */

static
WindowHelp()
{
	int	retval ;
	int	fld_no;
	int	item_no;
	long	tmp_date;

	if(sr.curfld >= ITEM_ST_FLD) {	
		item_no = (sr.curfld - ITEM_ST_FLD) / STEP;
		fld_no = sr.curfld - (item_no * STEP);
	}
	else {
		fld_no = sr.curfld;
	}

	switch(fld_no){

	case KEY_START:
		retval = emp_hlp(s_sth.s_employee,7,13);
		if(retval == DBH_ERR) return(retval);
		if(retval >= 0) redraw();
		if(retval == 0) return(ERROR);
		if(retval < 0) return(ERROR);

		strcpy(emp_rec.em_numb,s_sth.s_employee);
		retval = get_employee(&emp_rec,BROWSE,0,e_mesg);
		if(retval < 0) {
			fomen(e_mesg);
			get();
			return(retval);
		}

		strcpy(s_sth.s_name, emp_rec.em_last_name);
		strcat(s_sth.s_name, ", ");
		strcat(s_sth.s_name, emp_rec.em_first_name);
		strcat(s_sth.s_name, " ");
		strcat(s_sth.s_name, emp_rec.em_mid_name);

		break;

	case	CODE_FLD:
		retval = class_hlp(s_sth.s_items[item_no].s_class_code,
			&tmp_date,7,13);
		if(retval == DBH_ERR) return(retval);
		if(retval >= 0) redraw();
		if(retval == 0) return(ERROR);
		if(retval < 0) return(ERROR);
		/* Check  if code already entered */
		if(item_no != 0) {
			retval = CheckCode(item_no);
			if(retval < 0){
				fomer("Classification Code Already Listed, Please Re-Enter");
				s_sth.s_items[item_no].s_class_code[0]=LV_CHAR;
				return(ERROR);
			}
		}

		strcpy(barg_unit.b_code,emp_rec.em_barg);
		barg_unit.b_date = get_date();
		flg_reset(BARG);

		retval = get_n_barg(&barg_unit,BROWSE,0,BACKWARD,e_mesg);
		if(retval == EFL ||
			strcmp(barg_unit.b_code, emp_rec.em_barg) != 0){
			sprintf(e_mesg,"Bargaining Unit does no exist: %s",
				emp_rec.em_barg);
  			DispError((char *)&s_sth,e_mesg);
			return(NOERROR);
		}
		if(retval < 0){
  			DispError((char *)&s_sth,e_mesg);
  			return(ERROR);
		}
		seq_over(BARG);

		strcpy(pay_per.pp_code,barg_unit.b_pp_code);
		pay_per.pp_year = 0;
		flg_reset(PAY_PERIOD);

		retval = get_n_pay_per(&pay_per,BROWSE,0,FORWARD,e_mesg);
		if(retval < 0){
		  DispError((char *)&s_sth,e_mesg);
		  return(retval);
		}
		if(strcmp(pay_per.pp_code,barg_unit.b_pp_code)!=0){
#ifdef ENGLISH
		    sprintf(e_mesg,"Pay Period Code %s Not on File",
			    	barg_unit.b_pp_code);
#else
		    sprintf(e_mesg,"Pay Period Code %s Not on File",
	    			barg_unit.b_pp_code);
#endif
		    DispError((char *)&s_sth,e_mesg);
		    return(ERROR);
		}
		seq_over(PAY_PERIOD);

		s_sth.s_items[item_no].s_amount = class.c_yrly_inc /
						  pay_per.pp_numb;

		break;


	default :
		fomer("No Help Window for This Field");
	}	/* Switch sr.curfld */

	return(NOERROR) ;
}	/* HdrAndKeyWindowHelp() */
/*-----------------------------------------------------------------------*/
/* Take the confirmation from user for the items part of the screen      */
/*-----------------------------------------------------------------------*/
static
ConfirmItems()
{
	int	err ;

	/* Options:
	     YSLNPC
	*/

	for( ; ; ) {
	    if(s_sth.s_fn[0] == DELETE) {
#ifdef ENGLISH
			err = GetOption((char *)&s_sth,"Y(es), C(ancel)","YC");
#else
			err = GetOption((char *)&s_sth,"O(ui), A(nnul)","OA");
#endif 
	    }
	    else if(s_sth.s_fn[0] != INQUIRE) {
#ifdef ENGLISH
			err = GetOption((char *)&s_sth,
		"Y(es), A(dd), D(el), R(eactivate), N(ext), P(rev), C(ancel)"
		,"YADRNPC");
#else
			err = GetOption((char *)&s_sth,
		"O(ui), A(dd), D(el), R(eactivate), S(uiv), P(rec), A(nnul)"
		,"OSLA");
#endif
	    }
	    else {
#ifdef ENGLISH
			err = GetOption((char *)&s_sth,
		"Y(es), N(ext), P(rev)","YNP");
#else
			err = GetOption((char *)&s_sth,
		"O(ui), S(uiv), P(rec)" ,"OSP");
#endif
	    }
	    switch(err) {
	    case  YES  :
		return(YES);
	    case  ADDITEMS:
		err = AddItems();
		break;
	    case  SCREENEDIT:
		err = ScreenEdit();
		break;
	    case  LINEEDIT  :
		err = ChangeFields();
		break ;
	    case  DELITEM:
	    case  REACTITEM:
		err = ChangeStatus(err);
		break;
	    case  NEXT:
		if(CurPage == CurLast || CurLast == NULL) {
#ifdef ENGLISH
			fomer("No More Pages....");
#else
			fomer("Plus de pages....");
#endif
			continue;
		}
		CurPage = CurPage->NextPage ;
		err = ShowItems(CurPage);
		break;
	    case  PREV:
		if(CurLast == NULL || CurPage == FirstPage) {
#ifdef ENGLISH
			fomer("No More Pages....");
#else
			fomer("Plus de pages....");
#endif
			continue;
		}
		CurPage = CurPage->PrevPage ;
		err = ShowItems(CurPage);
		break;
	    case  CANCEL :
#ifdef ENGLISH
		err = GetOption((char *)&s_sth,
				"Confirm the Cancel (Y/N)?", "YN") ;
#else
		err = GetOption((char *)&s_sth,
				"Confirmer l'annulation (O/N)?", "ON") ;
#endif
		if(err == YES) return(CANCEL) ;
		break ;
	    }	/* switch err */

	    if(err == PROFOM_ERR) return(err) ;
	    if(err == DBH_ERR) return(err) ;
	}	/* for(; ; ) */
}	/* ConfirmItems() */
/*---------------------------------------------------------------------*/
/* Change screen.  Allows editing of the students on the screen        */
/*---------------------------------------------------------------------*/
static
ScreenEdit()
{
     	int i;
	int retval;

	/* make copy of screen incase user presses ESC-F */
	scpy((char *)&image,(char *)&s_sth,sizeof(s_sth));

#ifdef ENGLISH
	strcpy(s_sth.s_mesg,"Press ESC-F to Terminate");
#else
	strcpy(s_sth.s_mesg,"Appuyer sur ESC-F pour terminer");
#endif
	DispMesgFld((char *)&s_sth);

	if(SetDupBuffers(ITEM_ST_FLD, END_FLD - 200,1)<0) return(PROFOM_ERR);

	for(i=0;i<CurPage->NoItems;i++) {
		if(strcmp(CurPage->Items[i].s_status,INACTIVE) ==0){
			continue;
		}
		retval = ReadItem(i,UPDATE);
		if(retval != NOERROR && retval != RET_USER_ESC) {
			return(retval);
		}

		if(retval == RET_USER_ESC) 
			return(retval);

		scpy((char*)&(CurPage->Items[i]), 
		     (char*)&(s_sth.s_items[i]),sizeof(S_item)) ;
		if(s_sth.s_fn[0] == CHANGE) {
			CurPage->I_Status[i][0] = CHANGE;
		}
	}

     	s_sth.s_mesg[0] = HV_CHAR ;
     	DispMesgFld((char *)&s_sth);

	if(SetDupBuffers(ITEM_ST_FLD, END_FLD-200,0)<0) return(PROFOM_ERR);

	return(NOERROR);
}	/* ScreenEdit() */
/*-----------------------------------------------------------------------*/
/*                                                                       */
/* Changing fields. Accept fld of the student to be changed and read     */
/* that fld 		 */
static
ChangeFields()
{
	int retval;

	/* make copy screen every time field changed in case user */
	/* presses ESC-F */
	scpy((char*)&image,(char*)&s_sth, sizeof(s_sth));

	SetDupBuffers(ITEM_ST_FLD, END_FLD - 200, 2);

	/* Get The Field to Be Modified */
#ifdef	ENGLISH
	strcpy(s_sth.s_mesg,"Enter RETURN to Terminate Edit");
#else
	strcpy(s_sth.s_mesg,"Appuyer sur RETURN pour terminer l'ajustement");
#endif
	DispMesgFld((char *)&s_sth); ;
        
     	for (; ;) {
		s_sth.s_field = LV_SHORT;
		retval = ReadFields((char *)&s_sth,CHG_FLD,CHG_FLD,
			(int (*)())NULL,(int (*)())NULL, 1);

		if (retval < 0) return(-1);
		if (retval == RET_USER_ESC) break;	/* User enter ESC-F */

       		if (s_sth.s_field == 0 ) break;  /* Finished changing fields */

		if(strcmp(CurPage->Items[s_sth.s_field-1].s_status,INACTIVE)==0){
			fomer("Item Has a Deleted Status Cannot Edit");
			continue;
		}
		retval = ReadItem(s_sth.s_field - 1,UPDATE);
		if(retval != NOERROR && retval != RET_USER_ESC) {
			return(retval);
		}

		if(retval == RET_USER_ESC)
			continue;

		/* make copy screen every time field changed in case user */
		/* presses ESC-F */
		scpy((char*)&image,(char*)&s_sth, sizeof(s_sth));

		scpy((char*)&(CurPage->Items[s_sth.s_field -1]), 
		     (char*)&(s_sth.s_items[s_sth.s_field -1]),sizeof(S_item)) ;

		if(s_sth.s_fn[0] == CHANGE) {
			CurPage->I_Status[s_sth.s_field-1][0] = CHANGE;
		}
	}

     	s_sth.s_field = HV_SHORT ;
	if ( WriteFields((char *)&s_sth,CHG_FLD, CHG_FLD) < 0 ) return(-1);

     	s_sth.s_mesg[0] = HV_CHAR ;
     	DispMesgFld((char *)&s_sth);

	if(SetDupBuffers(ITEM_ST_FLD, END_FLD - 200, 0)<0) return(PROFOM_ERR);

	return(NOERROR);
}	/* ChangeFields() */
/*------------------------------------------------------------------------*/
static
ChangeStatus(status)
int	status;
{
	int	retval;
	int	st_fld, end_fld;

	/* Get The Field to Be Modified */
#ifdef	ENGLISH
	strcpy(s_sth.s_mesg,"Enter RETURN to Terminate Edit");
#else
	strcpy(s_sth.s_mesg,"Appuyer sur RETURN pour terminer l'ajustement");
#endif
	DispMesgFld((char *)&s_sth); ;
        
     	for (; ;) {
		s_sth.s_field = LV_SHORT;
		retval = ReadFields((char *)&s_sth,CHG_FLD,CHG_FLD,
			(int (*)())NULL,(int (*)())NULL, 1);

		if (retval < 0) return(-1);
		if (retval == RET_USER_ESC) break;	/* User enter ESC-F */

       		if (s_sth.s_field == 0 ) break;  /* Finished changing fields */

	
		if(s_sth.s_items[s_sth.s_field -1].s_class_code[0] != HV_CHAR) {
			st_fld=ITEM_ST_FLD+(STEP*(s_sth.s_field-1))+STATUS_FLD;
			end_fld=ITEM_ST_FLD+(STEP*(s_sth.s_field-1))+STATUS_FLD;

			if(status == DELITEM) {
				if(strcmp(s_sth.s_items[s_sth.s_field-1].
			    	s_status,INACTIVE)==0) {
					fomer("Item is Already Deleted");
				}
				else {
					strcpy(s_sth.s_items[s_sth.s_field-1].
						s_status,INACTIVE);
				}
			}
			else {
				if(strcmp(s_sth.s_items[s_sth.s_field-1].
				s_status,ACTIVE)==0) {
					fomer("Item is Already Active");
				}
				else {
					strcpy(s_sth.s_items[s_sth.s_field-1].
						s_status,ACTIVE);
				}
			}
			/* Update Linked List */
			scpy((char*)&(CurPage->Items[s_sth.s_field -1]), 
			     (char*)&(s_sth.s_items[s_sth.s_field-1]),
			     sizeof(S_item)) ;
		
			ret(WriteFields((char *)&s_sth,st_fld,end_fld));
		}
	}
     	s_sth.s_field = HV_SHORT ;
	if ( WriteFields((char *)&s_sth,CHG_FLD, CHG_FLD) < 0 ) return(-1);

	return(NOERROR);
}
/*------------------------------------------------------------------------*/
/* Move High values to all data fields and clear the screen */

static
ClearScreens()
{
	int	i;

	/* Move High Values to Hedaer part */
	s_sth.s_page = HV_SHORT;
	s_sth.s_dummy[0] = HV_CHAR;
	
	/* Move High Values to All items */
	for(i = 0 ; i < PAGESIZE ; i++)
		InitItem(i,HV_CHAR,HV_DOUBLE);

	ret( WriteFields((char *)&s_sth,ITEM_ST_FLD, (END_FLD - 200)) );

	return(NOERROR);
}	/* ClearScreens() */
/*-------------------------------------------------------------------------*/
/* Initialize Given screen item with either Low values or High values */

static
InitItem(item_no, t_char,t_double)
int	item_no ;
char	t_char ;
double	t_double ;
{
	s_sth.s_items[item_no].s_class_code[0] = t_char ;
	s_sth.s_items[item_no].s_amount = t_double ;
	s_sth.s_items[item_no].s_status[0] = t_char ;

	return(NOERROR) ;
}	/* Inititem() */
/*-----------------------------------------------------------------------*/
/*                                                                       */
static
Screen()
{
	int	retval;

	s_sth.s_field = LV_SHORT;
	retval = ReadFields((char *)&s_sth,CHG_FLD,CHG_FLD,
		(int (*)())NULL,(int (*)())NULL, 1);

	if (retval < 0) return(-1);
	if (retval == RET_USER_ESC) return(NOERROR);	/* User enter ESC-F */

       	if (s_sth.s_field == 0 ) return(NOERROR); /* Finished changing fields */

	if (s_sth.s_field > MAX_SCREEN) {
		fomen("Invalid Field Number");
		get();
		s_sth.s_field = LV_SHORT;
		return(NOERROR);
	}

	switch (s_sth.s_field) {
	case SCR_1  :		/* SCR - 1  'DEMOGRAPHIC' */
	case SCR_2  :		/* SCR - 2  'EMPLOYMENT' */
	case SCR_4  :		/* SCR - 4  'EARNINGS' */
	case SCR_5  :		/* SCR - 5  'MISCELLANIOUS' */
	case SCR_6  :		/* SCR - 6  'BENEFIT' */
	case SCR_7  :		/* SCR - 7  'DEDUCTION' */
	case SCR_8  :		/* SCR - 8  'CSB/LOAN' */
	case SCR_9  :		/* SCR - 9  'GARNISHMENT' */
	case SCR_10 :		/* SCR - 10 'CHEQUE LOCATION' */
	case SCR_11 :		/* SCR - 11 'ATTENDANCE' */
	case SCR_12 :		/* SCR - 12 'SENIORITY' */
	case SCR_13 :		/* SCR - 13 'TEACHER QUALIFICATION' */
	case SCR_14 :		/* SCR - 14 'TEACHER ASSIGNMENT' */
	case SCR_15 :		/* SCR - 15 'COMPETITION' */
	case SCR_16 :		/* SCR - 16 'STATUS' */
		Cur_Option = s_sth.s_field ;
		return( JUMP ) ;
	default   : 
		return(NOERROR);
	}  /*   end of the switch statement */
}
/*-------------------- E n d   O f   P r o g r a m ---------------------*/
