/******************************************************************************
		Sourcename    : streputl.c
		System        : Budgetary Financial system.
		Module        : Inventory reports
		Created on    : 89-09-14
		Created  By   : K HARISH.
		Cobol sources : 

HISTORY:
 Date           Programmer     Description of modification
____/__/__      __________     ___________________________

Calls for the user:	( Check for the value returned: -1 on error )

int	AddMenuItem( char *name, int (* fnptr)() );
int	Initialize( char *terminalname , char *heading );
int	Process();
int	GetCostcenRange( short *, short * );
int	GetItemidRange( long *, long * );
int	GetFatypeRange( char *, char * );
int	GetDeptnoRange( char *, char * );
int	GetDateRange( long *, long * );
int	DisplayMessage( char * );
int	GetResponse( char * );
int	HideMessage();
int	GetOutputon( char * );
int	GetFilename( char * );
int	GetPrinter( short * );
int	GetNbrCopies( short * );
int	Confirm();		returns 1 for Yes, and 0 for anyother input

The programmer should make calls for appending menuitems in the following order.
		AddMenuItem( menuname, functionpointer );( max. 9 options )
		Initialize( screenheading );
		Process();	 for menu item selection
		{	Any "Get...." calls }
		Confirm();	It clears the screen and resets terminal
A maximum of 9 menuitems can be added, excluding one for Quitting the screen
which is automatically appended by the system.

For all the calls starting with "Get", user can pass any default values by 
initialising the corresponding variables before passing their address(es)
as parameters. The program doesnot do any validation except that it disallows
user's entry of end value ( range limit ) if it is smaller than starting value.

The last call should be "Confirm()",  which clears the profom screen and resets
the terminal characteristics

******************************************************************************/
#include <stdio.h>

#include <bfs_defs.h>
#include <cfomstrc.h>

#define SCREEN_NAME	"farep"
#define EXIT		12
#define PATH_FILE_SIZE	50
#define STARTLINENUM	18
#define LOW 		-1
#define HIGH 		 1
#define HL_CHAR(VAL)	VAL==HIGH ? HV_CHAR : LV_CHAR
#define ESC_F		sr.retcode==RET_USER_ESC && \
			(sr.escchar[0]=='F'||sr.escchar[0]=='f')
#define	OPTIONLEN	36
#define MAXOPTIONS	10
#define MAXQUERYLINES	5	
#define	COSTCEN		0
#define	ITEMID		1
#define	FA_TYPE		2
#define	DEPTNO		3
#define DATE		4

#ifdef ENGLISH
#define PRINTER 	'P'
#define DISPLAY		'D'
#define FILE_IO		'F'
#define YES		'Y'
#else
#define PRINTER		'I'
#define DISPLAY		'A'
#define FILE_IO		'D'
#define YES		'O'
#endif

/* glrep.sth - header for C structure generated by PROFOM EDITOR */

static struct	s_struct	{
	char	s_progname[12];	/* 100 program name */
	char	s_scrhdg[16];	/* 200 */
	long	s_rundt;	/* 300 DATE YYYYFMMFDD */
	char	s_item[MAXOPTIONS][OPTIONLEN];	/* 400 - 1300 options */
	short	s_option;	/* 1400 user's input */
	char	s_hypline[2];	/* 1500 mask for seperator line */
	char	s_outputon[2];	/* 1600 report output on D / F / P */
	char	s_filename[16];	/* 1700 name of file if option is F */
	short	s_printer;	/* 1800 printer# if option is P */
	short	s_nbrcopies;	/* 1900 page length in no of lines */
	short	s_costcen1;	/* 2000 starting cost center */
	short	s_costcen2;	/* 2100 ending cost center */
	long	s_itemid1;      /* 2200 starting item id  */
	long	s_itemid2;      /* 2300 ending item id  */
	char	s_fatype1[5];	/* 2400 starting fa type */
	char	s_fatype2[5];	/* 2500 ending fa type */
	char	s_deptno1[5];	/* 2600 staring dept no. */
	char	s_deptno2[5];	/* 2700 ending dept no. */
	long 	s_date1;	/* 2800 starting date */
	long	s_date2;	/* 2900 ending date */
	char	s_mesg[77];	/* 3000 message field */
	char	s_resp[2];	/* 3100 response field */
}	s_rec;

typedef struct{
	char	name[OPTIONLEN];
	int	(* fnptr)();
	int	mainflno;
}Menu;

struct stat_rec 	sr;		/* profom status record */

static int		line[MAXQUERYLINES];/* for positioning key queries */
static short		call_no;
static short		totaloptions;
static int retval;	/* Global variable to store function values */
static Menu	menu[MAXOPTIONS];
static	int	initialised ;
extern e_mesg[80];	/* used to store error messages */

Initialize( terminal,heading )	/* initialize profom and screen */
char *terminal;
char *heading;	
{
	if( (retval=InitProfom(terminal))<0 ){	/* initialize profom */
		fomcs();
		fomrt();
		return(retval);
	}
	if( (retval=InitScreen(heading))<0 ){		/* initialize screen */
		fomcs();
		fomrt();
		return(retval);
	}
	initialised = 1 ;
	return(0);
}	
static
InitProfom(terminal)	/* initialize profom */
char *terminal;
{
	if ( initialised )
		return(0) ;
	STRCPY( sr.termnm, terminal );
	fomin( &sr );		/* initialize the screen */
	ret( err_chk(&sr) );	/* if profom error return */

	return(0);
}
static
InitScreen(heading)		/* initialize the screen */
char 	*heading;
{
	/* initialize the profom screen variables */
	STRCPY( sr.scrnam, NFM_PATH );
	strcat( sr.scrnam, SCREEN_NAME );

	/* initialize the fields of the profom screen */
	if( initialised==0 ){
		if( FillScrHdg(heading)<0 ) 		return(-1);
		if( FillMenu()<0 ) 			return(-1);
		if( FillOption(HIGH)<0 )		return(-1);
		if( FillSeperatorLine(LOW)<0 ) 		return(-1);
	}

	/* Move Highs to inquiry area and write the entire screen */
	if( (retval=ClearInquiryArea())<0 )	return(retval);

	fomcf( 1,1 ) ;		/* Enable snap screen */
	return(0);
}

/* Fill the screen heading fields, the program name and the date */
static
FillScrHdg(heading)
char *heading;
{
	STRCPY( s_rec.s_progname, PROG_NAME );
	STRCPY( s_rec.s_scrhdg, heading );
	s_rec.s_rundt = get_date();
	return(0);
}

/* Add a menu item to the array of report menu items */
AddMenuItem( menuname, fnptr, mainflno )
char	*menuname;
int	(* fnptr)();
int	mainflno;
{
	if( totaloptions==0 ){ /* no options added to array yet */
#ifdef ENGLISH
		STRCPY( menu[totaloptions].name, "RETURN TO PREVIOUS MENU" );
#else
		STRCPY( menu[totaloptions].name, "RETOURNER AU MENU PRECEDENT");
#endif
		menu[totaloptions].fnptr = (int (*)())NULL;
		totaloptions++;
	}

	if( totaloptions>=MAXOPTIONS )	/* array can't accomodate any more */ 
		return(-1);
	if( menuname==NULL )		/* menu name can't be null */
		return(-1);
	STRCPY( menu[totaloptions].name, menuname );
	menu[totaloptions].fnptr = fnptr;	/* copy function pointer */
	menu[totaloptions].mainflno = mainflno;  /* copy main file used */

	totaloptions++;

	return(totaloptions-1);
}
/* Fill Menu Options with the proper names */
static
FillMenu()
{
	short	i;

	for( i=0; i<totaloptions; i++ )
		STRCPY( s_rec.s_item[i], menu[i].name );
	for( i=totaloptions; i<MAXOPTIONS; i++ )
		s_rec.s_item[i][0] = HV_CHAR;
	return(0);
}
static
FillOption( value )
short value;
{
	s_rec.s_option = value * HV_SHORT;
	return(0);
}
/* Fill the demarkating line field with high/low values */
static
FillSeperatorLine(value)
short	value;
{
	s_rec.s_hypline[0] = value * HV_CHAR;
	return(0);
}
/* Fill output details with high or low values */
static
FillOutputDetails( value )
short value;
{
	s_rec.s_outputon[0] = HL_CHAR(value);
	s_rec.s_filename[0] = HL_CHAR(value);
	s_rec.s_printer = HV_SHORT * value;
	s_rec.s_nbrcopies = HV_SHORT * value;
	return(0);
}
static
FillCostcen( val1, val2 )
short	val1, val2;
{
	s_rec.s_costcen1 = HV_SHORT * val1;
	s_rec.s_costcen2 = HV_SHORT * val2;
	return(0);
}
static
FillItemid( val1, val2 )
short	val1, val2;
{
	s_rec.s_itemid1 = HV_LONG * val1;
	s_rec.s_itemid2 = HV_LONG * val2;
	return(0);
}
static
FillFatype( val1, val2 )
short	val1, val2;
{
	s_rec.s_fatype1[0] = HL_CHAR( val1 );
	s_rec.s_fatype2[0] = HL_CHAR( val2 );
	return(0);
}
static
FillDeptno( val1, val2 )
short	val1, val2;
{
	s_rec.s_deptno1[0] = HL_CHAR( val1 );
	s_rec.s_deptno2[0] = HL_CHAR( val2 );
	return(0);
}
static
FillDate( val1, val2 )
short	val1, val2;
{
	s_rec.s_date1 = HV_LONG * val1;
	s_rec.s_date2 = HV_LONG * val2;
	return(0);
}
/* Fill the message and response fields with high or low values */
static
FillMsgRespFields( value )
short value;
{
	s_rec.s_mesg[0] = HL_CHAR( value );
	s_rec.s_resp[0] = HL_CHAR( value );

	return(0);
}
/* Accept user's option and call the corresponding routine in a loop */
Process(terminal, heading)
char	*terminal ;
char	*heading  ;
{
	int	field;

	if( (retval=Initialize(terminal, heading))<0 )
		return(retval);
	call_no = 0;	/* No get calls made yet */
	for( ; ; ){
		mainfileno = -1;

		retval = ReadOption();
		if( retval<0 )
			return(retval);
		if( s_rec.s_option>=totaloptions ){
#ifdef ENGLISH
			fomer("Invalid option");
#else
			fomer("Option invalide");
#endif
			continue;
		}
		if( s_rec.s_option==0 ){   /* option 0 is reserved to quit */
			fomcs();
			fomrt();
			return(0);
		}
		if((retval = CheckAccess(menu[s_rec.s_option].mainflno,
					BROWSE,e_mesg))<0)
				return(retval);

		mainfileno = menu[s_rec.s_option].mainflno ;

		/* Highlight option. Dehighlight in Confirm() */
		field = 400+(s_rec.s_option*100);
		fomca1( field, 9, 3 );

		/* if a corresponding function exists, call it  */
		if( menu[s_rec.s_option].fnptr ){
			if( (retval=(*menu[s_rec.s_option].fnptr)())<0 )
				return(retval);
			fomst();
		}
		else 	/* there isn't corr. function,  return value */
			return (s_rec.s_option);

		if( (retval=ClearInquiryArea())<0 )
			return(-1);
	}
}

/*	The following Get....() calls display default values given as parameter 
*	and fill up the variable with the value entered by the user 
*	The fields for accepting input are positioned in the order in which
*	they are called. For this, they make use of variable 'call_no'
*/

GetCostcenRange( costcen1, costcen2 )
short	*costcen1, *costcen2;
{
	int	retval=0;

	if( line[COSTCEN]==0 )	/* no fund call made yet */
		line[COSTCEN] = STARTLINENUM + call_no++;
	fomca2( 2000,1, line[COSTCEN], 1 );
	fomca2( 2000,2, line[COSTCEN], 19 );
	fomca2( 2100,1, line[COSTCEN], 40 );
	fomca2( 2100,2, line[COSTCEN], 45 );

	s_rec.s_costcen1 = *costcen1 ;
	s_rec.s_costcen2 = *costcen2 ;
	fomca1( 2000, 19, 2 );
	fomca1( 2100, 19, 2 );
	sr.nextfld = 2000;
	sr.endfld = 2100;
	fomud( (char *)&s_rec );
	if( FillCostcen( LOW, LOW )<0 )
		return(-1);
	retval = ReadFields( 2000, 2100 );
	if( retval!=EXIT && retval>=0 ){
		*costcen1 = s_rec.s_costcen1;
		*costcen2 = s_rec.s_costcen2;
	}
	fomca1( 2000, 19, 0 );
	fomca1( 2100, 19, 0 );

	return(retval);
}
GetItemidRange( itemid1, itemid2 )
long	*itemid1, *itemid2;
{
	int	retval=0;

	if( line[ITEMID]==0 )	/* no itemid call made yet */
		line[ITEMID] = STARTLINENUM + call_no++;
	fomca2( 2200,1, line[ITEMID], 1 );
	fomca2( 2200,2, line[ITEMID], 19 );
	fomca2( 2300,1, line[ITEMID], 40 );
	fomca2( 2300,2, line[ITEMID], 45 );

	s_rec.s_itemid1 = *itemid1 ;
	s_rec.s_itemid2 = *itemid2 ;
	fomca1( 2200, 19, 2 );
	fomca1( 2300, 19, 2 );
	sr.nextfld = 2200;
	sr.endfld = 2300;
	fomud( (char *)&s_rec );
	if( FillItemid( LOW, LOW )<0 )
		return(-1);
	retval = ReadFields( 2200, 2300 );
	if( retval!=EXIT && retval>=0 ){
		*itemid1 = s_rec.s_itemid1;
		*itemid2 = s_rec.s_itemid2;
	}
	fomca1( 2200, 19, 0 );
	fomca1( 2300, 19, 0 );

	return(retval);
}

GetFatypeRange( fatype1, fatype2 )
char *fatype1, *fatype2;
{
	int	retval=0;

	if( line[FA_TYPE]==0 )	/* no stock fatype call made yet */
		line[FA_TYPE] = STARTLINENUM + call_no++;
	fomca2( 2400,1, line[FA_TYPE], 1 );
	fomca2( 2400,2, line[FA_TYPE], 19 );
	fomca2( 2500,1, line[FA_TYPE], 40 );
	fomca2( 2500,2, line[FA_TYPE], 45 );

	STRCPY( s_rec.s_fatype1, fatype1 );
	STRCPY( s_rec.s_fatype2, fatype2 );
	fomca1( 2400, 19, 2 );
	fomca1( 2500, 19, 2 );
	sr.nextfld = 2400;
	sr.endfld = 2500;
	fomud( (char *)&s_rec );
	s_rec.s_fatype1[0] = LV_CHAR;
	s_rec.s_fatype2[0] = LV_CHAR;
	retval = ReadFields( 2400, 2500 );
	if( retval!=EXIT && retval>=0 ){
		strcpy( fatype1, s_rec.s_fatype1 );
		strcpy( fatype2, s_rec.s_fatype2 );
	}
	fomca1( 2400, 19, 0 );
	fomca1( 2500, 19, 0 );

	return(retval);
}
GetDeptnoRange( deptno1, deptno2 )
char *deptno1, *deptno2;
{
	int	retval=0;

	if( line[DEPTNO]==0 )	/* no stock code call made yet */
		line[DEPTNO] = STARTLINENUM + call_no++;
	fomca2( 2600,1, line[DEPTNO], 1 );
	fomca2( 2600,2, line[DEPTNO], 19 );
	fomca2( 2700,1, line[DEPTNO], 40 );
	fomca2( 2700,2, line[DEPTNO], 45 );

	STRCPY( s_rec.s_deptno1, deptno1 );
	STRCPY( s_rec.s_deptno2, deptno2 );
	fomca1( 2600, 19, 2 );
	fomca1( 2700, 19, 2 );
	sr.nextfld = 2600;
	sr.endfld = 2700;
	fomud( (char *)&s_rec );
	s_rec.s_deptno1[0] = LV_CHAR;
	s_rec.s_deptno2[0] = LV_CHAR;
	retval = ReadFields( 2600, 2700 );
	if( retval!=EXIT && retval>=0 ){
		strcpy( deptno1, s_rec.s_deptno1 );
		strcpy( deptno2, s_rec.s_deptno2 );
	}
	fomca1( 2600, 19, 0 );
	fomca1( 2700, 19, 0 );

	return(retval);
}
GetDateRange( date1, date2 )
long	*date1, *date2;
{
	int	retval=0;

	if( line[DATE]==0 )	/* no date call made yet */
		line[DATE] = STARTLINENUM + call_no++;
	fomca2( 2800,1, line[DATE], 1 );
	fomca2( 2800,2, line[DATE], 19 );
	fomca2( 2900,1, line[DATE], 40 );
	fomca2( 2900,2, line[DATE], 45 );

	s_rec.s_date1 = *date1 ;
	s_rec.s_date2 = *date2 ;
	fomca1( 2800, 19, 2 );
	fomca1( 2900, 19, 2 );
	sr.nextfld = 2800;
	sr.endfld = 2900;
	fomud( (char *)&s_rec );
	if( FillDate( LOW, LOW )<0 )
		return(-1);
	retval = ReadFields( 2800, 2900 );
	if( retval!=EXIT && retval>=0 ){
		*date1 = s_rec.s_date1;
		*date2 = s_rec.s_date2;
	}
	fomca1( 2800, 19, 0 );
	fomca1( 2900, 19, 0 );

	return(retval);
}

Confirm()	/* returns 1 for yes, 0 for no, -1 for error */
{		/* Clears the profom screen when user's response is 'Y' */
	int	field;

#ifdef ENGLISH
	if( (retval=DisplayMessage("Confirm (Y/N)?"))<0 )
#else
	if( (retval=DisplayMessage("Confirmer (O/N)?"))<0 )
#endif
		return(retval);
	if( (retval=GetResponse(s_rec.s_resp))<0 )
		return(retval);
	field = s_rec.s_option*100 + 400;

	if( s_rec.s_resp[0]==YES ){
		fflush( stdout );
		fomcs();
		fomrt();
		return(1);
	}
	/* Dehighlight the option which is highlighted in Process() */
	fomca1( field, 9, 5 );

	return( HideMessage() );
}

static
ClearInquiryArea()
{
	short i;

	call_no = 0;	/* Reset the call_no */
	for( i=0; i<MAXQUERYLINES; i++ )/* so that next time fields can be */
		line[i] = 0;	/* repositioned for next routine calls */
	if(FillOutputDetails(HIGH)<0 )
		return(-1);
	if(FillCostcen(HIGH,HIGH)<0 )
		return(-1);
	if(FillItemid(HIGH,HIGH)<0 )
		return(-1);
	if(FillFatype(HIGH,HIGH)<0 )
		return(-1);
	if(FillDeptno(HIGH,HIGH)<0 )
		return(-1);
	if(FillDate(HIGH,HIGH)<0 )
		return(-1);
	if(FillMsgRespFields(HIGH)<0 )
		return(-1);
	return( WriteFields(1,0) );
}
static
ReadOption()
{
	s_rec.s_option = LV_SHORT;
	return( ReadFields(1400,1400) );
}
static
ReadFields(start,end)	/* read fields whose numbers range from start to end */
int start, end;		/* start and end fields */
{
	int retval;

	sr.nextfld = start;
	sr.endfld = end;
	for( ; ; ){
		fomrd( (char *)&s_rec );
		ret(err_chk(&sr));
		if( sr.retcode==RET_USER_ESC || sr.retcode==RET_VAL_CHK ){
			if( ESC_F ) return(EXIT);
			retval=Validate();
			if( retval<0 || retval==EXIT)	return(retval);
			continue;
		}
		break;
	}
	return(0);
}
static
WriteFields( start,end )/* write fields whose numbers range from start to end */
int start, end;
{
	sr.nextfld = start;
	sr.endfld = end;
	fomwr( (char *)&s_rec );
	ret( err_chk(&sr) );
	return(0);
}
static
Validate()	/* Validate the values entered by the user */
{
	switch( sr.curfld ){
		case 1400:	/* menu option */
			if( s_rec.s_option<0 || s_rec.s_option>=totaloptions ){
#ifdef ENGLISH
				fomer("Invalid option");
#else
				fomer("Option invalide");
#endif
				s_rec.s_option = LV_SHORT;
			}
			break;
		case 1600:	/* output on */
			if( s_rec.s_outputon[0]!= DISPLAY &&
			    s_rec.s_outputon[0]!= PRINTER &&
			    s_rec.s_outputon[0]!= FILE_IO   ){
#ifdef ENGLISH
				fomer("D(isplay), P(rinter), F(ile)");
#else
				fomer("A(fficher), I(mprimante), D(ossier)");
#endif
				s_rec.s_outputon[0] = LV_CHAR;
			}
			break;
		case 1700:	/* Filename */
			break;
		case 1800:	/* Printer */
			break;
		case 1900:	/* Page Size */
			break;
		case 2000:	/* start cost center code */
			if( s_rec.s_costcen1<1 ){
#ifdef ENGLISH
				fomer("Cost Center can't be less than 1");
#else
				fomer("Centre de couts ne peut pas etre moins que 1");
#endif
				s_rec.s_costcen1 = LV_SHORT;
			}
			break;
		case 2100:	/* end cost center code */
			if( s_rec.s_costcen2 < s_rec.s_costcen1 ){
#ifdef ENGLISH
				fomer("Value can't be less than starting Cost Center");
#else
				fomer("Valeur ne peut pas etre moins que la valeur du centre de couts debutant");
#endif
				s_rec.s_costcen2 = LV_SHORT;
			}
			break;
		case 2200:	/* start item id */
			if( s_rec.s_itemid1<1 ){
#ifdef ENGLISH
				fomer("Item id can't be less than 1");
#else
				fomer("Identite d'article ne peut pas etre moins que 1");
#endif
				s_rec.s_itemid1 = LV_LONG;
			}
			break;
		case 2300:	/* end item id */
			if( s_rec.s_itemid2 < s_rec.s_itemid1 ){
#ifdef ENGLISH
				fomer("Value can't be less than start Item id");
#else
				fomer("Valeur ne peut pas etre moins que l'identite d'article dedutant");
#endif
				s_rec.s_itemid2 = LV_LONG; 
			} 
			break;
		case 2500:	/* ending fixed asset type */
			if( strcmp( s_rec.s_fatype2,s_rec.s_fatype1 )<0 ){
#ifdef ENGLISH
				fomer("End Fixed Asset Item Type smaller than starting Fixed Asset Item Type");
#else
				fomer("Genre d'articles AI finissant plus petit que le genre d'articles AI debutant");
#endif
				s_rec.s_fatype2[0]=LV_CHAR;
			}
			break; 
		case 2700:	/* ending dept no */
			if( strcmp( s_rec.s_deptno2,s_rec.s_deptno1 )<0 ){
#ifdef ENGLISH
				fomer("End dept no smaller than start dept no");
#else
				fomer("Numero du dept. finissant plus petit que le numero du dept. debutant");
#endif
				s_rec.s_deptno2[0]=LV_CHAR;
			}
			break; 
		case 2900: 	/* ending date */
			if(s_rec.s_date1 > s_rec.s_date2) {
#ifdef ENGLISH
				fomer("Ending date smaller than starting date");
#else
				fomer("Date finissante plus tot que la date debutante");
#endif
				s_rec.s_date2 = LV_LONG;
			}
			break;
	}
	sr.nextfld = sr.curfld;
	return(0);
}
DisplayMessage(mesg)	/* Display the given message in the message field */
char *mesg;
{
	STRCPY( s_rec.s_mesg, mesg );
	return( WriteFields(3000,3000) );
}
HideMessage()	/* Hide the message field */
{
	if( FillMsgRespFields(HIGH)<0 )	return(-1);
	return( WriteFields(3000,3100) );
}
GetResponse( respchar )
char *respchar;
{
	int	retval;

	s_rec.s_resp[0] = LV_CHAR;
	retval = ReadFields( 3100, 3100 );
	if( retval!=EXIT && retval>=0 )
		*respchar = s_rec.s_resp[0];
	return( retval );
}
GetOutputon( outputon )
char	*outputon;
{
	int	retval;

#ifdef ENGLISH
	fomer("D(isplay), P(rinter), F(ile)");
#else
	fomer("A(fficher), I(mprimante), D(ossier)");
#endif
	STRCPY( s_rec.s_outputon, outputon );
	fomca1( 1600, 19, 2 );
	sr.nextfld = 1600;
	sr.endfld = 1600;
	fomud( (char *)&s_rec );
	s_rec.s_outputon[0] = LV_CHAR;
	retval = ReadFields(1600,1600);
	if( retval!=EXIT && retval>=0 )
		*outputon = s_rec.s_outputon[0];
	fomca1( 1600, 19, 0 );
	return( retval );
}
GetFilename( filename )
char	*filename;
{
	int	retval;

	STRCPY( s_rec.s_filename, filename );
	fomca1( 1700, 19, 2 );
	sr.nextfld = 1700;
	sr.endfld = 1700;
	fomud( (char *)&s_rec );
	s_rec.s_filename[0] = LV_CHAR;
	retval = ReadFields(1700,1700);
	if( retval!=EXIT && retval>=0 )
		strcpy( filename , s_rec.s_filename ) ;
	fomca1( 1700, 19, 0 );
	return( retval );
}
GetPrinter( printer )
short	*printer;
{
	int	retval;

	s_rec.s_printer = *printer ;
	fomca1( 1800, 19, 2 );
	sr.nextfld = 1800;
	sr.endfld = 1800;
	fomud( (char *)&s_rec );
	s_rec.s_printer = LV_SHORT;
	retval = ReadFields(1800,1800);
	if( retval!=EXIT && retval>=0 )
		*printer = s_rec.s_printer;
	fomca1( 1800, 19, 0 );
	return( retval );
}
GetNbrCopies( nbrcopies )
short	*nbrcopies;
{
	int	retval;

	s_rec.s_nbrcopies = *nbrcopies ;
	fomca1( 1900, 19, 2 );
	sr.nextfld = 1900;
	sr.endfld = 1900;
	fomud( (char *)&s_rec );
	s_rec.s_nbrcopies = LV_SHORT;
	retval = ReadFields(1900,1900);
	if( retval!=EXIT && retval>=0 )
		*nbrcopies = s_rec.s_nbrcopies;
	fomca1( 1900, 19, 0 );
	return( retval );
}
