/*-----------------------------------------------------------------------
Source Name: department.c
System     : Personnel/Payroll
Created  On: August 27, 1991.
Created  By: Eugene Roy.

DESCRIPTION:
	Program to store the various departments.

MODIFICATIONS:        

Programmer     YY/MM/DD       Description of modification
------------------------------------------------------------------------*/
#define	MAIN		/* Main program. This is to declare Switches */
#define MAINFL		DEPARTMENT	/* main file used */

#define	SYSTEM		"Pers/Pay"	/* Sub System Name */
#define	MOD_DATE	"27-AUG-91"		/* Progran Last Modified */

#include <stdio.h>
#include <cfomstrc.h>
#include <bfs_defs.h>
#include <bfs_pp.h>

/* User Interface define constants */
#ifdef ENGLISH
#define ADDREC		'A'
#define CHANGE		'C'
#define DELETE		'D'
#define INQUIRE		'I'
#define EXITOPT		'E'
#define	NEXTPAGE	'N'
#define	PREVPAGE	'P'

#define	YES		'Y'
#define NO		'N'
#define	LINEEDIT	'L'
#define SCREENEDIT	'S'
#define	CANCEL		'C'

#else
#define ADDREC		'R'
#define CHANGE		'C'
#define DELETE		'E'
#define INQUIRE		'I'
#define EXITOPT		'F'
#define	NEXTPAGE	'S'
#define	PREVPAGE	'P'

#define	YES		'O'
#define NO		'N'
#define	LINEEDIT	'L'
#define SCREENEDIT	'S'
#define	CANCEL		'A'

#endif

/* PROFOM Releted declarations */

#define	SCR_NAME	"department"	/* PROFOM screen Name */

#define	PAGESIZE	15		/* No of Items */

/* PROFOM Screen STH file */

/* Field PROFOM numbers */

#define	ITEM_ST_FLD	1100	/* Item 1 Start Field */
#define ITEM_DISP_FLD	700	/* Item Display Start Field */
#define	END_FLD		7200	/* Last Field of the screen */
#define	STEP		300	/* NO of fields diff. between 2 items */

/* Header Field numbers for line edit */

#define	FN_FLD		400	/* Field: */
#define	CHG_FLD		500	/* Field: */

/* Item Fields. These numbers are difference between that field
   and the 1st fld within the item */
#define	DEPT_FLD	100
#define DESC_FLD	200
#define	STATUS_FLD	300

/* department.sth - header for C structure generated by PROFOM EDITOR */

typedef	struct	{	/* Start Fld 2200, Endfld 6100 and Step 400 */

	char	s_code[7];	/* 1100 STRING X(12) */
	char	s_desc[31];	/* 1200 STRING X(30) */
	char	s_status[4]; 	/* 1300 STRING X(12) */
}	S_item ;

typedef struct	{

	char	s_pgname[11];		/* 100 STRING x(10)	*/
	long	s_rundate;		/* 300 Date YYYYMMDD	*/
	char	s_fn[3];		/* 400 Fn		*/
	short	s_field;		/* 500 Numeric 99	*/
	short	s_page;			/* 900 Numeric 99
	S_item	s_items[PAGESIZE] ;	/* Start Filed 1100 and end field 7000
					   Step 400	 */
	char	s_mesg[78];		/* 7100 string x(77)	*/
	char	s_resp[2];		/* 7200 string x	*/

}	S_struct ;

static	S_struct	s_sth,image;	/* PROFOM Screen Structure	*/
static	S_item	s_ith;	/* PROFOM Screen Structure	*/
static	struct	stat_rec	sr;	/* PROFOM Status rec		*/
static	char 	e_mesg[100];  		/* dbh will return err msg in this */

static	Dept	department;

int	ItemsValidation() ;
int	ItemsWindowHelp() ;
int	Argc;
char	**Argv;

/*
*	Doubly linked list to maintain department items. Each node in this list
*	contains one page full of department items. This list is freed only at
*	the time of exiting program. 
*/

typedef struct Page {
	S_item	Items[PAGESIZE] ;	/* Items Information */
	short	DeptItemNo[PAGESIZE] ;	/* Corresponding Item # 	*/
	char	DeptStatus[PAGESIZE] ;	/* Status Add, Change	*/
	struct	Page	*PrevPage ;	/* ptr to previous page */
	struct	Page	*NextPage ;	/* ptr to next page */
	short	NoItems;		/* number of Items on the page */
	short	Pageno;			/* Page number */
}	Page;

static	Page	*FirstPage,		/* Address of First Page */
		*CurPage,		/* Address of Current Page */
		*DeptLast,		/* Address of Curr. record last page */
		*LastPage;		/* Address of Last Page of Memory
					   Allocated */

typedef struct List {
	char	Code[7];
	struct	List	*PrevCode ;
	struct	List	*NextCode ;
	short	NoCodes;
	short	Codeno;
}	List;

static	List	*FirstCode,
		*CurCode,
		*CodeLast,
		*LastCode;

void	free() ;
char	*malloc() ;

main(argc,argv)
int argc;
char *argv[];
{
	int 	retval;

	/* These two are passed to execute() when it is called */
	Argc = argc;
	Argv = argv;

	retval = Initialize(argc,argv);	/* Initialization routine */

	if (retval == NOERROR) retval = Process();

	CloseRtn();			/* return to menu */
	if (retval != NOERROR) exit(-1);
	exit(0);
}

/*-------------------------------------------------------------------*/
/* Initialize PROFOM */

Initialize(argc, argv)
int	argc ;
char	*argv[] ;
{
	int	retval ;

	/*
	*	Initialize DBH Environment
	*/
	strncpy(SYS_NAME,SYSTEM,50);	/* Sub system name */
	strncpy(CHNG_DATE,MOD_DATE,10);	/* Modification Date */

	proc_switch(argc, argv, MAINFL) ; 	/* Process Switches */

	/*
	*	Initialize PROFOM & Screen
	*/
	strcpy(sr.termnm,terminal);	/* Copy Terminal Name */
	fomin(&sr);
	ret(err_chk(&sr)) ;		/* Check for PROFOM Error */
	fomcf(1,1);			/* Enable Snap screen option */

	retval = InitScreen() ;		/* Initialize Screen */
	if(NOERROR != retval) return(retval) ;

	FirstPage = NULL;
	LastPage = NULL;

	return(NOERROR) ;
}	/* Initialize() */
/*----------------------------------------------------------------*/
/* Initialize screen before going to process options */
static
InitScreen()
{
	int	retval ;

	/* move screen name to Profom status structure */
	strcpy(sr.scrnam,NFM_PATH);
	strcat(sr.scrnam,SCR_NAME) ;

	strcpy(s_sth.s_pgname,PROG_NAME);

	s_sth.s_rundate = get_date();	/* get Today's Date in YYYYMMDD format*/
	s_sth.s_field = HV_SHORT ;
	s_sth.s_mesg[0] = HV_CHAR ;
	s_sth.s_resp[0] = HV_CHAR ;

	/* Move High Values to data fields and Display the screen */
	retval = ClearScreen() ;
	if(NOERROR != retval) return(retval) ;

	return(NOERROR) ;
}	/* InitScreen() */

/*--------------------------------------------------------------------------*/
/* Close nessary files and environment before exiting program               */
static
CloseRtn() 
{
	/* Free the linked list for the end */
	for( ;LastCode != FirstCode ; ) {
		LastCode = LastCode->PrevCode;
		free((char *)LastCode->NextCode);
		LastCode->NextCode = NULL;
	}
	if(FirstCode != NULL) {
		free((char *)FirstCode);
	}

	FirstCode = LastCode = NULL;

	/* Free the linked list for the end */
	for( ;LastPage != FirstPage ; ) {
		LastPage = LastPage->PrevPage;
		free((char *)LastPage->NextPage);
		LastPage->NextPage = NULL;
	}
	if(FirstPage != NULL) {
		free((char *)FirstPage);
	}

	FirstPage = LastPage = NULL;

	/* Set terminal back to normal mode from PROFOM */
	fomcs();
	fomrt();

	close_dbh();	/* Close files */

	return(NOERROR);
}	/* CloseRtn() */
/*-------------------------------------------------------------------*/
/* Get Option from user and call corresponding function */

Process()
{
	int retval;

	for( ; ; ){

		/* Get the Fn: option from the user */
		if((retval = ReadFunction()) != NOERROR) return(retval) ;

		retval = ProcFunction() ;	/* Process Function */

		if(QUIT == retval) return(NOERROR) ;    /* Exit */
		if(NOACCESS == retval)	fomen(e_mesg);	     /* security */
		if(PROFOM_ERR == retval) return(PROFOM_ERR);  /* PROFOM ERROR */
		if(DBH_ERR == retval) {
			DispError(e_mesg);
#ifdef ENGLISH
			sprintf(e_mesg,"%s %d Dberror: %d Errno: %d",
				"System Error... Iserror:",
				iserror, dberror, errno);
#else
			sprintf(e_mesg,"%s %d Dberror: %d Errno: %d",
				"Erreur du systeme... Iserror:",
				iserror, dberror, errno);
#endif
			DispError(e_mesg);
			return(DBH_ERR); /* DBH ERROR */
		}
	}      /*   end of the for( ; ; )       */
}	/* Process() */
/*----------------------------------------------------------------*/
/* Display the Function (Fn:) options and get the option from the user */

ReadFunction()
{
	/* Display Fn: options */
#ifdef ENGLISH
	fomer("A(dd), C(hange), I(nquire), N(ext), P(rev), E(xit)");
#else
	fomer("R(ajouter), C(hanger), I(nterroger), S(uivant), P(recedent), F(in)");
#endif
	/* Read Fn: field to get the option */
	sr.nextfld = FN_FLD ;
	fomrf( (char *)&s_sth );
	ret(err_chk(&sr));	/* Check for PROFOM error */

	return(NOERROR) ;
}	/* ReadFunction() */
/*----------------------------------------------------------------*/
/* Process the user selected Fn: option */

ProcFunction()
{
	int retval;

	switch (s_sth.s_fn[0]) {
	case ADDREC  :			/* ADD */
		CHKACC(retval,ADD,e_mesg);
		return( Add() ) ;
	case CHANGE  :			/* CHANGE */
		CHKACC(retval,UPDATE,e_mesg);
		return( Change() ) ;
	case INQUIRE  :			/* Inquire Dept */
		CHKACC(retval,BROWSE,e_mesg);
		return( Inquire() ) ;
	case NEXTPAGE  :			/* Next Dept */
		CHKACC(retval,BROWSE,e_mesg);
		return( Next(FORWARD) ) ;
	case PREVPAGE  :			/* Previous Dept */
		CHKACC(retval,BROWSE,e_mesg);
		return( Next(BACKWARD) ) ;
	case EXITOPT  :			/* Exit */
		return( QUIT ) ;
	}  /*   end of the switch statement */

	return(retval);
}	/* ProcFunction() */
/*----------------------------------------------------------------------*/
/* Adding Departments. Accept details and update the files */

Add()
{
	int	retval ;

	CurPage = NULL ;
	DeptLast = NULL ;
	CurCode = NULL ;
	CodeLast = NULL ;

	/* Clear The Screen */
	retval = ClearScreen();
	if(retval != NOERROR) return(retval) ;

	retval = GetDetails() ;
	if(PROFOM_ERR == retval || DBH_ERR == retval) return(retval) ;
	if(retval < 0 || CANCEL == retval) {
		roll_back(e_mesg) ;	/* Unlock the locked Records */
		return(ClearScreen()) ;	/* Clear the Screen */
	}

	return(NOERROR);
}	/* Add() */
/*-----------------------------------------------------------------------*/
/* Change the Dept */

Change()
{
	int	retval ;

	return(NOERROR) ;
}	/* Change() */
/*-----------------------------------------------------------------------*/
/* Show the Departmetns        */

Inquire()
{
	int	retval ;

	retval = Select(BROWSE) ;
	if(NOERROR != retval) return(retval) ;

	retval = ConfirmItems() ;
	if(retval < 0) return(retval) ;

	return(NOERROR) ;
}	/* Inquire() */
/*----------------------------------------------------------*/
/* Show the next or previous Dept */

Next(direction)
int	direction ;
{
	int retval;

	return( ShowDept() ) ;
}	/* Next() */
/*------------------------------------------------------------*/
/* Read the Department Details from the User */

GetDetails()
{
	int	retval ;

	retval = AddItems();
	if(NOERROR != retval) return(retval) ;

	for( ; ; ) {
		retval = ConfirmItems() ;
		if(retval != YES) break;

		retval = WriteRecords(ADD) ;
		if(retval != LOCKED) break;
	}
	return(retval) ;
}	/* GetDetails() */
/*------------------------------------------------------------*/
/* Read Item Details from the User */

AddItems()
{
	int	i, retval ;

	/* If the last node of department is Partial filled then Show Page */
	if(DeptLast != NULL && DeptLast->NoItems < PAGESIZE ) {
		ret( ShowItems(DeptLast) ) ;
		i = DeptLast->NoItems ;
		CurPage = DeptLast ;
	}
	else {
		/* Calculate the page# */
		if(DeptLast != NULL) {
			i = PAGESIZE ;
			CurPage = DeptLast ;
		}
		else {
			s_sth.s_page_no = 1 ;
			s_sth.s_dummy1[0] = ' ' ;
			ret( WriteFields(PAGENO_FLD, COLHDG_FLD) ) ;
			i = 0 ;
		}
	}


	for( ; ; ) {
		if( PAGESIZE == i) {	/* Page Full */

			/* Move High Values to All items except first */
			for(i-- ; i > 0 ; i--)
				InitItem(i, HV_CHAR, HV_CHAR, HV_CHAR, ADD) ;

			/* Calculate the page# */
			s_sth.s_page_no = DeptLast->Pageno + 1 ;

			ret( WriteFields(PAGENO_FLD, (END_FLD - 200)) ) ;

			i = 0 ;
		}

		retval = ReadItem(i,ADD) ;		/* Read Each Item Line */
		if(PROFOM_ERR == retval || DBH_ERR == retval) return(retval) ;
		if(NOERROR != retval) break ;	/* ESC-F */

		if(0 == i)	/* First Item in the Page */
			if((retval = MakeFreshPage()) < 0) return(retval) ;
		
		/* Copy the Item to Page List */
		scpy((char*)&(CurPage->Items[i]), (char*)&(s_sth.s_items[i]),
			sizeof(S_item)) ;

		CurPage->DeptItemNo[i] = ((DeptLast->Pageno - 1) * 
					PAGESIZE) + (i + 1) ;
		CurPage->DeptStatus[i] = 'A' ;
		i++ ;

		CurPage->NoItems = i;

		/* Copy the Item to Code List */
		scpy((char*)&(CurCode->Items[i]), (char*)&(s_sth.s_items[i]),
			sizeof(S_item)) ;

		CurCode->CodeItemNo[i] = ((CodeLast->Codeno - 1) * 
					PAGESIZE) + (i + 1) ;
		CurCode->CodeStatus[i] = 'A' ;
		i++ ;

		CurPage->NoItems = i;

	}
	if(i == 0) 
		if((retval=ShowItems(CurPage))<0) return(retval) ;

	return(NOERROR) ;
}	/* AddItems() */
/*-----------------------------------------------------------------------*/
/* Take the confirmation from user for the items part of the screen */

ConfirmItems()
{
	int	retval ;

	/* Options:
	     YSLNPC
	*/

	for( ; ; ) {
#ifdef ENGLISH
		retval = GetOption((char *)&s_sth,
		"Y(es), S(creen Edit), L(ine edit), N(ext), P(rev), C(ancel)"
		,"YSLNPC");
#else
		retval = GetOption((char *)&s_sth,
		"O(ui), S(creen edit), L(ine edit), S(uiv), P(rec), A(nnul)"
		,"OSLA");
#endif

	    switch(retval) {
	    case  YES  :
		return(YES);
	    case  SCREENEDIT:
		retval = ScreenEdit();
		break;
	    case  LINEEDIT  :
		retval = ChangeFields();
		break ;
	    case  NEXTPAGE:
		if(CurPage == DeptLast || DeptLast == NULL) {
#ifdef ENGLISH
			fomer("No More Pages....");
#else
			fomer("Plus de pages....");
#endif
			continue;
		}
		CurPage = CurPage->NextPage ;
		retval = ShowItems(CurPage);
		break;
	    case  PREVPAGE:
		if(DeptLast == NULL || CurPage == FirstPage) {
#ifdef ENGLISH
			fomer("No More Pages....");
#else
			fomer("Plus de pages....");
#endif
			continue;
		}
		CurPage = CurPage->PrevPage ;
		retval = ShowItems(CurPage);
		break;
	    case  CANCEL :
#ifdef ENGLISH
		retval = GetOption((char *)&s_sth,
				"Confirm the Cancel (Y/N)?", "YN") ;
#else
		retval = GetOption((char *)&s_sth,
				"Confirmer l'annulation (O/N)?", "ON") ;
#endif
		if(retval == YES) return(CANCEL) ;
		break ;
	    }	/* switch retval */

	    if(retval == PROFOM_ERR) return(retval) ;
	    if(retval == DBH_ERR) return(retval) ;
	}	/* for(; ; ) */
}	/* ConfirmItems() */
/*-----------------------------------------------------------------------*/ 
/* Write the Daily attendance record to the file.	  	         */
/*-----------------------------------------------------------------------*/ 
WriteRecords(temppage,item_no,mode)
Page	*temppage;
int	item_no;
int	mode;
{
	int	retval;

	if(mode == ADD) {
		retval = get_department(&department,UPDATE,0,e_mesg);
		if (retval < 0){
			DispError(e_mesg);
			return(err);
		}
	}


	

	retval = commit(e_mesg) ;
	if(retval < 0) {
		DispError((char *)&s_sth,BADSAVE); 
		DispError((char *)&s_sth,e_mesg);
		roll_back(e_mesg);
		return(retval);
	}
	return(NOERROR);
}
/*-------------------------------------------------------------------------*/
/* Initialize Given screen item with either Low values or High values */
static
InitItem(item_no, t_char)
int	item_no ;
char	t_char ;
{
	s_sth.s_items[item_no].s_code[0] = t_char ;
	s_sth.s_items[item_no].s_desc[0] = t_char ;
	s_sth.s_items[item_no].s_status[0] = t_char ;

	return(NOERROR) ;
}	/* Inititem() */
/*------------------------------------------------------------*/
/* Read details of given item# */

ReadItem(item_no,mode)
int	item_no ;
int	mode ;
{
	int	i, j, k ;
	int	st_fld ;
	int	end_fld ;

#ifdef ENGLISH
	STRCPY(s_sth.s_mesg,"Press ESC-F to Terminate");
#else
	STRCPY(s_sth.s_mesg,"Appuyer sur ESC-F pour terminer");
#endif
	DispMesgFld((char *)&s_sth);

	st_fld  = ITEM_ST_FLD + (STEP * item_no) ;
	end_fld = st_fld + STEP - 100 ;

	/* If mode == UPDATE turn ON dup control, else OFF */
	SetDupBuffers(st_fld,end_fld,(mode == UPDATE) ? 1 : 0); 

	if(ADD == mode) {
		/* Get Offset of the begining field of the Item in 'k' */
		fomfp(st_fld,&k,&j) ;
		/* Offset to the field where ESC-F Pressed in 'j' */
		fomfp(sr.curfld,&j,&i);
		i =  j - k ;	/* Offset within item */

		j = sizeof(S_item) - i ;  /* Length to copy */
       		scpy((char *)(&s_sth.s_items[item_no])+i,
			(char*)(&CurPage->Items[item_no])+i, j);

		return(RET_USER_ESC) ;
	}

	/** Set previous account number to last account number entered **/
	STRCPY(Prev_acct,s_sth.s_items[item_no].s_accno);

	/* Calculate and Display totals at Bottom of Screen */
	s_sth.s_total_po = s_sth.s_po_amt;
	s_sth.s_total_itm += s_sth.s_items[item_no].s_value;
	s_sth.s_total_diff = s_sth.s_total_po - s_sth.s_total_itm;

	ret(WriteFields(TOTAL_ST_FLD,TOTAL_END_FLD));

	return(NOERROR) ;
}	/* ReadItem() */
/*----------------------------------------------------------------*/
/* Validation function() for Item fields when PROFOM returns RET_VAL_CHK */
ItemsValidation()
{
	int retval;
	Page	*temppage ;
	int	item_no;

	item_no = (sr.curfld - ITEM_ST_FLD - STATUS_FLD) / STEP;
	fld_no = (sr.curfld - ITEM_ST_FLD - STATUS_FLD) % STEP;

	switch(fld_no){
	case DEPT_FLD :			/* Department code field */
		strcpy(d_code,s_ith.s_code);
		d_desc = LV_CHAR;

		/*  Verify Department code is not already present in 
		    Deparment file.					*/

		for( ; ; ){
			retval = get_n_dept(&department, BROWSE, 0, direction,
				 e_mesg);
			if(retval == UNDEF )
				mode = ADD;
			if(retval < 0) {
				DispError(e_mesg);
				return(retval);
			}
			if(retval != UNDEF){
/*		Display error message				*/
#ifdef ENGLISH
				sprintf(e_mesg,
			"Department Code Already Exists, Please Re-enter",
			);
#else
				sprintf(e_mesg,
			"Code de departement existe deja, SVP reseille",
			);
#endif
				DispError(e_mesg);
				return(retval);
			}
		}

		/*	Verify department code is not in linked list.	*/


		if(DeptLast != NULL) {
			for(temppage=FirstPage; temppage!=LastPage;
			    temppage=temppage->NextPage) {
				for(i =0; i< temppage->NoItems; i++) {
					if(s_sth.s_items[i] == s_ith.s_code) {

	/*		Display error message				*/
#ifdef ENGLISH
				sprintf(e_mesg,
			"Department Code Already Exists, Please Re-enter",
			);
#else
				sprintf(e_mesg,
			"Code de departement existe deja, SVP reseille",
			);
#endif
				DispError(e_mesg);
				return(ERROR);
				}
				i++;
			}

			CurPage = CurPage->NextPage;

		}
	default : 
#ifdef ENGLISH
		sprintf(e_mesg,"No Validity Check For Field# %d", sr.curfld);
#else
		sprintf(e_mesg,"Pas de controle de validite pour le Champ#  %d",				sr.curfld);
#endif
		fomen(e_mesg);
		get();
		return(ERROR);
	}			/* Switch sr.curfld	*/
	sr.nextfld = sr.curfld;
	return(NOERROR) ;
}	/* ItemsValidation() */
/*-----------------------------------------------------------------------*/
/* Items Help Window */
ItemsWindowHelp()
{
	int	item_no;
	int	retval;
	char	type[2];

	item_no = (sr.curfld - ITEM_ST_FLD) / STEP;
	fld_no = (sr.curfld - ITEM_ST_FLD) % STEP;

	switch(fld_no){
	case DEPT_FLD :
		retval = dept_hlp(&s_sth.s_items[item_no].s_code, 7,13);
		if (retval == DBH_ERR) return(retval);
		if (retval >= 0) redraw();
		if (retval < 1) return(ERROR);
		break;
	default :
#ifdef ENGLISH
		fomer("No Help Window for this field:);
#else
		fomer("Pas de fenetre d'assistance pour ce champ:);
#endif
	}
	return(NOERROR);
}	/* ItemsWindowHelp() */
/*------------------------------------------------------------*/
/* Show all the items on the current page 		      */
ShowItems(pageptr)
Page	*pageptr ;
{
	int	i ;

	get_day();

	if(pageptr != NULL) {
		/* Copy the items to screen */
		scpy((char*)s_sth.s_items, (char*)pageptr->Items,
			(pageptr->NoItems * sizeof(S_item)) );

		s_sth.s_page   = pageptr->Pageno ;

		i = pageptr->NoItems ;
	}
	else {
		s_sth.s_page = HV_SHORT ;
		i = 0 ;
	}

	/* Move High Values to remaining Items */
	for( ; i < PAGESIZE ; i++ )
		InitItem(i, HV_CHAR) ;

	ret( WriteFields((char *)&s_sth, ITEM_DISP_FLD, (END_FLD - 200)) );

	return(NOERROR) ;
}	/* ShowItems() */
/*---------------------------------------------------------------------*/
/* Change screen.  Allows editing of all the students on the screen    */
/*---------------------------------------------------------------------*/
ScreenEdit()
{
     	int i;
	int retval;

	/* make copy of screen incase user presses ESC-F */
	scpy((char *)&image,(char *)&s_sth,sizeof(s_sth));

#ifdef ENGLISH
	strcpy(s_sth.s_mesg,"Press ESC-F to Terminate");
#else
	strcpy(s_sth.s_mesg,"Appuyer sur ESC-F pour terminer");
#endif
	DispMesgFld((char *)&s_sth);

	if(SetDupBuffers(ITEM_ST_FLD, END_FLD - 200,1)<0) return(PROFOM_ERR);

	for(i=0;i < PAGESIZE; i++) {
	}

	retval=ReadFields((char *)&s_sth,ITEM_ST_FLD,END_FLD - 200,
			ItemsValidation,ItemsWindowHelp,1) ;
	if(retval == PROFOM_ERR || retval == DBH_ERR) return(retval);
	if(retval == RET_USER_ESC) {
		/* When user gives ESC-F while changing fields, assumption is
		* he completed his changes, and remaining fields are same as
		* old. But, at this point STH will be having low values in the 
		* remaining fields. So move the old values form the linked list.
		*/

		retval=CopyBack((char *)&s_sth,(char *)&image,
				sr.curfld,END_FLD - 200);
		if(retval == PROFOM_ERR) return(retval);

		return(RET_USER_ESC) ;
	}

	scpy((char *)&CurPage->Items,(char *)&s_sth.s_items,
			sizeof(CurPage->Items));

     	s_sth.s_mesg[0] = HV_CHAR ;
     	DispMesgFld((char *)&s_sth);

	if(SetDupBuffers(ITEM_ST_FLD, END_FLD-200,0)<0) return(PROFOM_ERR);

	return(NOERROR);
}	/* ScreenEdit() */
/*-----------------------------------------------------------------------*/
/* Changing fields. Accept fld of the student to be changed and read     */
/* that fld.		 */
ChangeFields()
{
	int retval;

	/* make copy screen every time field changed in case user */
	/* presses ESC-F */
	scpy((char*)&image,(char*)&s_sth, sizeof(s_sth));

	SetDupBuffers(ITEM_ST_FLD, END_FLD - 200, 1);

	/* Get The Field to Be Modified */
#ifdef	ENGLISH
	strcpy(s_sth.s_mesg,"Enter RETURN to Terminate Edit");
#else
	strcpy(s_sth.s_mesg,"Appuyer sur RETURN pour terminer l'ajustement");
#endif
	DispMesgFld((char *)&s_sth); ;
        
     	for (; ;) {
		s_sth.s_field = LV_SHORT;
		retval = ReadFields((char *)&s_sth,CHG_FLD,CHG_FLD,
			(int (*)())NULL,(int (*)())NULL, 1);

		if (retval < 0) return(-1);
		if (retval == RET_USER_ESC) break;	/* User enter ESC-F */

       		if (s_sth.s_field == 0 ) break;  /* Finished changing fields */


		retval = ReadItem(s_sth.s_field - 1,UPDATE);
		if(retval != NOERROR) {
			return(retval);
		}
		strcpy(CurPage->Items[s_sth.s_field-1].s_att_code,
			s_sth.s_items[s_sth.s_field-1].s_att_code);

		/* reset dup buffers so if user edits same fields again */
		/* the last value valid value entered will be the default */
		SetDupBuffers(ITEM_ST_FLD, END_FLD - 200, 1);

		/* make copy screen every time field changed in case user */
		/* presses ESC-F */
		scpy((char*)&image,(char*)&s_sth, sizeof(s_sth));
	}

     	s_sth.s_field = HV_SHORT ;
	if ( WriteFields((char *)&s_sth,CHG_FLD, CHG_FLD) < 0 ) return(-1);

     	s_sth.s_mesg[0] = HV_CHAR ;
     	DispMesgFld((char *)&s_sth);

	if(SetDupBuffers(HDR_ST_FLD, HDR_END_FLD, 0)<0) return(PROFOM_ERR);

	return(NOERROR);
}	/* ChangeFields() */
/*------------------------------------------------------------------------*/
/* Move High values to all data fields and clear the screen */

ClearScreen()
{
	int	i;

	s_sth.s_page = HV_SHORT;

	/* Move High Values to All items */
	for(i = 0 ; i < PAGESIZE ; i++)
		InitItem(i, HV_CHAR) ;

	ret( WriteFields((char *)&s_sth,HDR_ST_FLD, (END_FLD - 200)) );

	return(NOERROR);
}	/* ClearScreen() */
/*----------------------------------------------------------------*/
/* Set Duplication buffers for fields 				  */
SetDupBuffers( firstfld, lastfld, value )
int	firstfld, lastfld;	/* field numbers range */
int	value;			/* ENABLE or DISABLE */
{
	int i ;

	for( i=firstfld; i<=lastfld; i+=100 )
		fomca1( i, 19, value);
	if( value==0 )
		return(0);
	sr.nextfld = firstfld;
	sr.endfld = lastfld;
	fomud( (char *)&s_sth );
	ret( err_chk(&sr) );

	return( 0 );
}
/*-------------------- E n d   O f   P r o g r a m ---------------------*/
