/*-----------------------------------------------------------------------
Source Name: mon_att.c
System     : Personnel/Payroll System.
Created  On: March 26, 1992.
Created  By: Eugene Roy.

DESCRIPTION:
	The Monthly Attendance Screen is used to verify and enter 
	attendance for an individual for a specific month.

MODIFICATIONS:        

Programmer     YY/MM/DD       Description of modification
------------------------------------------------------------------------*/
#define	MAIN		/* Main program. This is to declare Switches */
#define MAINFL		EMP_ATT		/* main file used */

#define	SYSTEM		"PERSONNEL"	/* Sub System Name */
#define	MOD_DATE	"26-MAR-92"		/* Progran Last Modified */

#include <stdio.h>
#include <cfomstrc.h>
#include <bfs_defs.h>
#include <bfs_pp.h>

/* User Interface define constants */
#ifdef ENGLISH
#define CHANGE		'C'
#define INQUIRE		'I'
#define EXITOPT		'E'
#define	NEXT		'N'
#define	PREV		'P'

#define	YES		'Y'
#define NO		'N'
#define SCREENEDIT	'S'
#define	LINEEDIT	'L'
#define HEADEREDIT	'H'
#define DELITEM		'D'
#define REACTITEM	'R'
#define	CANCEL		'C'

#define ACTIVE		"ACT"
#define DELETED		"DEL"
#define	WEEKEND		'W'
#else
#define CHANGE		'C'
#define INQUIRE		'I'
#define EXITOPT		'F'
#define	NEXT		'S'
#define	PREV		'P'

#define	YES		'O'
#define NO		'N'
#define SCREENEDIT	'S'
#define	LINEEDIT	'L'
#define HEADEREDIT	'H'
#define DELITEM		'D'
#define REACTITEM	'R'
#define	CANCEL		'A'

#define ACTIVE		"ACT"
#define DELETED		"ELI"
#define	WEEKEND		'W'
#endif

#define FOUND		0
#define NOTFOUND	1
#define NO_CHANGE	2

/* PROFOM Releted declarations */

#define	SCR_NAME	"mon_att"	/* PROFOM screen Name */

/* PROFOM Screen STH file */

/* Field PROFOM numbers */

#define FN_FLD		400	/* Fn: */

#define KEY_START	500	/* Key Start Field */
#define KEY_END		600	/* Key End Field */
#define CHG_FLD		700

#define HDR_ST_FLD	1100	/* Desc. Field */
#define HDR_END_FLD	1500	/* Units/Year Field */

#define NAME_FLD	900	/* Description field */
#define STAT_FLD	1000	/* Description field */
#define MONTH_FLD	1300	/* Description field */

#define CODE_ST_FLD	1700	/* Units/Year Field */
#define CODE_END_FLD	4700	/* Units/Year Field */

#define PAGE_FLD	1700	/* Page# Field */
#define TEACH_FLD	4800
#define	END_FLD		5100	/* Last Field of the screen */

/* number of days in months */

short	d_month[12] = { 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 };

char	month[12][4] = { "JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG",
			"SEP", "OCT", "NOV", "DEC" };

#define	JAN	01
#define	JUL	07
#define	DEC	12

/* area.sth - header for C structure generated by PROFOM EDITOR */

typedef struct	{

	char	s_pgname[11];	/* 100 STRING X(10) */
	long	s_rundate;	/* 300 DATE YYYYFMMFDD */
	char	s_fn[2];	/* 400 STRING X */
	char	s_emp[13];	/* 500 STRING X(6) */
	short	s_mth;		/* 600 NUMERIC 99 */
	short	s_field;	/* 600 NUMERIC 99 */

	char	s_name[41];	/* 900 STRING X(20) */
	char	s_status[5];	/* 900 STRING X(20) */
	double	s_bal_sick;	/* 1100 NUMERIC 999.99 */
	double	s_bal_vac;	/* 1100 NUMERIC 999.99 */
	char	s_month[5];	/* 1000 STRING X(6) */
	char	s_att[32];	/* 1000 STRING X(6) */
	double	s_sick_bk;	/* 1200 NUMERIC 999.99 */

	char	s_day[31][4];	/* 900 STRING X(20) */
	char	s_repl[13];
	char	s_repl_name[31];

	char	s_mesg[78];	/* 4300 STRING X(77) */
	char	s_resp[2];	/* 4400 STRING X */
} s_struct;

static	s_struct  s_sth,image;	/* PROFOM Screen Structure */
static	struct  stat_rec  sr;		/* PROFOM status rec */

static	char 	e_mesg[200];  		/* dbh will return err msg in this */

static	int	change_code;

int	Validation() ;
int	WindowHelp() ;

int	Argc;
char	**Argv;

static	Emp_at_his	att_his,	 pre_att_his;
static	Att	att;
static	Emp	emp_rec;
static	Barg_unit	barg_unit;
static	Pay_param	pay_param;
static	Position	position;
static	double	non_sen_days;
static	double	real_bal_sick;
static	int	mode;
static	int	check_dates;
static	double	att_perc[32];

void	free() ;
char	*malloc() ;

main(argc,argv)
int argc;
char *argv[];
{
	int 	retval;

	/* These two are passed to execute() when it is called */
	Argc = argc;
	Argv = argv;

	retval = Initialize(argc,argv);	/* Initialization routine */

	if (retval == NOERROR) retval = Process();

	CloseRtn();			/* return to menu */
	if (retval != NOERROR) exit(-1);
	exit(0);
}

/*-------------------------------------------------------------------*/
/* Initialize PROFOM */

Initialize(argc, argv)
int	argc ;
char	*argv[] ;
{
	int	err ;

	/*
	*	Initialize DBH Environment
	*/
	strncpy(SYS_NAME,SYSTEM,50);	/* Sub system name */
	strncpy(CHNG_DATE,MOD_DATE,10);	/* Modification Date */

	proc_switch(argc, argv, MAINFL) ; 	/* Process Switches */

	/*
	*	Initialize PROFOM & Screen
	*/
	strcpy(sr.termnm,terminal);	/* Copy Terminal Name */
	fomin(&sr);
	ret(err_chk(&sr)) ;		/* Check for PROFOM Error */
	fomcf(1,1);			/* Enable Snap screen option */

	err = InitScreen() ;		/* Initialize Screen */
	if(NOERROR != err) return(err) ;

	return(NOERROR) ;
}	/* Initialize() */

/*--------------------------------------------------------------------------*/
/* Close nessary files and environment before exiting program               */

CloseRtn() 
{
	/* Set terminal back to normal mode from PROFOM */
	fomcs();
	fomrt();

	close_dbh();	/* Close files */

	return(NOERROR);
}	/* CloseRtn() */
/*----------------------------------------------------------------*/
/* Initialize screen before going to process options */

InitScreen()
{
	int	err ;

	/* move screen name to Profom status structure */
	strcpy(sr.scrnam,NFM_PATH);
	strcat(sr.scrnam,SCR_NAME) ;

	strcpy(s_sth.s_pgname,PROG_NAME);

	s_sth.s_rundate = get_date();	/* get Today's Date in YYYYMMDD format*/
	s_sth.s_field = HV_SHORT ;
	s_sth.s_mesg[0] = HV_CHAR ;
	s_sth.s_resp[0] = HV_CHAR ;

	/* Move High Values to data fields and Display the screen */
	err = ClearScreen() ;
	if(NOERROR != err) return(err) ;

	return(NOERROR) ;
}	/* InitScreen() */
/*-------------------------------------------------------------------*/
/* Get Option from user and call corresponding function */

Process()
{
	int err;

	for( ; ; ){

		/* Get the Fn: option from the user */
		if((err = ReadFunction()) != NOERROR) return(err) ;

		err = ProcFunction() ;	/* Process Function */

		if(QUIT == err)		return(NOERROR) ;    /* Exit */
		if(NOACCESS == err)	fomen(e_mesg);	     /* security */
		if(PROFOM_ERR == err)	return(PROFOM_ERR);  /* PROFOM ERROR */
		if(DBH_ERR == err) {
			DispError((char *)&s_sth,e_mesg);
#ifdef ENGLISH
			sprintf(e_mesg,"%s %d Dberror: %d Errno: %d",
				"System Error... Iserror:",
				iserror, dberror, errno);
#else
			sprintf(e_mesg,"%s %d Dberror: %d Errno: %d",
				"Erreur du systeme... Iserror:",
				iserror, dberror, errno);
#endif
			DispError((char *)&s_sth,e_mesg);
			return(DBH_ERR); /* DBH ERROR */
		}
	}      /*   end of the for( ; ; )       */
}	/* Process() */
/*----------------------------------------------------------------*/
/* Display the Function (Fn:) options and get the option from the user */

ReadFunction()
{
	/* Display Fn: options */
#ifdef ENGLISH
	fomer("C(hange), I(nquire), N(ext), P(rev), E(xit)");
#else
	fomer("C(hanger), I(nterroger), S(uivant), P(recedent), F(in)");
#endif
	/* Read Fn: field to get the option */
	sr.nextfld = FN_FLD ;
	fomrf( (char *)&s_sth );
	ret(err_chk(&sr));	/* Check for PROFOM error */

	return(NOERROR) ;
}	/* ReadFunction() */
/*----------------------------------------------------------------*/
/* Process the user selected Fn: option */

ProcFunction()
{
	int retval;

	switch (s_sth.s_fn[0]) {
	case CHANGE  :			/* CHANGE */
		CHKACC(retval,UPDATE,e_mesg);
		mode = UPDATE;
		return( Change() ) ;
	case INQUIRE  :			/* Inquire */
		CHKACC(retval,BROWSE,e_mesg);
		mode = BROWSE;
		return( Inquire() ) ;
	case NEXT  :			/* Next */
		CHKACC(retval,BROWSE,e_mesg);
		return( Next(FORWARD) ) ;
	case PREV  :			/* Previous */
		CHKACC(retval,BROWSE,e_mesg);
		return( Next(BACKWARD) ) ;
	case EXITOPT  :			/* Exit */
		return( QUIT ) ;
	}  /*   end of the switch statement */

	return(retval);
}	/* ProcFunction() */
/*-----------------------------------------------------------------------*/
/* Change. Students Study halls and update the files if a day/semester   */
/* is changed to NO delete record.			  		 */
/*-----------------------------------------------------------------------*/
Change()
{
	int	err ;

	err = SelectRecord(UPDATE) ;
	if(NOERROR != err) return(err);

	for( ; ; ) {
		err = ConfirmItems() ;
		if(err != YES) {
			roll_back(e_mesg);
			break;
		}
		err = commit(e_mesg);
		if(err < 0) {
			fomer(e_mesg);
			get();
			roll_back(e_mesg);
			break;
		}
		err = DeleteOldRecords();
		if(err < 0) {
			fomer(e_mesg);
			get();
			roll_back(e_mesg);
			break;
		}
		err = WriteRecords(ADD) ;
		if(err==NOERROR) break;
		if(err==LOCKED) {
			roll_back(e_mesg) ;
			continue;
		}
		if (err < 0) {
			roll_back(e_mesg);
			return(err) ;
		}
	}

	return(NOERROR) ;
}	/* Change() */
/*-----------------------------------------------------------------------*/ 
/* Write the Area record to the file.			 		 */ 
/*-----------------------------------------------------------------------*/ 
WriteRecords(mode)
int	mode;
{
	int	retval;
	int	i;
	long	temp_date, year;

	scpy((char *)&pre_att_his,(char *)&att_his,sizeof(att_his));

	if(pay_param.pr_st_mth == 1)
		temp_date = pay_param.pr_cal_st_dt;
	if(pay_param.pr_st_mth == 2)
		temp_date = pay_param.pr_fisc_st_dt;
	if(pay_param.pr_st_mth == 3)
		temp_date = pay_param.pr_schl_st_dt;

	if(s_sth.s_mth < ((temp_date/100)%100))
		year = (temp_date / 10000) + 1;
	else
		year = (temp_date / 10000);

	temp_date = (year*10000) + (s_sth.s_mth * 100);
	
	for(i=0 ; i<31 ; i++){
	  if(mode == P_DEL && i != (s_sth.s_field-1)){
		if(i > (s_sth.s_field-1)) break;
		continue;
	  }
	  if(s_sth.s_day[i][0] != '\0'){
		strcpy(att.at_code,s_sth.s_day[i]);

		retval = get_att(&att,BROWSE,1,e_mesg);
		if(retval < 0) 
			continue;

		strcpy(att_his.eah_numb,s_sth.s_emp);

		att_his.eah_date = temp_date +(i + 1); 
		strcpy(att_his.eah_code,s_sth.s_day[i]);

		retval = get_emp_at(&att_his,UPDATE,0,e_mesg) ;
		if(mode == P_DEL && retval == UNDEF)
			continue;
/*		if(retval == NOERROR && mode != P_DEL)
			continue; */
		if(retval < 0 && retval != UNDEF) {
			DispError((char *)&s_sth,e_mesg);
			roll_back(e_mesg);
			return(retval);
		}
		strcpy(att_his.eah_teach,s_sth.s_repl);
		if(att_his.eah_teach[0] == HV_CHAR)
			att_his.eah_teach[0] = '\0';
		if(att_perc[i] != 0)
			att_his.eah_perc = att_perc[i];
		else
			att_his.eah_perc = emp_rec.em_sen_perc;

		retval = put_emp_at(&att_his,mode,e_mesg) ;
		if(retval < 0) {
			DispError((char *)&s_sth,e_mesg);
			roll_back(e_mesg);
			return(retval);
		}
		retval = commit(e_mesg) ;
		if(retval < 0) {
			DispError((char *)&s_sth,"ERROR: Saving Records"); 
			DispError((char *)&s_sth,e_mesg);
			roll_back(e_mesg);
			return(retval);
		}
	  }
	}
	seq_over(EMP_ATT);

	return(NOERROR);
}
/*-----------------------------------------------------------------------*/
static
DeleteOldRecords()
{
	int	retval;
	long	temp_date, year, end_date, start_date;

	if(pay_param.pr_st_mth == 1)
		temp_date = pay_param.pr_cal_st_dt;
	if(pay_param.pr_st_mth == 2)
		temp_date = pay_param.pr_fisc_st_dt;
	if(pay_param.pr_st_mth == 3)
		temp_date = pay_param.pr_schl_st_dt;

	if(s_sth.s_mth < ((temp_date/100)%100))
		year = (temp_date / 10000) + 1;
	else
		year = (temp_date / 10000);

	temp_date = (year*10000) + (s_sth.s_mth * 100);
	
	start_date = temp_date + 1;

	end_date = temp_date + d_month[s_sth.s_mth - 1];
	strcpy(att_his.eah_numb,s_sth.s_emp);

	for(;;){
		att_his.eah_date = start_date; 
		flg_reset(EMP_ATT);

		retval = get_n_emp_at(&att_his,UPDATE,0,FORWARD,e_mesg) ;
		if(retval < 0) {
			if(retval = EFL) 	break;
			DispError((char *)&s_sth,e_mesg);
			return(retval);
		}
		if(att_his.eah_date > end_date ||
		   strcmp(att_his.eah_numb,s_sth.s_emp) != 0) {
			break;
		}

		retval = put_emp_at(&att_his,P_DEL,e_mesg) ;
		if(retval < 0) {
			DispError((char *)&s_sth,e_mesg);
			roll_back(e_mesg);
			return(retval);
		}

		retval = commit(e_mesg) ;
		if(retval < 0) {
			DispError((char *)&s_sth,"ERROR: Deleting Old Records");
			DispError((char *)&s_sth,e_mesg);
			roll_back(e_mesg);
			return(retval);
		}
	}
	seq_over(EMP_ATT);

	return(NOERROR);
}
/*---------------------------------------------------------------------*/
/* Show Student Student halls base on users input */
Inquire()
{
	int	err ;

	err = SelectRecord(BROWSE) ;
	if(NOERROR != err) return(err) ;

	err = ConfirmItems() ;
	
	return(NOERROR) ;
}	/* Inquire() */
/*---------------------------------------------------------------------*/
/* Show the next or previous Students Study halls */

Next(direction)
int	direction ;
{
	int retval;

	strcpy(emp_rec.em_numb,s_sth.s_emp);
	if (flg_start(EMPLOYEE) != direction) {
		inc_str(emp_rec.em_numb, sizeof(emp_rec.em_numb)-1, 
			direction);
		flg_reset(EMPLOYEE);
	}

	for( ; ; ){
	  retval = get_n_employee(&emp_rec, BROWSE, 0, direction, e_mesg);
#ifndef ORACLE
	  seq_over(EMPLOYEE);
#endif
	  if(ERROR == retval)return(DBH_ERR) ;
	  if(EFL == retval) {
		fomen("No More Records....");
		get();
		return(NOERROR) ;
	  }

	  retval = UsrBargVal(BROWSE,emp_rec.em_numb,emp_rec.em_barg,0,e_mesg);
	  if(retval < 0){
		if(retval == UNDEF){
			fomen(e_mesg);
			get();
			return(ERROR);
		}
	  }
	  else{
		break;
	  }
	}
	strcpy( s_sth.s_emp,emp_rec.em_numb);

	return(ShowScreen());
}	/* Next() */
/*----------------------------------------------------------------------*/
/* Get the Student Study Hall key from user. In ADD mode disable dup buffers, */
/* other modes enable dup buffers and show the current key as a default key */
/*----------------------------------------------------------------------*/
ReadKey()
{
	int	i;
	
	/* In Add mode turn off dup control for key fields.
	   Other modes reverse it */
	SetDupBuffers(KEY_START,KEY_END,1);

#ifdef ENGLISH
	strcpy(s_sth.s_mesg,"Press ESC-F to Go Back to Fn:");
#else
	strcpy(s_sth.s_mesg,"Appuyer sur ESC-F pour retourner a Fn:");
#endif
	DispMesgFld((char *)&s_sth);

	s_sth.s_emp[0] = LV_CHAR;
	s_sth.s_mth = LV_SHORT;

	i = ReadFields((char *)&s_sth,KEY_START, KEY_END,
		Validation, WindowHelp,1) ;
	if(PROFOM_ERR == i || DBH_ERR == i) return(i) ;
	if(RET_USER_ESC == i){
		
		ret( WriteFields((char *)&s_sth,KEY_START, KEY_END) ) ;

		s_sth.s_mesg[0] = HV_CHAR;
		DispMesgFld((char *)&s_sth);

		return(RET_USER_ESC) ;
	}

	s_sth.s_mesg[0] = HV_CHAR;
	DispMesgFld((char *)&s_sth);

	return(NOERROR);
}	/*  ReadKey() */
/*----------------------------------------------------------*/
/* Get the key and show the record */
SelectRecord(mode)
int	mode;
{
	int	err ;

	err = ReadKey();
	if(err != NOERROR) return(err) ;

	err = ShowScreen();
	if(err < 0) {
		return(err);
	}

	return(NOERROR);
}	/* SelectRecord() */
/*------------------------------------------------------------*/
ReadScreen()
{
	int err;

	scpy((char *)&image,(char *)&s_sth,sizeof(image));

	SetDupBuffers(CODE_ST_FLD,END_FLD-200,1); /* Off Dup Control */
	
	InitHdr(LV_CHAR);

	err = ReadFields((char *)&s_sth,CODE_ST_FLD, END_FLD-200,
			Validation, WindowHelp,1) ;
	if(PROFOM_ERR == err || DBH_ERR == err) return(err) ;
	if(RET_USER_ESC == err){
		if(mode == ADD) {
			InitHdr(HV_CHAR);
			ret(WriteFields((char *)&s_sth,CODE_ST_FLD,END_FLD-200));
		}
		else {
		/* When user gives ESC-F while changing fields, assumption is
		* he completed his changes, and remaining fields are same as
		* old. But, at this point STH will be having low values in the 
		* remaining fields. So move the old values form the linked list.
		*/

			err = CopyBack((char *)&s_sth,(char *)&image,
				sr.curfld, END_FLD);
			if(err == PROFOM_ERR) return(err);
		}
		s_sth.s_mesg[0] = HV_CHAR;
		DispMesgFld((char *)&s_sth);

		return(RET_USER_ESC) ;
	}

	return(NOERROR);
}
/*-----------------------------------------------------------*/
ChangeFields()
{
	int	retval ;
	int	fld_no;

	scpy((char *)&image,(char *)&s_sth,sizeof(image));

	SetDupBuffers(CODE_ST_FLD, END_FLD - 200, 1);

	/* Get The Field to Be Modified */
#ifdef	ENGLISH
	strcpy(s_sth.s_mesg,"Enter RETURN to Terminate Edit");
#else
	strcpy(s_sth.s_mesg,"Appuyer sur RETURN pour terminer l'ajustement");
#endif
	DispMesgFld((char *)&s_sth); ;
        
     	for (; ;) {
		s_sth.s_field = LV_SHORT;
		retval = ReadFields((char *)&s_sth,CHG_FLD,CHG_FLD,
			(int (*)())NULL,(int (*)())NULL, 1);

		if (retval < 0) return(-1);
		if (retval == RET_USER_ESC) break;	/* User enter ESC-F */

       		if (s_sth.s_field == 0 ) break;  /* Finished changing fields */

		fld_no = CODE_ST_FLD + (100 * (s_sth.s_field-1));
		if(s_sth.s_day[s_sth.s_field-1][0] == 'W' && check_dates == 1){
			fomer("Day is a Weekend - Cannot Edit Field");
			continue;
		}
		retval = ReadFields((char *)&s_sth,fld_no, fld_no,
			Validation, WindowHelp,1) ;
		if(PROFOM_ERR == retval || DBH_ERR == retval) return(retval) ;
		if(RET_USER_ESC == retval){
		/* When user gives ESC-F while changing fields, assumption is
		* he completed his changes, and remaining fields are same as
		* old. But, at this point STH will be having low values in the 
		* remaining fields. So move the old values form the linked list.
		*/
			retval = CopyBack((char *)&s_sth,(char *)&image,
				sr.curfld, END_FLD);
			if(retval == PROFOM_ERR) return(retval);

     			s_sth.s_field = HV_SHORT ;
			if ( WriteFields((char *)&s_sth,CHG_FLD, CHG_FLD) < 0 ) 
				return(-1);

		     	s_sth.s_mesg[0] = HV_CHAR ;
		     	DispMesgFld((char *)&s_sth);
			return(RET_USER_ESC) ;
		}

	}
     	s_sth.s_field = HV_SHORT ;
	if ( WriteFields((char *)&s_sth,CHG_FLD, CHG_FLD) < 0 ) return(-1);

     	s_sth.s_mesg[0] = HV_CHAR ;
     	DispMesgFld((char *)&s_sth);

	if(SetDupBuffers(CODE_ST_FLD, END_FLD-200, 0)<0) return(PROFOM_ERR);

	return(NOERROR);
}
/*------------------------------------------------------------*/
ShowScreen() 
{
	int	retval;

	retval = ClearScreen() ;
	if(NOERROR != retval) return(retval) ;
	
	strcpy(s_sth.s_name, emp_rec.em_last_name);
	strcat(s_sth.s_name, ", ");
	strcat(s_sth.s_name, emp_rec.em_first_name);
	strcat(s_sth.s_name, " ");
	strcat(s_sth.s_name, emp_rec.em_mid_name);
	s_sth.s_name[30] = '\0';

	strcpy(s_sth.s_status,emp_rec.em_status);

	ShowAtt();

	ret( WriteFields((char *)&s_sth, KEY_START, END_FLD-200) );
	
	return(NOERROR);
}
/*----------------------------------------------------------------*/
/* Set Duplication buffers for fields 				  */
SetDupBuffers( firstfld, lastfld, value )
int	firstfld, lastfld;	/* field numbers range */
int	value;			/* ENABLE or DISABLE */
{
	int i ;

	for( i=firstfld; i<=lastfld; i+=100 )
		fomca1( i, 19, value);
	if( value==0 )
		return(0);
	sr.nextfld = firstfld;
	sr.endfld = lastfld;
	fomud( (char *)&s_sth );
	ret( err_chk(&sr) );

	return( 0 );
}
/*----------------------------------------------------------------*/
/* Validation function() for Key and Header fields when PROFOM returns
  RET_VAL_CHK */

Validation()
{
	int	retval;
	int	i, item_no, fld_no;

	if(sr.curfld == TEACH_FLD)
		fld_no = sr.curfld;
	else{
		if(sr.curfld >= CODE_ST_FLD && sr.curfld < TEACH_FLD){
			fld_no = CODE_ST_FLD;
			item_no = (sr.curfld - fld_no)/100;
		}
		else{
			fld_no = sr.curfld;
		}
	}

	switch(fld_no){
	case KEY_START:
		Right_Justify_Numeric(s_sth.s_emp,
			sizeof(s_sth.s_emp)-1);
		strcpy(emp_rec.em_numb,s_sth.s_emp);

		retval = get_employee(&emp_rec,BROWSE,0,e_mesg);
		if(retval < 0) {
			fomer("Employee Number Does not Exist");
			s_sth.s_emp[0] = LV_CHAR;
			return(ERROR);
		}

		retval = UsrBargVal(mode,emp_rec.em_numb,emp_rec.em_barg,1,e_mesg);
		if(retval < 0){
			DispError((char *)&s_sth,e_mesg);
		  	s_sth.s_emp[0] = LV_CHAR;
			return(-1);
		}
		strcpy(position.p_code,emp_rec.em_pos);
				
		retval = get_position(&position,BROWSE,0,e_mesg);
		if(retval < 0){
			fomer("Error Reading Employee's Position Record");
		  	s_sth.s_emp[0] = LV_CHAR;
			return(ERROR);
		}
 		if(strcmp(position.p_type,"PT")!=0 &&
		   strcmp(position.p_type,"FT")!=0){
			fomer("Employee is not Permanent");
		  	s_sth.s_emp[0] = LV_CHAR;
			return(ERROR);
		}
		strcpy(s_sth.s_name, emp_rec.em_last_name);
		strcat(s_sth.s_name, ", ");
		strcat(s_sth.s_name, emp_rec.em_first_name);
		strcat(s_sth.s_name, " ");
		strcat(s_sth.s_name, emp_rec.em_mid_name);
		s_sth.s_name[31] = '\0';

		strcpy(barg_unit.b_code,emp_rec.em_barg);
		barg_unit.b_date = get_date();
		flg_reset(BARG);

		retval = get_n_barg(&barg_unit,BROWSE,0,BACKWARD,e_mesg);
		if(retval < 0 || strcmp(barg_unit.b_code,emp_rec.em_barg)!=0){
			DispError((char *)&s_sth,"Error Reading Bargaining Unit File");
			return(-1);
		}
		seq_over(BARG);

		strcpy(s_sth.s_status,emp_rec.em_status);
		check_dates = 1;

		/* Saint John Codes */	
		if(strcmp(emp_rec.em_barg,"    03")==0)
			check_dates = 0; 

		ret(WriteFields((char *)&s_sth,NAME_FLD,STAT_FLD));
		break;
	case KEY_END:
		if(s_sth.s_mth <= 0 || s_sth.s_mth > 12){
			fomer("Invalid Month - Must be 1 - 12");
			s_sth.s_mth = LV_SHORT;
			return(ERROR);
		}

		break;

	case CODE_ST_FLD :
		if(s_sth.s_day[item_no][0] == 'W'){
			retval = Get_Weekend(item_no);
			ret( WriteFields((char *)&s_sth,KEY_START,HDR_END_FLD));

			ret( WriteFields((char *)&s_sth, sr.curfld, sr.curfld));
			if(s_sth.s_day[item_no][0] == 'W')	
				break;
			else{
				fomer("Day is Not a Weekend");	
				s_sth.s_day[item_no][0] = LV_CHAR;
				return(ERROR);
			}
		}
		change_code = 0;
		Right_Justify_Numeric(s_sth.s_day[item_no],
			sizeof(s_sth.s_day[item_no])-1);
		if((strncmp(image.s_day[item_no],
		   s_sth.s_day[item_no],strlen(image.s_day[item_no]))==0)&& 
		  (strncmp(image.s_day[item_no],
		   s_sth.s_day[item_no],strlen(s_sth.s_day[item_no]))==0)) {
			sr.curfld += 100;
			break;
		}

		ret( WriteFields((char *)&s_sth, MONTH_FLD, MONTH_FLD+100) );
		if(s_sth.s_day[item_no][0] == '\0'){
		  if(image.s_day[item_no][0] == 'W'){
			retval = Get_Weekend(item_no);
			if(retval < 0)	return(retval);

			ret( WriteFields((char *)&s_sth,KEY_START,HDR_END_FLD));

			ret( WriteFields((char *)&s_sth, sr.curfld, sr.curfld));
			break;
		  }
		  else{
			strcpy(att.at_code,image.s_day[item_no]);
			retval = get_att(&att,BROWSE,1,e_mesg);
			if(retval < 0) {
				fomer("Old Attendance Code Does not Exist");
				return(ERROR);
			}
			UpdtHdr(item_no,P_DEL);
			sr.curfld += 100;
			break;
		  }	
		}
		else {
			strcpy(att.at_code,s_sth.s_day[item_no]);
			retval = get_att(&att,BROWSE,1,e_mesg);
			if(retval < 0) {
				fomer("Attendance Code Does not Exist");
				s_sth.s_day[item_no][0] = LV_CHAR;
				return(ERROR);
			}
			if(image.s_day[item_no][0] == '\0' ||
			   image.s_day[item_no][0] == 'W') {
				retval = UpdtHdr(item_no,ADD);
				if(retval < 0) {
					fomer("Attendance Code Already Exists for this Date");
					s_sth.s_day[item_no][0] = LV_CHAR;
					return(ERROR);
				}
			}
			else {
				change_code = 1;
				strcpy(att.at_code,image.s_day[item_no]);
				retval = get_att(&att,BROWSE,1,e_mesg);
				if(retval < 0) {
					fomer("Attendance Code Does not Exist");
					return(ERROR);
				}
				UpdtHdr(item_no,P_DEL);
				strcpy(att.at_code,s_sth.s_day[item_no]);
				retval = get_att(&att,BROWSE,1,e_mesg);
				if(retval < 0) {
					fomer("Attendance Code Does not Exist");
					s_sth.s_day[item_no][0] = LV_CHAR;
					return(ERROR);
				}
				UpdtHdr(item_no,UPDATE);
			}
		}
		strcpy(image.s_day[item_no],s_sth.s_day[item_no]);
		break;

	case TEACH_FLD:
		if(s_sth.s_repl[0] == '\0'){
			s_sth.s_repl[0] = HV_CHAR;
			s_sth.s_repl_name[0] = HV_CHAR;
			break;
		}
		Right_Justify_Numeric(s_sth.s_repl,
			sizeof(s_sth.s_repl)-1);
		strcpy(emp_rec.em_numb,s_sth.s_repl);

		retval = get_employee(&emp_rec,BROWSE,0,e_mesg);
		if(retval < 0) {
			fomer("Employee Number Does not Exist");
			s_sth.s_repl[0] = LV_CHAR;
			return(ERROR);
		}

		retval = UsrBargVal(mode,emp_rec.em_numb,emp_rec.em_barg,1,e_mesg);
		if(retval < 0){
			DispError((char *)&s_sth,e_mesg);
		  	s_sth.s_repl[0] = LV_CHAR;
			return(-1);
		}
		strcpy(e_mesg,emp_rec.em_first_name);
		strcat(e_mesg," ");
		strcat(e_mesg,emp_rec.em_last_name);
		strncpy(s_sth.s_repl_name, e_mesg,30);
		ret( WriteFields((char *)&s_sth, TEACH_FLD, END_FLD-200) );
		break;

	default:
#ifdef ENGLISH
		sprintf(e_mesg,"No Validity Check for Field#  %d",sr.curfld);
		
#else
		sprintf(e_mesg,"Pas de controle de validite pour le Champ#  %d",sr.curfld);
#endif
		fomen(e_mesg);
		get();
		return(ERROR) ;
	}	/* Switch sr.curfld */

	return(NOERROR) ;
}	/* Validation() */
/*----------------------------------------------------------------*/
/* Show Help Windows, if applicable, when user gives ESC-H in key
   and header fields */

WindowHelp()
{
	int	retval ;
	int	item_no, fld_no;
	short	reccod;
	int	i;

	if(sr.curfld == TEACH_FLD)
		fld_no = sr.curfld;
	else{
		if(sr.curfld >= CODE_ST_FLD && sr.curfld < TEACH_FLD){
			fld_no = CODE_ST_FLD;
			item_no = (sr.curfld - fld_no)/100;
		}
		else{
			fld_no = sr.curfld;
		}
	}

	switch(fld_no){
	case KEY_START:
		retval = emp_hlp(s_sth.s_emp,7,13);
		if(retval == DBH_ERR) return(retval);
		if(retval >= 0) redraw();
		if(retval == 0) return(ERROR);
		if(retval < 0) return(ERROR);
		Right_Justify_Numeric(s_sth.s_emp,
			sizeof(s_sth.s_emp)-1);
		strcpy(emp_rec.em_numb,s_sth.s_emp);

		retval = get_employee(&emp_rec,BROWSE,0,e_mesg);
		if(retval < 0) {
			fomer("Employee Number Does not Exist");
			s_sth.s_emp[0] = LV_CHAR;
			return(ERROR);
		}
		strcpy(position.p_code,emp_rec.em_pos);
				
		retval = get_position(&position,BROWSE,0,e_mesg);
		if(retval < 0){
			fomer("Error Reading Employee's Position Record");
		  	s_sth.s_emp[0] = LV_CHAR;
			return(ERROR);
		}
 		if(strcmp(position.p_type,"PT")!=0 &&
		   strcmp(position.p_type,"FT")!=0){
			fomer("Employee is not Permanent");
		  	s_sth.s_emp[0] = LV_CHAR;
			return(ERROR);
		}

		strcpy(s_sth.s_name, emp_rec.em_last_name);
		strcat(s_sth.s_name, ", ");
		strcat(s_sth.s_name, emp_rec.em_first_name);
		strcat(s_sth.s_name, " ");
		strcat(s_sth.s_name, emp_rec.em_mid_name);
		s_sth.s_name[31] = '\0';

		strcpy(barg_unit.b_code,emp_rec.em_barg);
		barg_unit.b_date = get_date();
		flg_reset(BARG);

		retval = get_n_barg(&barg_unit,BROWSE,0,BACKWARD,e_mesg);
		if(retval < 0 || strcmp(barg_unit.b_code,emp_rec.em_barg)!=0){
			DispError((char *)&s_sth,"Error Reading Bargaining Unit File");
			return(-1);
		}
		seq_over(BARG);

		strcpy(s_sth.s_status,emp_rec.em_status);
		check_dates = 1;

		/* Saint John Codes */	
		if(strcmp(emp_rec.em_barg,"    03")==0)
			check_dates = 0; 

		ret(WriteFields((char *)&s_sth,NAME_FLD,STAT_FLD));
		break;

	case CODE_ST_FLD:
		change_code = 0;
		retval = att_hlp(s_sth.s_day[item_no],7,13);
		if(retval == DBH_ERR) return(retval);
		if(retval >= 0) redraw();
		if(retval == 0) return(ERROR);
		if(retval < 0) return(ERROR);
		if((strncmp(image.s_day[item_no],
		   s_sth.s_day[item_no],strlen(image.s_day[item_no]))==0)&& 
		  (strncmp(image.s_day[item_no],
		   s_sth.s_day[item_no],strlen(s_sth.s_day[item_no]))==0)) {
			sr.curfld += 100;
			break;
		}
		ret( WriteFields((char *)&s_sth, MONTH_FLD, MONTH_FLD+100) );
		ret( WriteFields((char *)&s_sth, sr.curfld, sr.curfld) );
		if(s_sth.s_day[item_no][0] == '\0') {
		  if(s_sth.s_day[item_no][0] == 'W'){
			retval = Get_Weekend(item_no);
			if(retval < 0)	return(retval);
			ret( WriteFields((char *)&s_sth,KEY_START,HDR_END_FLD));
			ret( WriteFields((char *)&s_sth, sr.curfld, sr.curfld));
			break;
		  }
		  else{
			strcpy(att.at_code,image.s_day[item_no]);
			retval = get_att(&att,BROWSE,1,e_mesg);
			if(retval < 0) {
				fomer("Old Attendance Code Does not Exist");
				s_sth.s_day[item_no][0] = LV_CHAR;
				return(ERROR);
			}
			UpdtHdr(item_no,P_DEL);
		  }
		}
		else {
			strcpy(att.at_code,s_sth.s_day[item_no]);
			retval = get_att(&att,BROWSE,1,e_mesg);
			if(retval < 0) {
				fomer("Attendance Code Does not Exist");
				return(ERROR);
			}
			if(image.s_day[item_no][0] == '\0') {
				UpdtHdr(item_no,ADD);
			}
			else {
			  if(image.s_day[item_no][0] == '\0' ||
			     image.s_day[item_no][0] == 'W') {
				retval = UpdtHdr(item_no,ADD);
				if(retval < 0) {
					fomer("Attendance Code Already Exists for this Date");
					s_sth.s_day[item_no][0] = LV_CHAR;
					return(ERROR);
				}
			  }
			  else {
				change_code = 1;
				strcpy(att.at_code,image.s_day[item_no]);
				retval = get_att(&att,BROWSE,1,e_mesg);
				if(retval < 0) {
					fomer(
					  "Old Attendance Code Does not Exist");
					return(ERROR);
				}
				UpdtHdr(item_no,P_DEL);
				strcpy(att.at_code,s_sth.s_day[item_no]);
				retval = get_att(&att,BROWSE,1,e_mesg);
				if(retval < 0) {
					fomer("Attendance Code Does not Exist");
					s_sth.s_day[item_no][0] = LV_CHAR;
					return(ERROR);
				}
				UpdtHdr(item_no,UPDATE);
			  }
			}
		}
		strcpy(image.s_day[item_no],s_sth.s_day[item_no]);
		sr.curfld += 100;
		break;
	case TEACH_FLD:
		retval = emp_hlp(s_sth.s_repl,7,13);
		if(retval == DBH_ERR) return(retval);
		if(retval >= 0) redraw();
		if(retval == 0) return(ERROR);
		if(retval < 0) return(ERROR);
		Right_Justify_Numeric(s_sth.s_repl,
			sizeof(s_sth.s_repl)-1);
		strcpy(emp_rec.em_numb,s_sth.s_repl);

		retval = get_employee(&emp_rec,BROWSE,0,e_mesg);
		if(retval < 0) {
			fomer("Employee Number Does not Exist");
			s_sth.s_repl[0] = LV_CHAR;
			return(ERROR);
		}

		strcpy(e_mesg,emp_rec.em_first_name);
		strcat(e_mesg," ");
		strcat(e_mesg,emp_rec.em_last_name);
		strncpy(s_sth.s_repl_name, e_mesg,30);
		ret( WriteFields((char *)&s_sth, TEACH_FLD, END_FLD-200) );
		break;

	default :
		fomer("No Help Window for This Field");
	}	/* Switch sr.curfld */

	return(NOERROR) ;
}	/* HdrAndKeyWindowHelp() */
/*-----------------------------------------------------------------------*/
/* Take the confirmation from user for the items part of the screen      */
/*-----------------------------------------------------------------------*/
ConfirmItems()
{
	int	err ;

	/* Options:
	     YSLNPC
	*/

	for( ; ; ) {
	    if(s_sth.s_fn[0] != INQUIRE) {
#ifdef ENGLISH
			err = GetOption((char *)&s_sth,
		"Y(es), S(creen Edit), L(ine Edit), C(ancel)"
		,"YSLC");
#else
			err = GetOption((char *)&s_sth,
		"O(ui), S(creen edit), L(ine edit), A(nnuler)"
		,"OSLA");
#endif
	    }
	    else {
#ifdef ENGLISH
			err = GetOption((char *)&s_sth,
		"Y(es)","Y");
#else
			err = GetOption((char *)&s_sth,
		"O(ui)" ,"O");
#endif
	    }
	    switch(err) {
	    case  YES  :
		return(YES);
	    case  SCREENEDIT:
		err = ReadScreen();
		break;
	    case  LINEEDIT  :
		err = ChangeFields();
		break ;
	    case  CANCEL :
#ifdef ENGLISH
		err = GetOption((char *)&s_sth,
				"Confirm the Cancel (Y/N)?", "YN") ;
#else
		err = GetOption((char *)&s_sth,
				"Confirmer l'annulation (O/N)?", "ON") ;
#endif
		if(err == YES) return(CANCEL) ;
		break ;
	    }	/* switch err */

	    if(err == PROFOM_ERR) return(err) ;
	    if(err == DBH_ERR) return(err) ;
	}	/* for(; ; ) */
}	/* ConfirmItems() */
/*------------------------------------------------------------------------*/
/* Move High values to all data fields and clear the screen */

ClearScreen()
{
	int	i;

	s_sth.s_name[0] = HV_CHAR;
	s_sth.s_status[0] = HV_CHAR;
	s_sth.s_bal_sick = HV_DOUBLE;
	s_sth.s_bal_vac = HV_DOUBLE;
	s_sth.s_month[0] = HV_CHAR;
	strcpy(s_sth.s_att, "                               ");
	s_sth.s_sick_bk = HV_DOUBLE;

	InitHdr(HV_CHAR);

	strcpy(s_sth.s_repl,"            ");
	s_sth.s_repl[0] = HV_CHAR;
	s_sth.s_repl_name[0] = HV_CHAR;

	ret( WriteFields((char *)&s_sth,HDR_ST_FLD, END_FLD-200) );

	return(NOERROR);
}	/* ClearScreen() */
/*-------------------------------------------------------------------------*/
InitHdr(t_char)
char	t_char;
{
	int i, j;

	if(t_char != HV_CHAR){
		i = s_sth.s_mth - 1;
		for(j=0; j< d_month[i]; j++){
		  if(s_sth.s_day[j][0] != WEEKEND || check_dates == 0)
			s_sth.s_day[j][0] = t_char;
		}
	}
	else{
		for(j=0; j< 32; j++)
			s_sth.s_day[j][0] = t_char;
	}
	s_sth.s_repl[0] = t_char;
	s_sth.s_repl_name[0] = t_char;

	return(NOERROR);
}
/*--------------------------------------------------------------------
 ShowAtt()     - this routine reads the attendance information and   
   		 copies it onto the screen
--------------------------------------------------------------------*/
int
ShowAtt()
{
	int 	retval, i, j, curr_day, curr_month;

 	retval = get_pay_param(&pay_param,BROWSE,1,e_mesg);
	if(retval < 0) {
  		DispError((char *)&s_sth,e_mesg);
		return(retval);
	}

	InitHdr(LV_CHAR);

	i = s_sth.s_mth - 1;
	strcpy(s_sth.s_month, month[i]);

	/* Check for leap year	*/

	if(((get_date() / 1000) % 4 != 0) && i == 1){
		strncpy(s_sth.s_att, 
		"...............................",d_month[i]+1);
	}
	else
		strncpy(s_sth.s_att, 
		"...............................",d_month[i]);

	j = d_month[i];
	for( ;j< 31; j++){
		s_sth.s_day[j][0] = HV_CHAR;
		att_perc[j] = 0;
	}

	Get_day();

	retval = CalcBal();
	real_bal_sick = s_sth.s_bal_sick;
	if(s_sth.s_bal_sick > barg_unit.b_sick_max)
		s_sth.s_bal_sick = barg_unit.b_sick_max;

	s_sth.s_sick_bk = emp_rec.em_sic_bk;
	
	strcpy(att_his.eah_numb, s_sth.s_emp);
	if(pay_param.pr_st_mth == 1){
		curr_month = ((pay_param.pr_cal_st_dt/100) % 100);
		if(curr_month <= s_sth.s_mth)
		   att_his.eah_date = (pay_param.pr_cal_st_dt / 10000) *
			10000 + (s_sth.s_mth * 100);
		else
		   att_his.eah_date = (pay_param.pr_cal_st_dt / 10000 + 1) *
			10000 + (s_sth.s_mth * 100);
	}
	if(pay_param.pr_st_mth == 2){
		curr_month = ((pay_param.pr_fisc_st_dt/100) % 100);
		if(curr_month <= s_sth.s_mth)
		   att_his.eah_date = (pay_param.pr_fisc_st_dt / 10000) *
			10000 + (s_sth.s_mth * 100);
		else
		   att_his.eah_date = (pay_param.pr_fisc_st_dt / 10000 + 1) *
			10000 + (s_sth.s_mth * 100);
	}
	if(pay_param.pr_st_mth == 3){
		curr_month = ((pay_param.pr_schl_st_dt/100) % 100);
		if(curr_month <= s_sth.s_mth)
		   att_his.eah_date = (pay_param.pr_schl_st_dt / 10000) *
			10000 + (s_sth.s_mth * 100);
		else
		   att_his.eah_date = (pay_param.pr_schl_st_dt / 10000 + 1) *
			10000 + (s_sth.s_mth * 100);
	}
	flg_reset(EMP_ATT);

	for(;;){
		retval = get_n_emp_at(&att_his, BROWSE, 0, FORWARD, e_mesg);
		if(retval == EFL ||	
		((strcmp(att_his.eah_numb, s_sth.s_emp)) != 0)){
			break;
		}
		if(retval < 0) {
			fomen(e_mesg);
			get();
			return(-1);
		}
		curr_month = ((att_his.eah_date/100) % 100);
		if(curr_month != s_sth.s_mth) break;

		strcpy(att.at_code, att_his.eah_code);

		retval = get_att(&att,BROWSE,1,e_mesg);
		if(retval < 0)  {
			fomen(e_mesg);
			get();
			return(retval);
		}
 		/* copy the code in the daily attendance record to the
					screen structure */
		curr_day = (att_his.eah_date % 100);

		s_sth.s_att[curr_day - 1] = 
					    att.at_disp_code[0];
		strcpy(s_sth.s_day[curr_day - 1],att.at_code);
		att_perc[curr_day-1] = att_his.eah_perc;

		att_his.eah_date ++;
		att_his.eah_code[0] = '\0';
		flg_reset(EMP_ATT);
	}
	seq_over(EMP_ATT);

	return(NOERROR);
}
/*--------------------------------------------------------------------
 CalcBal()     - this routine reads the attendance information and   
   		 copies it onto the screen
--------------------------------------------------------------------*/
CalcBal()
{
	int 	retval, i;
	double	total, fraction;
	long	dollars;

	s_sth.s_bal_vac = emp_rec.em_vac_ent;
	s_sth.s_bal_sick = emp_rec.em_sic_ent;
	for (i=0; i < 12; i++) {
		total = emp_rec.em_sck_acc[i] * 10;
		dollars = (long)total;
		fraction = total - (double)dollars;
		if(fraction > 0.49)
			dollars += 1;
		s_sth.s_bal_sick += (double)dollars/10;
	}

	strcpy(att_his.eah_numb, emp_rec.em_numb);
	if(pay_param.pr_st_mth == 1){
		att_his.eah_date = pay_param.pr_cal_st_dt;  
	}
	if(pay_param.pr_st_mth == 2){
		att_his.eah_date = pay_param.pr_fisc_st_dt;  
	}
	if(pay_param.pr_st_mth == 3){
		att_his.eah_date = pay_param.pr_schl_st_dt;  
	}
	flg_reset(EMP_ATT);

	for(;;){
		retval = get_n_emp_at(&att_his, BROWSE, 0, FORWARD, e_mesg);

		if(retval == EFL ||		
		   (strcmp(att_his.eah_numb, emp_rec.em_numb)) != 0){
			break;
		}
		if(retval < 0) {
			fomen(e_mesg);
			get();
			return(-1);
		}
		strcpy(att.at_code, att_his.eah_code);

		retval = get_att(&att,BROWSE,1,e_mesg);
		if(retval < 0)  {
			fomen(e_mesg);
			get();
			return(retval);
		}
		if(strcmp(att.at_sick, "Y") == 0){
			s_sth.s_bal_sick -= 
		      		(att.at_units * (att_his.eah_perc/100.0));
		}
		if(strcmp(att.at_vac, "Y") == 0){
		        s_sth.s_bal_vac -= 
		   		(att.at_units * (att_his.eah_perc/100.0));
		}
	}
	seq_over(EMP_ATT);

	return(NOERROR);
}
/*----------------------------------------------------------------*/
/* takes the date entered on the screen and get the corresponding */
/* day's name. i.e. MON, TUE, etc.                                */
/*----------------------------------------------------------------*/
Get_day()
{
	int	remain, month, year;
	long	julian, long_date, end_date;
	short	day;

	if(pay_param.pr_st_mth == 1)
		long_date = pay_param.pr_cal_st_dt;
	if(pay_param.pr_st_mth == 2)
		long_date = pay_param.pr_fisc_st_dt;
	if(pay_param.pr_st_mth == 3)
		long_date = pay_param.pr_schl_st_dt;

	month = (long_date/100)% 100;
	if(month > s_sth.s_mth){
		long_date = long_date/10000 +1;
		long_date = (long_date * 10000) + (s_sth.s_mth * 100)+ 1;
	}
	else{
		long_date = long_date/10000;
		long_date = (long_date * 10000) + (s_sth.s_mth * 100)+ 1;
	}
		
	for( ; ; ){

		julian = days(long_date);
		remain = julian % 7;

		day = long_date % 100;	
		month = (long_date / 100)%100;
		year = long_date / 10000;

		if(remain == 6 || remain == 0){
		  	s_sth.s_att[day - 1] = WEEKEND; 
		 	strcpy(s_sth.s_day[day - 1],"W  ");
		}
		if((++day) <= d_month[month-1])
			long_date ++;
		else
			break;
	}

	return(NOERROR);
}	/* get_day() */
/*----------------------------------------------------------------*/
/* if a weekend attendance code is deleted this routine will put  */
/* the 'W' back into the field                                    */
/*----------------------------------------------------------------*/
Get_Weekend(item_no)
int	item_no;
{
	int	remain, month, year;
	long	julian, long_date, end_date;
	short	day;

	if(pay_param.pr_st_mth == 1)
		long_date = pay_param.pr_cal_st_dt;
	if(pay_param.pr_st_mth == 2)
		long_date = pay_param.pr_fisc_st_dt;
	if(pay_param.pr_st_mth == 3)
		long_date = pay_param.pr_schl_st_dt;

	month = (long_date/100)% 100;
	if(month > s_sth.s_mth){
		long_date = long_date/10000 +1;
		long_date = (long_date * 10000) + (s_sth.s_mth * 100)+ 1;
	}
	else{
		long_date = long_date/10000;
		long_date = (long_date * 10000) + (s_sth.s_mth * 100)+ 1;
	}
		
	for( ; ; ){

		julian = days(long_date);
		remain = julian % 7;

		day = long_date % 100;	
		month = (long_date / 100)%100;
		year = long_date / 10000;

		if(remain == 6 || remain == 0){
			if(item_no != (day - 1)){
				if((++day) <= d_month[month-1])
					long_date ++;
				else
					break;
				continue;
			}
			if(s_sth.s_day[day -1][0] == '\0' ||
			   strcmp(s_sth.s_day[day -1],"   ")==0){
			  	s_sth.s_att[day - 1] = WEEKEND; 
			 	strcpy(s_sth.s_day[day - 1],"W  ");
			}
		}
		else{
			if(s_sth.s_day[day-1][0] == 'W')
				strcpy(s_sth.s_day[day-1],"   ");
		}
		if((++day) <= d_month[month-1])
			long_date ++;
		else
			break;
	}

	return(NOERROR);
}	/* get_day() */
/*----------------------------------------------------------------*/
UpdtHdr(item_no,mode)
int	item_no;
int	mode;
{
	int	retval;
	long	temp_date, year;
	short	month;

	strcpy(att_his.eah_numb, emp_rec.em_numb);
	if(pay_param.pr_st_mth == 1){
		month = ((pay_param.pr_cal_st_dt/100) % 100);
		if(month <= s_sth.s_mth)
	    	   att_his.eah_date = pay_param.pr_cal_st_dt; 
		else
		   att_his.eah_date = pay_param.pr_cal_st_dt + 10000;  
	}
	if(pay_param.pr_st_mth == 2){
		month = ((pay_param.pr_fisc_st_dt/100) % 100);
		if(month <= s_sth.s_mth)
		   att_his.eah_date = pay_param.pr_fisc_st_dt;  
		else
		   att_his.eah_date = pay_param.pr_fisc_st_dt + 10000;  
	}
	if(pay_param.pr_st_mth == 3){
		month = ((pay_param.pr_schl_st_dt/100) % 100);
		if(month <= s_sth.s_mth)
		   att_his.eah_date = pay_param.pr_schl_st_dt;  
		else
		   att_his.eah_date = pay_param.pr_schl_st_dt + 10000;  
	}

	att_his.eah_date = (att_his.eah_date/10000)* 10000 +
			(s_sth.s_mth * 100) + (item_no+1);  

	retval = get_emp_at(&att_his, BROWSE, 0, e_mesg);
	if(retval < 0 && retval != UNDEF) {
		DispError((char *)&s_sth,e_mesg);
		return(retval);
	}
	if(retval == UNDEF){
		if(strcmp(att.at_sick,"Y") == 0){
			real_bal_sick -= (att.at_units * (emp_rec.em_sen_perc/
							  100.0));
			s_sth.s_bal_sick = real_bal_sick;
		}
		if(strcmp(att.at_vac,"Y") == 0)
  			s_sth.s_bal_vac -= (att.at_units * (emp_rec.em_sen_perc/
							    100.0));
		s_sth.s_att[item_no] = 
			att.at_disp_code[0];
	}
	else{
		if(strcmp(att.at_sick,"Y") == 0){
		  if(mode == UPDATE){
			real_bal_sick -= (att.at_units * (att_his.eah_perc/
							  100.0));
			s_sth.s_bal_sick -= (att.at_units * (att_his.eah_perc/
							     100.0));
		  }
		  else{
			real_bal_sick += (att.at_units * (att_his.eah_perc/
							  100.0));
			s_sth.s_bal_sick += (att.at_units * (att_his.eah_perc/
							     100.0));
		  }
		}
		if(strcmp(att.at_vac,"Y") == 0){
		  if(mode == UPDATE){
  			s_sth.s_bal_vac -= (att.at_units * (att_his.eah_perc/
							    100.0));
		  }
		  else{
  			s_sth.s_bal_vac += (att.at_units * (att_his.eah_perc/
							    100.0));
		  }
		}

		s_sth.s_att[item_no] = '.';

		if(change_code == 0) 
			s_sth.s_day[item_no][0] = '\0';
	}

	if(s_sth.s_bal_sick > barg_unit.b_sick_max)
		s_sth.s_bal_sick = barg_unit.b_sick_max;

	retval = Get_Weekend(item_no);
	if(retval < 0)	return(retval);

	ret( WriteFields((char *)&s_sth, KEY_START, HDR_END_FLD) );

	ret( WriteFields((char *)&s_sth, sr.curfld, sr.curfld) );

	return(NOERROR);
}
/*-------------------- E n d   O f   P r o g r a m ---------------------*/
