/*------------------------------------------------------------------------
Source Name: pre_sen.c
System     : Personnel/Payroll System.
Created  On: July 10, 1992.
Created  By: Eugene Roy.

DESCRIPTION:

MODIFICATIONS:        

Programmer     YY/MM/DD       Description of modification
~~~~~~~~~~     ~~~~~~~~       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Eugene Roy	1992/09/11	Adding a link list to the screen to allow the
				user to select individual employees.
------------------------------------------------------------------------*/

#define	MAIN		/* Main program. This is to declare Switches */

#define	SYSTEM		"PAYROLL PROCESSING"	/* Sub System Name */
#define	MOD_DATE	"13-JUL-91"		/* Program Last Modified */

#include <stdio.h>
#include <cfomstrc.h>
#include <bfs_defs.h>
#include <bfs_com.h>
#include <bfs_pp.h>
#include <repdef.h>
#include <filein.h>
#include <isnames.h>

#define EXIT	   	12

/* User Interface define constants */
#ifdef ENGLISH
#define SELECT		'S'
#define EXITOPT		'E'

#define	YES		'Y'
#define NO		'N'
#define	EDIT		'E'

#define	ADDITEMS	'A'
#define	DELITEM		'D'
#define	REACTITEM	'R'
#define	NEXT		'N'
#define	PREV		'P'
#define	CANCEL		'C'
#else
#define SELECT		'C'
#define EXITOPT		'F'

#define	YES		'O'
#define NO		'N'
#define	EDIT		'M'

#define	ADDITEMS	'A'
#define	DELITEM		'D'
#define	REACTITEM	'R'
#define	NEXT		'N'
#define	PREV		'P'
#define	CANCEL		'A'
#endif
#define U_NO		'N'

#define	DELETED		"DEL"
#define	ACTIVE		"ACT"
/* PROFOM Releted declarations */

#define	SCR_NAME	"pre_sen3"	/* PROFOM screen Name */

#define	PAGESIZE	3		/* No of Items */
/* Field PROFOM numbers */
#define START_FLD 	400	/* Start Field in range */
#define	END_FLD		3000	/* Last Field of the screen */

#define	ITEM_ST_FLD	2000
#define	STEP		300

#define BARG1		400	/* Starting Bargaining Unit		*/
#define BARG2		500	/* Ending Bargaining Unit		*/
#define POS1		600	/* Starting Classification		*/
#define POS2		700	/* Ending Classification		*/
#define	CENTER1		800
#define	CENTER2		900
#define PAYDATE		1000	/* Payment for Pay Date			*/
#define PAYPER1		1100	/* Include from Pay Period		*/
#define	TEACH		1200
#define	RGIND		1300
#define EMP1		1400	/* Starting Employee Number		*/
#define EMP2		1500	/* Ending Employee Number		*/
#define OPTION		1600	/* */
#define	CHG_FLD		1700
#define	PAGE_FLD	1900
#define	EMP_ITEM	100
#define	STATUS_FLD	200

#define MESSAGE		2900
#define RESPONSE	3000

/* pre_earn.sth - header for C structure generated by PROFOM EDITOR */

typedef	struct	{	/* Start Fld 1500, Endfld 4200 */

	char	s_emp[13];	/* 800 STRING X(6) */
	char	s_name[30];	/* 900 STRING X(30) */
	char	s_status[5];	/* 1300 STRING XXX */

}	S_item ;

typedef struct	{

	char	s_pgm[11];	/* 100 program name */
	long	s_rundate;	/* 300 run date */
	char	s_barg1[7];	/* 400 due date */
	char	s_barg2[7];	/* 500 transaction date */
	char	s_pos1[7];	/* 600 release holdbacks option */
	char 	s_pos2[7];	/* 700 starting supplier code */
	short	s_center1;
	short	s_center2;
	long	s_paydate;	/* 1000 ending trans ref. no. */
	short	s_payper1;	/* 1100 past due date */
	char	s_teach[2];	/* 900 starting trans ref. no. */
	char	s_rgind[2];	/* 900 starting trans ref. no. */
	char	s_emp1[13];	/* 800 ending supllier code */
	char	s_emp2[13];	/* 900 starting trans ref. no. */
	char	s_option[2];	/* 1300 option choice */
	short	s_field;
	char	s_dummy[2];
	short	s_page;

	S_item	s_items[PAGESIZE] ;	/* Start Fld 800, End Fld 3100  */

	char	s_mesg[78];	/* 1500 message field */
	char	s_resp[2];	/* 1600 response field */
	} s_struct;

static	s_struct  s_sth,image;	/* PROFOM Screen Structure */
static	struct  stat_rec  sr;		/* PROFOM status rec */

typedef struct Page {
	S_item	Items[PAGESIZE] ;	/* Items Information */
	struct	Page	*PrevPage ;	/* ptr to previous page */
	struct	Page	*NextPage ;	/* ptr to next page */
	char	I_Status[PAGESIZE][2];	/* item status ie A(DD) C(hange) */
	short	NoItems;		/* number of Items on the page */
	short	Pageno;			/* Page number */
}	Page;

static	Page	*FirstPage,		/* Address of First Page */
		*CurPage,		/* Address of Current Page */
		*CurLast,		/* Address of Curr. record last page */
		*LastPage;		/* Address of Last Page of Memory
					   Allocated */

/* File structures */
static	Pa_rec	pa_rec;
static	Barg_unit	barg_unit;
static	Time	time_rec;
static	Position	position;
static	Class	class;
static	Emp	emp_rec;
static	Emp_sched1	emp_sched1;
static	Emp_at_his	att_his, pre_att_his;
static	Emp_sen	emp_sen;
static	Pay_per	pay_period;
static	Pay_per_it	pay_per_it;
static	Pay_param	pay_param;
static	Gov_param	gov_param;
static	Sen_par	sen_par;
static	Att	att;
static	Tmp_sen	tmp_sen;
static	Sch_rec	sch_rec;

/* number of days in months */

short	d_month[12] = { 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 };

static	int	day, day2, month, month2, curr_month;
static	int	start_mth;
static	long	curr_year;

static	double	non_sen_days;
static	double	num_sen_days0, num_sen_days1;
static	int	sched_flag;

static	char 	e_mesg[180];  		/* dbh will return err msg in this */

static int	PG_SIZE;
static char 	discfile[15];	/* for storing outputfile name */
static short	pgcnt; 		/* for page count */

static	Validation();
static	WindowHelp();

void	free() ;
char	*malloc() ;

double 	D_Roundoff();
main(argc,argv)
int argc;
char *argv[];
{
	int 	retval;

	LNSZ = 133;
	retval = Initialize(argc,argv);	/* Initialization routine */

	if (retval == NOERROR) retval = Process();

	CloseRtn();			/* return to menu */
	if (retval != NOERROR) exit(1);
	exit(0);
}

/*-------------------------------------------------------------------*/
/* Initialize PROFOM */

Initialize(argc, argv)
int	argc ;
char	*argv[] ;
{
	int	err ;

	/*
	*	Initialize DBH Environment
	*/
	strncpy(SYS_NAME,SYSTEM,50);	/* Sub system name */
	strncpy(CHNG_DATE,MOD_DATE,10);	/* Modification Date */

	proc_switch(argc, argv, CHEQUE) ; 	/* Process Switches */

	/*
	*	Initialize PROFOM & Screen
	*/
	STRCPY(sr.termnm,terminal);	/* Copy Terminal Name */
	fomin(&sr);
	ret(err_chk(&sr)) ;		/* Check for PROFOM Error */
	fomcf(1,1);			/* Enable Snap screen option */

	err = InitScreen() ;		/* Initialize Screen */
	if(NOERROR != err) return(err) ;

	FirstPage = NULL;
	LastPage = NULL;

	return(NOERROR) ;
}	/* Initialize() */

/*--------------------------------------------------------------------------*/
/* Close nessary files and environment before exiting program               */

CloseRtn() 
{
	FreeList();

	/* Set terminal back to normal mode from PROFOM */
	fomcs();
	fomrt();
	close_dbh();			/* Close files */
	close_rep();

	return(NOERROR);
}	/* CloseRtn() */
/* Free the linked list */

static
FreeList()	
{
	int 	i;

	/* clear the screen items from linked list */

	for(CurPage = FirstPage;CurPage;CurPage = CurPage->NextPage){
		for( i=0; i <= PAGESIZE; i++) {
			if(i >= CurPage->NoItems) break;
		}
	}

	for( CurPage=LastPage; CurPage; CurPage=LastPage){
		LastPage=LastPage->PrevPage;
		free((char *)CurPage );
	}

	FirstPage = NULL;

	return(NOERROR);
}
/*----------------------------------------------------------------*/
/* Initialize screen before going to process options */

InitScreen()
{
	/* move screen name to Profom status structure */
	STRCPY(sr.scrnam,NFM_PATH);
	strcat(sr.scrnam,SCR_NAME) ;

	STRCPY(s_sth.s_pgm,PROG_NAME);
	s_sth.s_rundate = get_date();	/* get Today's Date in YYYYMMDD format*/
	s_sth.s_option[0] = HV_CHAR;
	s_sth.s_mesg[0] = HV_CHAR ;
	s_sth.s_resp[0] = HV_CHAR ;

	/* Move Low Values to data fields */
	InitFields() ;

	s_sth.s_emp1[0] = HV_CHAR;
	s_sth.s_emp2[0] = HV_CHAR;

	ClearScreen();

	return(NOERROR) ;
}	/* InitScreen() */

/*-------------------------------------------------------------------*/
/* Get Option from user and call corresponding function */

Process()
{
	int	err;

	for( ; ; ){

		if((err = ReadOption())<0) 
			return(err);

		switch(s_sth.s_option[0]) {
		case  EXITOPT :
			return(NOERROR);
		case  SELECT :
			CHKACC(err,ADD,e_mesg);
			err = ProcOption() ;
			break ;
		default :
			continue;
		}

		if(NOACCESS == err)	fomen(e_mesg);
		if(PROFOM_ERR == err)	return(PROFOM_ERR);  /* PROFOM ERROR */
		if(DBH_ERR == err) {
			DispError((char *)&s_sth,e_mesg);
#ifdef ENGLISH
			sprintf(e_mesg,"%s %d Dberror: %d Errno: %d",
				"System Error... Iserror:",
				iserror, dberror, errno);
#else
			sprintf(e_mesg,"%s %d Dberror: %d Errno: %d",
				"Erreur du systeme... Iserror:",
				iserror, dberror, errno);
#endif
			DispError((char *)&s_sth,e_mesg);
			return(DBH_ERR); /* DBH ERROR */
		
		}
		fomce();
	}      /*   end of the for( ; ; )       */
}	/* Process() */
/*------------------------------------------------------------*/
ReadOption()
{

	fomer("                                                    ");
	s_sth.s_mesg[0] = HV_CHAR;
	DispMesgFld((char *)&s_sth);	
#ifdef ENGLISH
	fomer("S(elect), E(xit)");
#else
	fomer("C(hoisir), F(in)");
#endif
	sr.nextfld = OPTION;
	fomrf((char *)&s_sth);
	ret(err_chk(&sr));

}	/* ReadOption */
/*------------------------------------------------------------*/
ProcOption()
{
	int	i, err ;

	for(i = START_FLD ; i <= END_FLD - 300 ; i += 100)
		fomca1(i, 19, 0) ;    /* disable dup control */

	err = ReadRange(ADD) ;
	if(err != NOERROR) return(err) ;

	err = Confirm() ;
	if(err != YES) return(NOERROR) ;

	unlink_file(TMP_SEN);

	if(strcmp(s_sth.s_rgind, "R") == 0)
		err = ProcRanges() ;
	else
		err = ProcItemUpdates();

	if(pgcnt){
		if(term < 99)
			last_page();
#ifndef	SPOOLER
	else
		rite_top();
#endif
	}

	return(NOERROR);
}	/* ProcSelection() */
/*------------------------------------------------------------*/
/* Get the Header details from user */

ReadRange(mode)
int	mode ;
{
	int	 i, err ;

	if(mode == ADD) {
#ifdef ENGLISH
		STRCPY(s_sth.s_mesg,"Press ESC-F to Go to Option:");
#else
		STRCPY(s_sth.s_mesg,"Appuyer sur ESC-F pour retourner a Option:");
#endif
		DispMesgFld((char *)&s_sth);

		fomca1(BARG1, 19, 2) ;
		fomca1(BARG2, 19, 2) ;
		fomca1(POS1, 19, 2);
		fomca1(POS2, 19, 2) ;
		fomca1(CENTER1, 19, 2) ;
		fomca1(CENTER2, 19, 2) ;
		fomca1(PAYDATE, 19, 2) ;
		fomca1(PAYPER1, 19, 2) ;
		fomca1(TEACH, 19, 2) ;
		fomca1(RGIND, 19, 2) ;
		strcpy(s_sth.s_barg1, "     0");
		strcpy(s_sth.s_barg2, "ZZZZZZ");
		strcpy(s_sth.s_pos1, "     0");
		strcpy(s_sth.s_pos2, "ZZZZZZ");
		s_sth.s_center1 = 0;
		s_sth.s_center2 = 9999;
		s_sth.s_paydate = 99991231 ;
		s_sth.s_payper1 = 1 ;
		sr.nextfld = BARG1 ;
		sr.endfld = RGIND ;
		fomud((char*)&s_sth);
		ret(err_chk(&sr));
	}
	InitFields() ;

	i = ReadFields((char *)&s_sth,START_FLD, END_FLD - 200,
			Validation, WindowHelp, 1) ;
	if(PROFOM_ERR == i || DBH_ERR == i) return(i) ;
	if(RET_USER_ESC == i) {	/* ESC-F */
		return(RET_USER_ESC) ;
	}

	ReadEmp();

	return(NOERROR) ;
}	/* ReadRange() */
/*------------------------------------------------------------*/
/* Get the Header details from user */

ReadEmp()
{
	int	 i, err ;

	if(strcmp(s_sth.s_rgind, "R") == 0){
		fomca1(EMP1, 19, 2) ;
		fomca1(EMP2, 19, 2) ;
		strcpy(s_sth.s_emp1, "           0");
		strcpy(s_sth.s_emp2, "ZZZZZZZZZZZZ");
		sr.nextfld = EMP1 ;
		sr.endfld = EMP2;
		fomud((char*)&s_sth);
		ret(err_chk(&sr));
		s_sth.s_emp1[0] = LV_CHAR;
		s_sth.s_emp2[0] = LV_CHAR;

		ClearScreen();	/* Clear the Screen */

		i = ReadFields((char *)&s_sth, EMP1, EMP2,
			Validation, WindowHelp, 1) ;
		if(PROFOM_ERR == i || DBH_ERR == i) return(i) ;
		if(RET_USER_ESC == i) {	/* ESC-F */
			return(RET_USER_ESC) ;
		}
	}
	else{
		s_sth.s_emp1[0] = HV_CHAR;
		s_sth.s_emp2[0] = HV_CHAR;

		ret( WriteFields((char *)&s_sth, EMP1, EMP2) );

		i = Add();
		if(NOERROR != i) return(i) ;
	}

	return(NOERROR) ;
}	/* ReadEmp() */
/*----------------------------------------------------------------*/
/* Validation function() for Key and Header fields when PROFOM returns
  RET_VAL_CHK */

static
Validation()
{
	int	retval;
	int	fld_no, item_no, st_fld;
	
	fld_no = sr.curfld;
	if(sr.curfld >= ITEM_ST_FLD) {	
		item_no = (sr.curfld - ITEM_ST_FLD) / STEP;
 		fld_no = (sr.curfld - ITEM_ST_FLD) % STEP + 100;

		st_fld = ITEM_ST_FLD + (STEP * item_no);
	}

	switch(fld_no){
	case BARG1:  /* ending bargaining unit code */
		Right_Justify_Numeric(s_sth.s_barg1
					,(sizeof(s_sth.s_barg1)-1));
		break;
	case BARG2:  /* ending bargaining unit code */
		Right_Justify_Numeric(s_sth.s_barg2
					,(sizeof(s_sth.s_barg2)-1));
		if(strcmp(s_sth.s_barg2,s_sth.s_barg1) <0) {
#ifdef ENGLISH
			fomer("Ending code cannot precede starting code");
#else
			fomer("Code finissant ne peut pas preceder le code debutant");
#endif
			s_sth.s_barg2[0] = LV_CHAR;
		}
		break;
	case POS1:  
		Right_Justify_Numeric(s_sth.s_pos1
					,(sizeof(s_sth.s_pos1)-1));
		break;
	case POS2: 
		Right_Justify_Numeric(s_sth.s_pos2
					,(sizeof(s_sth.s_pos2)-1));
		if(strcmp(s_sth.s_pos2,s_sth.s_pos1) <0) {
#ifdef ENGLISH
			fomer("Ending code cannot precede starting code");
#else
			fomer("Code finissant ne peut pas preceder le code debutant");
#endif
			s_sth.s_pos2[0] = LV_CHAR;
		}
		break;
	case CENTER2:  
		if(s_sth.s_center2 < s_sth.s_center1) {
#ifdef ENGLISH
			fomer("Ending number cannot precede starting number");
#else
			fomer("Numero finissant ne peut pas preceder le numero debutant");
#endif
			s_sth.s_center2 = LV_SHORT;
		}
		break;
	case TEACH:  /* ending employee code */
		if(s_sth.s_teach[0] != 'T' &&
			 s_sth.s_teach[0] != 'N' &&
			 s_sth.s_teach[0] != 'B'){
#ifdef ENGLISH
			fomer("Invalid option - PLEASE re-enter");
#else
			fomer("Invalid option - PLEASE re-enter");
#endif
			s_sth.s_teach[0] = LV_CHAR;
		}
		break;
	case RGIND:  /* ending employee code */
		if(s_sth.s_rgind[0] != 'R' &&
			 s_sth.s_rgind[0] != 'I'){
#ifdef ENGLISH
			fomer("Invalid option - PLEASE re-enter");
#else
			fomer("Invalid option - PLEASE re-enter");
#endif
			s_sth.s_rgind[0] = LV_CHAR;
		}
		break;
	case EMP1:
		Right_Justify_Numeric(s_sth.s_emp1
					,(sizeof(emp_rec.em_numb)-1));
		break;
	case EMP2:  /* ending employee code */
		Right_Justify_Numeric(s_sth.s_emp2
					,(sizeof(emp_rec.em_numb)-1));
		if(strcmp(s_sth.s_emp2,s_sth.s_emp1) <0) {
#ifdef ENGLISH
			fomer("Ending number cannot precede starting number");
#else
			fomer("Numero finissant ne peut pas preceder le numero debutant");
#endif
			s_sth.s_emp2[0] = LV_CHAR;
		}
		break;
	case EMP_ITEM:
		Right_Justify_Numeric(s_sth.s_items[item_no].s_emp,
			sizeof(s_sth.s_items[item_no].s_emp)-1);
		strcpy(emp_rec.em_numb,s_sth.s_items[item_no].s_emp);
		retval = get_employee(&emp_rec,BROWSE,0,e_mesg);
		if(retval < 0) {
			fomer("Employee Does not Exist");
			s_sth.s_items[item_no].s_emp[0] = LV_CHAR;
			return(ERROR);
		}
		retval=UsrBargVal(BROWSE,emp_rec.em_numb,emp_rec.em_barg,
								1,e_mesg);
		if(retval < 0){
			DispError((char *)&s_sth,e_mesg);
			s_sth.s_items[item_no].s_emp[0] = LV_CHAR;
			return(ERROR);
		}
	
		retval = CheckEmp(emp_rec.em_numb);
		if(retval < 0){
			s_sth.s_items[item_no].s_emp[0] = LV_CHAR;
			return(ERROR);
		}

		strcpy(s_sth.s_items[item_no].s_name, emp_rec.em_last_name);
		strcat(s_sth.s_items[item_no].s_name, ", ");
		strcat(s_sth.s_items[item_no].s_name, emp_rec.em_first_name);
		strcat(s_sth.s_items[item_no].s_name, " ");
		strcat(s_sth.s_items[item_no].s_name, emp_rec.em_mid_name);
		break;
	default :
#ifdef ENGLISH
		sprintf(e_mesg,"No Validity Check For Field#  %d",sr.curfld);
#else
		sprintf(e_mesg,"Pas de controle de validite pour le Champ#  %d",sr.curfld);
#endif
		fomen(e_mesg);
		get();
		return(ERROR) ;
	}	/* Switch sr.curfld */

	return(NOERROR) ;
}	/* Validation() */
/*----------------------------------------------------------------*/
/* Show Help Windows, if applicable, when user gives ESC-H in key
   and header fields */

static
WindowHelp()
{
	int	retval ;
	int	fld_no;
	int	item_no;
	int	st_fld;

	fld_no = sr.curfld;
	if(sr.curfld >= ITEM_ST_FLD) {	
		item_no = (sr.curfld - ITEM_ST_FLD) / STEP;
 		fld_no = (sr.curfld - ITEM_ST_FLD) % STEP + 100;

		st_fld = ITEM_ST_FLD + (STEP * item_no);
	}

	switch(fld_no){
	case EMP_ITEM:
		retval = emp_hlp(s_sth.s_items[item_no].s_emp,7,13);
		if(retval == DBH_ERR) return(retval);
		redraw();
		strcpy(emp_rec.em_numb,s_sth.s_items[item_no].s_emp);
		retval = get_employee(&emp_rec,BROWSE,0,e_mesg);
		if(retval < 0) {
			fomer("Employee Number Does not Exist");
			s_sth.s_items[item_no].s_emp[0] = LV_CHAR;
			return(ERROR);
		}
		retval=UsrBargVal(BROWSE,emp_rec.em_numb,emp_rec.em_barg,
								1,e_mesg);
		if(retval < 0){
			DispError((char *)&s_sth,e_mesg);
			s_sth.s_items[item_no].s_emp[0] = LV_CHAR;
			return(ERROR);
		}
	
		retval = CheckEmp(emp_rec.em_numb);
		if(retval < 0){
			s_sth.s_items[item_no].s_emp[0] = LV_CHAR;
			return(ERROR);
		}

		strcpy(e_mesg,emp_rec.em_last_name);
		strcat(e_mesg,", ");
		strcat(e_mesg,emp_rec.em_first_name);
		strncpy(s_sth.s_items[item_no].s_name,e_mesg,28);

		if ( WriteFields((char *)&s_sth,
					st_fld+100, st_fld+100) < 0 ) 
			return(-1);
		break;
	default :
		fomer("No Help Window for This Field");
	}	/* Switch sr.curfld */

	return(NOERROR) ;
}	/* HdrAndKeyWindowHelp() */
/*----------------------------------------------------------------*/
CheckEmp(emp)
char	*emp;
{
	int	retval;
	int	i;
	Page	*temppage;

	if(emp[0] == '\0') {
		fomer("This is a Required Field");
		return(ERROR);
	}

	/* check to see if item is already in list */
	if(CurLast != NULL) {
	   for(temppage=FirstPage; temppage!=NULL;temppage=temppage->NextPage) {
	      for(i =0; i< temppage->NoItems; i++) {
			if(temppage->Items[i].s_emp[0] == NULL) {
				return(NOERROR);
			}
			if(strcmp(temppage->Items[i].s_emp,emp) == 0) {
				fomer("Employee Number Already Entered on Screen");
				return(ERROR);
			}
	      }
	      if(temppage == CurLast) break;
	   }
	}

	return(NOERROR);
}
/*-----------------------------------------------------------------------*/
/* Take the confirmation from user for the items part of the screen      */
/*-----------------------------------------------------------------------*/
Confirm()
{
	int	err ;

	/* Options:
	     YLNPC
	*/

	for( ; ; ) {
	    if(strcmp(s_sth.s_rgind, "R") == 0){
#ifdef ENGLISH
		err = GetOption((char *)&s_sth,"Y(es), E(dit), C(ancel)", "YEC");
#else
		err = GetOption((char *)&s_sth,"O(ui), M(odifier), A(nnuler)", "OMA");
#endif
	    }
	    else{
#ifdef ENGLISH
		err = GetOption((char *)&s_sth,
		"Y(es), A(dd), E(dit), D(el), R(eactivate), N(ext), P(rev), C(ancel)"
		,"YAEDRNPC");
#else
		err = GetOption((char *)&s_sth,
		"Y(es), A(dd), E(dit), D(el), R(eactivate), N(ext), P(rev), C(ancel)"
		,"ORCLEVSPA");
#endif
	    }
	    switch(err) {
	    case  YES  :
		return(YES);
	    case  EDIT  :
		err = FieldEdit();
		break ;
	    case  ADDITEMS:
		err = AddItems();
		break;
	    case  DELITEM:
	    case  REACTITEM:
		err = ChangeStatus(err);
		break;
	    case  NEXT:
		if(CurPage == CurLast || CurLast == NULL) {
#ifdef ENGLISH
			fomer("No More Pages....");
#else
			fomer("Plus de pages....");
#endif
			continue;
		}
		CurPage = CurPage->NextPage ;
		err = ShowItems(CurPage);
		break;
	    case  PREV:
		if(CurLast == NULL || CurPage == FirstPage) {
#ifdef ENGLISH
			fomer("No More Pages....");
#else
			fomer("Plus de pages....");
#endif
			continue;
		}
		CurPage = CurPage->PrevPage ;
		err = ShowItems(CurPage);
		break;
	    case  CANCEL :
#ifdef ENGLISH
		err = GetOption((char *)&s_sth,
				"Confirm the Cancel (Y/N)?", "YN") ;
#else
		err = GetOption((char *)&s_sth,
				"Confirmer l'annulation (O/N)?", "ON") ;
#endif
		if(err == YES) return(CANCEL) ;
		break ;
	    }	/* switch err */

	    if(err == PROFOM_ERR) return(err) ;
	    if(err == DBH_ERR) return(err) ;
	}	/* for(; ; ) */
}	/* ConfirmItems() */
/*-----------------------------------------------------------------------*/
/*                                                                       */
/* Changing fields. Accept fld to be changed and read that fld 		 */

FieldEdit()
{
     	int	i,retval;

     	for ( i = START_FLD; i <= END_FLD - 300 ; i += 100 )
       		fomca1( i,19,2 );      		/*  enable Dup Control */

     	sr.nextfld = START_FLD;
     	sr.endfld = END_FLD - 300;
     	fomud( (char *) &s_sth );
     	ret(err_chk(&sr));

	retval = ReadRange(UPDATE);
	if(retval != NOERROR) return(retval) ;

     	return(NOERROR);
}	/* FieldEdit() */
/*-------------------------------------------------------------------------*/
/* Initialize Screen Header with either Low Values */

InitFields()
{
	s_sth.s_barg1[0] = LV_CHAR;
	s_sth.s_barg2[0] = LV_CHAR;
	s_sth.s_pos1[0] = LV_CHAR;
	s_sth.s_pos2[0] = LV_CHAR;
	s_sth.s_center1 = LV_SHORT;
	s_sth.s_center2 = LV_SHORT;
	s_sth.s_paydate = LV_LONG;
	s_sth.s_payper1 = LV_SHORT;
	s_sth.s_teach[0] = LV_CHAR;
	s_sth.s_rgind[0] = LV_CHAR;
	
	return(NOERROR) ;
}	/* InitFields() */
/*----------------------------------------------------------------------*/
/* Adding.  Get the unique Key, accept details and update the files */
Add()
{
	int	err ;

	FirstPage = NULL;
	LastPage = NULL;
	CurLast = NULL;

	err = GetDetails() ;
	if(PROFOM_ERR == err || DBH_ERR == err) return(err) ;
	if(err < 0 || CANCEL == err) {
		roll_back(e_mesg) ;	/* Unlock the locked Records */
		return(ClearScreen()) ;	/* Clear the Screen */
	}

	return(NOERROR);
}	/* Add() */
/*------------------------------------------------------------*/
/* Read the Area Details from the User */

GetDetails()
{
	int	i ;

	i = AddItems();
	if(NOERROR != i) return(i) ;

	return(NOERROR) ;
}	/* GetDetails() */
/*------------------------------------------------------------*/
/* Read Item Details from the User */

AddItems()
{
	int	i, err ;

	/* If the last node of po is Partial filled then Show Page */
	if(CurLast != NULL && CurLast->NoItems < PAGESIZE ) {
		ret( ShowItems(CurLast) ) ;
		i = CurLast->NoItems ;
		CurPage = CurLast ;
	}
	else {
		/* Calculate the page# */
		if(CurLast != NULL) {
			i = PAGESIZE ;
			CurPage = CurLast ;
		}
		else {
			s_sth.s_page = 1 ;
			WriteFields((char*)&s_sth,PAGE_FLD,PAGE_FLD);
			i = 0 ;
		}
	}

	for( ; ; ) {
		if( PAGESIZE == i) {	/* Page Full */

			/* move High Values to All items exept First one */
			for(i--;i > 0; i--)
				InitItem(HV_CHAR,i);

			/* Calculate the page# */
			s_sth.s_page = CurLast->Pageno + 1 ;

			ret( WriteFields((char *)&s_sth,PAGE_FLD, 
				(END_FLD - 200)) ) ;

			i = 0 ;
		}

		err = ReadItem(i,ADD) ;		/* Read Each Item Line */
		if(PROFOM_ERR == err || DBH_ERR == err) return(err) ;
		if(NOERROR != err) break ;	/* ESC-F */

		if(0 == i)	/* First Item in the Page */
			if((err = MakeFreshPage()) < 0) return(err) ;
		
		/* Copy the Item to List */
		scpy((char*)&(CurPage->Items[i]), (char*)&(s_sth.s_items[i]),
			sizeof(S_item)) ;

		CurPage->I_Status[i][0] = ADDITEMS;

		i++ ;

		CurPage->NoItems = i;
	}
	if(i == 0) 
		if((err=ShowItems(CurPage))<0) return(err) ;

	return(NOERROR) ;
}	/* AddItems() */
/*-----------------------------------------------------------------------*/
/*	Get the next node in linked list to add invoice items. If the
*	(Cur. invc last page) = (Last Page in linked List) or no
*	nodes in list, allocate node and add to linked list
*/

MakeFreshPage()
{
	Page	*tempptr ;

	/* If, no node is allocated yet or Current invoice used all the nodes,
	   then allocate new node */

	if( LastPage == NULL || CurLast == LastPage ){
		tempptr= (Page *)malloc((unsigned)sizeof(Page)) ;

		if( tempptr == NULL ){
			DispError((char*)&s_sth,"Memory Allocation Error");
			return(ERROR);
		}
		tempptr->NextPage = NULL ;

		if( LastPage == NULL ){	/* No node is allocated Yet */
			tempptr->PrevPage = NULL ;
			tempptr->Pageno = 1 ;
			FirstPage = tempptr ;
		}
		else {				/* Not a first node in list */
			tempptr->Pageno = LastPage->Pageno + 1 ;
			LastPage->NextPage = tempptr ;
			tempptr->PrevPage = LastPage ;
		}
		LastPage = tempptr ;
	}

	if(CurLast == NULL)
		CurLast = FirstPage ;
	else
		CurLast = CurLast->NextPage ;

	CurLast->NoItems = 0 ;
	CurPage = CurLast ;

	return(NOERROR);
}	/* MakeFreshPage() */
/*------------------------------------------------------------*/
/* Show all the items on the current page 		      */
ShowItems(pageptr)
Page	*pageptr ;
{
	int	i ;


	if(pageptr != NULL) {
		/* Copy the items to screen */
		scpy((char*)s_sth.s_items, (char*)pageptr->Items,
			(pageptr->NoItems * sizeof(S_item)) );

		s_sth.s_page   = pageptr->Pageno ;
		i = pageptr->NoItems ;
	}
	else {
		s_sth.s_page = HV_SHORT ;
		i = 0 ;
	}

	/* Move High Values to remaining Items */
	for( ; i < PAGESIZE ; i++ )
		InitItem(HV_CHAR,i);

	ret( WriteFields((char *)&s_sth, PAGE_FLD, (END_FLD - 200)) );

	return(NOERROR) ;
}	/* ShowItems() */
/*-----------------------------------------------------------------------*/ 
/* Process all the items in the link list and write any changes to the   */
/* file.								 */
/*-----------------------------------------------------------------------*/ 
ProcItemUpdates()
{
	Page	*temppage;
	int	i;
	int	retval;
	int	write_mode;

	if(CurLast != NULL) {
	   for(temppage=FirstPage; temppage!=NULL;temppage=temppage->NextPage) {
	      for(i =0; i< temppage->NoItems; i++) {
		if(strcmp(temppage->Items[i].s_status, ACTIVE) == 0){
			strcpy(s_sth.s_emp1,temppage->Items[i].s_emp);
			strcpy(s_sth.s_emp2,temppage->Items[i].s_emp);

			retval = ProcRanges();
  			if(retval < 0) break; 
		}
	      }
	      if(temppage == CurLast) break;
	   }
	}
	return(NOERROR);
}
/*------------------------------------------------------------*/
/* Read details of given item# */
/*------------------------------------------------------------*/
ReadItem(item_no,mode)
int	item_no ;
int	mode ;
{
	int	i;
	int	st_fld ;
	int	end_fld ;

#ifdef ENGLISH
	strcpy(s_sth.s_mesg,"Press ESC-F to Terminate");
#else
	strcpy(s_sth.s_mesg,"Appuyer sur ESC-F pour terminer");
#endif
	DispMesgFld((char *)&s_sth);

	if(mode == ADD) {
		SetDupBuffers(ITEM_ST_FLD, END_FLD - 200,0);
		strcpy(s_sth.s_items[item_no].s_status,"ACT");
	}
	else {
		SetDupBuffers(ITEM_ST_FLD, END_FLD - 200,1);
	}

	st_fld = ITEM_ST_FLD + (STEP * item_no);
	end_fld = ITEM_ST_FLD + (STEP * item_no) + STATUS_FLD;
	
	s_sth.s_items[item_no].s_emp[0] = LV_CHAR;
	s_sth.s_items[item_no].s_name[0] = LV_CHAR;

	i = ReadFields((char *)&s_sth,st_fld,end_fld,Validation,WindowHelp,1) ;
	if(PROFOM_ERR == i || DBH_ERR == i) return(i) ;
	if(RET_USER_ESC == i) {
		if(mode == ADD) {
			InitItem(HV_CHAR,item_no);
			WriteFields((char *)&s_sth,st_fld,end_fld);
			return(RET_USER_ESC);
		}
		/* When user gives ESC-F while changing fields, assumption is
		* he completed his changes, and remaining fields are same as
		* old. But, at this point STH will be having low values in the 
		* remaining fields. So move the old values form the linked list.
		*/

		i = CopyBack((char *)&s_sth,(char *)&image,sr.curfld, END_FLD);
		if(i == PROFOM_ERR) return(i);

		return(RET_USER_ESC) ;
	}

	return(NOERROR) ;
}	/* ReadItem() */
/*----------------------------------------------------------------*/
/* Set Duplication buffers for fields 				  */
SetDupBuffers( firstfld, lastfld, value )
int	firstfld, lastfld;	/* field numbers range */
int	value;			/* ENABLE or DISABLE */
{
	int i ;

	for( i=firstfld; i<=lastfld; i+=100 )
		fomca1( i, 19, value);
	if( value==0 )
		return(0);
	sr.nextfld = firstfld;
	sr.endfld = lastfld;
	fomud( (char *)&s_sth );
	ret( err_chk(&sr) );

	return( 0 );
}

/*------------------------------------------------------------------------*/
ChangeStatus(status)
int	status;
{
	int	retval;
	int	st_fld, end_fld;
	int	invalid_delete;

	/* Get The Field to Be Modified */
#ifdef	ENGLISH
	strcpy(s_sth.s_mesg,"Enter RETURN to Terminate Edit");
#else
	strcpy(s_sth.s_mesg,"Appuyer sur RETURN pour terminer l'ajustement");
#endif
	DispMesgFld((char *)&s_sth); ;
        
     	for (; ;) {
		s_sth.s_field = LV_SHORT;
		retval = ReadFields((char *)&s_sth,CHG_FLD,CHG_FLD,
			(int (*)())NULL,(int (*)())NULL, 1);

		if (retval < 0) return(-1);
		if (retval == RET_USER_ESC) break;	/* User enter ESC-F */
		if (s_sth.s_field > CurPage->NoItems)
			continue;

       		if (s_sth.s_field == 0 ) break;  /* Finished changing fields */

		st_fld  = ITEM_ST_FLD + (STEP * (s_sth.s_field-1)) + STATUS_FLD;
		end_fld  = ITEM_ST_FLD + (STEP * (s_sth.s_field-1))+STATUS_FLD;

		if(status == DELITEM) {
			if(strcmp(s_sth.s_items[s_sth.s_field-1].s_status,
			   DELETED)==0) {
				fomer("Item is Already Deleted");
			}
			else {
				strcpy(s_sth.s_items[s_sth.s_field-1].s_status,
			   		DELETED);
			}
		}
		else {
			if(strcmp(s_sth.s_items[s_sth.s_field-1].s_status,
			   ACTIVE)==0) {
				fomer("Item is Already Active");
			}
			else {
				strcpy(s_sth.s_items[s_sth.s_field-1].s_status,
			   		ACTIVE);
			}
		}
		/* Update Linked List */
		scpy((char*)&(CurPage->Items[s_sth.s_field -1]), 
		     (char*)&(s_sth.s_items[s_sth.s_field -1]),sizeof(S_item)) ;
		
		ret(WriteFields((char *)&s_sth,st_fld,end_fld));
	}
     	s_sth.s_field = HV_SHORT ;
	if ( WriteFields((char *)&s_sth,CHG_FLD, CHG_FLD) < 0 ) return(-1);

	return(NOERROR);
}
/*------------------------------------------------------------------------*/
/* Move High values to all data fields and clear the screen */

ClearScreen()
{
	int	i;

	FreeList();

	/* Move High Values to Hedaer part */
	s_sth.s_field = HV_SHORT;
	s_sth.s_dummy[0] = HV_CHAR;
	s_sth.s_page = HV_SHORT;
	
	/* Move High Values to The one item */
	for( i=0; i < PAGESIZE ; i++) {
		InitItem(HV_CHAR,i);
	}

	ret( WriteFields((char *)&s_sth,PAGE_FLD, (END_FLD - 200)) );

	return(NOERROR);
}	/* ClearScreen() */
/*-------------------------------------------------------------------------*/
/* Initialize Given screen item with either Low values or High values */

InitItem(t_char, item_no)
char	t_char ;
short	item_no ;
{
	int	i;

	s_sth.s_items[item_no].s_emp[0] = t_char ;
	s_sth.s_items[item_no].s_name[0] = t_char ;
	if(t_char != LV_CHAR){
		s_sth.s_items[item_no].s_status[0] = t_char ;
	}

	return(NOERROR) ;
}	/* Inititem() */
/*-----------------------------------------------------------------------*/
ProcRanges()
{
	int	i, j, retval, err;
	int	gl_true;

	gov_param.gp_eff_date = get_date();

	flg_reset(GOV_PARAM);

	err = get_n_gov_param(&gov_param,BROWSE, 0, BACKWARD, e_mesg) ;
	if(err == EFL) {
		DispError((char *)&s_sth,"Government Parameter Record Not Setup");
		return(err);
	}
	if(err < 0) {
  		DispError((char *)&s_sth,e_mesg);
		return(ERROR) ;
	}
	seq_over(GOV_PARAM);

 	retval = get_pay_param(&pay_param,BROWSE,1,e_mesg);
	if(retval < 0) {
  		DispError((char *)&s_sth,e_mesg);
		return(retval);
	}

	if(InitPrinter1()<0) {
		return(-1);
	}	

	retval = PrntHdg();
	if(retval < 0)	return(retval);

	retval = Calc_Time();
	if(retval != NOERROR){
		DispError((char *)&s_sth,e_mesg) ;
		return(ERROR);
	}

	strcpy(emp_rec.em_numb, s_sth.s_emp1);
	flg_reset(EMPLOYEE);

	for( ; ; ){
			
	  retval = get_n_employee(&emp_rec,BROWSE,0,FORWARD,e_mesg);
	  if(retval < 0) {
		if(retval == EFL) break;
		DispError((char *)&s_sth,e_mesg);
	  	retval = PrntRec(e_mesg);
	  	if(retval < 0){
	  		DispError((char *)&s_sth,e_mesg) ;
	  	}
		return(retval);
	  }
	  retval=UsrBargVal(BROWSE,emp_rec.em_numb,emp_rec.em_barg,1,e_mesg);
	  if(retval < 0)
		continue;
	
	  if(strcmp(emp_rec.em_numb,s_sth.s_emp1) < 0)
	  	continue ;
	  if(strcmp(emp_rec.em_numb,s_sth.s_emp2) > 0)

		break;

	  if((strcmp(emp_rec.em_barg,s_sth.s_barg1) < 0) ||
	     (strcmp(emp_rec.em_barg,s_sth.s_barg2) > 0))
	  	continue ;


  	  if((strcmp(emp_rec.em_pos,s_sth.s_pos1) < 0) ||
   	    (strcmp(emp_rec.em_pos,s_sth.s_pos2) > 0))
	  	continue ;

  	  if((emp_rec.em_cc < s_sth.s_center1) ||
   	     (emp_rec.em_cc > s_sth.s_center2))
	  	continue ;

	  if(strcmp(emp_rec.em_status, "ACT") != 0){
		sprintf(e_mesg,"Employee Status: %s", emp_rec.em_status);
	  	retval = PrntRec(e_mesg) ;
	  	if(retval < 0){
	  		DispError((char *)&s_sth,e_mesg) ;
	  	}
		continue;
	  }

	  if(s_sth.s_teach[0] != 'B'){
/*
	    if(s_sth.s_teach[0] != 'T'){
		if(strcmp(emp_rec.em_barg, "    01") == 0)
			continue;
	    }
	    else{
		if(strcmp(emp_rec.em_barg, "    01") != 0)
			continue;
	    }
*/
	    if(s_sth.s_teach[0] != 'T'){
		if((strcmp(emp_rec.em_barg, "NBTA") == 0) ||
		  (strcmp(emp_rec.em_barg, "AEFNB") == 0))
			continue;
	    }
	    else{
		if((strcmp(emp_rec.em_barg, "NBTA") != 0) &&
		  (strcmp(emp_rec.em_barg, "AEFNB") != 0))
			continue;
	    }
	  }

	  retval = Pre_Sched();
	  if(retval != NOERROR){
		DispError((char *)&s_sth,e_mesg) ;
		return(ERROR);
	  }
	}
	seq_over(EMPLOYEE);

	return(NOERROR) ;
}

/*--------------------------------------------------------------*/
/* Read all time entry info for the key's given 		*/

Pre_Sched()
{
	int retval, err, err1;
	int last_pp;
	int i, j , line_items;
	double	reg_inc;
	double	temp_units, temp_rate, temp_total;

	tmp_sen.tsn_perm_days0 = 0;
	tmp_sen.tsn_perm_days1 = 0;
	tmp_sen.tsn_sick_acc0 = 0;
	tmp_sen.tsn_sick_acc1 = 0;
	sched_flag = 1;

	sprintf(e_mesg,"Employee Number: %s",emp_rec.em_numb);
	fomen(e_mesg);
	fflush(stdout);

	strcpy(barg_unit.b_code,emp_rec.em_barg);
	barg_unit.b_date = get_date();
	flg_reset(BARG);

	err = get_n_barg(&barg_unit,BROWSE,0,BACKWARD,e_mesg);
	if(err == EFL ||
		strcmp(barg_unit.b_code, emp_rec.em_barg) != 0){
		sprintf(e_mesg,"Bargaining Unit does no exist: %s",
			emp_rec.em_barg);
  		DispError((char *)&s_sth,e_mesg);
	  	retval = PrntRec(e_mesg) ;
	  	if(retval < 0){
	  		DispError((char *)&s_sth,e_mesg) ;
	  	}
		return(NOERROR);
	}
	if(err < 0){
  		DispError((char *)&s_sth,e_mesg);
	  	retval = PrntRec(e_mesg) ;
	  	if(retval < 0){
	  		DispError((char *)&s_sth,e_mesg) ;
	  	}
  		return(ERROR);
	}
	seq_over(BARG);

	line_items = 0;

	strcpy(emp_sched1.es_numb,emp_rec.em_numb);
	emp_sched1.es_week = 0;
	emp_sched1.es_fund = 0;
	emp_sched1.es_class[0] = LV_CHAR;
	emp_sched1.es_cost = 0;
	emp_sched1.es_dept[0] = LV_CHAR;
	emp_sched1.es_area[0] = LV_CHAR;
	flg_reset(EMP_SCHED1);

	for( ; ; ) {
		retval = get_n_emp_sched1(&emp_sched1,BROWSE,0,
					   FORWARD,e_mesg);
		if(retval < 0) {
			roll_back(e_mesg);
			if(retval == EFL){
				if(line_items == 0){
					Pre_Emp();
				}
				break;
			}
			DispError((char *)&s_sth,e_mesg);
	  		retval = PrntRec(e_mesg) ;
	 	 	if(retval < 0){
	  			DispError((char *)&s_sth,e_mesg) ;
	  		}
			return(retval);
		}
		if(strcmp(emp_sched1.es_numb,emp_rec.em_numb) !=0){
			roll_back(e_mesg);
			if(line_items == 0){
				Pre_Emp();
			}
			break;
		}

		retval = GetClass(emp_sched1.es_class);
		if(retval == UNDEF) continue;

		retval = GetPos(class.c_pos);
		if(retval == UNDEF) continue;

		/**********					*********/
		/*  Calculate Seniority for employee			*/
		SenAcc(class.c_pos);

	}
	seq_over(EMP_SCHED1);

	return(NOERROR);
}
/*--------------------------------------------------------------*/
/* Read all time entry info for the key's given 		*/

Pre_Emp()
{
	int retval, err, err1;
	int last_pp;
	int i, j , line_items;
	double	reg_inc;
	double	temp_units, temp_rate, temp_total;

	sched_flag = 2;

	if(strcmp(pay_param.pr_prov, "NB") != 0)
			return(NOERROR);

	retval = GetClass(emp_rec.em_class);
	if(retval == UNDEF) return(NOERROR);

	retval = GetPos(class.c_pos);
	if(retval == UNDEF) return(NOERROR);

	if((strcmp(position.p_type,"CA") == 0) ||
		   (strcmp(position.p_type,"SU") == 0))
		return(NOERROR);

	/**********					*********/
	/*  Calculate Seniority for employee			*/
	SenAcc(class.c_pos);

	return(NOERROR);
}
/*-----------------------------------------------------------------------*/
Calc_Time()
{
	int	i, j, retval, err, err2;

	int	gl_true;
	double	temp_units, temp_rate, temp_total;

	strcpy(time_rec.tm_numb, s_sth.s_emp1);
	time_rec.tm_date = s_sth.s_paydate;
	time_rec.tm_no = 0;
	flg_reset(TIME);

 	for( ; ; ) {
	
		retval = get_n_ptime(&time_rec,BROWSE,0,FORWARD,e_mesg);
		if(retval == EFL)
			break ;
		if(retval < 0){
			DispError((char *)&s_sth,e_mesg) ;
	  		retval = PrntRec(e_mesg);
	  		if(retval < 0){
	  			DispError((char *)&s_sth,e_mesg) ;
	  		}
			return(ERROR);
		}
	
		if(time_rec.tm_date != s_sth.s_paydate)
			continue;
		if(strcmp(time_rec.tm_stat,"ACT") != 0){
			continue;
		}
	  	if(strcmp(time_rec.tm_numb,s_sth.s_emp1) < 0)
			continue;
	    	if(strcmp(time_rec.tm_numb,s_sth.s_emp2) > 0)
			break;

		strcpy(emp_rec.em_numb,time_rec.tm_numb);

		retval = get_employee(&emp_rec,BROWSE,0,e_mesg);
		if(retval < 0){
	  		DispError((char *)&s_sth,e_mesg) ;
	  		retval = PrntRec(e_mesg);
	  		if(retval < 0){
	  			DispError((char *)&s_sth,e_mesg) ;
	  		}
	  		return(ERROR);
	  	}
	  	retval=UsrBargVal(BROWSE,emp_rec.em_numb,emp_rec.em_barg,0,
									e_mesg);
	  	if(retval < 0)
			continue;

	 	if((strcmp(emp_rec.em_barg,s_sth.s_barg1) < 0) ||
	   	  (strcmp(emp_rec.em_barg,s_sth.s_barg2) > 0))
			continue;

	  	if((strcmp(emp_rec.em_pos,s_sth.s_pos1) < 0) ||
	   	  (strcmp(emp_rec.em_pos,s_sth.s_pos2) > 0))
	  		continue ;

  	  	if((emp_rec.em_cc < s_sth.s_center1) ||
   	  	   (emp_rec.em_cc > s_sth.s_center2))
	  		continue ;

	  	if(s_sth.s_teach[0] != 'B'){
/*
	    	  if(s_sth.s_teach[0] != 'T'){
		  	if(strcmp(emp_rec.em_barg, "    01") == 0)
			  	continue;
	   	   }
	   	   else{
		  	if(strcmp(emp_rec.em_barg, "    01") != 0)
			  	continue;
	   	   }
*/
	 	   if(s_sth.s_teach[0] != 'T'){
		     if((strcmp(emp_rec.em_barg, "NBTA") == 0) ||
		  	  (strcmp(emp_rec.em_barg, "AEFNB") == 0))
				continue;
	  	   }
		   else{
			if((strcmp(emp_rec.em_barg, "NBTA") != 0) &&
			  (strcmp(emp_rec.em_barg, "AEFNB") != 0))
				continue;
		   }
		}

		retval = GetClass(time_rec.tm_class);
		if(retval == UNDEF) continue;

		retval = GetPos(class.c_pos);
		if(retval == UNDEF) continue;

		sprintf(e_mesg,"Employee Number: %s",emp_rec.em_numb);
		fomen(e_mesg);
		fflush(stdout);

		GetPPit();

		/**********					*********/
		/*  Update Attendance For the employee			*/
		sched_flag = 0;

		/**********					*********/
		/*  Calculate Seniority for employee			*/

		if((strcmp(position.p_type,"FT") != 0) &&
		   (strcmp(position.p_type,"PT") != 0))

			SenAcc(class.c_pos);
	}
	seq_over(TIME);
	
	return(NOERROR);
}
/*-----------------------------------------------------------------------*/
GetPos(pos)
char	*pos;
{
	int	retval;

	strcpy(position.p_code,pos);

	retval = get_position(&position,BROWSE,0,e_mesg);
	if(retval < 0) {
		DispError((char *)&s_sth,e_mesg);
	  	retval = PrntRec(e_mesg);
	  	if(retval < 0){
	  		DispError((char *)&s_sth,e_mesg) ;
	  	}
		return(UNDEF);
	}

	return(NOERROR);
}
/*--------------------------------------------------------------*/
GetClass(class_rec)
char	*class_rec;
{
	int	retval;

	strcpy(class.c_code,class_rec);
	class.c_date = s_sth.s_rundate;
	flg_reset(CLASSIFICATION);

	retval = get_n_class(&class,BROWSE,0,BACKWARD,e_mesg);
	if(retval < 0 && retval != EFL){
		DispError((char *)&s_sth, e_mesg);
	  	retval = PrntRec(e_mesg);
	  	if(retval < 0){
	  		DispError((char *)&s_sth,e_mesg) ;
	  	}
		return(UNDEF);
	}
	if((strcmp(class.c_code,class_rec) != 0) || retval == EFL){
		sprintf(e_mesg,"Classification Code Does Not Exist %s",class_rec);
		DispError((char *)&s_sth, e_mesg);
	  	retval = PrntRec(e_mesg);
	  	if(retval < 0){
	  		DispError((char *)&s_sth,e_mesg) ;
	  	}
	    	return(UNDEF);
	}
	seq_over(CLASSIFICATION);
	return(NOERROR);
}
/*--------------------------------------------------------------*/
AttAcc()
{
	int	i, j, err;

	if(month >= start_mth){
		i = month-start_mth;
	}
	else{
		i = month+start_mth-2;
	}
	if(month2 >= start_mth){
		j = month2-start_mth;
	}
	else{
		j = month2+start_mth-2;
	}

	if(sched_flag != 1){
	  if(sen_par.sn_poss_days[i] != 0)
	    tmp_sen.tsn_sick_acc0 = ((barg_unit.b_sick_rate /
		(double)sen_par.sn_poss_days[i]) * (double)num_sen_days0 *
				     (emp_rec.em_sen_perc / 100.0));
	  else
	    tmp_sen.tsn_sick_acc0 = 0;

	  if(sen_par.sn_poss_days[j] != 0)
	    tmp_sen.tsn_sick_acc1 = ((barg_unit.b_sick_rate /
		(double)sen_par.sn_poss_days[j]) * (double)num_sen_days1 *
				     (emp_rec.em_sen_perc / 100.0));
	  else
	    tmp_sen.tsn_sick_acc1 = 0;
	}
	else{
	  if(sen_par.sn_poss_days[i] != 0)
	    tmp_sen.tsn_sick_acc0 += ((barg_unit.b_sick_rate /
		(double)sen_par.sn_poss_days[i]) * (double)num_sen_days0 *
				     (emp_rec.em_sen_perc / 100.0) *
				(emp_sched1.es_amount / emp_rec.em_perc));
	  else
	    tmp_sen.tsn_sick_acc0 += 0;

	  if(sen_par.sn_poss_days[j] != 0)
	    tmp_sen.tsn_sick_acc1 += ((barg_unit.b_sick_rate /
		(double)sen_par.sn_poss_days[j]) * (double)num_sen_days1 *
				     (emp_rec.em_sen_perc / 100.0) *
				(emp_sched1.es_amount / emp_rec.em_perc));
	  else
	    tmp_sen.tsn_sick_acc1 += 0;
	}

	return(NOERROR);
}
/*--------------------------------------------------------------*/
SenAcc(pos)
char *pos;
{
	int	j, err, retval;
	int	mode, mth;
	double	temp_units0, temp_units1;
	int	tmp_day, no_weeks, week, no_days;
	double	tmp_total;

	num_sen_days0 = 0;
	num_sen_days1 = 0;

	GetPPit();

	strcpy(emp_sen.esn_numb,emp_rec.em_numb);
	emp_sen.esn_month = pay_per_it.ppi_end_date;
	strcpy(emp_sen.esn_pos, pos);
	strcpy(emp_sen.esn_class, class.c_code);

	retval = get_emp_sen(&emp_sen,BROWSE,0,e_mesg) ;
	if(retval < 0 && retval != UNDEF){
	  	DispError((char *)&s_sth,e_mesg) ;
	 	retval = PrntRec(e_mesg);
	  	if(retval < 0){
	  		DispError((char *)&s_sth,e_mesg) ;
	  	}
	  	return(ERROR);
	}

	strcpy(tmp_sen.tsn_numb, emp_rec.em_numb); 

	tmp_sen.tsn_month = pay_per_it.ppi_end_date;
	strcpy(tmp_sen.tsn_pos, pos);
	strcpy(tmp_sen.tsn_class, class.c_code);

	err = get_tmp_sen(&tmp_sen,UPDATE,0,e_mesg);
	if(err < 0 && err != UNDEF){
	  	DispError((char *)&s_sth,e_mesg) ;
	 	err = PrntRec(e_mesg);
	  	if(err < 0){
	  		DispError((char *)&s_sth,e_mesg) ;
	  	}
	  	return(ERROR);
	}
	if(err == UNDEF)
		mode = ADD;
	else
		mode = UPDATE;

	strcpy(sen_par.sn_position,pos);
	sen_par.sn_eff_date = get_date();
	flg_reset(SEN_PAR);

	err = get_n_sen_par(&sen_par, BROWSE, 0, BACKWARD, e_mesg);
	if(err < 0) {
  		DispError((char *)&s_sth,e_mesg);
	 	err = PrntRec(e_mesg);
	  	if(err < 0){
	  		DispError((char *)&s_sth,e_mesg) ;
	  	}
		return(ERROR);
	}
	seq_over(SEN_PAR);
	if(strcmp(sen_par.sn_position,pos)!=0){
		sprintf(e_mesg,"Error Reading Seniority Parameter File");
		DispError((char *)&s_sth,e_mesg);
	 	err = PrntRec(e_mesg);
	  	if(err < 0){
	  		DispError((char *)&s_sth,e_mesg) ;
	  	}
		return(ERROR);
	}

        temp_units0 = 0;
        temp_units1 = 0;

	if((strcmp(position.p_type,"FT") != 0) &&
			(strcmp(position.p_type,"PT") != 0)){
	  if(month != month2){
	    strcpy(pay_period.pp_code, pay_param.pr_payper);
	    pay_period.pp_year = 0;
	    flg_reset(PAY_PERIOD);

	    err = get_n_pay_per(&pay_period,BROWSE, 0,FORWARD, e_mesg) ;
	    if(err < 0) {
	  	DispError((char *)&s_sth,e_mesg);
	 	err = PrntRec(e_mesg);
	  	if(err < 0){
	  		DispError((char *)&s_sth,e_mesg) ;
	  	}
	  	return(ERROR) ;
	    }
	    if(strcmp(pay_period.pp_code,pay_param.pr_payper)!=0){
		sprintf(e_mesg,"Error Reading Pay Period File");
	  	DispError((char *)&s_sth,e_mesg);
	 	err = PrntRec(e_mesg);
	  	if(err < 0){
	  		DispError((char *)&s_sth,e_mesg) ;
	  	}
		return(ERROR);
	    }
	    seq_over(PAY_PERIOD);

	    day = pay_per_it.ppi_st_date % 100;
	    day2 = pay_per_it.ppi_end_date % 100;
	    if(day > day2){	/* split pay period	*/
	    	no_weeks = (52 / pay_period.pp_numb);
	   	tmp_day = d_month[month-1] - day;
	 	week = (tmp_day/7) + 1;
		tmp_day = tmp_day - (7* (week-1));
	    }
	    else
		week = 0; /* Not a split pay period	*/

	    if(sched_flag == 1){
	      if(emp_sched1.es_week < week){
	        temp_units0 = 0;
	        for(j=0 ; j<7 ; j++) {
		    temp_units0 += emp_sched1.es_units[j];
	        }
	      }
	      else if(emp_sched1.es_week == week){

	          tmp_day = tmp_day % 7; 
	          temp_units0 = 0;
	          for(j=0 ; j<=tmp_day ; j++) {
		    temp_units0 += emp_sched1.es_units[j];
	          }
	          temp_units1 = 0;
	          for(j=tmp_day+1 ; j<7 ; j++) {
		    temp_units1 += emp_sched1.es_units[j];
	          }
	      }
	      else{
	          temp_units1 = 0;
	          for(j=0 ; j<7 ; j++) {
		    temp_units1 += emp_sched1.es_units[j];
	          }
	      }
	    }
	    else{
	      if(time_rec.tm_week < week){
	        temp_units0 = 0;
	        for(j=0 ; j<7 ; j++) {
		    temp_units0 += time_rec.tm_units[j];
	        }
	      }
	      else if(time_rec.tm_week == week){
	          tmp_day = tmp_day % 7; 
	          temp_units0 = 0;
	          for(j=0 ; j<=tmp_day ; j++) {
		    temp_units0 += time_rec.tm_units[j];
	          }
	          temp_units1 = 0;
	          for(j=tmp_day+1 ; j<7 ; j++) {
		    temp_units1 += time_rec.tm_units[j];
	          }
	      }
	      else{
	          temp_units1 = 0;
	          for(j=0 ; j<7 ; j++) {
		    temp_units1 += time_rec.tm_units[j];
	          }
	      }
	    }
	  }
	  else{
	        temp_units1 = 0;
	        for(j=0 ; j<7 ; j++) {
	    	  if(sched_flag == 1)
	          	temp_units1 += emp_sched1.es_units[j];
		  else
	         	temp_units1 += time_rec.tm_units[j];
	        }
	  }
	  if(mode == UPDATE){
	    if(sen_par.sn_num_hrs_day != 0){
		tmp_sen.tsn_cas_hrs0 += D_Roundoff(temp_units0);
		tmp_sen.tsn_cas_totd0 += D_Roundoff(temp_units0 /
					 sen_par.sn_num_hrs_day);
		tmp_sen.tsn_cas_hrs1 += D_Roundoff(temp_units1);
		tmp_sen.tsn_cas_totd1 += D_Roundoff(temp_units1 /
					 sen_par.sn_num_hrs_day);
	    }
	    else{
		tmp_sen.tsn_cas_days0 += D_Roundoff(temp_units0);
		tmp_sen.tsn_cas_totd0 += D_Roundoff(temp_units0);
		tmp_sen.tsn_cas_days1 += D_Roundoff(temp_units1);
		tmp_sen.tsn_cas_totd1 += D_Roundoff(temp_units1);
	    }
	  }
	  else{
	    if(sen_par.sn_num_hrs_day != 0){
		tmp_sen.tsn_cas_hrs0 = D_Roundoff(temp_units0);
		tmp_sen.tsn_cas_days0 = 0;
		tmp_sen.tsn_cas_totd0 = D_Roundoff(temp_units0 /
					 sen_par.sn_num_hrs_day);
		tmp_sen.tsn_perm_days0 = 0;
		tmp_sen.tsn_cas_hrs1 = D_Roundoff(temp_units1);
		tmp_sen.tsn_cas_days1 = 0;
		tmp_sen.tsn_cas_totd1 = D_Roundoff(temp_units1 /
					 sen_par.sn_num_hrs_day);
		tmp_sen.tsn_perm_days1 = 0;
	    }
	    else{
		tmp_sen.tsn_cas_hrs0 = 0;
		tmp_sen.tsn_cas_days0 = D_Roundoff(temp_units0);
		tmp_sen.tsn_cas_totd0 = D_Roundoff(temp_units0);
		tmp_sen.tsn_perm_days0 = 0;
		tmp_sen.tsn_cas_hrs1 = 0;
		tmp_sen.tsn_cas_days1 = D_Roundoff(temp_units1);
		tmp_sen.tsn_cas_totd1 = D_Roundoff(temp_units1);
		tmp_sen.tsn_perm_days1 = 0;
	    }
	  }
	}
	else{
	  if(retval != UNDEF) return(NOERROR);
	  if(mode != ADD && sched_flag != 1) return(NOERROR);

	  /* Get Number of Seniority Days	*/
	  GetSen();

	  /* Get Number of Non-Seniority Days	*/
	  GetNonSen();

	  tmp_sen.tsn_cas_hrs0 = 0;
	  tmp_sen.tsn_cas_days0 = 0;
	  tmp_sen.tsn_cas_totd0 = 0;
	  tmp_sen.tsn_cas_hrs1 = 0;
	  tmp_sen.tsn_cas_days1 = 0;
	  tmp_sen.tsn_cas_totd1 = 0;
	  if(sched_flag == 1){
	    tmp_sen.tsn_perm_days0 += D_Roundoff((double)num_sen_days0 *
					(emp_rec.em_sen_perc / 100.0) *
				(emp_sched1.es_amount / emp_rec.em_perc));
	    tmp_sen.tsn_perm_days1 += D_Roundoff((double)num_sen_days1*
					(emp_rec.em_sen_perc / 100.0) *
				(emp_sched1.es_amount / emp_rec.em_perc));
	  }
	  else{
	    tmp_sen.tsn_perm_days0 = D_Roundoff((double)num_sen_days0 *
					(emp_rec.em_sen_perc / 100.0));
	    tmp_sen.tsn_perm_days1 = D_Roundoff((double)num_sen_days1*
					(emp_rec.em_sen_perc / 100.0));
	  }

	  /*   Accrual Attendance for the Pay Period	*/

	  if(num_sen_days0 != 0 || num_sen_days1 != 0)
	  	AttAcc();
	}
	tmp_total = tmp_sen.tsn_cas_hrs0 + tmp_sen.tsn_cas_days0 +
			tmp_sen.tsn_perm_days0 + tmp_sen.tsn_cas_totd0 +
			tmp_sen.tsn_cas_hrs1 + tmp_sen.tsn_cas_days1 +
			tmp_sen.tsn_perm_days1 + tmp_sen.tsn_cas_totd1;

	if(tmp_total != 0){
  		err = put_tmp_sen(&tmp_sen,mode,e_mesg);	
		if(err < 0) {
		 	DispError((char *)&s_sth,e_mesg);
	  		retval = PrntRec(e_mesg);
	  		if(retval < 0){
	  			DispError((char *)&s_sth,e_mesg) ;
	  		}
		  	return(ERROR);
		}
		err = commit(e_mesg);
		if(err < 0) {
			DispError((char *)&s_sth,e_mesg);
			roll_back(e_mesg);
			return(ERROR);
		}
	}
	else{
		roll_back(e_mesg);
		if(sched_flag != 0){
		  sprintf(e_mesg,"Employee does not have seniority");
	  	  retval = PrntRec(e_mesg);
	  	  if(retval < 0)
	  		DispError((char *)&s_sth,e_mesg) ;
	  	}
	}
	return(NOERROR);
}
/*--------------------------------------------------------------*/
GetPPit()
{
	int	retval;

	strcpy(pay_per_it.ppi_code,pay_param.pr_payper);
	if(sched_flag == 0)
		pay_per_it.ppi_numb = time_rec.tm_pp;
	else
		pay_per_it.ppi_numb = s_sth.s_payper1;
	pay_per_it.ppi_year = 9999;
	flg_reset(PAY_PER_ITEM);

	retval = get_n_pp_it(&pay_per_it,BROWSE,3,BACKWARD,e_mesg);
	if(retval < 0 || strcmp(pay_per_it.ppi_code,pay_param.pr_payper)!=0){
	  	fomer("Error Reading Pay Period Item File") ;
	  	return(NOERROR);
	}
	if(sched_flag == 0){
		if(pay_per_it.ppi_numb != time_rec.tm_pp){
	  	    return(NOERROR);
		}
	}
	else{
		if(pay_per_it.ppi_numb != s_sth.s_payper1){
	  	    return(NOERROR);
		}
	}
	seq_over(PAY_PER_ITEM);
	if(pay_param.pr_st_mth == 1){
		start_mth = ((pay_param.pr_cal_st_dt / 100) % 100);
	}
	if(pay_param.pr_st_mth == 2){
		start_mth = ((pay_param.pr_fisc_st_dt / 100) % 100);
	}
	if(pay_param.pr_st_mth == 3){
		start_mth = ((pay_param.pr_schl_st_dt / 100) % 100);
	}
	day = (pay_per_it.ppi_st_date) % 100; 
	day2 = (pay_per_it.ppi_end_date) % 100; 
	month = (pay_per_it.ppi_st_date / 100) % 100; 
	month2 = (pay_per_it.ppi_end_date / 100) % 100; 

	return(NOERROR);
}
	
/*--------------------------------------------------------------*/
GetNonSen()
{
	int 	retval, i,j, curr_day, curr_month, last_month;
	long	attdate;

	strcpy(att_his.eah_numb, emp_rec.em_numb);
	att_his.eah_date = pay_per_it.ppi_st_date;
	flg_reset(EMP_ATT);

	for(;;){
		retval = get_n_emp_at(&att_his, BROWSE, 0, FORWARD, e_mesg);
		if(retval == EFL ||		
		    (strcmp(att_his.eah_numb, emp_rec.em_numb) != 0)){
			break;
		}
		if(retval < 0) {
			fomen(e_mesg);
			get();
			return(-1);
		}

		if(att_his.eah_date > pay_per_it.ppi_end_date)
			break;
		strcpy(att.at_code, att_his.eah_code);

		retval = get_att(&att,BROWSE,1,e_mesg);
		if(retval < 0)  {
			fomen(e_mesg);
			get();
			return(retval);
		}
		curr_month = ((att_his.eah_date /100) % 100);

		if(att.at_sen[0] == 'Y'){
		  if(month != month2){
			if(curr_month == month)
				num_sen_days0 --;
	    		else
				num_sen_days1 --;
		  }
		  else
			num_sen_days1 --;
		}

		att_his.eah_date ++;
		flg_reset(EMP_ATT);
	}
	seq_over(EMP_ATT);

	return(NOERROR);
}
/*--------------------------------------------------------------*/
GetSen()
{
	int	retval, i;

	Disp_Mth();
	if(curr_year > pay_per_it.ppi_st_date){
		month = start_mth;
		day = 1;
	}

	if(month != month2){
	  for(i=day; i<= d_month[month-1]; i++){
	      if(sen_par.sn_month[month-(start_mth)][i-1] == '.')
		num_sen_days0 ++;
	  }
	  for(i=1; i<= day2; i++){
	      if(month < month2){
	  	if(sen_par.sn_month[month2-start_mth][i-1] == '.')
			num_sen_days1 ++;
	      }
	      else{
	  	if(sen_par.sn_month[month2+start_mth-2][i-1] == '.')
			num_sen_days1 ++;
	      }
	  }
	}
	else{
	    if(start_mth <= month2){
		    for(i=day; i<= day2; i++){
		      if(sen_par.sn_month[month2-start_mth][i-1] == '.')
			num_sen_days1 ++;
		    }
	    }
	    else{
		    for(i=day; i<= day2; i++){
		      if(sen_par.sn_month[month2+start_mth-2][i-1] == '.')
			num_sen_days1 ++;
		    }
	    }
	}
	return(NOERROR);
}
/*-----------------------------------------------------------*/
Disp_Mth()
{
	int	retval;
	
	if(pay_param.pr_st_mth == 1){
		start_mth = ((pay_param.pr_cal_st_dt / 100) % 100);
		curr_year = pay_param.pr_cal_st_dt;
	}
	if(pay_param.pr_st_mth == 2){
		start_mth = ((pay_param.pr_fisc_st_dt / 100) % 100);
		curr_year = pay_param.pr_fisc_st_dt;
	}
	if(pay_param.pr_st_mth == 3){
		start_mth = ((pay_param.pr_schl_st_dt / 100) % 100);
		curr_year = pay_param.pr_schl_st_dt;
	}
	return(NOERROR);
}
/*-----------------------------------------------------------------*/
InitPrinter1()

{
	char	resp[2] ;
	char	discfile[15] ;

	/* Always to Printer */
	STRCPY(resp,"P");
	discfile[0]= '\0';
	PG_SIZE = 60;

	if( opn_prnt( resp, discfile, 1, e_mesg, 1 /* spool */)<0 ){
		return(REPORT_ERR);
	}
	pgcnt = 0;		/* Page count is zero */
	LNSZ = 132;		/* line size in no. of chars */
	linecnt = PG_SIZE;	/* Page size in no. of lines */

	return(NOERROR) ;
}
/******************************************************************************
Prints the headings
******************************************************************************/
static
PrntHdg()	/* Print heading  */
{
	long	sysdt ;
	int	offset;

	if( pgcnt && term < 99)   /* new page and display */
		if(next_page()<0) return(EXIT);	
		
	if( pgcnt || term < 99) { /* if not the first page or display */
		if( rite_top()<0 ) return( -1 );	/* form_feed */
	}
	else
		linecnt = 0;
	pgcnt++; 			/* increment page no */

	mkln( 1, PROG_NAME, 10 );
#ifdef ENGLISH
	mkln( 103, "Date:", 5 );
#else
	mkln( 103, "Date:", 5 );
#endif
	sysdt = get_date() ;
	tedit( (char *)&sysdt,"____/__/__",line+cur_pos, R_LONG ); 
	cur_pos += 10;

#ifdef ENGLISH
	mkln( 122, "PAGE:", 5 );
#else
	mkln( 122, "PAGE:", 5 );
#endif
	tedit( (char *)&pgcnt,"__0_",  line+cur_pos, R_SHORT ); 
	cur_pos += 4;
	if(prnt_line() < 0 )	return(REPORT_ERR);
 
	offset = ( LNSZ-strlen(pa_rec.pa_co_name) )/2;
	mkln( offset, pa_rec.pa_co_name, strlen(pa_rec.pa_co_name) );
	if( prnt_line()<0 )	return(REPORT_ERR);

#ifdef ENGLISH
	mkln((LNSZ-27)/2,"SENIORITY ERROR AUDIT TRAIL", 27 );
#else
	mkln((LNSZ-26)/2,"TRANSLATE        ", 26 );
#endif
	if(prnt_line() < 0 )	return(REPORT_ERR);
	if(prnt_line() < 0 )	return(REPORT_ERR);

	mkln(3,"EMPLOYEE",8);
	mkln(14,"EMPLOYEE NAME",13);
	mkln(14,"COMMENT",7);

	if(prnt_line() < 0 )	return(REPORT_ERR);
	if(prnt_line() < 0 )	return(REPORT_ERR);

	return(NOERROR);
}
/****************************************************************************/
static
PrntRec(err_mesg)
char	*err_mesg;
{
	char	txt_line[132];
	int	retval;

	mkln(1,emp_rec.em_numb,12);
	sprintf(txt_line,"%s, %s",
		emp_rec.em_last_name,
		emp_rec.em_first_name);
	mkln(15,txt_line,22);
	mkln(40,err_mesg,90);
	if(prnt_line() < 0 )	return(REPORT_ERR);
	mkln(40,err_mesg+91,90);
	if(prnt_line() < 0 )	return(REPORT_ERR);
	if(prnt_line() < 0 )	return(REPORT_ERR);
			
	else if(linecnt > PG_SIZE) {
		if((retval=PrntHdg()) == EXIT)	
			return(retval);
	}

	return(NOERROR);
}
/******************   END OF PROGRAM *******************************/
