/* repcd.h - used by repcd.c and repcd2.c */


#define	SCRNM1		"deduct"
#define	SCRNM2		"deduct2"
#define	PRGNM		"deduct"

#define	ALLOC_ERROR	-19
#define	MAX_KEYS	12

#ifdef ENGLISH

#define NEXT		'N'
#define EDITITEMS	'E'
#define INQREC		'I'
#define FIXED		'F'
#define PERCENT		'P'
#define ADDITEM		'A'
#define DELITEM		'D'
#define REACTIVATE	'R'
#define PREV		'P'
#define END 		'E'
#define ACTIVE		"ACT"
#define INACTIVE	"DEL"
#define ADDREC		'A'
#define	CHGREC		'C'
#define DELREC		'D'
#define EXIT		'E'
#define NEXTREC		'N'
#define PREVREC		'P'
#define ITEMEDIT	'I'
#define	HDREDIT		'H'
#define YES		'Y'
#define NO		'N'
#define	LINEEDIT	'L'
#define	SCREDIT		'S'
#define	FIRST_SCR	'1'
#define	SECOND_SCR	'2'
#define	CANCEL		'C'
#define	ALL		'A' 

#else		/* if FRENCH */

#define NEXT		'N'
#define EDITITEMS	'E'
#define INQREC		'I'
#define FIXED		'F'
#define PERCENT		'P'
#define ADDITEM		'A'
#define DELITEM		'D'
#define REACTIVATE	'R'
#define PREV		'P'
#define END 		'E'
#define ACTIVE		"ACT"
#define INACTIVE	"DEL"
#define ADDREC		'A'
#define	CHGREC		'C'
#define DELREC		'D'
#define EXIT		'E'
#define NEXTREC		'N'
#define PREVREC		'P'
#define ITEMEDIT	'I'
#define	HDREDIT		'H'
#define YES		'O'
#define NO		'N'
#define	LINEEDIT	'M'
#define	SCREDIT		'C'
#define	FIRST_SCR	'1'
#define	SECOND_SCR	'2'
#define	CANCEL		'A'
#define	ALL		'T' 

#endif


#define STEP		700
#define	PAGESIZE1	3
#define NO_PDS		5

#define FOUND		0
#define NOTFOUND	1
#define NO_CHANGE	2

/*-------------------- screen 1 information -------------------------*/

/* repcd1.sth - header for C structure generated by PROFOM EDITOR */
typedef struct{
	char	s_group[7];	/* group code */
	char	s_gdesc[16];	/* group description */
	char	s_fp[2];	/* amount f - p */
	double	s_amount;	/* amount */
	short	s_eeshare;	/* employee share */
	short	s_ershare;	/* employer share */
	char	s_status[4];	/* status */
	} S1_item;

typedef struct{
	char	dmp[2];		/* deduct monthly periods y/n */
	} S3_item;

typedef struct{
	long	s_sysdate;	/* 300 system date */
	char	s_ftn[2];	/* 500 fucntion */
	char	s_dedcd[7];	/* 600 deduction code */
	char	s_paypd[7];	/* 700 pay period */
	short	s_field;	/* 800 field: */
	char	s_desc[31];	/* 900 deduction description */
	char	s_secode[3];	/* 1100 second code */
	char	s_t4[2];	/* 1200 t4 code */
	char	s_tdesc[13];	/* 1300 t4 description */
	double	s_earn;		/* 1400 minimum earnings */
	double	s_cont;		/* 1500 maximum contributions */
	S3_item	s_monpd[NO_PDS];/* 1600 - 2000 deduct montlhy pay periods */
	short	s_page;		/* 2200 line number 1 */
	S1_item	s_groups[PAGESIZE1];/*2300 - 4600 group information */
	char	s_mesg[78];	/* 4700 message line */
	char	s_opt[2];	/* 4800 message option line */
	} s1_struct;

#define FTN_FLD1	500	/* function field */
#define DEDCD_FLD1	600	/* deduction code field */
#define	PAYPD_FLD1	700	/* pay period code field */
#define	CHG_FLD1	800	/* field: prompt */

#define DDESC_FLD	1000/* deduction description field */
#define SECODE_FLD	1100 	/* second code field */
#define	T4_FLD		1200	/* t4 code field */
#define	TDESC_FLD	1300	/* t4 description field */

#define EARN_FLD	1400	/* minimum earnings field */
#define CONT_FLD	1500	/* maximum contribution field */
#define PD1_FLD		1600	/* deduct monthly pay periods */
#define PD2_FLD		1700	
#define PD3_FLD		1800
#define PD4_FLD		1900
#define PD5_FLD		2000

#define PAGE_FLD	2200	/* page number field */
#define	GRP_FLD2	3000

#define	STDESC_FLD	2400	/* start group description field */

#define STFP_FLD	2500	/* start f - p field */
#define FP_FLD2		3200	
#define ENDFP_FLD	3900

#define STAMT_FLD	2600	/* start amount field */
#define STESH_FLD	2700	/* start employee share field */
#define ESH_FLD2	3400
#define ENDESH_FLD	4100

#define STRSH_FLD	2800	/* start employer share field */
#define STSTAT_FLD	2900	/* start status field */

#define	ITEM_ST_FLD	2300
#define	ITEM_END_FLD	4300
#define	STATUS_FLD	600

#define	MESG_FLD1	4400
#define	OPT_FLD1	4500

/*-------------------- screen 2 information -------------------------*/

/* repcd2.sth - header for C structure generated by PROFOM EDITOR */

typedef	struct	{
	long	s_sysdate;	/* 300 system date */
	char	s_ftn[2];	/* 500 function */
	char	s_dedcd[7];	/* 600 deduction code */
	char	s_paypd[7];	/* 700 pay period code */
	short	s_field;	/* 800 field: */
	short	s_fund;		/* 1000 fund number */
	char	s_account[19];	/* 1100 expense GL account */
	long	s_acckey[12];	/* 1300 - 2400 account keys */
	char	s_mesg[78];	/* 2500 message field */
	char	s_opt[2];	/* 2600	message option */
	} s2_struct;

#define FTN_FLD2	500	/* function field */
#define DEDCD_FLD2	600	/* deduction code field */
#define PAYPD_FLD2	700	/* pay period code field */
#define	CHG_FLD2	800	/* field: prompt */

#define FUND_FLD	1000	/* fund field */
#define ACC_FLD		1100	/* expense GL acount field */

#define ACCKEY_FLD1	1300	/* account key fields */
#define ACCKEY_FLD2	1400
#define ACCKEY_FLD3	1500
#define ACCKEY_FLD4	1600
#define ACCKEY_FLD5	1700
#define ACCKEY_FLD6	1800
#define ACCKEY_FLD7	1900
#define ACCKEY_FLD8	2000
#define ACCKEY_FLD9	2100
#define ACCKEY_FLD10	2200
#define ACCKEY_FLD11	2300
#define ACCKEY_FLD12	2400

#define	MESG_FLD2	2500	/* message line */
#define	OPT_FLD2	2600	/* message option field */

static	Deduction	deduct;	/* deduction file */
static	Emp_dh		empdh;	/* employee deduction history file */
static  Ctl_rec		control;/* control file */
static 	Gl_rec		glmast; /* gl master file */
static  Ded_group	dedgrp, pre_dedgrp; /* deduction group file */
static  Pay_per		payper; /* pay period file */
static  Pay_param	param;	/* payroll parameter file */
static  T4_rec		t4rec;	/* t4 file */
static  Sch_rec		school;	/* school file */
static  Gl_acct		gl_acct;	/* gl account file */

struct stat_rec	sr;
s1_struct	s1_sth, tmp1_sth;
s2_struct	s2_sth, tmp2_sth;

char	e_mesg[80];

/* link list node for holding one page of entries */

typedef struct Page {
	S1_item	Items[PAGESIZE1] ;	/* Items Information */
	struct	Page	*PrevPage ;	/* ptr to previous page */
	struct	Page	*NextPage ;	/* ptr to next page */
	char	I_Status[PAGESIZE1][2];	/* item status ie A(DD) C(hange) */
	short	NoItems;		/* number of Items on the page */
	short	Pageno;			/* Page number */
}	Page;

static	Page	*FirstPage,		/* Address of First Page */
		*CurPage,		/* Address of Current Page */
		*CurLast,		/* Address of Curr. record last page */
		*LastPage;		/* Address of Last Page of Memory
					   Allocated */

static int totalitemsadded;		/* total items added in add session */
