/*------------------------------------------------------------------------
Source Name: updt_sen.c
System     : Personnel/Payroll.
Created  On: July 13, 1991.
Created  By: Eugene Roy.

DESCRIPTION:
	Program to update seniority.

MODIFICATIONS:        

Programmer     YY/MM/DD       Description of modification
~~~~~~~~~~     ~~~~~~~~       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
------------------------------------------------------------------------*/
#define 	MAIN 
#define		MAINFL	TMP_SEN		/* main file used */

#include <stdio.h>
#include <cfomstrc.h>
#include <repdef.h>
#include <bfs_defs.h>
#include <bfs_com.h>
#include <bfs_pp.h>

#define	SYSTEM		"ACCOUNTS PAYABLE"	/* Sub System Name */
#define	MOD_DATE	"13-JUL-92"		/* Program Last Modified */
#define	SCR_NAME	"updt_sen"		/* First screen */

#define OPTION_FLD	400
#define MESG_FLD	600

#define EXIT	12

#ifdef ENGLISH
#define PROCCHQ	'U'
#define EXITOPT	'E'

#define	YES	'Y'
#define NO	'N'
#define CANCEL	'C'

#else
#define PROCCHQ	'T'
#define EXITOPT	'F'

#define	YES	'O'

#define NO	'N'
#define CANCEL	'A'

#endif
/* cheque.sth - header for C structure generated by PROFOM EDITOR */

typedef struct	{

	char	s_pgm[11];	/* STRING XXXXXXXXXX 	Field 100 */
	long	s_rundate;	/* NUMERIC 9999F99F99 	Field 300 */
	char	s_resp[2]; 	/* STRING X 		Field 900 */
	char	s_mesg[78];	/* STRING X(78) 	Field 1500 */
	char	s_opt[2];	/* STRING X 		Field 1600 */
	} S_STRUCT;

static	S_STRUCT	s_sth ;

/* PROFOM Related variables */

struct  	stat_rec  sr;	/* PROFOM status rec */

static	Pa_rec		pa_rec ;
static	Pay_param	pay_param;
static	Emp_sen	emp_sen;
static	Tmp_sen	tmp_sen;
static	Time	time_rec;
static	Sen_par	sen_par;
static	Pay_per_it	pay_per_it;
static	Att	att;
static	Emp	emp_rec;
static	Emp_at_his	att_his, pre_att_his;
static	Barg_unit	barg_unit;

static	Position	position;
static	Class	class;

char 	e_mesg[100];	/* dbh will return err msg in this */

short	d_month[12] = { 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 };

int	Validation();
int	Window();

double 	D_Roundoff();

static	int	day, day2, month, month2, curr_month;
static	int	start_mth;
static	long	curr_year;

static	double	non_sen_days;
static	double	num_sen_days0, num_sen_days1;
static	int	sched_flag;

static char	emp_name[48];

main(argc,argv)
int argc;
char *argv[];
{
int 	retval ;

	strncpy(SYS_NAME,SYSTEM,50);	/* Sub system name */
	strncpy(CHNG_DATE,MOD_DATE,10);	/* Modification Date */
	proc_switch(argc, argv, CHQHIST) ; 	/* Process Switches */

	STRCPY(sr.termnm,terminal);	/* Copy Terminal Name */

	retval = get_param(&pa_rec, BROWSE, 1, e_mesg) ;
	if(retval < 1) {

#ifdef ENGLISH
		printf("Parameters Are Not Setup..") ;
#else
		printf("Parametres ne sont pas etablis..") ;
#endif
		close_dbh() ;
		exit(-1) ;
	}

	if (Initialize()<0)
		exit(-1);		/* Initialization routine */

	if ( Process() < 0) { 		/* Initiate Process */
		Close();
		exit(-1);
	}

	Close();			/* return to menu */
	exit(NOERROR);

} /* END OF MAIN */

/*-------------------------------------------------------------------*/
/* Reset information */
Close()
{
	/* Set terminal back to normal mode from PROFOM */

	fomcs();
	fomrt();
	close_dbh();			/* Close files */
}
/*-------------------------------------------------------------------*/
/* Initialize PROFOM  and Screens*/
Initialize()
{
	if(InitProfom()<0) { 			/* Initialize PROFOM */
		fomcs();
		fomrt();
		return(-1);
	}	
	if(InitScreens()<0) { 
		fomcs();
		fomrt();
		return(-1);
	}	
	return(NOERROR);
}

/*-------------------------------------------------------------------*/
/* Initialize PROFOM */

InitProfom()
{
	fomin(&sr);
	/* Check for Error */
	ret( err_chk(&sr) );

	fomcf(1,1);			/* Enable Print screen option */
	return(NOERROR);
}	/* InitProfom() */
/*----------------------------------------------------------------*/
/* Initialize screens before going to process options */
InitScreens()
{
	int	retval ;

	STRCPY(sr.scrnam,NFM_PATH);
	strcat(sr.scrnam,SCR_NAME) ;

	STRCPY(s_sth.s_pgm,PROG_NAME);
	s_sth.s_rundate = get_date();	/* get Today's Date in YYMMDD format */
	s_sth.s_mesg[0] = HV_CHAR ;
	s_sth.s_opt[0] = HV_CHAR ;

	return(NOERROR);

}	/* InitScreens() */
/*-----------------------------------------------------------------*/
Process()
{
	int	err;

	s_sth.s_mesg[0] = HV_CHAR;
	DispMesgFld((char *)&s_sth);	
	for( ; ; ){

#ifdef ENGLISH
		fomer("U(pdate Seniority), E(xit)");
#else
		fomer("T(raitement de seniorite), F(in)");
#endif

		sr.nextfld = OPTION_FLD;
		fomrf((char *)&s_sth);
		ret(err_chk(&sr));

		switch(s_sth.s_resp[0]) {
		case  EXITOPT :
			return(EXIT);
		case  PROCCHQ :
			CHKACC(err,ADD,e_mesg);	
			CHKACC(err,UPDATE,e_mesg);	
			err = SenProcess() ;
			break ;
		default :
			continue;
		}

		if(NOACCESS == err) {
			fomen(e_mesg);
			get();
		}
		if(PROFOM_ERR == err)	return(PROFOM_ERR);  /* PROFOM ERROR */
		if(DBH_ERR == err) {
			DispError((char *)&s_sth,e_mesg);
#ifdef ENGLISH
			sprintf(e_mesg,"%s %d Dberror: %d Errno: %d",
				"System Error... Iserror:",
				iserror, dberror, errno);
#else
			sprintf(e_mesg,"%s %d Dberror: %d Errno: %d",
				"Erreur du systeme... Iserror:",
				iserror, dberror, errno);
#endif
			DispError((char *)&s_sth,e_mesg);
			return(DBH_ERR); /* DBH ERROR */
		
		}
	}      /*   end of the for( ; ; )       */
}
/*-----------------------------------------------------------------*/
SenProcess()
{
	int 	retval ;
	int	prntno;

	retval = ConfirmScreen() ;
	if( retval != YES ) 
		return(NOERROR) ;
	
	if(retval != YES) 
	return(NOERROR) ;

	retval = ChequeProcess();
	if( retval < 0 ) 
		return(retval) ;

	return(NOERROR) ;
}
/*-----------------------------------------------------------------------*/
/*                                                                       */
/* Reads the cheque and prints the cheque after accumulating invoices.   */
ChequeProcess()
{
	int	err ;
	int	mode, month;
	int	tmp_month, tmp_date;

#ifdef ENGLISH
	STRCPY(s_sth.s_mesg, "Seniority Being Updated, PLEASE WAIT");
#else
	STRCPY(s_sth.s_mesg, "Traitement de la seniorite en progres, ATTENDEZ S.V.P.");
#endif
	DispMesgFld((char *)&s_sth);
	fflush(stdout) ;

 	err = get_pay_param(&pay_param,BROWSE,1,e_mesg);
	if(err < 0) {
  		DispError((char *)&s_sth,e_mesg);
		return(err);
	}

	if(pay_param.pr_st_mth == 1){
		start_mth = ((pay_param.pr_cal_st_dt / 100) % 100);
	}
	if(pay_param.pr_st_mth == 2){
		start_mth = ((pay_param.pr_fisc_st_dt / 100) % 100);
	}
	if(pay_param.pr_st_mth == 3){
		start_mth = ((pay_param.pr_schl_st_dt / 100) % 100);
	}

	tmp_sen.tsn_numb[0] = '\0';
	tmp_sen.tsn_month = 0;
	tmp_sen.tsn_pos[0] = '\0';
	tmp_sen.tsn_class[0] = '\0';
	flg_reset(TMP_SEN);

	for( ; ; ){
	  err = get_n_tmp_sen(&tmp_sen,BROWSE,0,FORWARD,e_mesg);
	  if(err < 0 && err != EFL){
	  	DispError((char *)&s_sth,e_mesg) ;
	  	return(ERROR);
	  }
	  if(err == EFL) break;

	  strcpy(emp_rec.em_numb, tmp_sen.tsn_numb);

	  err = get_employee(&emp_rec,BROWSE,0,e_mesg);
	  if(err != NOERROR){
  		DispError((char *)&s_sth,e_mesg) ;
 		return(ERROR);
  	  }

	  err=UsrBargVal(UPDATE,emp_rec.em_numb,emp_rec.em_barg,1,e_mesg);
	  if(err < 0){
		continue;
	  }
	
	  sprintf(e_mesg,"Employee Number: %s",tmp_sen.tsn_numb);
	  fomen(e_mesg);
	  fflush(stdout);

	  /*   Accrual Attendance for the Pay Period	*/

	  if(tmp_sen.tsn_sick_acc0 != 0 || tmp_sen.tsn_sick_acc1 != 0){
	  	err = AttAcc();
		if(err < 0 )
			continue;
	  }

	  if(tmp_sen.tsn_vac_acc0 != 0 || tmp_sen.tsn_vac_acc1 != 0){
	  	err = VacAcc();
		if(err < 0 )
			continue;
	  }

	  strcpy(emp_sen.esn_numb,tmp_sen.tsn_numb);
	  emp_sen.esn_month = 6;
	  strcpy(emp_sen.esn_pos,tmp_sen.tsn_pos);
	  strcpy(emp_sen.esn_class,tmp_sen.tsn_class);

	    err = get_emp_sen(&emp_sen,UPDATE,0,e_mesg);
	    if(err < 0 && err != UNDEF){
	  	DispError((char *)&s_sth,e_mesg) ;
	  	return(ERROR);
	    }
	    if(err == UNDEF){
		roll_back(e_mesg);
		mode = ADD;
	    	emp_sen.esn_cas_hrs = tmp_sen.tsn_cas_hrs0;
	 	emp_sen.esn_cas_days = tmp_sen.tsn_cas_days0;
	   	emp_sen.esn_perm_days = tmp_sen.tsn_perm_days0;
	   	emp_sen.esn_cas_totd = tmp_sen.tsn_cas_totd0;
	    }
	    if(err != UNDEF){
		mode = UPDATE;
	    	emp_sen.esn_cas_hrs += tmp_sen.tsn_cas_hrs0;
	 	emp_sen.esn_cas_days += tmp_sen.tsn_cas_days0;
	   	emp_sen.esn_perm_days += tmp_sen.tsn_perm_days0;
	   	emp_sen.esn_cas_totd += tmp_sen.tsn_cas_totd0;
	    }

  	    err = put_emp_sen(&emp_sen,mode,e_mesg);	
	    if(err < 0) {
		if(err == DUPE)	continue;
	 	DispError((char *)&s_sth,e_mesg);
	  	return(ERROR);
	    }
	  err = commit(e_mesg);
	  if(err < 0) {
		DispError((char *)&s_sth,e_mesg);
		roll_back(e_mesg);
		return(ERROR);
	  }
	}
	seq_over(TMP_SEN);

/*	unlink_file(TMP_SEN);*/

#ifdef ENGLISH
	STRCPY(s_sth.s_mesg, "Seniority Updated Successfully");
#else
	STRCPY(s_sth.s_mesg, "Traitement de Seniorite Reussie");
#endif
	DispMesgFld((char *)&s_sth) ;
	fflush(stdout) ;
	return(NOERROR) ;

}
/*----------------------------------------------------------------*/
/* Validation function() for Key and Header fields when PROFOM returns
  RET_VAL_CHK */

Validation()
{
	return(NOERROR) ;
}	/* Validation() */
/*----------------------------------------------------------------*/
Window()
{
	return(NOERROR);
}
/*-----------------------------------------------------------------------*/
/*                                                                       */
ConfirmScreen() 
{
	int	err ;

	for( ; ; ) {
#ifdef ENGLISH
		err = GetOption((char *)&s_sth,"Y(es), C(ancel)", "YC");
#else
		err = GetOption((char *)&s_sth,"O(ui), A(nnuler)", "OA"); 
#endif
		if(err == PROFOM_ERR) return(err) ;

		switch(err) {
		case  YES :
			return(YES) ;
		case  CANCEL :
#ifdef ENGLISH
			err = GetOption((char *)&s_sth,"Confirm the Cancel (Y/N)?", "YN") ;
#else
			err = GetOption((char *)&s_sth,"Confirmer l'annulation (O/N)?", "ON") ;
#endif
			if(err == YES) { 
				roll_back(e_mesg) ;	/* Unlock  Records */
				return(CANCEL) ;
			}
			break ;
		}	/* switch err */

		if(err == PROFOM_ERR) return(err) ;
		if(err == DBH_ERR) return(err) ;
	}	/* for(; ; ) */
}	/* ConfirmScreen() */

/*-----------------------------------------------------------------------*/
GetPos(pos)
char	*pos;
{
	int	retval;

	strcpy(position.p_code,pos);

	retval = get_position(&position,BROWSE,0,e_mesg);
	if(retval < 0) {
		DispError((char *)&s_sth,e_mesg);
	}

	return(NOERROR);
}
/*--------------------------------------------------------------*/
GetClass(class_rec)
char	*class_rec;
{
	int	retval;

	strcpy(class.c_code,class_rec);
	class.c_date = s_sth.s_rundate;
	flg_reset(CLASSIFICATION);

	retval = get_n_class(&class,BROWSE,0,BACKWARD,e_mesg);
	if(retval < 0 && retval != EFL){
		DispError((char *)&s_sth, e_mesg);
		return(NOERROR);
	}
	if((strcmp(class.c_code,class_rec) != 0) || retval == EFL){
		sprintf(e_mesg,"Classification Code Does Not Exist %s",class_rec);
		DispError((char *)&s_sth, e_mesg);
	    	return(NOERROR);
	}
	seq_over(CLASSIFICATION);
	return(NOERROR);
}
/*--------------------------------------------------------------*/
AttAcc()
{
	int	i, j, err;
	double	total, fraction;
	long	dollars;

	err = get_employee(&emp_rec,UPDATE,0,e_mesg);
	if(err != NOERROR){
  		DispError((char *)&s_sth,e_mesg) ;
 		return(ERROR);
  	}
	if(6 == 1)
		month = 12;
	else
		month = 7 - 1;

	month2 = 6;

	if(month >= start_mth){
		i = month-start_mth;
	}
	else{
		i = month+start_mth-2;
	}
	if(month2 >= start_mth){
		j = month2-start_mth;
	}
	else{
		j = month2+start_mth-2;
	}

	emp_rec.em_sck_acc[i] += tmp_sen.tsn_sick_acc0;
/*	emp_rec.em_sck_acc[j] += tmp_sen.tsn_sick_acc1;*/

  	err = put_employee(&emp_rec,UPDATE,e_mesg);	
	if(err < 0) {
	 	DispError((char *)&s_sth,e_mesg);
	  	return(ERROR);
	}
	err = commit(e_mesg);
	if(err < 0) {
		DispError((char *)&s_sth,e_mesg);
		roll_back(e_mesg);
		return(ERROR);
	}

	return(NOERROR);
}
/*--------------------------------------------------------------*/
VacAcc()
{
	int	i, j, err;
	double	total, fraction;
	long	dollars;

	err = get_employee(&emp_rec,UPDATE,0,e_mesg);
	if(err != NOERROR){
  		DispError((char *)&s_sth,e_mesg) ;
 		return(ERROR);
  	}

	if(6 == 1)
		month = 12;
	else
		month = 7 - 1;

	month2 = 6;

	if(month >= start_mth){
		i = month-start_mth;
	}
	else{
		i = month+start_mth-2;
	}
	if(month2 >= start_mth){
		j = month2-start_mth;
	}
	else{
		j = month2+start_mth-2;
	}

	emp_rec.em_vac_acc[i] += tmp_sen.tsn_vac_acc0;
/*	emp_rec.em_vac_acc[j] += tmp_sen.tsn_vac_acc1;*/

  	err = put_employee(&emp_rec,UPDATE,e_mesg);	
	if(err < 0) {
	 	DispError((char *)&s_sth,e_mesg);
	  	return(ERROR);
	}
	err = commit(e_mesg);
	if(err < 0) {
		DispError((char *)&s_sth,e_mesg);
		roll_back(e_mesg);
		return(ERROR);
	}

	return(NOERROR);
}
/*-------------------- E n d   O f   P r o g r a m ---------------------*/
