/*------------------------------------------------------------------------
Source Name: updt_sen.c
System     : Personnel/Payroll.
Created  On: July 13, 1991.
Created  By: Eugene Roy.

DESCRIPTION:
	Program to update seniority.

MODIFICATIONS:        

Programmer     YY/MM/DD       Description of modification
~~~~~~~~~~     ~~~~~~~~       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

------------------------------------------------------------------------*/
#define 	MAIN 
#define		MAINFL	TMP_SEN		/* main file used */

#include <stdio.h>
#include <isnames.h>
#include <cfomstrc.h>
#include <repdef.h>
#include <bfs_defs.h>
#include <bfs_com.h>
#include <bfs_pp.h>

#define	SYSTEM		"ACCOUNTS PAYABLE"	/* Sub System Name */
#define	MOD_DATE	"13-JUL-92"		/* Program Last Modified */
#define	SCR_NAME	"updt_sen"		/* First screen */

#define OPTION_FLD	400
#define MESG_FLD	600

#define EXIT	12

#ifdef ENGLISH
#define PROCCHQ	'U'
#define EXITOPT	'E'

#define	YES	'Y'
#define NO	'N'
#define CANCEL	'C'

#else
#define PROCCHQ	'T'
#define EXITOPT	'F'

#define	YES	'O'

#define NO	'N'
#define CANCEL	'A'

#endif
/* cheque.sth - header for C structure generated by PROFOM EDITOR */

typedef struct	{

	char	s_pgm[11];	/* STRING XXXXXXXXXX 	Field 100 */
	long	s_rundate;	/* NUMERIC 9999F99F99 	Field 300 */
	char	s_resp[2]; 	/* STRING X 		Field 900 */
	char	s_mesg[78];	/* STRING X(78) 	Field 1500 */
	char	s_opt[2];	/* STRING X 		Field 1600 */
	} S_STRUCT;

static	S_STRUCT	s_sth ;

/* PROFOM Related variables */

struct  	stat_rec  sr;	/* PROFOM status rec */

static	Gl_rec		gl_rec ;
static	Tr_hdr		tr_hdr ;
static	Tr_item		tr_item ;
static	Jr_ent		jr_ent ;
static	Pa_rec		pa_rec ;
static	Pay_param	pay_param;
static	Emp_sen		emp_sen;
static	Tmp_sen		tmp_sen;
static	Emp		emp_rec;
static	Position	position;
static	Class		class;
static	Sen_par		sen_par;
static	Barg_unit	barg_unit;
static	Pay_per		pay_per;

char 	e_mesg[100];	/* dbh will return err msg in this */

short	d_month[12] = { 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 };

int	Validation();
int	Window();

double 	D_Roundoff();

static	int	month, month2;
static	int	start_mth;
static	long	tmp_seq_no;
static	short	item_no;
static	double	hours;
static	double	salary;
static	double	vacation;
static	double	code_total;
static	double	grand_total;

static int	PG_SIZE;
static char 	discfile[15];	/* for storing outputfile name */
static short	pgcnt; 		/* for page count */
static	char	last_barg[7];

main(argc,argv)
int argc;
char *argv[];
{
int 	retval ;

	strncpy(SYS_NAME,SYSTEM,50);	/* Sub system name */
	strncpy(CHNG_DATE,MOD_DATE,10);	/* Modification Date */
	proc_switch(argc, argv, CHQHIST) ; 	/* Process Switches */

	STRCPY(sr.termnm,terminal);	/* Copy Terminal Name */

	retval = get_param(&pa_rec, BROWSE, 1, e_mesg) ;
	if(retval < 1) {

#ifdef ENGLISH
		printf("Parameters Are Not Setup..") ;
#else
		printf("Parametres ne sont pas etablis..") ;
#endif
		close_dbh() ;
		exit(-1) ;
	}

	if (Initialize()<0)
		exit(-1);		/* Initialization routine */

	if ( Process() < 0) { 		/* Initiate Process */
		Close();
		exit(-1);
	}

	Close();			/* return to menu */
	exit(NOERROR);

} /* END OF MAIN */

/*-------------------------------------------------------------------*/
/* Reset information */
Close()
{
	/* Set terminal back to normal mode from PROFOM */

	fomcs();
	fomrt();
	close_dbh();			/* Close files */
	close_rep();			/* Close files */
}
/*-------------------------------------------------------------------*/
/* Initialize PROFOM  and Screens*/
Initialize()
{
	if(InitProfom()<0) { 			/* Initialize PROFOM */
		fomcs();
		fomrt();
		return(-1);
	}	
	if(InitScreens()<0) { 
		fomcs();
		fomrt();
		return(-1);
	}	
	return(NOERROR);
}

/*-------------------------------------------------------------------*/
/* Initialize PROFOM */

InitProfom()
{
	fomin(&sr);
	/* Check for Error */
	ret( err_chk(&sr) );

	fomcf(1,1);			/* Enable Print screen option */
	return(NOERROR);
}	/* InitProfom() */
/*----------------------------------------------------------------*/
/* Initialize screens before going to process options */
InitScreens()
{

	STRCPY(sr.scrnam,NFM_PATH);
	strcat(sr.scrnam,SCR_NAME) ;

	STRCPY(s_sth.s_pgm,PROG_NAME);
	s_sth.s_rundate = get_date();	/* get Today's Date in YYMMDD format */
	s_sth.s_mesg[0] = HV_CHAR ;
	s_sth.s_opt[0] = HV_CHAR ;

	return(NOERROR);

}	/* InitScreens() */
/*-----------------------------------------------------------------*/
Process()
{
	int	err;

	s_sth.s_mesg[0] = HV_CHAR;
	DispMesgFld((char *)&s_sth);	
	for( ; ; ){

#ifdef ENGLISH
		fomer("U(pdate Seniority), E(xit)");
#else
		fomer("T(raitement de seniorite), F(in)");
#endif

		sr.nextfld = OPTION_FLD;
		fomrf((char *)&s_sth);
		ret(err_chk(&sr));

		switch(s_sth.s_resp[0]) {
		case  EXITOPT :
			return(EXIT);
		case  PROCCHQ :
			CHKACC(err,ADD,e_mesg);	
			CHKACC(err,UPDATE,e_mesg);	
			err = SenProcess() ;
			break ;
		default :
			continue;
		}

		if(NOACCESS == err) {
			fomen(e_mesg);
			get();
		}
		if(PROFOM_ERR == err)	return(PROFOM_ERR);  /* PROFOM ERROR */
		if(DBH_ERR == err) {
			DispError((char *)&s_sth,e_mesg);
#ifdef ENGLISH
			sprintf(e_mesg,"%s %d Dberror: %d Errno: %d",
				"System Error... Iserror:",
				iserror, dberror, errno);
#else
			sprintf(e_mesg,"%s %d Dberror: %d Errno: %d",
				"Erreur du systeme... Iserror:",
				iserror, dberror, errno);
#endif
			DispError((char *)&s_sth,e_mesg);
			return(DBH_ERR); /* DBH ERROR */
		
		}
	}      /*   end of the for( ; ; )       */
}
/*-----------------------------------------------------------------*/
SenProcess()
{
	int 	retval ;
	char	devname[30];

	retval = ConfirmScreen() ;
	if( retval != YES ) 
		return(NOERROR) ;
	
	if(retval != YES) 
	return(NOERROR) ;

	retval = ChequeProcess();
	if( retval < 0 ) 
		return(retval) ;

	/* Update General Ledger		*/
	if( UpdtGl()<0) {
		roll_back(e_mesg);
		return(-1);
	}
	if( commit(e_mesg)<0 ){	/* If everything goes right, commit */
		DispError((char *)&s_sth,e_mesg) ;
		return(-1);
	}

	retval = joursum(1);
	if(retval < 0) return(retval);

	for( ; ; ){
		strcpy(e_mesg,"cat joursum.dat > ");
		strcat(e_mesg,devname);
		system(e_mesg);
		strcpy(e_mesg,"echo  > ");
		strcat(e_mesg,devname);
		system(e_mesg);
	
		for( ; ; ) {
#ifdef ENGLISH
       		 	retval = GetOption((char *)&s_sth, "Reprint JOURNAL LISTING (Y/N)?","YN") ;
#else
       		 	retval = GetOption((char *)&s_sth, "Re-imprimer le LISTE DE JOURNAL (O/N)?","ON") ;
#endif
			if(retval == YES || retval == NO) 
				break ;
		}
		if(retval == NO) break;
	}

	retval = PrntRep();
	if( retval < 0 ) 
		return(retval) ;

	unlink_file(TMP_SEN);
	unlink_file(JR_ENT);

	return(NOERROR) ;
}
/*-----------------------------------------------------------------------*/
/*                                                                       */
/* Reads the cheque and prints the cheque after accumulating invoices.   */
ChequeProcess()
{
	int	err ;
	int	mode;

#ifdef ENGLISH
	STRCPY(s_sth.s_mesg, "Seniority Being Updated, PLEASE WAIT");
#else
	STRCPY(s_sth.s_mesg, "Traitement de la seniorite en progres, ATTENDEZ S.V.P.");
#endif
	DispMesgFld((char *)&s_sth);
	fflush(stdout) ;

 	err = get_pay_param(&pay_param,BROWSE,1,e_mesg);
	if(err < 0) {
  		DispError((char *)&s_sth,e_mesg);
		return(err);
	}

	if(pay_param.pr_st_mth == 1){
		start_mth = ((pay_param.pr_cal_st_dt / 100) % 100);
	}
	if(pay_param.pr_st_mth == 2){
		start_mth = ((pay_param.pr_fisc_st_dt / 100) % 100);
	}
	if(pay_param.pr_st_mth == 3){
		start_mth = ((pay_param.pr_schl_st_dt / 100) % 100);
	}

	tmp_sen.tsn_numb[0] = '\0';
	tmp_sen.tsn_month = 0;
	tmp_sen.tsn_pos[0] = '\0';
	tmp_sen.tsn_class[0] = '\0';
	flg_reset(TMP_SEN);

	for( ; ; ){
	  err = get_n_tmp_sen(&tmp_sen,BROWSE,0,FORWARD,e_mesg);
	  if(err < 0 && err != EFL){
	  	DispError((char *)&s_sth,e_mesg) ;
	  	return(ERROR);
	  }
	  if(err == EFL) break;

	  strcpy(emp_rec.em_numb, tmp_sen.tsn_numb);

	  err = get_employee(&emp_rec,BROWSE,0,e_mesg);
	  if(err != NOERROR){
  		DispError((char *)&s_sth,e_mesg) ;
 		return(ERROR);
  	  }

	  err=UsrBargVal(UPDATE,emp_rec.em_numb,emp_rec.em_barg,1,e_mesg);
	  if(err < 0){
		continue;
	  }
	
	  sprintf(e_mesg,"Employee Number: %s",tmp_sen.tsn_numb);
	  fomen(e_mesg);
	  fflush(stdout);

	  /*   Accrual Attendance for the Pay Period	*/

	  if(tmp_sen.tsn_sick_acc0 != 0 || tmp_sen.tsn_sick_acc1 != 0){
	  	err = AttAcc();
		if(err < 0 )
			continue;
	  }

	  if(tmp_sen.tsn_vac_acc0 != 0 || tmp_sen.tsn_vac_acc1 != 0){
	  	err = VacAcc();
		if(err < 0 )
			continue;
	  }

	  strcpy(emp_sen.esn_numb,tmp_sen.tsn_numb);
	  emp_sen.esn_month = tmp_sen.tsn_month;
	  strcpy(emp_sen.esn_pos,tmp_sen.tsn_pos);
	  strcpy(emp_sen.esn_class,tmp_sen.tsn_class);

	  err = get_emp_sen(&emp_sen,UPDATE,0,e_mesg);
	  if(err < 0 && err != UNDEF){
	  	DispError((char *)&s_sth,e_mesg) ;
	  	return(ERROR);
	  }
	  if(err == UNDEF){
		roll_back(e_mesg);
		mode = ADD;
	  	emp_sen.esn_cas_hrs = tmp_sen.tsn_cas_hrs1;
	 	emp_sen.esn_cas_days = tmp_sen.tsn_cas_days1;
		emp_sen.esn_perm_days = tmp_sen.tsn_perm_days1;
		emp_sen.esn_cas_totd = tmp_sen.tsn_cas_totd1;

	  }
	  if(err != UNDEF){
		mode = UPDATE;
	  	emp_sen.esn_cas_hrs += tmp_sen.tsn_cas_hrs1;
	 	emp_sen.esn_cas_days += tmp_sen.tsn_cas_days1;
		emp_sen.esn_perm_days += tmp_sen.tsn_perm_days1;
		emp_sen.esn_cas_totd += tmp_sen.tsn_cas_totd1;
	  }

  	  err = put_emp_sen(&emp_sen,mode,e_mesg);	
	  if(err < 0) {
		if(err == DUPE)	continue;
	 	DispError((char *)&s_sth,e_mesg);
	  	return(ERROR);
	  }

	  if(tmp_sen.tsn_perm_days0 > 0 ||
		tmp_sen.tsn_cas_totd0 > 0){
	    if(tmp_sen.tsn_month == 1)
		emp_sen.esn_month = 12;
	    else
	    	emp_sen.esn_month = tmp_sen.tsn_month - 1;

	    err = get_emp_sen(&emp_sen,UPDATE,0,e_mesg);
	    if(err < 0 && err != UNDEF){
	  	DispError((char *)&s_sth,e_mesg) ;
	  	return(ERROR);
	    }
	    if(err == UNDEF){
		roll_back(e_mesg);
		mode = ADD;
	    	emp_sen.esn_cas_hrs = tmp_sen.tsn_cas_hrs0;
	 	emp_sen.esn_cas_days = tmp_sen.tsn_cas_days0;
	   	emp_sen.esn_perm_days = tmp_sen.tsn_perm_days0;
	   	emp_sen.esn_cas_totd = tmp_sen.tsn_cas_totd0;
	    }
	    if(err != UNDEF){
		mode = UPDATE;
	    	emp_sen.esn_cas_hrs += tmp_sen.tsn_cas_hrs0;
	 	emp_sen.esn_cas_days += tmp_sen.tsn_cas_days0;
	   	emp_sen.esn_perm_days += tmp_sen.tsn_perm_days0;
	   	emp_sen.esn_cas_totd += tmp_sen.tsn_cas_totd0;
	    }

  	    err = put_emp_sen(&emp_sen,mode,e_mesg);	
	    if(err < 0) {
		if(err == DUPE)	continue;
	 	DispError((char *)&s_sth,e_mesg);
	  	return(ERROR);
	    }
	  }
	  err = commit(e_mesg);
	  if(err < 0) {
		DispError((char *)&s_sth,e_mesg);
		roll_back(e_mesg);
		return(ERROR);
	  }
	}
	seq_over(TMP_SEN);

#ifdef ENGLISH
	STRCPY(s_sth.s_mesg, "Seniority Updated Successfully");
#else
	STRCPY(s_sth.s_mesg, "Traitement de Seniorite Reussie");
#endif
	DispMesgFld((char *)&s_sth) ;
	fflush(stdout) ;
	return(NOERROR) ;

}
/*----------------------------------------------------------------*/
/* Validation function() for Key and Header fields when PROFOM returns
  RET_VAL_CHK */

Validation()
{
	return(NOERROR) ;
}	/* Validation() */
/*----------------------------------------------------------------*/
Window()
{
	return(NOERROR);
}
/*-----------------------------------------------------------------------*/
/*                                                                       */
ConfirmScreen() 
{
	int	err ;

	for( ; ; ) {
#ifdef ENGLISH
		err = GetOption((char *)&s_sth,"Y(es), C(ancel)", "YC");
#else
		err = GetOption((char *)&s_sth,"O(ui), A(nnuler)", "OA"); 
#endif
		if(err == PROFOM_ERR) return(err) ;

		switch(err) {
		case  YES :
			return(YES) ;
		case  CANCEL :
#ifdef ENGLISH
			err = GetOption((char *)&s_sth,"Confirm the Cancel (Y/N)?", "YN") ;
#else
			err = GetOption((char *)&s_sth,"Confirmer l'annulation (O/N)?", "ON") ;
#endif
			if(err == YES) { 
				roll_back(e_mesg) ;	/* Unlock  Records */
				return(CANCEL) ;
			}
			break ;
		}	/* switch err */

		if(err == PROFOM_ERR) return(err) ;
		if(err == DBH_ERR) return(err) ;
	}	/* for(; ; ) */
}	/* ConfirmScreen() */

/*-----------------------------------------------------------------------*/
GetPos(pos)
char	*pos;
{
	int	retval;

	strcpy(position.p_code,pos);

	retval = get_position(&position,BROWSE,0,e_mesg);
	if(retval < 0) {
		DispError((char *)&s_sth,e_mesg);
	}

	return(NOERROR);
}
/*--------------------------------------------------------------*/
GetClass(class_rec)
char	*class_rec;
{
	int	retval;

	strcpy(class.c_code,class_rec);
	class.c_date = s_sth.s_rundate;
	flg_reset(CLASSIFICATION);

	retval = get_n_class(&class,BROWSE,0,BACKWARD,e_mesg);
	if(retval < 0 && retval != EFL){
		DispError((char *)&s_sth, e_mesg);
		return(NOERROR);
	}
	if((strcmp(class.c_code,class_rec) != 0) || retval == EFL){
		sprintf(e_mesg,"Classification Code Does Not Exist %s",class_rec);
		DispError((char *)&s_sth, e_mesg);
	    	return(NOERROR);
	}
	seq_over(CLASSIFICATION);
	return(NOERROR);
}
/*--------------------------------------------------------------*/
AttAcc()
{
	int	i, j, err;

	err = get_employee(&emp_rec,UPDATE,0,e_mesg);
	if(err != NOERROR){
  		DispError((char *)&s_sth,e_mesg) ;
 		return(ERROR);
  	}
	if(tmp_sen.tsn_month == 1)
		month = 12;
	else
		month = tmp_sen.tsn_month - 1;

	month2 = tmp_sen.tsn_month;

	if(month >= start_mth){
		i = month-start_mth;
	}
	else{
		i = month+start_mth-2;
	}
	if(month2 >= start_mth){
		j = month2-start_mth;
	}
	else{
		j = month2+start_mth-2;
	}

	emp_rec.em_sck_acc[i] += tmp_sen.tsn_sick_acc0;
	emp_rec.em_sck_acc[j] += tmp_sen.tsn_sick_acc1;

  	err = put_employee(&emp_rec,UPDATE,e_mesg);	
	if(err < 0) {
	 	DispError((char *)&s_sth,e_mesg);
	  	return(ERROR);
	}
	err = commit(e_mesg);
	if(err < 0) {
		DispError((char *)&s_sth,e_mesg);
		roll_back(e_mesg);
		return(ERROR);
	}

	return(NOERROR);
}
/*--------------------------------------------------------------*/
VacAcc()
{
	int	i, j, err;

	err = get_employee(&emp_rec,UPDATE,0,e_mesg);
	if(err != NOERROR){
  		DispError((char *)&s_sth,e_mesg) ;
 		return(ERROR);
  	}

	if(tmp_sen.tsn_month == 1)
		month = 12;
	else
		month = tmp_sen.tsn_month - 1;

	month2 = tmp_sen.tsn_month;

	if(month >= start_mth){
		i = month-start_mth;
	}
	else{
		i = month+start_mth-2;
	}
	if(month2 >= start_mth){
		j = month2-start_mth;
	}
	else{
		j = month2+start_mth-2;
	}

	emp_rec.em_vac_acc[i] += tmp_sen.tsn_vac_acc0;
	emp_rec.em_vac_acc[j] += tmp_sen.tsn_vac_acc1;

  	err = put_employee(&emp_rec,UPDATE,e_mesg);	
	if(err < 0) {
	 	DispError((char *)&s_sth,e_mesg);
	  	return(ERROR);
	}
	err = commit(e_mesg);
	if(err < 0) {
		DispError((char *)&s_sth,e_mesg);
		roll_back(e_mesg);
		return(ERROR);
	}

	return(NOERROR);
}
/*-----------------------------------------------------------------------*/ 
UpdtGl()
{
	int retval, err;
	char	prev_acct[19], prev_acct2[19];
	double	tot_amt, tot_db;
	short	prev_fund, prev_fund2;
	double	dbcr_amt;

#ifdef ENGLISH
	STRCPY(s_sth.s_mesg, "Updating GL Master File, PLEASE WAIT");
#else
	STRCPY(s_sth.s_mesg, "Le GL est en train de faire les mises a jour, ATTENDEZ S.V.P.");
#endif
	DispMesgFld((char *)&s_sth);
	fflush(stdout) ;

	prev_acct[0] = '\0';
	prev_fund = 0;

	tot_db = 0;
	dbcr_amt = 0;
	item_no = 1;

	if((retval = WriteTrHdr(pay_param.pr_fund,
				0.00))< 0 ) return(retval);
	tmp_seq_no = tr_hdr.th_seq_no;

	for( ; ; ){
		tot_amt = 0;

		jr_ent.jr_fund = prev_fund;
		strcpy(jr_ent.jr_acct,prev_acct);
		flg_reset(JR_ENT);

		for( ; ; ) {
			err = get_n_jr_ent(&jr_ent,BROWSE,5,FORWARD,e_mesg) ;
			if(err == EFL) break;
			if( err < 0) {
				DispError((char *)&s_sth,e_mesg) ;
				return(err) ;
			}

			if(prev_acct[0] == '\0'){
				strcpy(prev_acct, jr_ent.jr_acct);
				prev_fund = jr_ent.jr_fund;
			}

			if(prev_fund != jr_ent.jr_fund) {
				break;
			}

			if(strcmp(jr_ent.jr_acct,prev_acct) != 0) {
				break;
			}

			tot_amt += jr_ent.jr_amount;

			if(jr_ent.jr_amount > 0.00)
				tot_db += jr_ent.jr_amount;

			dbcr_amt += jr_ent.jr_amount;
		}

		sprintf(e_mesg,"acct # %s",prev_acct);
		fomen(e_mesg);
		fflush(stdout) ;

		if(prev_fund == 0) break;

		strcpy(prev_acct2, jr_ent.jr_acct);
		prev_fund2 = jr_ent.jr_fund;
		if((retval = WriteGlmast(prev_fund,
				prev_acct,tot_amt))< 0 ) return(retval);

		if((retval = WriteTrItems(prev_fund,
				prev_acct,tot_amt))< 0 ) return(retval);

		item_no++;

		if(err == EFL)  break;

		strcpy(prev_acct, prev_acct2);
		prev_fund = prev_fund2;
	}
	seq_over(JR_ENT);

	tr_hdr.th_fund = pay_param.pr_fund;
	tr_hdr.th_reccod = 99;
	tr_hdr.th_create[0] = 'G';
	tr_hdr.th_seq_no = tmp_seq_no;

	retval = get_trhdr( &tr_hdr, UPDATE, 0, e_mesg );
	if( retval==ERROR ){
		DispError((char *)&s_sth,e_mesg);
		return(-1);
	}

	tr_hdr.th_debits = tr_hdr.th_credits = tot_db;

	/*  Roundoff double items that have calculated values  */
	tr_hdr.th_debits 	= D_Roundoff(tr_hdr.th_debits);
	tr_hdr.th_credits 	= D_Roundoff(tr_hdr.th_credits);

	retval = put_trhdr( &tr_hdr, UPDATE, e_mesg );
	if(retval<0) {
		DispError((char *)&s_sth,e_mesg);
		roll_back(e_mesg);
		return(retval);
	}
	if( commit(e_mesg)<0 ){
		DispError((char *)&s_sth,e_mesg);
		return(-1);
	}

	return(NOERROR);
}
/*-----------------------------------------------------------------------*/ 
WriteTrHdr(fund, amount)
short	fund;
double	amount;
{
	int	retval;

#ifdef ORACLE
	long	sno, get_maxsno();
#endif
	tr_hdr.th_fund = fund;
	tr_hdr.th_reccod = 99;
	tr_hdr.th_create[0] = 'G';

#ifndef ORACLE
	tr_hdr.th_seq_no = HV_SHORT;
	retval = get_n_trhdr( &tr_hdr, BROWSE, 0, BACKWARD, e_mesg );
	seq_over( GLTRHDR );
	if( retval==ERROR ){
		DispError((char *)&s_sth,e_mesg);
		roll_back(e_mesg);
		return(-1);
	}
	if( retval==EFL || 
	    tr_hdr.th_fund != fund ||	
	    tr_hdr.th_reccod != 99 || tr_hdr.th_create[0] != 'G' ){
		tr_hdr.th_fund = fund;
		tr_hdr.th_reccod = 99;
		tr_hdr.th_create[0] = 'G';
		tr_hdr.th_seq_no = 1;
	}
	else
		tr_hdr.th_seq_no++;
#else
	sno = get_maxsno(GLTRHDR,(char *)&tr_hdr,0,-1,e_mesg);
	if(sno < 0) {
		DispError((char *)&s_sth,e_mesg);
		roll_back(e_mesg);
		return(-1);
	}
	tr_hdr.th_seq_no = sno + 1;
#endif

	strcpy( tr_hdr.th_userid, User_Id );
	tr_hdr.th_sys_dt = get_date() ;
	tr_hdr.th_period = pa_rec.pa_cur_period;
	tr_hdr.th_date = get_date();
	tr_hdr.th_debits = tr_hdr.th_credits = amount;

	/*  Roundoff double items that have calculated values  */
	tr_hdr.th_debits 	= D_Roundoff(tr_hdr.th_debits);
	tr_hdr.th_credits 	= D_Roundoff(tr_hdr.th_credits);

	strcpy(tr_hdr.th_descr, "VACATION ACCRUALS");
	tr_hdr.th_supp_cd[0] = '\0';
	tr_hdr.th_type[0] = 'P';
	tr_hdr.th_print[0] = 'N';
	strcpy(tr_hdr.th_reference, "PAYROLL");

	retval = put_trhdr( &tr_hdr, ADD, e_mesg );
	if(retval<0) {
		DispError((char *)&s_sth,e_mesg);
		roll_back(e_mesg);
		return(retval);
	}
	if( commit(e_mesg)<0 ){
		DispError((char *)&s_sth,e_mesg);
		return(-1);
	}
	return(0);
}
/*-----------------------------------------------------------------------*/ 
WriteTrItems(fund, acct, amount)
short	fund;
char	*acct;
double	amount;
{

	tr_item.ti_fund = fund;
	tr_item.ti_reccod = 99;
	tr_item.ti_create[0] = 'G';
	tr_item.ti_seq_no = tr_hdr.th_seq_no;
	tr_item.ti_item_no = item_no;
	tr_item.ti_sys_dt = tr_hdr.th_sys_dt;
	tr_item.ti_period = tr_hdr.th_period;
	strcpy(tr_item.ti_accno,acct);
	tr_item.ti_section = gl_rec.sect;
	tr_item.ti_amount = amount;
	tr_item.ti_status = 0;

	/* Roundoff ti_amount which is double	*/
	tr_item.ti_amount = D_Roundoff(tr_item.ti_amount);

	if( put_tritem(&tr_item, ADD, e_mesg)<0 ){
		DispError((char *)&s_sth,e_mesg);
		roll_back(e_mesg);
		return(-1);
	}
	if( commit(e_mesg)<0 ){
		DispError((char *)&s_sth,e_mesg);
		return(-1);
	}

	return(NOERROR);
}
/*-----------------------------------------------------------------------*/ 
WriteGlmast(fund, acct, amount)
short	fund;
char	*acct;
double	amount;
{
	int	retval;

	for(;;) {
		gl_rec.funds = fund;
		strcpy(gl_rec.accno, acct);
		gl_rec.reccod = 99;
		retval = get_gl( &gl_rec, UPDATE, 0, e_mesg );
		if(retval == NOERROR)	break;
		if(retval == LOCKED) {
			DispError((char *)&s_sth,e_mesg);
			roll_back(e_mesg);
			continue;
		}
		if( retval!=NOERROR ){
			DispError((char *)&s_sth,e_mesg);
			roll_back(e_mesg);
			return(retval);
		}
	}
	gl_rec.currel[pa_rec.pa_cur_period-1] += amount; 
	gl_rec.ytd += amount;
	if(amount > 0.00)
		gl_rec.curdb += amount;
	else
		gl_rec.curcr += amount;

	gl_rec.currel[pa_rec.pa_cur_period-1] =
			 D_Roundoff(gl_rec.currel[pa_rec.pa_cur_period-1]);
	gl_rec.ytd = D_Roundoff(gl_rec.ytd);
	gl_rec.curdb = D_Roundoff(gl_rec.curdb);
	gl_rec.curcr = D_Roundoff(gl_rec.curcr);

	retval = put_gl( &gl_rec, UPDATE, e_mesg );
	if( retval!=NOERROR ){
		DispError((char *)&s_sth,e_mesg);
		roll_back(e_mesg);
		return(retval);
	}
	if( commit(e_mesg)<0 ){
		DispError((char *)&s_sth,e_mesg);
		return(-1);
	}

	return(NOERROR);

}
/*-----------------------------------------------------------------*/
PrntRep()
{

	char	tmpindxfile[50];
	char	tnum[5];
	int	retval,err,first_time;

	code_total = 0;
	grand_total = 0;

	unlink_file(TMPINDX_1);
	STRCPY(tmpindxfile,"emptemp");
	get_tnum(tnum);
	strcat(tmpindxfile,tnum);
	if(CreatTempIndx(tmpindxfile,"N","B" )<0){
		sprintf(e_mesg,"Error Creating tmp file : %d",iserror);
		fomer(e_mesg);get();
		return (-1);
	}
	if(InitPrinter()<0) {
		return(-1);
	}	

	first_time = 0;

	emp_rec.em_barg[0] = '\0';
	strcpy(last_barg,emp_rec.em_barg);
	emp_rec.em_first_name[0] = '\0';
	emp_rec.em_last_name[0] = '\0';
	flg_reset(TMPINDX_1);

	for (;;){
		retval = get_next((char*)&emp_rec,TMPINDX_1,0,FORWARD,BROWSE,e_mesg);
		if(retval==EFL)		break;
		if(retval<0)		return(-1);
	
		if(strcmp(last_barg,emp_rec.em_barg)!=0 ||
		   first_time == 0 || linecnt > PG_SIZE) {
			if(first_time == 1 && strcmp(last_barg,
			   emp_rec.em_barg) != 0) {
				retval = PrntCodeTot();
				if(retval < 0)	return(retval);
			}
			retval = PrntHdg();
			if(retval < 0){
				return(retval);
			}
			if(retval == EXIT)	break;
			first_time = 1;
		}

		err = PrntRec();
		if(err < 0)	return(err);
		strcpy(last_barg,emp_rec.em_barg);
	}
	retval = PrntCodeTot();
	if(retval < 0)	return(retval);

	retval = PrntGrndTot();
	if(retval < 0)	return(retval);

	return(NOERROR);

}
/*-----------------------------------------------------------------*/
InitPrinter()
{
	char	resp[2] ;
	char	discfile[15] ;

	/* Always to Printer */
	STRCPY(resp,"P");
	discfile[0]= '\0';
	PG_SIZE = 60;

	if( opn_prnt( resp, discfile, 1, e_mesg, 1 /* spool */)<0 ){
		return(REPORT_ERR);
	}
	pgcnt = 0;		/* Page count is zero */
	LNSZ = 132;		/* line size in no. of chars */
	linecnt = PG_SIZE;	/* Page size in no. of lines */

	return(NOERROR) ;
}
/******************************************************************************
Prints the headings
******************************************************************************/
static
PrntHdg()	/* Print heading  */
{
	long	sysdt ;
	int	offset;
	int	retval;

	if( pgcnt && term < 99)   /* new page and display */
		if(next_page()<0) return(EXIT);	
		
	if( pgcnt || term < 99) { /* if not the first page or display */
		if( rite_top()<0 ) return( -1 );	/* form_feed */
	}
	else
		linecnt = 0;
	pgcnt++; 			/* increment page no */

	mkln( 1, PROG_NAME, 10 );
#ifdef ENGLISH
	mkln( 103, "Date:", 5 );
#else
	mkln( 103, "Date:", 5 );
#endif
	sysdt = get_date() ;
	tedit( (char *)&sysdt,"____/__/__",line+cur_pos, R_LONG ); 
	cur_pos += 10;

#ifdef ENGLISH
	mkln( 122, "PAGE:", 5 );
#else
	mkln( 122, "PAGE:", 5 );
#endif
	tedit( (char *)&pgcnt,"__0_",  line+cur_pos, R_SHORT ); 
	cur_pos += 4;
	if(prnt_line() < 0 )	return(REPORT_ERR);
 
	offset = ( LNSZ-strlen(pa_rec.pa_co_name) )/2;
	mkln( offset, pa_rec.pa_co_name, strlen(pa_rec.pa_co_name) );
	if( prnt_line()<0 )	return(REPORT_ERR);

#ifdef ENGLISH
	mkln((LNSZ-24)/2,"VACATION ACCRUAL SUMMARY", 24 );
#else
	mkln((LNSZ-24)/2,"TRANSLATE        ", 24 );
#endif
	if(prnt_line() < 0 )	return(REPORT_ERR);
	if(prnt_line() < 0 )	return(REPORT_ERR);

	strcpy(barg_unit.b_code,emp_rec.em_barg);
	barg_unit.b_date = get_date();
	flg_reset(BARG);

	retval = get_n_barg(&barg_unit,BROWSE,0,BACKWARD,e_mesg);
	if(retval < 0){
		fomer(e_mesg);get();
  		sprintf(e_mesg,"Barg Unit does not Exist for Employee: %s",
			emp_rec.em_numb);
		fomer(e_mesg);get();
		/* return(UNDEF); */
	}

	if(strcmp(emp_rec.em_barg,barg_unit.b_code)!=0) {
		strcpy(barg_unit.b_name,
			"                              ");
	}
	mkln(1,"BARGAINING UNIT: ",17); 
	mkln(18,emp_rec.em_barg,6);
	mkln(25,barg_unit.b_name,30);
	seq_over(BARG);

	if(prnt_line() < 0 )	return(REPORT_ERR);
	if(prnt_line() < 0 )	return(REPORT_ERR);

	mkln(3,"EMPLOYEE",8);
	mkln(14,"EMPLOYEE",8);
	mkln(48,"G/L",3);
	mkln(66,"VACATION",8);
	mkln(79,"HOURS WORKED",12);
	mkln(98,"HOURLY",6);
	mkln(111,"VACATION",8);

	if(prnt_line() < 0 )	return(REPORT_ERR);

	mkln(4,"NUMBER",6);
	mkln(18,"NAME",4);
	mkln(46,"ACCOUNT",7);
	mkln(64,"ACCRUED DAYS",12);
	mkln(82,"PER DAY",7);
	mkln(98,"RATE",4);
	mkln(111,"$ACCRUED",8);

	if(prnt_line() < 0 )	return(REPORT_ERR);
	if(prnt_line() < 0 )	return(REPORT_ERR);

	return(NOERROR);
}
/****************************************************************************/
static
PrntRec()
{
	char	txt_line[132];
	int	retval;
	int	err;
	double	vacation;
	double	total;

	retval = CalcHours();
	if(retval < 0)	return(retval);

	retval = CalcSalary();
	if(retval < 0)	return(retval);

	strcpy(tmp_sen.tsn_numb,emp_rec.em_numb);
	tmp_sen.tsn_month = 0;
	tmp_sen.tsn_pos[0] = '\0';
	tmp_sen.tsn_class[0] = '\0';
	flg_reset(TMP_SEN);

	err = get_n_tmp_sen(&tmp_sen,BROWSE,0,FORWARD,e_mesg);
	if(err < 0 && err != EFL){
	  	DispError((char *)&s_sth,e_mesg) ;
	  	return(ERROR);
	}
	if(err == EFL) return(NOERROR);
	if(strcmp(tmp_sen.tsn_numb,emp_rec.em_numb) != 0)	
		return(NOERROR);

	vacation = tmp_sen.tsn_vac_acc0 + tmp_sen.tsn_vac_acc1;

	mkln(1,emp_rec.em_numb,12);
	sprintf(txt_line,"%s, %s",
		emp_rec.em_last_name,
		emp_rec.em_first_name);
	mkln(15,txt_line,22);

	strcpy(jr_ent.jr_emp_numb,emp_rec.em_numb);
	jr_ent.jr_type[0] = '\0';
	jr_ent.jr_fund = 0;
	jr_ent.jr_no = 0;

	flg_reset(JR_ENT);

	for( ; ; ) {
		retval = get_n_jr_ent(&jr_ent,BROWSE,5,FORWARD,e_mesg) ;
		if(retval == EFL) break;
		if( retval < 0) {
			DispError((char *)&s_sth,e_mesg) ;
			return(retval) ;
		}
		if(strcmp(jr_ent.jr_acct,pay_param.pr_teach_gl)==0) continue;
		if(strcmp(jr_ent.jr_emp_numb,emp_rec.em_numb)==0) break;
	}
	mkln(38,jr_ent.jr_acct,18);

	tedit((char*)&vacation,"___,_0_.____-",txt_line,R_DOUBLE);
	mkln(61,txt_line,13);

	tedit((char*)&hours,"___,_0_.__-",txt_line,R_DOUBLE);
	mkln(80,txt_line,11);

	tedit((char*)&salary,"___,_0_.__-",txt_line,R_DOUBLE);
	mkln(95,txt_line,11);

	total = D_Roundoff(salary*hours*vacation);

	tedit((char*)&total,"___,_0_.__-",txt_line,R_DOUBLE);
	mkln(110,txt_line,11);

	if(prnt_line() < 0 )	return(REPORT_ERR);
			
	if(linecnt > PG_SIZE) {
		if((retval=PrntHdg()) == EXIT)	
			return(retval);
	}

	code_total += total;

	return(NOERROR);
}
/*---------------------------------------------------------------------------*/
static
CalcHours()
{
	int retval;

	strcpy(sen_par.sn_position,emp_rec.em_pos);
	sen_par.sn_eff_date = get_date();

	flg_reset(SEN_PAR);

	retval = get_n_sen_par(&sen_par,BROWSE,0,BACKWARD,e_mesg);
	if(retval == EFL || strcmp(emp_rec.em_pos,sen_par.sn_position) != 0) {
		sprintf(e_mesg,"Seniority Parameter Not Setup, Employee: %s",
			emp_rec.em_numb); 
		fomen(e_mesg);
		return(retval);
	}
	if(retval < 0) {
		fomen(e_mesg) ;
		get();
		return(ERROR) ;
	}
	hours = D_Roundoff(sen_par.sn_num_hrs_day);

	return(NOERROR);
}
/*---------------------------------------------------------------------------*/
static
CalcSalary()
{
	int retval;
	double 	temp_calc = 0;
	int j;
	double	one_hundred;

	one_hundred = 100;

	strcpy(barg_unit.b_code,emp_rec.em_barg);
	barg_unit.b_date = get_date();
	flg_reset(BARG);

	retval = get_n_barg(&barg_unit,BROWSE,0,BACKWARD,e_mesg);
	if(retval == EFL ||
		strcmp(barg_unit.b_code, emp_rec.em_barg) != 0){
  		sprintf(e_mesg,"Barg Unit does not Exist for Employee: %s",
			emp_rec.em_numb);
		fomer(e_mesg);get();
		return(NOERROR);
	}
	if(retval < 0){
  		fomer(e_mesg);
  		return(ERROR);
	}
	seq_over(BARG);

	if(emp_rec.em_class[0] == '\0') {
		salary = 0;
	}
	else {
		strcpy(class.c_code,emp_rec.em_class);
		class.c_date = get_date();
		flg_reset(CLASSIFICATION);
		retval = get_n_class(&class,BROWSE,0,BACKWARD,e_mesg);
		if((retval < 0 ||
		    strcmp(class.c_code,emp_rec.em_class) != 0)){
			fomer("Classification Code Does Not Exist - Please Re-enter");
			get();
			salary = 0;
			return(-1);
		}
	 	if(class.c_units != 0) {	
 		        salary = D_Roundoff(class.c_yrly_inc / class.c_units); 
		}
		else{
			strcpy(pay_per.pp_code,barg_unit.b_pp_code);
			pay_per.pp_year = 0;
			flg_reset(PAY_PERIOD);

			retval = get_n_pay_per(&pay_per,BROWSE,0,FORWARD,
								e_mesg);
			if(retval < 0 || strcmp(pay_per.pp_code,
					        barg_unit.b_pp_code)!=0) {
				fomer("Pay Period Code Does not Exist");
				get();
			}
			seq_over(PAY_PERIOD);
			if(class.c_yrly_inc == 0){
				salary = 0;
			}
			else{
			 	temp_calc = class.c_yrly_inc / 
					(double)pay_per.pp_numb;
				temp_calc = temp_calc * emp_rec.em_perc/
					one_hundred; 
				temp_calc = D_Roundoff(temp_calc);
		    	}
			salary = (double)temp_calc;
		}
	}
	return(NOERROR);
}


/*-----------------------------------------------------------------------*/
CreatTempIndx ( tempindxnm,sortop1,sortop2 )
char	*tempindxnm;	/*temparary index file name*/
char	*sortop1;
char	*sortop2;
{
	int	keysarray[20];
	int	step=0;
	int	retval;
	int	use_file=0;

	keysarray[step++] = 4;

	/*Part 1*/
	keysarray[step++] = CHAR;
	keysarray[step++] =  6;
	keysarray[step++] = (char*)&emp_rec.em_barg[0] - (char*)&emp_rec;
	keysarray[step++] = ASCND;

	/*Part 2*/
	keysarray[step++] = CHAR;
	keysarray[step++] =  25;
	keysarray[step++] = (char*)&emp_rec.em_last_name[0] - (char*)&emp_rec;
	keysarray[step++] = ASCND;
	
	/*Part 3*/
	keysarray[step++] = CHAR;
	keysarray[step++] =  15;
	keysarray[step++] = (char*)&emp_rec.em_first_name[0] - (char*)&emp_rec;
	keysarray[step++] = ASCND;

	
	/*Part 4*/
	keysarray[step++] = CHAR;
	keysarray[step++] =  12;
	keysarray[step++] = (char*)&emp_rec.em_numb[0] - (char*)&emp_rec;
	keysarray[step++] = ASCND;

	retval = CrtTmpIndx(EMPLOYEE,TMPINDX_1,keysarray,tempindxnm,
		(int(*)())NULL,e_mesg);
	return(0);
}
/*--------------------------------------------------------------------*/
static
PrntCodeTot()
{
	char	txt_line[132];

	if(prnt_line() < 0 )	return(REPORT_ERR);

	mkln(1,"TOTAL FOR BARGAINING UNIT: ",27); 
	mkln(28,last_barg,6);

	tedit((char*)&code_total,"___,_0_.__",txt_line,R_DOUBLE);
	mkln(110,txt_line,10);

	if(prnt_line() < 0 )	return(REPORT_ERR);

	grand_total += code_total;	
	code_total = 0;	

	return(NOERROR);
}
/*--------------------------------------------------------------------*/
static
PrntGrndTot()
{
	char	txt_line[132];

	if(prnt_line() < 0 )	return(REPORT_ERR);

	mkln(1,"GRAND TOTAL",11); 

	tedit((char*)&grand_total,"___,_0_.__",txt_line,R_DOUBLE);
	mkln(110,txt_line,10);

	if(prnt_line() < 0 )	return(REPORT_ERR);

	return(NOERROR);
}
/*-------------------- E n d   O f   P r o g r a m ---------------------*/
