/*------------------------------------------------------------------------
Source Name: t4_print.c
System     : Personnel/Payroll.
Created  On: May 20, 1992.
Created  By: Andre Cormier.

DESCRIPTION:
	Program to print t4.

MODIFICATIONS:        

Programmer     YY/MM/DD       Description of modification
~~~~~~~~~~     ~~~~~~~~       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

L.Robichaud	1993/10/13	Pass new parameter to close_rep function for 
				a banner to print with 3000 family.
------------------------------------------------------------------------*/
#define 	MAIN 
#define		MAINFL	T4_ADJ		/* main file used */

#include <stdio.h>
#include <cfomstrc.h>
#include <repdef.h>
#include <bfs_defs.h>
#include <bfs_com.h>
#include <bfs_pp.h>

#define	SYSTEM		"PERSONNEL/PAYROLL"	/* Sub System Name */
#define	MOD_DATE	"20-MAY-92"		/* Program Last Modified */
#define	SCR_NAME	"t4_print"		/* First screen */

#define	PRINTER_FLD	400 
#define	ST_FLD		400 
#define	END_FLD		800 
#define MESG_FLD	700
#define OPTION_FLD	500
#define PRINTED_FLD	600

#define EXIT	12

#ifdef ENGLISH

#define PRINT	'P'
#define EXITOPT	'E'

#define	YES	'Y'
#define NO	'N'
#define EDIT	'E'
#define CANCEL	'C'

#else
#define PRINT	'I'
#define EXITOPT	'F'

#define	YES	'O'
#define NO	'N'
#define EDIT	'M'
#define CANCEL	'A'

#endif
/* cheque.sth - header for C structure generated by PROFOM EDITOR */

typedef struct	{

	char	s_pgm[11];	/* STRING XXXXXXXXXX 	Field 100 */
	long	s_rundate;	/* NUMERIC 9999F99F99 	Field 300 */
	short	s_printer;	/* NUMERIC ##		Field 400 */
	char	s_resp[2]; 	/* STRING X 		Field 1400 */
	long	s_printed;	/* NUMERIC ####		Field 400 */
	char	s_mesg[78];	/* STRING X(78) 	Field 1500 */
	char	s_opt[2];	/* STRING X 		Field 1600 */
	} S_STRUCT;

static	S_STRUCT	s_sth ;

/* PROFOM Related variables */

struct  	stat_rec  sr;	/* PROFOM status rec */

static	Emp		emp_rec ;
static	Emp_earn	emp_earn ;
static	Pa_rec		pa_rec ;
static	T4_adj		t4_adj;
static	Pay_param	pay_param;
static	Emp_ln_his	emp_ln_his;
static	Emp_dh		emp_dd_his;
static	Gov_param	gov_par;
char 	e_mesg[100];	/* dbh will return err msg in this */
static	char	temp_buf[80] ;	/* work variable for tedit */
static	double	earn_date;

int	Validation();
int	WindowHelp();

double 	D_Roundoff();

static	double	reg_pen;
static	double	while_cont;

static char	emp_name[48];

main(argc,argv)
int argc;
char *argv[];
{
int 	retval ;

	strncpy(SYS_NAME,SYSTEM,50);	/* Sub system name */
	strncpy(CHNG_DATE,MOD_DATE,10);	/* Modification Date */
	proc_switch(argc, argv, CHQHIST) ; 	/* Process Switches */

	STRCPY(sr.termnm,terminal);	/* Copy Terminal Name */

	retval = get_param(&pa_rec, BROWSE, 1, e_mesg) ;
	if(retval < 1) {

#ifdef ENGLISH
		printf("Parameters Are Not Setup..") ;
#else
		printf("Parametres ne sont pas etablis..") ;
#endif
		close_dbh() ;
		exit(-1) ;
	}

	retval = get_pay_param(&pay_param, BROWSE, 1, e_mesg) ;
	if(retval == ERROR) {
		DispError((char *)&s_sth,e_mesg);
		return(ERROR) ;
	}

	if (Initialize()<0)
		exit(-1);		/* Initialization routine */

	if ( Process() < 0) { 		/* Initiate Process */
		Close();
		exit(-1);
	}

	Close();			/* return to menu */
	exit(NOERROR);

} /* END OF MAIN */

/*-------------------------------------------------------------------*/
/* Reset information */
Close()
{
	/* Set terminal back to normal mode from PROFOM */
/*	unlink_file(T4_ADJ);*/

	fomcs();
	fomrt();
	close_dbh();			/* Close files */
	close_rep();
}
/*-------------------------------------------------------------------*/
/* Initialize PROFOM  and Screens*/
Initialize()
{
	if(InitProfom()<0) { 			/* Initialize PROFOM */
		fomcs();
		fomrt();
		return(-1);
	}	
	if(InitScreens()<0) { 
		fomcs();
		fomrt();
		return(-1);
	}	
	return(NOERROR);
}

/*-------------------------------------------------------------------*/
/* Initialize PROFOM */

InitProfom()
{
	fomin(&sr);
	/* Check for Error */
	ret( err_chk(&sr) );

	fomcf(1,1);			/* Enable Print screen option */
	return(NOERROR);
}	/* InitProfom() */
/*----------------------------------------------------------------*/
/* Initialize screens before going to process options */
InitScreens()
{
	int	retval ;

	STRCPY(sr.scrnam,NFM_PATH);
	strcat(sr.scrnam,SCR_NAME) ;

	STRCPY(s_sth.s_pgm,PROG_NAME);
	s_sth.s_rundate = get_date();	/* get Today's Date in YYMMDD format */
	s_sth.s_mesg[0] = HV_CHAR ;
	s_sth.s_opt[0] = HV_CHAR ;

	/* Move High Values to 1st screen data fields & Display */
	retval = ClearScreen() ;
	if( retval < 0 ) return(-1) ;

	return(NOERROR);

}	/* InitScreens() */
/*-----------------------------------------------------------------*/
InitPrinter()
{
	char	resp[2] ;
	char	discfile[15] ;

	/* Always to Printer */
	STRCPY( resp, "P" );
	discfile[0] = '\0';

	if( opn_prnt( resp, discfile, s_sth.s_printer, e_mesg, 0 )<0 ){
		fomen(e_mesg); get();
		return(-1);
	}
	return(NOERROR) ;
}
/*-----------------------------------------------------------------*/
/* Clears the screen. 						   */
ClearScreen()
{
	s_sth.s_printer = LV_SHORT;
	s_sth.s_resp[0] = LV_CHAR ;
	
	return(WriteFields((char *)&s_sth,ST_FLD,END_FLD) ) ;
}
/*-----------------------------------------------------------------*/
Process()
{
	int	err;

	s_sth.s_mesg[0] = HV_CHAR;
	DispMesgFld((char *)&s_sth);	
	for( ; ; ){

#ifdef ENGLISH
		fomer("P(rint), E(xit)");
#else
		fomer("I(mprimer), F(in)");
#endif
		sr.nextfld = OPTION_FLD;
		fomrf((char *)&s_sth);
		ret(err_chk(&sr));

		switch(s_sth.s_resp[0]) {
		case  EXITOPT :
			return(EXIT);
		case  PRINT :
			CHKACC(err,ADD,e_mesg);	
			CHKACC(err,UPDATE,e_mesg);	
			err = T4Process() ;
			break ;
		default :
			continue;
		}

		if(NOACCESS == err) {
			fomen(e_mesg);
			get();
		}
		if(PROFOM_ERR == err)	return(PROFOM_ERR);  /* PROFOM ERROR */
		if(DBH_ERR == err) {
			DispError((char *)&s_sth,e_mesg);
#ifdef ENGLISH
			sprintf(e_mesg,"%s %d Dberror: %d Errno: %d",
				"System Error... Iserror:",
				iserror, dberror, errno);
#else
			sprintf(e_mesg,"%s %d Dberror: %d Errno: %d",
				"Erreur du systeme... Iserror:",
				iserror, dberror, errno);
#endif
			DispError((char *)&s_sth,e_mesg);
			return(DBH_ERR); /* DBH ERROR */
		
		}
	}      /*   end of the for( ; ; )       */
}
/*-----------------------------------------------------------------*/
T4Process()
{
	int 	retval ;
	int	prntno;
	char	devname[30];

	retval = ReadInfo() ;
	if( retval == RET_USER_ESC ) return(NOERROR) ;
	if( retval < 0 ) return(retval) ;
	if( retval == EXIT ) return(NOERROR) ;

	retval = ConfirmScreen() ;
	if( retval != YES ) 
		return(NOERROR) ;
	
#ifdef ENGLISH
        retval = GetOption((char *)&s_sth, "Are you ready to print T4 (Y/N)?","YN") ;
#else
        retval = GetOption((char *)&s_sth, "Etes-vous prets a imprimer les T4 (O/N)?","ON") ;
#endif

	if(retval != YES) 
	return(NOERROR) ;

	if(InitPrinter()<0) {
		return(-1);
	}	

	retval = DoTestPrint() ;

	close_rep();
	if(InitPrinter()<0) {
		return(-1);
	}	

	retval = T4Print();
	if( retval < 0 ) 
		return(retval) ;

	close_rep();

	DispMesgFld((char *)&s_sth);
	fflush(stdout) ;
	retval = WriteFields((char *)&s_sth,ST_FLD,END_FLD) ;

	return(NOERROR) ;
 
}
/*-----------------------------------------------------------------------*/
/*                                                                       */
/* Reads T4 Print screen information.                                    */
ReadInfo()
{
	int 	i,retval ;

	/* In Add mode turn off dup control for key fields.
	   Other modes reverse it */
	for(i = ST_FLD ; i <= ST_FLD ; i += 100) {
		fomca1(i,19,2) ;	/* Off Dup Control */
		fomca1(i,10,1) ;
	}

	sr.endfld = PRINTER_FLD;
	fomud((char*)&s_sth);	/* Update Dup Buffers */

#ifdef ENGLISH
	STRCPY(s_sth.s_mesg,"Press ESC-F to Go Back to Option:");
#else
	STRCPY(s_sth.s_mesg,"Appuyer sur ESC-F pour retourner a Option:");
#endif
	DispMesgFld((char *)&s_sth);

	s_sth.s_printer = 1 ;
	retval = WriteFields((char *)&s_sth,PRINTER_FLD,PRINTER_FLD) ;
	if (retval < 0) return(retval) ; 
	s_sth.s_printer = LV_SHORT ;

	i = ReadFields((char *)&s_sth,PRINTER_FLD, PRINTER_FLD,Validation,
		WindowHelp,1); 
	if(PROFOM_ERR == i || DBH_ERR == i) return(i) ;
	if(EXIT == i){
		s_sth.s_mesg[0] = HV_CHAR;
		DispMesgFld((char *)&s_sth);
		return(i) ;
	}
	return(NOERROR) ;
}

/*-----------------------------------------------------------------------*/
/*  Printing the Test as many times needed for cheques to line up        */
DoTestPrint()
{
	int 	i,	retval ;

	for( ; ; ) {
#ifdef ENGLISH
		retval = GetOption((char *)&s_sth,"Do you want a Test Print (Y/N)?","YN") ;
#else
		retval = GetOption((char *)&s_sth,"Desirez-vous un test d'impression (O/N)?","ON") ;
#endif

		if( retval == NO ) 
			break ;

		mkln(6,"9.99",4) ;
		mkln(13,"9.99",4) ;
		mkln(20,"9.99",4) ;
		mkln(28,"9.99",4) ;
		mkln(37,"9.99",4) ;
		mkln(47,"9.99",4) ;
		mkln(56,"9.99",4) ;
		mkln(65,"9.99",4) ;
		mkln(71,"X X",3) ;
		if( prnt_line() < 0) return(-1) ;
		if( prnt_line() < 0) return(-1) ;
		if( prnt_line() < 0) return(-1) ;

		mkln(15,"9.99",4) ;
		mkln(24,"9.99",4) ;
		mkln(33,"9.99",4) ;
		mkln(42,"9.99",4) ;
		mkln(51,"9.99",4) ;
		mkln(60,"9.99",4) ;
		mkln(69,"9.99",4) ;
		if( prnt_line() < 0) return(-1) ;
		if( prnt_line() < 0) return(-1) ;
		if( prnt_line() < 0) return(-1) ;

		mkln(5,"9.99",4) ;
		mkln(14,"9.99",4) ;
		mkln(23,"9.99",4) ;
		mkln(34,"9.99",4) ;
		mkln(43,"9.99",4) ;
		mkln(49,"XX",2) ;
		mkln(54,"999-999-999",11) ;
		if( prnt_line() < 0) return(-1) ;
		if( prnt_line() < 0) return(-1) ;
		if( prnt_line() < 0) return(-1) ;

		mkln(43,"XXXXXXXXXXXXXXXXXXXXXXXXXXXXX",30) ;
		if( prnt_line() < 0) return(-1) ;

		mkln(2,"XXXXXXXXXX",10) ;
		mkln(23,"XXXXXXXXXX",10) ;
		mkln(36,"X",1) ;
		if( prnt_line() < 0) return(-1) ;

		mkln(2,"XXXXXXXXXXXXXXXXXXXX",20) ;
		mkln(43,"XXXXXXXXXXXXXXXXXXXX",20) ;
		if( prnt_line() < 0) return(-1) ;

		mkln(2,"XXXXXXXXXXXXXXXXXXXX",20) ;
		if( prnt_line() < 0) return(-1) ;

		mkln(2,"XXXXXXXXXXXXXXXXXXXX",20) ;
		mkln(45,"XXX999999",9) ;
		mkln(61,"XXXXXXXXXXXX",12) ;
		if( prnt_line() < 0) return(-1) ;

		mkln(2,"X9X 9X9",7) ;
		if( prnt_line() < 0) return(-1) ;
		mkln(43,"XXXXXXXXXXXX",12);
		if( prnt_line() < 0) return(-1) ;
		if( prnt_line() < 0) return(-1) ;
		if( prnt_line() < 0) return(-1) ;
		if( prnt_line() < 0) return(-1) ;
		if( prnt_line() < 0) return(-1) ;
		if( prnt_line() < 0) return(-1) ;
		if( prnt_line() < 0) return(-1) ;
		if( prnt_line() < 0) return(-1) ;
		if( prnt_line() < 0) return(-1) ;

#ifdef ENGLISH
		fomen("The Test Print Is Printing. Press any key to continue.");
#else
		fomen("La copie d'essaie imprime. Appuyer une touche pour continuer.");
#endif
		get();
	}
	return(NOERROR) ;
}
/*-----------------------------------------------------------------------*/
/*                                                                       */
/* Reads the cheque and prints the cheque after accumulating invoices.   */
T4Print()
{
	int	retval ;

	s_sth.s_printed = 0;

#ifdef ENGLISH
	STRCPY(s_sth.s_mesg, "T4 being Printed, PLEASE WAIT");
#else
	STRCPY(s_sth.s_mesg, "Les T4 sont en train d'etre imprimes, ATTENDEZ S.V.P.");
#endif
	DispMesgFld((char *)&s_sth);
	fflush(stdout) ;

	t4_adj.ta_numb[0] = '\0';

	flg_reset(T4_ADJ) ;

	for( ; ; ) {
		retval = get_n_t4_adj(&t4_adj,BROWSE,0,FORWARD,e_mesg) ;
		if( retval == EFL ) 
			break;

		if( retval < 0) {
			roll_back(e_mesg);
			DispError((char *)&s_sth,e_mesg) ;
			return(retval) ;
		}

		strcpy(emp_rec.em_numb,t4_adj.ta_numb);

		retval = get_employee(&emp_rec,BROWSE,0,e_mesg) ;
		if( retval < 0 ) {
			roll_back(e_mesg);
			DispError((char *)&s_sth,e_mesg) ;
			return(retval) ;
		}

		if(retval < 0) {
			fomen(e_mesg);
			get();
			return(retval);
		}

		retval = PrntRec() ;
		if(retval < 0){
			DispError((char *)&s_sth,e_mesg) ;
			roll_back(e_mesg);
			return(-1);
		}

		s_sth.s_printed ++;
	}

	seq_over(T4_ADJ);

	if(s_sth.s_printed == 0){
#ifdef ENGLISH
		DispError((char *)&s_sth,"No T4 to Process");
#else
		DispError((char *)&s_sth,"Pas de T4 a traiter");

#endif
		return(ERROR) ;
	}

#ifdef ENGLISH
	STRCPY(s_sth.s_mesg, "T4 Printed Successfully");
#else
	STRCPY(s_sth.s_mesg, "Impression des T4 reussie");
#endif
	DispMesgFld((char *)&s_sth) ;
	fflush(stdout) ;


	return(NOERROR) ;

}
Validation()	/* Validate the values entered by the user */
{
	int	retval;

	sr.nextfld = sr.curfld;
	return(0);
}
/*----------------------------------------------------------------*/
WindowHelp()
{

#ifdef ENGLISH
	sprintf(e_mesg,"No Window Help For Field#  %d",sr.curfld);
#else
	sprintf(e_mesg,"Pas de fenetre d'assistance pour le champ#  %d",sr.curfld);
#endif
	fomen(e_mesg);
	get();
	return(ERROR) ;
}
/*-----------------------------------------------------------------------*/
/*                                                                       */
ConfirmScreen() 
{
	int	err ;

	for( ; ; ) {
#ifdef ENGLISH
		err = GetOption((char *)&s_sth,"Y(es), E(dit), C(ancel)", "YEC");
#else
		err = GetOption((char *)&s_sth,"O(ui), M(odifier), A(nnuler)",
									 "OMA");
#endif
		if(err == PROFOM_ERR) return(err) ;

		switch(err) {
		case  YES :
			return(YES) ;
		case  EDIT  :
			err = ReadInfo();
			break ;
		case  CANCEL :
#ifdef ENGLISH
			err = GetOption((char *)&s_sth,"Confirm the Cancel (Y/N)?", "YN") ;
#else
			err = GetOption((char *)&s_sth,"Confirmer l'annulation (O/N)?", "ON") ;
#endif
			if(err == YES) { 
				roll_back(e_mesg) ;	/* Unlock  Records */
				return(CANCEL) ;
			}
			break ;
		}	/* switch err */

		if(err == PROFOM_ERR) return(err) ;
		if(err == DBH_ERR) return(err) ;
	}	/* for(; ; ) */
}	/* ConfirmScreen() */

/*-----------------------------------------------------------------------*/
/*                                                                       */
PrntRec()
{
	int i,retval;

	retval = GetRegPen();
	if(retval < 0)	return(retval);

	reg_pen = D_Roundoff(reg_pen);

	if(t4_adj.ta_emp_inc != 0) {
		tedit((char *)&t4_adj.ta_emp_inc,"____0_.__",temp_buf,R_DOUBLE);
		mkln(1,temp_buf, 9) ;
	}

	if(strcmp(pay_param.pr_prov,"PQ") == 0) {
		if(t4_adj.ta_cpp_cont != 0) {
			tedit((char *)&t4_adj.ta_cpp_cont,"_0_.__",temp_buf,
				R_DOUBLE) ;
			mkln(18,temp_buf, 6) ;
		}
	}
	else {
		if(t4_adj.ta_cpp_cont != 0) {
			tedit((char *)&t4_adj.ta_cpp_cont,"_0_.__",temp_buf,
				R_DOUBLE) ;
			mkln(11,temp_buf, 6) ;
		}
	}

	if(t4_adj.ta_uic_prem != 0) {
		tedit((char *)&t4_adj.ta_uic_prem,"__0_.__",temp_buf,R_DOUBLE) ;
		mkln(25,temp_buf, 7) ;
	}

	if(reg_pen != 0) {
		tedit((char *)&reg_pen,"____0_.__",temp_buf,R_DOUBLE) ;
		mkln(32,temp_buf, 9) ;
	}

	if(t4_adj.ta_tax_ded != 0) {
		tedit((char *)&t4_adj.ta_tax_ded,"___0_.__",temp_buf,R_DOUBLE) ;
		mkln(43,temp_buf, 8) ;
	}

	if(t4_adj.ta_uic_ins_earn != 0) {
		tedit((char *)&t4_adj.ta_uic_ins_earn,"___0_.__",temp_buf,
			R_DOUBLE) ;
		mkln(52,temp_buf, 8) ;
	}

	if(t4_adj.ta_cpp_pen_earn != 0) {
		tedit((char *)&t4_adj.ta_cpp_pen_earn,"___0_.__",temp_buf,
			R_DOUBLE) ;
		mkln(61,temp_buf, 8) ;
	}

	if(emp_rec.em_cpp_exp[0] == 'Y')
		mkln(71,"X", 1) ;

	if(emp_rec.em_uic_exp[0] == 'Y')
		mkln(73,"X", 1) ;

	if( prnt_line() < 0) return(-1) ;
	if( prnt_line() < 0) return(-1) ;
	if( prnt_line() < 0) return(-1) ;


	if(t4_adj.ta_housing != 0) {
		tedit((char *)&t4_adj.ta_housing,"_0_.__",temp_buf,R_DOUBLE) ;
		mkln(13,temp_buf, 6) ;
	}

	if(t4_adj.ta_travel != 0) {
		tedit((char *)&t4_adj.ta_travel,"__0_.__",temp_buf,R_DOUBLE) ;
		mkln(21,temp_buf, 7) ;
	}

	if(t4_adj.ta_auto != 0) {
		tedit((char *)&t4_adj.ta_auto,"__0_.__",temp_buf,R_DOUBLE) ;
		mkln(30,temp_buf, 7) ;
	}

	if(t4_adj.ta_intrest != 0) {
		tedit((char *)&t4_adj.ta_intrest,"__0_.__",temp_buf,R_DOUBLE) ;
		mkln(39,temp_buf, 7) ;
	}

	if(t4_adj.ta_other_tax != 0) {
		tedit((char *)&t4_adj.ta_other_tax,"__0_.__",temp_buf,R_DOUBLE);
		mkln(57,temp_buf, 7) ;
	}

	if(t4_adj.ta_emp_com != 0) {
		tedit((char *)&t4_adj.ta_emp_com,"__0_.__",temp_buf,R_DOUBLE) ;
		mkln(66,temp_buf, 7) ;
	}

	if( prnt_line() < 0) return(-1) ;
	if( prnt_line() < 0) return(-1) ;
	if( prnt_line() < 0) return(-1) ;


	if(t4_adj.ta_union_du != 0) {
		tedit((char *)&t4_adj.ta_union_du,"__0_.__",temp_buf,R_DOUBLE) ;
		mkln(1,temp_buf, 7) ;
	}

	if(t4_adj.ta_donnat != 0) {
		tedit((char *)&t4_adj.ta_donnat,"__0_.__",temp_buf,R_DOUBLE) ;
		mkln(11,temp_buf, 7) ;
	}

	if((t4_adj.ta_reg_pen_num[0]) != '\0') {
		mkln(28,t4_adj.ta_reg_pen_num, 13) ;
	}
	if(t4_adj.ta_pen_adj){
		tedit((char *)&t4_adj.ta_pen_adj,"__0_.__",temp_buf,R_DOUBLE);
		mkln(40,temp_buf, 7) ;
	}
	mkln(49,pay_param.pr_prov,2);

	strncpy(temp_buf,emp_rec.em_sin,3);
	temp_buf[3] = '\0';
	strcat(temp_buf, " ");
	temp_buf[4] = '\0';
	strncat(temp_buf, emp_rec.em_sin+3,3);
	temp_buf[7] = '\0';
	strcat(temp_buf, " ");
	temp_buf[8] = '\0';
	strncat(temp_buf, emp_rec.em_sin+6,3);
	temp_buf[11] = '\0';
	mkln(54,temp_buf,strlen(temp_buf));

	if( prnt_line() < 0) return(-1);
	if( prnt_line() < 0) return(-1);
	if( prnt_line() < 0) return(-1);

	if(while_cont != 0) {
		mkln(43,"While not a contrib",20);
		tedit((char *)&while_cont,"__0_.__",temp_buf,R_DOUBLE) ;
		mkln(62,temp_buf, 7) ;
	}
	if( prnt_line() < 0) return(-1);

	mkln(2,emp_rec.em_last_name,strlen(emp_rec.em_last_name));
	mkln(23,emp_rec.em_first_name,strlen(emp_rec.em_first_name));

	if( prnt_line() < 0) return(-1);

	mkln(2,emp_rec.em_add1,strlen(emp_rec.em_add1));
	mkln(43,pa_rec.pa_co_name,30);

	if( prnt_line() < 0) return(-1);

	mkln(2,emp_rec.em_add2,strlen(emp_rec.em_add2));
	if( prnt_line() < 0) return(-1);

	mkln(2,emp_rec.em_add3,strlen(emp_rec.em_add3));

	/* Round to thousands. ie 1993/00/00 */
	gov_par.gp_eff_date = (pay_param.pr_cal_st_dt/10000) * 10000;
	flg_reset(GOV_PARAM);

	retval = get_n_gov_param(&gov_par,BROWSE, 0, FORWARD, e_mesg) ;
	if(retval == EFL) {
		fomen("Government Parameter Record Not Setup");
		return(retval);
	}
	if(retval < 0) {
		fomer(e_mesg) ;
		return(ERROR) ;
	}
	mkln(45,gov_par.gp_tax_acct,12);

	if( prnt_line() < 0) return(-1);

	mkln(2,emp_rec.em_add4,strlen(emp_rec.em_add4));

	if( prnt_line() < 0) return(-1);

	mkln(43,emp_rec.em_numb,12);
	for(i=0;i<9;i++) {
		if( prnt_line() < 0) return(-1);
	}

	return(NOERROR);
}
/*-----------------------------------------------------------------------*/
/* Get the bargining unit range from the user                            */
GetRegPen()
{
	int	retval;

	reg_pen = 0;
	while_cont = 0;

	strcpy(emp_earn.en_numb,emp_rec.em_numb);
	emp_earn.en_date = pay_param.pr_cal_st_dt;
	emp_earn.en_pp = 0;
	emp_earn.en_week = 0;

	flg_reset(EMP_EARN) ;

	for( ; ; ) {
		retval = get_n_emp_earn(&emp_earn,BROWSE,0,FORWARD,e_mesg);
		if(retval < 0) {
			if(retval == EFL) break;
			DispError((char *)&s_sth,e_mesg);
			return(retval);
		}
		if(strcmp(emp_earn.en_numb,emp_rec.em_numb)!=0) { 
			break;
		}

		if(emp_earn.en_date < pay_param.pr_cal_st_dt || 
		   emp_earn.en_date > pay_param.pr_cal_end_dt)
			break;

		strcpy(emp_ln_his.elh_numb,emp_earn.en_numb);
		emp_ln_his.elh_pp=emp_earn.en_pp;
		strcpy(emp_ln_his.elh_code,"PENBUY");
		if(emp_earn.en_pp == 51)
			earn_date= 19931220;
		else
		if(emp_earn.en_pp == 52)
			earn_date = 19931221;
		else
		if(emp_earn.en_pp == 53)
			earn_date = 19931222;
		else
			earn_date = emp_earn.en_date;
		emp_ln_his.elh_date = earn_date;
		emp_ln_his.elh_seq = 0;

		flg_reset(EMP_LOAN_HIS);
		retval = get_n_emp_lhis(&emp_ln_his,BROWSE,0,FORWARD,e_mesg);
		if(retval < 0 && retval != EFL) {
			DispError((char *)&s_sth,e_mesg);
			return(retval);
		}
		if((strcmp(emp_ln_his.elh_numb,emp_earn.en_numb) == 0) &&
		  (emp_ln_his.elh_pp=emp_earn.en_pp ) &&
		 strcmp(emp_ln_his.elh_code,"PENBUY") == 0) {
			reg_pen += emp_ln_his.elh_amount;
			while_cont += emp_ln_his.elh_amount;
		}

		strcpy(emp_dd_his.edh_numb,emp_earn.en_numb);
		emp_dd_his.edh_pp=emp_earn.en_pp;
		strcpy(emp_dd_his.edh_code,"EX PEN");
		strcpy(emp_dd_his.edh_group,"EX PEN");
		if(emp_earn.en_pp == 51)
			earn_date= 19931220;
		else
		if(emp_earn.en_pp == 52)
			earn_date = 19931221;
		else
		if(emp_earn.en_pp == 53)
			earn_date = 19931222;
		else
			earn_date = emp_earn.en_date;
		emp_dd_his.edh_date = earn_date;

		flg_reset(EMP_DED_HIS);
		retval = get_n_emp_dhis(&emp_dd_his,BROWSE,0,FORWARD,e_mesg);
		if(retval < 0 && retval != EFL) {
			DispError((char *)&s_sth,e_mesg);
			return(retval);
		}
		if((strcmp(emp_dd_his.edh_numb,emp_earn.en_numb) == 0) &&
		  (emp_dd_his.edh_pp=emp_earn.en_pp ) &&
		 strcmp(emp_dd_his.edh_code,"EX PEN") == 0) {
			reg_pen += emp_dd_his.edh_amount;
			while_cont += emp_dd_his.edh_amount;
		}

		strcpy(emp_dd_his.edh_numb,emp_earn.en_numb);
		emp_dd_his.edh_pp=emp_earn.en_pp;
		strcpy(emp_dd_his.edh_code,"PENTCH");
		strcpy(emp_dd_his.edh_group,"PENTCH");
		if(emp_earn.en_pp == 51)
			earn_date= 19931220;
		else
		if(emp_earn.en_pp == 52)
			earn_date = 19931221;
		else
		if(emp_earn.en_pp == 53)
			earn_date = 19931222;
		else
			earn_date = emp_earn.en_date;
		emp_dd_his.edh_date = earn_date;

		flg_reset(EMP_DED_HIS);
		retval = get_n_emp_dhis(&emp_dd_his,BROWSE,0,FORWARD,e_mesg);
		if(retval < 0 && retval != EFL) {
			DispError((char *)&s_sth,e_mesg);
			return(retval);
		}
		if((strcmp(emp_dd_his.edh_numb,emp_earn.en_numb) == 0) &&
		  (emp_dd_his.edh_pp=emp_earn.en_pp ) &&
		 strcmp(emp_dd_his.edh_code,"PENTCH") == 0) {
			reg_pen += emp_dd_his.edh_amount;
			while_cont += emp_dd_his.edh_amount;
		}

		reg_pen += emp_earn.en_reg1 + emp_earn.en_reg2 + 
			emp_earn.en_reg3 ;

	}
	seq_over(EMP_EARN);

	return(NOERROR);
}
GetFilename(ptr)
char	*ptr;
{
	return(0);
}
GetOutputon(ptr)
char	*ptr;
{
	return(0);
}
GetNbrCopies(par)
short	par;
{
	return(0);
}
Confirm()
{
	return(0);
}
/*-------------------- E n d   O f   P r o g r a m ---------------------*/
